### ISSUE TITLE
Add support to batch update list items

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#1001]
Its supported to batch add and delete list items but not update.

**Comment by matsla** [comment]
@jansenbe maybe I was to fast, I check the documentation and did not found any samples regarding this topic, but now I see there is a item.UpdateBatchAsync() method, I will try this.

**Comment by jansenbe** [comment]
@matsla : there are also `UpdateOverwriteVersionBatchAsync` and `SystemUpdateBatchAsync` methods which can be used. The `UpdateBatchAsync` batches REST calls, the others batch CSOM calls under the covers.

**Comment by jansenbe** [comment]
@matsla : can this issue be closed?

**Comment by matsla** [comment]
@jansenbe yes, this works fine
