### ISSUE TITLE
Can't get LookupValue from ListItems

### ISSUE THREAD

**Issue by Luckillash** [pnp/pnpcore#1007]
## Category

- [x] Bug

## Describe the bug

Hi, everyone!

I am trying to obtain "TipoSolicitud" lookup value.

![1](https://user-images.githubusercontent.com/81302985/197617975-a1905413-d783-48c1-a2e3-c20715a67440.png)

But when i try to do so, i get the next error:

![4](https://user-images.githubusercontent.com/81302985/197619954-a9059d45-170b-434f-9282-99caffc80e76.png)

(I can only get the lookup id by the way!)

## Steps to reproduce

This is my code:

![2](https://user-images.githubusercontent.com/81302985/197619070-8719ad86-de00-46f2-a48a-9580f7643191.png)

![3](https://user-images.githubusercontent.com/81302985/197619075-d8e8a2e5-4444-4ed6-8634-e74b2943fa4a.png)

I tried following this syntax to access the lookup value: https://sharepoint.stackexchange.com/questions/301079/how-to-retrieve-lookup-field-value-in-pnp-core-in-c

But as i understood from the PnP Core documentation this is only valid when you add or update a lookup.

## Expected behavior

The lookup value should match the one that is displayed on the list.

For example:

![6](https://user-images.githubusercontent.com/81302985/197620656-bab3720b-4453-43a7-a762-087bdd087854.png)

(listItem.Values["TipoSolicitud"] as IFieldLookupValue).LookupValue = "Primera licencia"

## Environment details (*development & target environment*)

- **SDK version**: 1.7.106-nightly
- **OS**: Windows 11
- **SDK used in**: ASP.Net Web app
- **Framework**:  .NET6.0
- **Browser(s)**: Microsoft Edge 106.0.1370.52 (Compilación oficial) (64 bits)
- **Tooling**: Visual Studio 2022

Thanks for your attention.

// Also checking the PnP.Core repository i saw that only the lookup id was being set. I don't really know if that is causing the problem but i hope that it helps.

https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Core/Public/IFieldLookupValue.cs/

![8](https://user-images.githubusercontent.com/81302985/197622448-efd5927c-4a54-41d1-9ebb-305911779dbc.png)

**Comment by Luckillash** [comment]
Quick update!

I realized that i can get the lookup value using the "LoadListDataAsStreamAsync" method and it works fine!

![1](https://user-images.githubusercontent.com/81302985/197894117-13dba7f0-e7e3-425b-9dee-4edae9dcd6db.png)

![2](https://user-images.githubusercontent.com/81302985/197894128-81ba99a9-1eed-4125-8292-13d872b68dd7.png)

![3](https://user-images.githubusercontent.com/81302985/197894137-f278f78f-c5a4-49f2-b9a8-fdc21e8f41c2.png)

The problem starts when i try to return the listItem.values.

![6](https://user-images.githubusercontent.com/81302985/197894519-6b7f4cf9-3012-4cfe-8ae8-d580d60c8f6a.png)

I get the next error:

![11](https://user-images.githubusercontent.com/81302985/197894599-cc3ae346-033f-436c-b223-f75aab4ec0fd.png)

**Comment by jansenbe** [comment]
@Luckillash : thanks for the research and shared details. I'll plan to have a look at this in the coming days.

**Comment by jansenbe** [comment]
@Luckillash : I think your code assumes all properties of a `FieldUserValue` instance are populated, which is not always the case. When using `LoadListAsDataStream` the principal id ('LookupId') is set, but you would need to resolve that user if you need the user's details.

**Comment by jansenbe** [comment]
Also, https://github.com/pnp/pnpcore/discussions/795#discussioncomment-3982991 shows how to retrieve the possibly extra columns that are provided via a lookup column

**Comment by Luckillash** [comment]
@jansenbe : I was able to fix the error "Property Principal was not yet loaded" as soon as i commented the p => p.items.

![image](https://user-images.githubusercontent.com/81302985/198361755-8b4c8b5f-6dbf-42dc-9716-d5e535a5d7ab.png)

I am still using LoadListDataAsStreamAsync to get the Lookup Value.

![image](https://user-images.githubusercontent.com/81302985/198362136-281c58f4-6a3f-40d0-bd37-8098c2b5339e.png)

But i wish i would be able to get it without using that method. ¿Is that possible?

**Comment by jansenbe** [comment]
@Luckillash : that would not be possible, expaning the Items collection on a list will return lookup fields like this: 

```json
            "LookupSingleId": 1,
            "LookupMultipleId": [
                1,
                3392
            ],
```

So only the ID of the target list item is returned. That's why using a CAML query approach is better here as you can pull down all involved fields. Also the "expand items" approach is limited to 100 items.

Will be closing this issue now, but create a new issue to add extra documentation explaining how to handle lookup fields.
