### ISSUE TITLE
ListItemCollection.Add throws for lists with non-standard url.

### ISSUE THREAD

**Issue by jekeblad** [pnp/pnpcore#1009]
## Category

- [x] Bug

## Describe the bug

When adding items to a list with a non-standard url, e.g. _https://contoso.sharepoint.com/sites/mysite/mylist_, the Add method throws an exception. This is because the list url don't conform to the "entitytypename to url" standard and results in a call to _https://contoso.sharepoint.com/sites/mysite/lists/my_ which results in an error.

## Steps to reproduce

1. Create a list
2. Move root folder to a new url
3. Create list item with pnp

## Expected behavior

This should create a list item at the correct location

## Environment details (*development & target environment*)

- **SDK version**: [1.4.0]
- **Framework**: [.NET Standard 2.0]
- **Additional details**:  This has been confirmed using 1.4.0 but it seems like the same code is still in use in 1.7.0

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@jekeblad : what do you mean with "move root folder to a new URL"?

**Comment by jekeblad** [comment]
@jansenbe: To be honest, moving was something i googled on how to do. I think you can use pnp powershell lib to get the root folder of a list and move it to another url, thus giving the list a different url.

The list I’m working with can be accessed directly under the root, i.e. it does not have the /lists/ segment in the url. 

I think this has either been created when this was possible to set the url on creation, either in the UI or using the CSOM. Im not sure you can do it using the REST api.

**Comment by jansenbe** [comment]
@jekeblad : if you can provide me access to such a list or instructions on how to setup a repro I'm more then happy to have a look and see if there's a solution that does not involve doing additional server roundtrips.

**Comment by jansenbe** [comment]
@jekeblad : given I've no way to reproduce this I'm closing the issue. If you've an option for me to simulate this, then I'm happy to re-open and see if there's a fix.
