### ISSUE TITLE
Docs for using Managed Identity auth

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpcore#1013]
## Category

- [x] Documentation request

Would it make sense to add an example in [PnP Core Samples](https://pnp.github.io/pnpcore/demos/README.html) for using Azure Function with Managed Identity?
We need custom auth provider, I know =) 
I think it would be super nice to have a working example everyone could use.

I just implemented it, so if you are interested, I could contribute the sample. 
Or... is there something that is still not working, that I'm not yet aware?

**Comment by jansenbe** [comment]
@kkazala : that would be an awesome addition! Happy to help along the process getting the PR in.

**Comment by kkazala** [comment]
Perfect. Please give me a few days as I’m currently swamped. Latest next week

**Comment by jansenbe** [comment]
PR merged, thanks again @kkazala 💪🚀👍
