### ISSUE TITLE
Support the manipulation of UseAccessRequestDefault and AccessRequestSiteDescription 

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#1019]
## Category

- [x] Feature request

## Describe the feature

Based on discussion https://github.com/pnp/pnpcore/discussions/1016 it would be a good addition allowing to manipulate the IWeb values for UseAccessRequestDefault and AccessRequestSiteDescription. Both should call the endpoints _api/web/SetUseAccessRequestDefaultAndUpdate and _api/web/SetAccessRequestSiteDescriptionAndUpdate respectively.

I am new to this project and would love to contribute. I have a couple of questions before proceeding.
- [ ] Do you want to create dedicated methods to manipulate these values, or is there a more elegant way to do this? 
- [ ] How do we handle unit/integration tests the best possible way?

Thank you,
Patrick

**Comment by jansenbe** [comment]
@plamber : given a method needs to be called we cannot implement this as properties, adding a method for each REST equivalent is a good approach here.

Regarding unit tests: https://pnp.github.io/pnpcore/contributing/writing%20tests.html describes how to get started with writing/running tests. We do have a concept of offline tests, where that server data is mocked. To get to the mocked data you first need to run the test live. Key thing to setup is your appsettings.json file in the test project.

Feel free to ping me if you need help with setting things up.

**Comment by plamber** [comment]
I would love to take this up.

**Comment by jansenbe** [comment]
Assigned this one to you @plamber , thanks for helping out with PnP Core!

**Comment by plamber** [comment]
Hi @jansenbe,
I am working on the ability to specify the site access settings. I will handle the assignment of the description in a separate issue.

I am currently creating a method for IWeb SetAccessRequestAsync. You can pass an enum (Enabled, Disabled, SpecificMail) and as the optional second parameter, the mail for the access request.

In case someone selects Enabled or Disabled, I have to perform the setUseaccessrequestdefaultandupdate API call and update the setting RequestAccessEmail for the web. Do you want me to build a separate API REST call, or is there a way to call this update on the SDK level in my method?

Thank you for your feedback.
Patrick

**Comment by jansenbe** [comment]
@plamber : that would be a separate REST call then

**Comment by plamber** [comment]
Hi @jansenbe,
I have the following snippet:
```
var updateRequestAccessMail = new
            {
                RequestAccessEmail = targetMail
            }.AsExpando();
            string updateRequestAccessMailBody = JsonSerializer.Serialize(updateRequestAccessMail, typeof(ExpandoObject), PnPConstants.JsonSerializer_IgnoreNullValues);
            var updateRequestAccessMailRequest = new ApiCall($"_api/web", ApiType.SPORest, updateRequestAccessMailBody);
            await RawRequestAsync(updateRequestAccessMailRequest, HttpMethod.Patch).ConfigureAwait(false);
```

Is this the right approach to updating the value? Unfortunately, the HttpMethod.Patch is not available for all frameworks. Do you have a suggestion on how to solve this properly?

Thank you for being so helpful,
Patrick

**Comment by jansenbe** [comment]
@plamber : for the Patch method you can use `new HttpMethod("PATCH")`, the approach looks good.
