### ISSUE TITLE
[BUG] Issue with EnsureUserAsync and AddAsync

### ISSUE THREAD

**Issue by KarolFilipKozlowski** [pnp/pnpcore#1020]
## Category

- [x] Bug

## Describe the bug

Hey,
I try to learn PnP Core and move to it from CSOM, so on first attempt I test adding new items to list with alle types of fields.
I have issue with [User fields](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields).
According to the documentation I must EnsureUserAsync and I do it like in CSOM, the when I try adding new item i got exeption:

'PnP.Core.ClientException: 'Property AadObjectId was not yet loaded'

![image](https://user-images.githubusercontent.com/25957036/200178971-92fe194a-90ea-483d-b113-1a61b32c782f.png)

No idea why this few fields are not loaded. For example in AAD for this account filed departament have data.

- **SDK version**: [e.g. 1.7.0 ]
- **Framework**: [.NET Core v6.0 ]
- **Tooling**: [Visual Studio 2022]

**Comment by jansenbe** [comment]
@KarolFilipKozlowski : EnsureUser will only ensure the user does exist in the site collection, it will not load additional user properties. For that you can do a LoadAsync() to load the additional properties you need (see https://pnp.github.io/pnpcore/using-the-sdk/basics-getdata.html#i-want-to-load-data-into-the-pnpcontext)

**Comment by KarolFilipKozlowski** [comment]
@jansenbe I solved it. I wrong understand the documentation and forget to correctly declare field object.
