### ISSUE TITLE
Users deleted from AAD,Web. EnsureUserAsync and spUser.AsGraphUserAsync

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpcore#1030]
## Category

- [x] Bug

## Describe the bug

Imagine the following scenario:
- UserA has been added to the AAD in their work tenant
- They are referenced in a SP List item (Person field)
- They leave company and their account is deleted from AAD

At this point, 
- `pnpContext.Web.EnsureUserAsync(userName)` will resolve the user correctly, but
- adding new list item where the user is referenced in the Person field will throw exception

To ensure the user does exist in AAD and can be added to the Person field, I'm executing ` spUser.AsGraphUserAsync();`

Would it make sense for `Web.EnsureUserAsync(userName)` to only resolve users that can be "used"?

## Steps to reproduce

1. Create userA in AAD
1. Add/ensure user: `var spUser = await pnpContext.Web.EnsureUserAsync(userName);` 
1. Add new list item, adding UserA to the Person field as described [here](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields)
1. Delete the user from AAD
1. repeat the steps 2+3
2. An error will be thrown

## Expected behavior

I would expect the `pnpContext.Web.EnsureUserAsync(userName)` to correctly resolve users not only against the UserInformation list but also against the AAD.
Even if a user is in the UserInformation list, they cannot be referenced in the Person Fields if they are already deleted from AAD. 
I didn't test granting them access to the resources but it's probably the same case (?)

_(I also wonder if it would be possible to return `null` instead of throwing exception, if the user doesn't exist?)_

## Environment details (*development & target environment*)

- **SDK version**: "1.7.0
- **OS**:  Windows 10 
- **SDK used in**: Azure Function
- **Framework**: .NET Core v6.0
-  **Browser(s)**: n/a
- **Tooling**:  VS Code

**Comment by jansenbe** [comment]
@kkazala : `EnsureUser` calls the SharePoint EnsureUser REST method, what this does is ensuring the user exists in the user table of the site. If a user is removed from AAD then that user is not removed from the users table of the site and `EnsureUser` stays working as it essentially does nothing since the user is in the table. It's probably best to capture the specific error or alternatively query AAD to verify if the user exists. Catching the exception probably is the cheapest solution.

**Comment by jansenbe** [comment]
@kkazala : does the above answer your question? If so, I think the issue can be closed.

**Comment by kkazala** [comment]
Pleas give me till tomorrow? I actually wanted to follow up on this, but was a bit busy elsewhere :)

**Comment by kkazala** [comment]
@jansenbe Thank you for following up on this issue. And for the explanations :)

If we treat the `EnsureUser` method as a simple wrapper for the REST method- then it does exactly what it should do. 
But the PnP Core is so much more, isn't it? :)

If I ask myself, what would be a reason for calling the `EnsureUser`, the answer would NOT be: "_to ensure the user is in the_ /_catalogs/users/_".  
Instead, I would call it "_to make sure I can successfully reference the user in the SP List item 'user' field_", which in turn would mean- I don't get exceptions when saving such item.

In the context of the above statement, the `EnsureUsers` does exactly what it should do except of the case where the user did "exist" but was later deleted from AAD. And since the `myList.Items.AddAsync()` actually checks if the user exists in AAD, I have a situation where the `EnsureUsers` tells me that the user exists, but the `Add` method fails.

This is particularly disruptive when using multi-user fields, as the error doesn't provide me with the information on which user is missing exactly. 
If my payload contains "existing" users that were deleted from the AAD, creating an item would require 1) creating an item without data in the user field (if not mandatory, otherwise use a "dummy" user) and 2) adding users one by one.
And then, when ingesting large amount of data (which is my case) I would need to parse the responses of the batch operation and retry all the items that failed due to the user field. 
That's a lot of additional executions.

At the same time, I admit that `AsGraphUserAsync()` lasts, on average, almost as much as `EnsureUserAsync` (58.9 ms vs 68.5 ms, using a sample of 60 users).  I thought the `AsGraphUserAsync()` was faster ;)

So I guess that my initial idea to ensure that the `EnsureUser` also checks against AAD would significantly degrade the performance...
Would you consider mentioning it in the documentation instead?

**Comment by jansenbe** [comment]
@kkazala : thanks for the detailed analysis. The scenario you want to verify is whether a batch of users exists before using them and, as you've noticed, `EnsureUser` is not the right method for that. I'm thinking about these improvements:

1. Update `EnsureUser` docs to clarify how it works (and doesn't work)
2. Create a new UserExists method that allows to check whether a user exists. This method either has to support batching or alternatively can take an array of user id's as input. Will do some investigation on what the best API will be to use, most likely Microsoft Graph

**Comment by jansenbe** [comment]
@kkazala : I've added a note the docs to clarify how `EnsureUser` works (or does not work). I'll create a new issue to track the request for having a method that can validate a set of users.

**Comment by kkazala** [comment]
@jansenbe  I'm sorry for not replying earlier, it totally slipped my mind. 
Thank you for the follow up and the explanations. I think it's an excellent idea to add caching :)

**Comment by kkazala** [comment]
@jansenbe When do you think the [ValidateAndEnsureUsers(IList<String>)](https://pnp.github.io/pnpcore/api/PnP.Core.Model.SharePoint.IWeb.html#collapsible-PnP_Core_Model_SharePoint_IWeb_ValidateAndEnsureUsers_PnP_Core_Model_SharePoint_IList_System_String__) will be included in the release build? I cannot use nightly builds in production =) and it's still not in 1.8.0

**Comment by jansenbe** [comment]
Actually was planning to release today but code signing cert expired, so will be for tomorrow I hope

**Comment by kkazala** [comment]
Awesome, thank you :)
________________________________
