### ISSUE TITLE
No user field returned on Version items

### ISSUE THREAD

**Issue by aidanbha79** [pnp/pnpcore#1031]
## Category

- [x] Bug

## Describe the bug

When I try and get all the version history from a list item it doesn't contain any of the User lookup fields as part of it. these are being set on the create and when I look at the values on the main parent it has the values. I need to check if an item has been assigned to someone else.

## Steps to reproduce

`    
using var context = await _pnpContextFactory.GetContextAsyncForSite(url);
            var myList = await context.Web.Lists.GetByTitleAsync(listName, 
                p => p.Title, 
                p => p.Items,
                p => p.Fields,
                p => p.Fields.QueryProperties(p => p.InternalName,
                    p => p.FieldTypeKind,
                    p => p.TypeAsString,
                    p => p.Title));

            await myList.LoadListDataAsStreamAsync(new RenderListDataOptions()
            {
                RenderOptions = RenderListDataOptionsFlags.ListData
            });

            var foundItem = await myList.Items.GetByIdAsync(id, li => li.All, li => li.Versions);
            Dictionary<int,object> items = new Dictionary<int, object>();
            foreach (var version in foundItem.Versions.AsRequested())
            {

                var versionLabel = version.VersionLabel;
                items.Add(version.VersionLabel.ToInteger(0), version.Values);
            }
            items.Add(items.Count + 1, foundItem.Values);
`

## Expected behavior

Should show the user lookup fields within the version values.

## Environment details (*development & target environment*)

- **SDK version**: 1.7.0
- **OS**: windows 11
- **SDK used in**: ASP.Net Web app 
- **Framework**: .Net 6.0
- **Browser(s)**: Chrome
- **Tooling**:  Visual Studio 2022

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@aidanbha79 : I can confirm that the lookup field is skipped when parsing the API call response, so clearly a bug. Will work on a fix. Thanks for using PnP Core SDK and reporting this issue.
