### ISSUE TITLE
Connection forcibly closed when downloading 20MB file in chunks

### ISSUE THREAD

**Issue by stonekw** [pnp/pnpcore#1032]
## Category

- [x] Bug

## Describe the bug

I am using the code from https://github.com/pnp/pnpcore/issues/228 and https://pnp.github.io/pnpcore/using-the-sdk/files-large.html to download a "large" file - 20MB. When downloading directly from the browser, it takes approximately 5 seconds on my internet connection. We had a file corruption "event" and my program is downloading all files from a SharePoint site and checking them for corruption - in this case, the corruption is all the bytes in the file are replaced by null bytes. Using the code below, the file downloads fine as long as the file size is less than the buffer size. If it is larger, it isn't working. 

`
            List<IFile> nullByteFiles = new List<IFile>();

            string tempFilePath = $"{tempFolderPath}\\{file.Name}";

            long fileSize = file.Length;

            var bufferSize = 2 * 1024 * 1024;

            Stream downloadedContentStream;

            if (fileSize >= bufferSize)
            {
                downloadedContentStream = await file.GetContentAsync(true);
            }
            else
            {
                downloadedContentStream = await file.GetContentAsync();
            }

            bool isNullBytes = false;

            // This approach avoids the file being fully loaded in the process memory
            // 2 MB buffer
            using (var content = System.IO.File.Create(tempFilePath))
            {
                var buffer = new byte[bufferSize];
                int read;
                while ((read = await downloadedContentStream.ReadAsync(buffer, 0, buffer.Length)) != 0)
                {
                    content.Write(buffer, 0, read);
                    //check each chunk for null bytes
                    if (buffer.All(b => b.ToString() == "0"))
                    {
                        isNullBytes = true;
                    }
                    else
                    {
                        isNullBytes = false;
                        break;
                    }
                }
            }

            downloadedContentStream.Dispose();

            return isNullBytes;
`
I have a watch the "read" variable and breakpoint on content.Write(buffer, 0, read); The first loop iteration shows "read" with 58 bytes, 2-5 show 24576 bytes, and 6-n.. is 16384. (I haven't spent the time to go through all the iterations, but I checked ~50 iterations and they were all 16384.).

If I remove the breakpoint and let it run, the process eventually fails with the error: "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.."

I set the Http Request timeout to -1 (infinite) per the docs to avoid timeout while downloading large files. 

## Steps to reproduce

Execute the above code to download a file larger than 2MB.

## Expected behavior
 With a 2MB buffer size, I would expect each breakpoint show read as 2,097,152 until the last batch which would be 2,097,152 minus the amount remaining.  

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide clear & concise description of what you expected to happen.

## Environment details (*development & target environment*)

- **SDK version**: 1.7.0
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET 6
- **Browser(s)**: Console App
- **Tooling**: Visual Studio 2022 RC
- **Additional details**: 

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@stonekw :  I've been testing with various file sizes and various buffer sizes and have been not been able to reproduce this issue. This approach is not doing a chunked download, so there's only one call to SharePoint to get the file contents, the difference with the streaming approach is that received file bytes are directly written to disk and therefore this approach is avoids loading a file fully into memory before committing it disk. When you debug this code you'll see a ton of iterations each returning some bytes, how much each iteration returns depends on .NET, network speed, CPU cycles etc.

If you can have your files in memory the feel free to not use the streaming approach.


```csharp
IFolder parentFolder = await context.Web.Folders.FirstOrDefaultAsync(f => f.Name == "SiteAssets");

//string fileName = TestCommon.GetPnPSdkTestAssetName("2gb.test");
string fileName = "largevideo.mp4";

string fileUrl = $"{parentFolder.ServerRelativeUrl}/{fileName}";
IFile fileToDownload = await context.Web.GetFileByServerRelativeUrlAsync(fileUrl);

// Download the content
Stream downloadedContentStream = await fileToDownload.GetContentAsync(true);

var bufferSize = 10 * 1024 * 1024;  // 10 MB buffer
using (var content = System.IO.File.Create("d:\\temp\\largetestfiles\\largevideo.mp4.downloaded"))
{
    var buffer = new byte[bufferSize];
    int read;
    while ((read = await downloadedContentStream.ReadAsync(buffer, 0, buffer.Length)) != 0)
    {
        content.Write(buffer, 0, read);
    }
}
```
