### ISSUE TITLE
GetCommentsAsync does not return reply comments

### ISSUE THREAD

**Issue by larry-lau** [pnp/pnpcore#1033]
## Category

- [x] Bug

## Describe the bug

The GetCommentsAsync API does not return comment replies.  It only returns the top level comments. 

```
using (var context = await pnpContextFactory.CreateAsync(new Uri(siteUrl), appOnlyAuthProvider))
{
    var page = context.Web.GetPages(testDataConfig.Value.PageName).FirstOrDefault();
    if (page != null)
    {
        output.WriteLine($"Getting comments for the page [{page.PageId}]");

        var comments = await page.GetCommentsAsync(
            p => p.Author,
            p => p.Text,
            p => p.ReplyCount,
            p => p.Replies);

        var comment = comments.FirstOrDefault();
        output.WriteLine($"\t\t comment.ReplyCount = {comment.ReplyCount}");
        output.WriteLine($"\t\t comment.Replies.Length = {comment.Replies.Length}");
    }
}
```

Console Output
```
Getting comments for the page [398]
		 comment.ReplyCount = 1
		 comment.Replies.Length = 0
```
Note that the ReplyCount is correct but the Replies collection is empty.

## Steps to reproduce
1. Create a site page with Comments On.
2. Post a comment on the page
3. Click "Reply" to post a reply comment to the comment above
4. Call GetCommentsAsync on the page
5. Note that the comment.Replies collection of the first comment is empty. It should contain 1 reply comment.

## Expected behavior
The comment.ReplyCount should be 1 
The Replies collection should contain 1 comment

## Environment details (*development & target environment*)
- **SDK version**: [PnP.Core 1.7, 1.8]
- **OS**: [Windows 10]
- **SDK used in**: [Console App | Azure Functions App | xUnit]
- **Framework**: [.NET 6.0 ]
- **Browser(s)**: [not relevant]
- **Tooling**: [Visual Studio 2022 17.4]
- **Additional details**: *AppOnly permission is used to call GetCommentsAsync*

### Additional context
Here is what the page should look like with one comment and one reply
![comment with reply](https://user-images.githubusercontent.com/17136688/202311788-d39b0eff-0ec7-40fa-8d5d-58ededfb9e5a.png)

Here is the console output of the code above
![output](https://user-images.githubusercontent.com/17136688/202311989-a5c987cb-ae1e-40e8-889d-1f66a99825b8.png)

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Hi @larry-lau ,

In my testing this works, most likely the reason for your issue is this line:

```csharp
var comment = comments.FirstOrDefault();
```

Since you get a PnP Collection back you need to use `AsRequested()` before you apply LINQ operations on the result set, without that you're actually calling our LINQ provider and doing an extra request, in this case this request then is not loading the comments. See https://pnp.github.io/pnpcore/using-the-sdk/basics-iqueryable.html to learn more.

So change your code to the below and let me know if that works:

```csharp
var comment = comments.AsRequested().FirstOrDefault();
```

**Comment by larry-lau** [comment]
Hi @jansenbe,

Yes, adding AsRequested() populates the Replies collection. 

Thanks!
