### ISSUE TITLE
Support to set site sharing settings

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#1038]
Add support to set sharing permissions and access requests settings

**Comment by jansenbe** [comment]
@matsla : the sharing settings of a site can be configured by setting the relevant sharing properties of the site collection. See https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#getting-and-setting-site-collection-properties for how to do that. See https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Admin/Model/SharePoint/Core/Public/ISiteCollectionProperties.cs to learn more about the properties that can be set.

Regarding access request settings: @plamber is working on a PR to bring that functionality (see #1019)

**Comment by plamber** [comment]
Hi @matsla,
I just created a pull request for the access request feature. https://github.com/pnp/pnpcore/pull/1040

Cheers

**Comment by jansenbe** [comment]
@plamber : thanks for your PR, just merged it. @matsla : this means this issue can be closed now.
