### ISSUE TITLE
Object reference not set to an instance of an object - IAuthenticationProvider dependency injection - Azure Function

### ISSUE THREAD

**Issue by stonekw** [pnp/pnpcore#1043]
## Category

- [x] Bug

## Describe the bug

I have an azure function that will trigger some action against a site specified by URL in the function query string. In order to do this, I am trying to inject the IAuthenticationProviderFactory and IPnPContextFactory into my function code to create the PnPContext on the fly when the function is called (we don't know the site URL until the function is called). null reference exception occurs when I try 

` IAuthenticationProvider authProvider = _authFactory.Create(targetEnv.AuthConfigName);`

In this snippet, _authFactory is not null, nor is targetEnv or AuthConfigName. The exception appears to be internal to the Create() method

Here is my startup.cs:

`namespace MyNamespace.Functions
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddLogging();

            // Add the PnP Core SDK library services
            builder.Services.AddPnPCore(options =>
            {
                // Disable telemetry because of mixed versions on AppInsights dependencies in AZ functions
                options.DisableTelemetry = true;

                options.PnPContext.GraphFirst = true;
                options.HttpRequests.UserAgent = "NONISV|MyNamespace|SecurityMatrixFunction";
                options.HttpRequests.SharePointRest = new PnPCoreHttpRequestsSharePointRestOptions
                {
                    UseRetryAfterHeader = true,
                    MaxRetries = 5,
                    DelayInSeconds = 3,
                    UseIncrementalDelay = true,
                };
            });

            // Add the PnP Core SDK Authentication Providers
            builder.Services.AddPnPCoreAuthentication(options =>
            {

                foreach (MyPnPEnvironment env in AppConfig.Environments)
                {
                    //pnpcore getting a dictionary error if the config duplicates AuthConfigNames, added this check. 
                    if (options.Credentials.Configurations.ContainsKey(env.AuthConfigName) == false)
                    {
                        //PFX cert is in keyvault and lastpass. Password for certificate is in LastPass. 
                        //using managed identity DefaultAzureCredential to access Key Vault only. The same certificate is used to access field tenant and HQ tenant, both while debugging locally and published as a prod function 
                            CertificateClient client = new CertificateClient(vaultUri: new Uri(env.HQTenantKeyVaultUri), credential: new DefaultAzureCredential());
                            X509Certificate2 x509Cert = client.DownloadCertificate(env.HQTenantKeyVaultCertificateName);

                        options.Credentials.Configurations.Add(env.AuthConfigName,
                        new PnPCoreAuthenticationCredentialConfigurationOptions
                        {
                            ClientId = env.AppClientId,
                            TenantId = env.TenantId,
                            X509Certificate = new PnPCoreAuthenticationX509CertificateOptions
                            {
                                Certificate = x509Cert
                            }
                        });
                    }
                }
            });
        }
    }
}`

And here is my function code: 

`using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using PnP.Core.Services;
using PnP.Core.Auth.Services;
using MyNamespace.SharePoint;

namespace MyNamespace.Functions
{
    public class UpdateSite
    {
        private readonly ILogger _log;
        private readonly IPnPContextFactory _contextFactory;
        private readonly IAuthenticationProviderFactory _authFactory;
        public UpdateSite(IPnPContextFactory contextFactory, IAuthenticationProviderFactory authFactory, ILogger<UpdateSite> logger)
        {
            this._contextFactory = contextFactory;
            this._authFactory = authFactory;
            this._log = logger;
        }

        [FunctionName("UpdateSite")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "UpdateSite")] HttpRequest req)
        {
            try
            {
                // Parse the url parameters
                string siteUrl = req.Query["siteAbsoluteUrl"];
                if (siteUrl == null)
                {
                    throw new Exception($"siteAbsoluteUrl must be provided as URL parameter");
                }

                Uri testUri = null;
                bool testUriResult = Uri.TryCreate(siteUrl,UriKind.Absolute, out testUri);
                if(testUriResult == false)
                {
                    throw new Exception($"Supplied siteAbsoluteUrl {siteUrl} is invalid");
                }

                MyPnPEnvironment targetEnv = AppConfig.Environments.FirstOrDefault(e => siteUrl.StartsWith(e.SPRootUrl,StringComparison.CurrentCultureIgnoreCase));
                if (targetEnv == null)
                {
                    throw new Exception($"siteAbsoluteUrl {siteUrl} does not have supported SharePoint root site. Supported root sites: {string.Join(",", AppConfig.Environments.Select(e => e.SPRootUrl))}");
                }

                IAuthenticationProvider authProvider = _authFactory.Create(targetEnv.AuthConfigName);//_authFactory is not null here, nor is targetEnv or AuthConfigName. The exception appears to be internal to the Create() method
                using (PnPContext pnpContext = await _contextFactory.CreateAsync(new Uri(siteUrl), authProvider))
                {
                    SecurityMatrix matrix = new SecurityMatrix(pnpContext, _log);
                    matrix.Test();
                }
                return new OkObjectResult("Permissions Applied");
            }
            catch (Exception ex)
            {
                _log.LogError(ex,null);
                return new BadRequestObjectResult(ex.Message);
            }
        }
    }
}`

MyPnPEnvironment is part of AppConfig, which is a static class containing all the info I need to get the key vault certificate as well as the client ID for the app. I can provide this info if it is helpful

## Steps to reproduce

Build the solution and call the "UpdateSite" function using postman or fiddler

## Expected behavior

Return a IAuthenticationProvider which I can use to create PnPContext using IPnPContextFactory

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: Win10
- **SDK used in**: Azure Function
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022 RC

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@stonekw : please have a look at https://pnp.github.io/pnpcore/tutorials/azurefunctions/v4processisolatedapponly.html, this tutorial shows how you can PnP Core SDK in an Azure Function. You need to make two small changes to the sample code to get your scenario to work: 

In CreateSite.cs  replace `using (var pnpContext = await contextFactory.CreateAsync("Default"))` with `using (var pnpContext = await contextFactory.CreateAsync(new Uri("https://bertonline.sharepoint.com/sites/prov-2")))` allowing you to specify the site collection url you need.

In Program.cs in the `services.AddPnPCoreAuthentication` add `options.Credentials.DefaultConfiguration = "CertAuth";` at the end of the block to ensure the configured auth provider is the default one for contexts created without specifying an explicit auth provider.

**Comment by stonekw** [comment]
@jansenbe  thanks, I created a new project that uses .net isolated, same as the example, and it seems to work now. To clarify, are we saying PnP core only supports out-of-process/isolated functions? Was hoping to keep it in-process since I will be converting this to a durable function, which is still only in beta for isolated functions.

**Comment by jansenbe** [comment]
@stonekw : both models should work, it's just a sample and for that we used out-of-process.
