### ISSUE TITLE
SPQueryThrottledException while loading document libraries with more than 5000 elements

### ISSUE THREAD

**Issue by bajce** [pnp/pnpcore#1044]
Im loading the Items by following CamlQuery:

`<View>
  <Query>
  </Query>
  <OrderBy Override='TRUE' ><FieldRef Name='ID' Ascending='FALSE' /></OrderBy>
  <RowLimit>{PAGE_SIZE}</RowLimit> 
</View>` 
and using `list.LoadItemsByCamlQuery(...)` with paging as described on API documentation page.

However when a list has more than 5000 elements I'm getting `SPQueryThrottledException` with message (translated) "The attempted operation is invalid because it exceeds the list view threshold."

By setting the RowLimit and using pagination I was expecting that im able to work with libraries that contain more than 5000 elements as im not loading them all at once with one server round trip but for each page one.

I found some articles which advice to modify the query so no more than 5000 elements are returned but I thought by setting the row number and using pagination approach only `PAGE_SIZE` (in my case 500) elements should be returned at once. 

Besides that, by using my workaround from [#839](https://github.com/pnp/pnpcore/issues/839) when some of the folders contain `#` or `$` im forced to set Caml query scope to RecursiveAll meaning that 5000 elements limit will even be reached faster as im not able to load the items by depth level. 

In our solution we are loading all SharePoint securables, therefore we are looking for workaround for this limitation.

**Comment by bajce** [comment]
> 

@jansenbe I just tried your suggestion but it didn't change anything. Im still getting same Exception.

**Comment by jansenbe** [comment]
@bajce : can you try to simplify the where clause of the CAML query or removing it all together?

**Comment by jansenbe** [comment]
@bajce : using `LoadListDataAsStreamAsync` there are no issues in my testing, the `LoadItemsByCamlQueryAsync` keeps on failing so far. See #919 and #586 for more context. See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#c-getting-list-items-via-the-loaditemsbycamlquery-approach for docs. Now, I'm not sure if `LoadListDataAsStreamAsync` will allow all your other scenarios... Will do some more testing with `LoadItemsByCamlQueryAsync` to see if I can get that to work properly

```csharp
string viewXml1 = @"<View>
                        <ViewFields>
                          <FieldRef Name='Title' />
                          <FieldRef Name='FileLeafRef' />
                          <FieldRef Name='FSObjType'/>
                          <FieldRef Name='FileDirRef'/>
                        </ViewFields>
                        <Query>
                          <Where>
                            <Contains>
                              <FieldRef Name='FileLeafRef'/>
                              <Value Type='Text'>File_10</Value>
                            </Contains>
                          </Where>
                        </Query>
                        <OrderBy Override='TRUE'><FieldRef Name='ID' Ascending='FALSE' /></OrderBy>
                        <RowLimit Paged='TRUE'>500</RowLimit>
                       </View>";

                string viewXml = @"<View>
                        <ViewFields>
                          <FieldRef Name='Title' />
                          <FieldRef Name='FileLeafRef' />
                          <FieldRef Name='FSObjType'/>
                          <FieldRef Name='FileDirRef'/>
                        </ViewFields>
                        <OrderBy Override='TRUE'><FieldRef Name='ID' Ascending='FALSE' /></OrderBy>
                        <RowLimit Paged='TRUE'>500</RowLimit>
                       </View>";

                // Fails:
                //await myList.LoadItemsByCamlQueryAsync(new CamlQueryOptions { ViewXml = viewXml, PagingInfo = null });

                // Works:
                await myList.LoadListDataAsStreamAsync(new RenderListDataOptions()
                {
                    ViewXml = viewXml,
                    RenderOptions = RenderListDataOptionsFlags.ListData,
                    Paging = null,
                });
```

**Comment by jansenbe** [comment]
@bajce : adding `Scope='RecursiveAll'` makes the CAML query work, using a where clause (like in viewXml1 in previous comment) does not work.

```csharp
string viewXml = @"<View Scope='RecursiveAll'>
                        <ViewFields>
                          <FieldRef Name='Title' />
                          <FieldRef Name='FileLeafRef' />
                          <FieldRef Name='FSObjType'/>
                          <FieldRef Name='FileDirRef'/>
                        </ViewFields>
                        <OrderBy Override='TRUE'><FieldRef Name='ID' Ascending='FALSE' /></OrderBy>
                        <RowLimit Paged='TRUE'>500</RowLimit>
                       </View>";

                // Fails:
                await myList.LoadItemsByCamlQueryAsync(new CamlQueryOptions { ViewXml = viewXml, PagingInfo = null });
```

**Comment by jansenbe** [comment]
@bajce : closing this one, re-open if you can't get things to work.

**Comment by bajce** [comment]
@jansenbe sorry for late answer but I had couple of day off. Unfortunately non of the suggestions is not applicable in our solution. 

_"If you really need the where clause you might need to ensure proper indexed columns to back the filter when using LoadItemsByCamlQueryAsync"_ 
In our solution we are reading the SharePoint data of different customers and we are not able to force them to create indexes on specific columns so we could read the list. 

_"Adding Scope='RecursiveAll' makes the CAML query work, using a where clause"_
I can't completely ignore where clause as sometimes we just want to read folders and not files (depending on configuration) so we filter for specific `FSObjType`. In some cases we are using where in order to find the specific item by UniqueID. Also when reading the items of some folder we use where clause to filter on `FileDirRef` so only items of this folders are returned.

_"using LoadListDataAsStreamAsync there are no issues in my testing"_
Using  `LoadItemsByCamlQueryAsync` im able to load additional properties with selectors and by using `LoadListDataAsStreamAsync ` not. For example:

`list.LoadItemsByCamlQuery(new CamlQueryOptions()
                        {
                            ViewXml = camlQueryOptions.ViewXml,
                            DatesInUtc = true,
                            PagingInfo = nextPage,
                            FolderServerRelativeUrl = camlQueryOptions.FolderServerRelativeUrl
                        },
                        item => item.UniqueId,
                        item => item.FileSystemObjectType,
                        item => item.FieldValuesAsText,
                        item => item.File,
                        item => item.Folder,
                        item => item.HasUniqueRoleAssignments);`

Even do the suggestions from above are maybe applicable in some scenarios, they still don't cover all use cases. I think this issue should be reopened.

**Comment by jansenbe** [comment]
@bajce : sure, I'll re-open this one for now.

**Comment by jansenbe** [comment]
@bajce : I don't see much other solutions then then one I described, this is how SharePoint works today and this open-source project cannot change that, we can try to get the most out of the existing SharePoint APIs. Using `LoadItemsByCamlQuery` is more strict compared to `LoadListDataAsStreamAsync` and I do understand why you've chosen that approach. Options I see are: - experiment with the used CAML query and maybe have a special case for whenever the list you're processing has more than 5000 items
- Use `LoadListDataAsStreamAsync` with your current CAML query when the list has more than 5000 items and then use a less optimal approach to fetch the security settings

**Comment by jansenbe** [comment]
@bajce : any feedback here?

**Comment by bajce** [comment]
@jansenbe unfortunately I won't be able to adapt the solution with special case when list has more  than 5000 elements that fast due to tasks of higher priority. If you prefer to close  the issue I totally understand that. I will post the feedback once I tried that.

**Comment by jansenbe** [comment]
Gonna close this then, let me know how it things turn out. Don't see many other options besides the already mentioned options, so hope one these work for you.
