### ISSUE TITLE
Support passing X509 object to OnBehalfOfAuthenticationProvider

### ISSUE THREAD

**Issue by rlv-dan** [pnp/pnpcore#1046]
## Category

- [x] Feature request

## Describe the feature

When creating an `X509CertificateAuthenticationProvider` you can either provide StoreName/StoreLocation/Thumbprint or a ready `X509Certificate2` object. Great! Another provider I was using is `OnBehalfOfAuthenticationProvider`. But this only accepts the StoreName/StoreLocation/Thumbprint parameters, not a certificate object.

_Originally posted by @rlv-dan in https://github.com/pnp/pnpcore/issues/897#issuecomment-1339067652_
## Describe the solution you'd like

Allow creation of `OnBehalfOfAuthenticationProvider` with an `X509Certificate2` object in addition to Thumbprint

**Comment by mloitzl** [comment]
@jansenbe I could have a look at this one...

**Comment by jansenbe** [comment]
Thanks for helping out @mloitzl 💪🚀

**Comment by jansenbe** [comment]
Thanks for your PR @mloitzl ! @rlv-dan , you can use this using the next nightly build (version 1.8.33 or higher). Closing issue now, feel free to re-open in case needed
