### ISSUE TITLE
Add support to the IWeb WebTemplatesGalleryFirstRunEnabled property

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#1057]
## Category

- [x] Domain model extension

## Describe the domain model extension

The IWeb already supports the boolean property to manage the first run of the next steps wizard through `NextStepsFirstRunEnabled`. Another property called `WebTemplatesGalleryFirstRunEnabled` controls if the web template gallery should be displayed. Latter is missing in IWeb.

### Additional Information

Properties can be controlled with these examples: 
- https://areflyen.no/2022/05/25/hide-the-next-steps-dialog-from-newly-created-sites-in-sharepoint/
- https://areflyen.no/2022/05/25/hide-the-template-gallery-from-newly-created-sites-in-sharepoint/

**Comment by plamber** [comment]
Do you have a recommendation how to temporarily add a batch request for a missing property until the SDK is supporting this?

**Comment by jansenbe** [comment]
@plamber : adding this one right now, can trigger an extra nightly build if you need it today

**Comment by plamber** [comment]
Would be awesome. Would this be the right approach to patch the Web and add it as Batch?

```
string body = SerializeJSON(new
{
    WebTemplatesGalleryFirstRunEnabled = spWeb.WebTemplatesGalleryFirstRunEnabled.Value
});
var accessRequest = new ApiRequest(HttpMethod.Patch, ApiRequestType.SPORest, "_api/web", body);
web.ExecuteRequestBatch(accessRequest);
```

**Comment by jansenbe** [comment]
See https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#batching-custom-api-requests for the batching of custom API calls. 

I've just pushed the change, if you can wait for 30 minutes there's a new nightly release that contains this, so then you don't need to fall back to a custom API call

**Comment by jansenbe** [comment]
Nightly nuget release running, when you see version 1.8.37 appearing then that's the version that contains this change

**Comment by plamber** [comment]
Thank you. Highly appreciated
