### ISSUE TITLE
Changed properties are not updated if not initially loaded

### ISSUE THREAD

**Issue by ypcode** [pnp/pnpcore#106]
## Category

- [x] Bug

## Describe the bug

When trying to update a property that was not specifically loaded, it does not get added to the changed properties and then is not saved when calling an update method

## Steps to reproduce

With the following code
```csharp
IList sharedDocs = await context.Web.Lists.GetByTitleAsync("Documents");
// Enable major versioning
sharedDocs.Title = "Documents UPDATED";
sharedDocs.EnableMinorVersions = true;
await sharedDocs.UpdateAsync();
```
`Title` of the list is updated, but not `EnableMinorVersions`

With the following code
```csharp
IList sharedDocs = await context.Web.Lists.GetByTitleAsync("Documents", l => l.EnableMinorVersions);
// Enable major versioning
sharedDocs.Title = "Documents UPDATED";
sharedDocs.EnableMinorVersions = true;
await sharedDocs.UpdateAsync();
```

`EnableMinorVersions` is updated but not `Title`

The values of properties are not updated, but no error is raised

## Expected behavior

Either handle seamlessly the change of not specifically loaded properties
Or raise an error when trying to set a value of a not loaded property

## Environment details (*development & target environment*)

- **SDK version**: latest dev
- **OS**: Windows 10
- **SDK used in**: Console App / Unit Tests
- **Framework**: *
- **Browser(s)**: -
- **Tooling**: Visual Studio 2019
- **Additional details**: -

### Additional context
 ...

**Comment by jansenbe** [comment]
Implemented
