### ISSUE TITLE
Improve error handling to avoid issuing API calls with unresolved tokens

### ISSUE THREAD

**Issue by ypcode** [pnp/pnpcore#107]
## Category

- [x] Feature request

## Describe the feature

In some cases, especially in Batch calls, the tokens (e.g. `{Id}`, `{Parent.Id}`, ...) might not be resolved, that leads the service the return an error because the API URI is invalid.

## Describe the solution you'd like

 It would be preferred to raise a client exception that states what information is not resolved (not available) before issuing the API call.

## Additional context

Here is some code that illustrates a case where this happens
```csharp
string testDocumentServerRelativeUrl = $"{context.Uri.PathAndQuery}/Shared Documents/test.docx";
IFile testDocument = await context.Web.GetFileByServerRelativeUrlBatchAsync(testDocumentServerRelativeUrl);

// At this point, the Id of the document to publish is not yet known since it will be part of the same Batch call
await testDocument.PublishBatchAsync("TEST PUBLISH WITH BATCH");
await context.ExecuteAsync();
```

**Comment by jansenbe** [comment]
Implemented
