### ISSUE TITLE
"No User or App Context found" when trying to perform a Search

### ISSUE THREAD

**Issue by Gareth064** [pnp/pnpcore#1070]
## Category

- [x] Bug

## Describe the bug

When trying to perform a Search, I get a `No User or App Context found` error from the SharePoint REST Service.

## Steps to reproduce

**Configuration**
```cs
public static IServiceCollection AddFilingService(this IServiceCollection services,
        string clientId,
        string tenantId,
        string certificateThumbprint,
        string baseSiteURL,
        string[] sites)
    {


        services.AddPnPCore(options =>
        {
            // Configure an authentication provider with certificate (Required for app only)

            var authProvider = new X509CertificateAuthenticationProvider(clientId,
                tenantId,
                StoreName.My,
                StoreLocation.LocalMachine,
                certificateThumbprint);

            // And set it as default
            options.DefaultAuthenticationProvider = authProvider;

            foreach (var site in sites)
            {
                var siteUrl = $"{baseSiteURL}/sites/{site}";

                options.Sites.Add(site,
                    new PnP.Core.Services.Builder.Configuration.PnPCoreSiteOptions
                    {
                        SiteUrl = siteUrl,
                        AuthenticationProvider = authProvider
                    });
            }

            options.PnPContext.GraphFirst = false;

        });
```

**Usage**
```cs
public async Task<string> GetDocumentURLFromUniqueId(string site, string uniqueDocumentId)
    {
        try
        {
            SearchOptions searchOptions = new SearchOptions($"uniqueId: {uniqueDocumentId}")
            {
                SelectProperties = new List<string> { "EncodedAbsUrl", "FileRef" }
            };

            using var pnpContext = await pnpContextFactory.CreateAsync(site);

            var searchResults = await pnpContext.Web.SearchAsync(searchOptions);  /////// Errors Here

            foreach (var item in searchResults.Rows)
            {
                Console.WriteLine(item["EncodedAbsUrl"]);
                Console.WriteLine(item["FileRef"]);
            }

            return "";
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            Console.WriteLine(ex);
        }
        return "";
    }
```

**Full Error**
```
SharePoint Rest service exception
HttpResponseCode: 400
Code: Microsoft.Office.Server.Search.REST.SearchServiceException
Message: No User or App Context found
ClientRequestId: ad238ba0-d057-6000-0df7-040704a33503
SPClientServiceRequestDuration: 68
X-SharePointHealthScore: 3
X-SP-SERVERSTATE: ReadOnly=0

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.SharePoint.Web.SearchAsync(SearchOptions query)
   at CHG.SPO.FilingService.Brokers.Apis.SharePointOnlineBroker.GetDocumentURLFromUniqueId(String site, String uniqueDocumentId) in C:\code\Clarion Application Services\SPOFiling\src\CHG.SPO.FilingServiceLibrary\Brokers\Apis\SharePointOnlineBroker.Documents.cs:line 20
```

## Expected behavior

Return a search result

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: Windows Server 2019
- **SDK used in**: Currently Testing in a Console app, but destined for a Web API
- **Framework**: Dotnet 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
Hi @Gareth064 , thanks for using PnP Core SDK!

Question: what permissions did you grant your app in Azure AD? To use search via app-only you need to grant Sites.FullControl.All

**Comment by Gareth064** [comment]
I don't want to use MS Graph if possible. Especially if it is being granted Sites.FullControl.All. Our IT Security team will not be happy with that as I only have to interact with a small set of sites. Hence using the SharePoint.SelectedSites approach.

**Comment by jansenbe** [comment]
@Gareth064 : unfortunately the `sites.selected` permission scope does not work when using search. The search backend is not (yet) able to trim the results for just the site collections granted access via `sites.selected`. We're looking into improving this scenario, but as we're only in an early design phase for that it will take a long time before a solution hits the service.

**Comment by Gareth064** [comment]
Thanks @jansenbe, is this a limitation of this library, or of the SharePoint backend?

Either way, do you have any suggestions on how I can find a document using it's unique ID across all sites of which the App Registration has access to? 😄

**Comment by jansenbe** [comment]
@Gareth064 : it's a SharePoint limitation. 

If you happen to have something else besides just the unique ID (e.g. a sharing link) you can use the `GetFileByLink` methods (see https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#get-a-file-using-a-link). If you have the driveid and /or driveitemid you can decode that via https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Utilities/DriveHelper.cs.

If you only have the unique id's and you know the sites your app has access to you can opt to iterate over the webs and try to load the file via the `GetFileById` methods (see https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#getting-a-single-file). Obviously this approach is not optimal and might not work for your scope.

Other approach is running part of the your logic using a service account and delegated permissions, not ideal either though.

**Comment by Gareth064** [comment]
Thanks for the advice @jansenbe . I got the Search working with `Sites.Read.All` which is an easier conversation to have with IT Security. But good to know that there is an alternative approach I can test.

**Comment by jansenbe** [comment]
@Gareth064 : interesting and good to see it working with `sites.read.all`, still assumed we needed more permissions. Will cross check that on this.

**Comment by Gareth064** [comment]
If it helps, this is the exact api permissions I have granted
![image](https://user-images.githubusercontent.com/22307223/211801373-0fc4c0ab-164d-4350-8bab-f9422de15ab8.png)

**Comment by jansenbe** [comment]
@Gareth064 : using `sites.read.all` indeed works, just tested myself. Talking with search folks this most likely is because the Graph search API in beta now also supports application permissions using `sites.read.all` or `files.read.all`. 

Think we can close the issue now?

**Comment by heinrich-ulbricht** [comment]
Just fyi: the original ask still doesn't work (app-only + Sites.Selected + search). Tried it, got the "No User or App Context found" error, Google sent me here ^^
