### ISSUE TITLE
Navigation Audience Targeting Features Missing

### ISSUE THREAD

**Issue by benjblack** [pnp/pnpcore#1072]
## Category

- [x] Bug

## Describe the bug

The sample code under the "Using audience targeting" topic is not working:
https://pnp.github.io/pnpcore/using-the-sdk/audience-targeting-intro.html?q=audience            

## Steps to reproduce

```
var node = await context.Web.Navigation.QuickLaunch.AddAsync(
                new NavigationNodeOptions
                {
                    Title = "My node",
                    Url = "/sites/demo/mylibrary",
                    AudienceIds = new List<Guid> { Guid.Parse("7bf72917-4c72-4a83-91d6-1362fcf7222a"),  Guid.Parse("0402aa20-e67a-47e3-bad4-03801247be9e") }
                });
```

The above code produces this error:

Error	CS0117	'NavigationNodeOptions' does not contain a definition for 'AudienceIds'	

```
// Load the node to update
var node = await context.Web.Navigation.QuickLaunch.GetByIdAsync(1204);

// Update the node by adding an audience
node.AudienceIds = new System.Collections.Generic.List<Guid> { Guid.Parse("7bf72917-4c72-4a83-91d6-1362fcf7222a") };
await node.UpdateAsync();
```

The above code produces this error: 
Error	CS0200	Property or indexer 'INavigationNode.AudienceIds' cannot be assigned to -- it is read only	

## Expected behavior

The provided code examples should work

## Environment details (*development & target environment*)

- **SDK version**: tested in 1.7.0 and 1.8.0
- **OS**: Windows 10 
- **SDK used in**: .NET Core app
- **Framework**: .NET 6.0
- **Browser(s)**: n/a
- **Tooling**: Visual Studio 2022 (17.1.16)

### Additional context

n/a

**Comment by jansenbe** [comment]
Please use the latest nightly, this functionality was just checked in a few days ago.

**Comment by benjblack** [comment]
That worked - thanks!
