### ISSUE TITLE
"Unresolved tokens" error when looping through navigation nodes 

### ISSUE THREAD

**Issue by benjblack** [pnp/pnpcore#1074]
## Category

- [x] Bug

## Describe the bug

The sample code under the "Working with navigation" topic is not working:
https://pnp.github.io/pnpcore/using-the-sdk/navigation-intro.html?q=navigation

## Steps to reproduce

```
var quickLaunchEnum = quickLauchNav.QuickLaunch.GetEnumerator()
```

The above code produces an error:

*PnP.Core.ClientException : Unresolved tokens found in API call https://ktslaw.sharepoint.com/sites/EliteHub/_api/Web/Navigation/GetNodeById({Id})?$top=100*

## Expected behavior

Need a way to loop through navigation nodes.

## Environment details (*development & target environment*)

- **SDK version**: tested in 1.8.67-nightly
- **OS**: Windows 10 
- **SDK used in**: .NET Core app
- **Framework**: .NET 6.0
- **Browser(s)**: n/a
- **Tooling**: Visual Studio 2022 (17.1.16)

### Additional context

n/a

**Comment by jansenbe** [comment]
@benjblack : can you do something like this:

```csharp
var web = context.Web.Navigation.Get(n => n.QuickLaunch);

foreach(var node in web.QuickLaunch.AsRequested())
{
  // do something with the navigation node
}
```

**Comment by jansenbe** [comment]
@benjblack : did above help? Can we close this issue?

**Comment by jansenbe** [comment]
@benjblack : I'm closing this issue, if the problem still persists then please re-open or create a new one. Thanks for using PnP Core SDK.
