### ISSUE TITLE
Include private channel sites in GetSiteCollectionsWithDetailsAsync() with application permissions

### ISSUE THREAD

**Issue by valpvt** [pnp/pnpcore#1076]
## Category

- [x] Feature request

## Describe the feature

> Update the `GetSiteCollectionsWithDetailsAsync()`  method to return private channel sites when using app permissions.

## Describe the solution you'd like

> When listing all site collections in the M365 Tenant it would be useful to get private channel sites as well. 

## Additional context

> This is currently possible with `Get-PnPTenantSite -Detailed` in PowerShell

**Comment by jansenbe** [comment]
@valpvt : that's a good addition to have. I'll have a look.

**Comment by jansenbe** [comment]
@valpvt : using `GetSiteCollectionsWithDetailsAsync` you can now specify a bool to request loading of the sites behind private/shared team channels. This will be part of the next nightly build (version 1.8.79 or higher). I'm closing this issue now, feel free to re-open or create a new in case the feature is not working as expected.
