### ISSUE TITLE
Unable to find example in documentation for renaming folder

### ISSUE THREAD

**Issue by No1e** [pnp/pnpcore#1080]
## Category

- [x] Bug
No documentation regarding an example how to rename folder

## Environment details (*development & target environment*)

- **SDK version**: [e.g. 0.1.2005.0 ]
- **OS**: Windows 10 
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2020
- **Additional details**: N/A

### Additional context

None

**Comment by jansenbe** [comment]
@No1e : renaming folders was indeed not easy enough, therefore I've added a new method `RenameFolder` on `IFolder` that you can use with the next nightly release. Closing this issue now, if you still have issues when using the next nightly then please re-open or create a new issue

**Comment by No1e** [comment]
@jansenbe 
Awesome. Thank you very much!

Nice weekend!

Best regards,
Nole
