### ISSUE TITLE
Not Implemented PageLayoutType enum lookup "NewsDigest"

### ISSUE THREAD

**Issue by DmitriiPavlenko** [pnp/pnpcore#1086]
## Category

- [x] Bug

## Describe the bug

Loading pages from site where Page with type "News Digest" is present causing unhandled enum parsing exception in file 
https://github.com/pnp/pnpcore/blob/1.8.0/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs line 983

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/61537467/216389823-dbe55479-43c1-4117-8067-69f6bcbaefa8.png">

My StackTrace

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/61537467/216390544-da95238b-1f8c-4b4b-82c0-e7eaa395effe.png">

## Steps to reproduce

1. Create page on your Sharepoint site with "News Digest" type https://support.microsoft.com/en-us/office/create-and-send-a-news-digest-42efc3c6-605f-4a9a-85d5-1f9ff46019bf.
2. Init PnP context with Sharepoint site url where you create the page.
3. Execute `PnPContext.Web.GetPagesAsync()` method on previously initialised context.

## Expected behavior

- Page has to be loaded alongside with other pages;
- Pages loading should not be affected by single page loading error;
- `Enum.Parse` should be changed to `Enum.TryParse` with appropriate handling.

## Environment details (*development & target environment*)

- **SDK version**: 1.8
- **OS**: Linux
- **SDK used in**: ASP.Net Web app
- **Framework**: NET 6
- **Browser(s)**: non related
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@DmitriiPavlenko : I've implemented support for this, you can now read news digest pages and if needed clone them. There's no support for creating those using the API, does not feel like an API scenario. The updates will be included in the next nightly build (version 1.8.97 or higher), will close the issue now but feel free to re-open or create a new one if the implemented fix is not working for you.
