### ISSUE TITLE
CopyTo and CopyToAsync ignores MoveCopyOptions for same site 

### ISSUE THREAD

**Issue by bburramukku** [pnp/pnpcore#1091]
## Category

- [x] Bug

## Describe the bug

1) In CopyTo Method MoveCopyOptions parameter is ignored when calling CopyToAsync

2) In CopyToAsync MoveCopyOptions are preserved only if the copy is to a different site

We are trying to use ResetAuthorAndCreatedOnCopy while copying a file in the same site and it's not working

![image](https://user-images.githubusercontent.com/23268647/217669937-07fedd6f-0b84-49da-87bd-82cb71d24d05.png)

## Expected behavior

When copying a file I am expecting the author and Created information will be reset to "SharePoint App" like Modified By

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0 
- **OS**: Windows 10
- **SDK used in**: Azure Function App
- **Framework**:.NET 6
- **Browser(s)**: Chrome
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
See also #989

**Comment by jansenbe** [comment]
@bburramukku : now the same implementation is used for copy, regardless of intra site or cross site and this will fix your issue. This change will appear in the next nightly (version 1.8.100 or higher). Closing this issue now, please re-open or create a new one if the issue is still not solved.
