### ISSUE TITLE
Not able to create group in a site using pnp core c# sdk

### ISSUE THREAD

**Issue by sagar-agaskar** [pnp/pnpcore#1093]
private void CreateGroupDestination(GroupInfo srcGroupInfo, PnPContext destContext)
        {
            try
            {
                destContext.Web.Load(p => p.SiteGroups.QueryProperties(u => u.Users, u => u.Title, u => u.OwnerTitle));                

                var destGroup = destContext.Web.SiteGroups;               
                destGroup.Add("ABC");
             }
}

 I am trying to create group in site whose context is available with me but while calling Add method with group name as string "ABC" am getting Sharepoint rest exception System.UnauthorizedAccessException 403 status code.

However am able to fetch all group details using c# and I am using site collection admin credentails.

**Comment by jansenbe** [comment]
@sagar-agaskar : what permissions did you grant to your app in Azure AD: you need "Full Control" to manage permissions.

**Comment by sagar-agaskar** [comment]
API / Permissions name	Type	Description	Admin consent required	Status

Microsoft Graph (1)		
		
User.Read	Delegated	Sign in and read user profile	No	 Granted for q7q0

SharePoint (9)	
			
Sites.FullControl.All	Application	Have full control of all site collections	                        Yes	 Granted for q7q0
Sites.Manage.All	Application	Read and write items and lists in all site collections	Yes	 Granted for q7q0
Sites.Read.All	Application	        Read items in all site collections	                 Yes	 Granted for q7q0
Sites.ReadWrite.All	Application	Read and write items in all site collections	Yes	 Granted for q7q0
Sites.Selected	Application	        Access selected site collections	                 Yes	 Granted for q7q0
TermStore.Read.All	Application	Read managed metadata	                        Yes	 Granted for q7q0
TermStore.ReadWrite.All	Application	Read and write managed metadata	Yes	 Granted for q7q0
User.Read.All	Application	                Read user profiles	                                 Yes	 Granted for q7q0
User.ReadWrite.All	Application	Read and write user profiles	                          Yes	 Granted for q7q0

**Comment by sagar-agaskar** [comment]
I have given all possible permissions for SharePoint

**Comment by jansenbe** [comment]
Hey @sagar-agaskar ,

I justed reran our test case that creates and configures a SharePoint group and that worked fine using delegated permissions. Looking at the table able you've granted "application" permissions, so assume you're testing with application permissions?

https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/Security/SharePointGroupTests.cs
![image](https://user-images.githubusercontent.com/7451219/218061971-ffb9b97d-a75c-4d3a-927b-19a9eb9918c9.png)

**Comment by jansenbe** [comment]
@sagar-agaskar : any feedback here?

**Comment by jansenbe** [comment]
@sagar-agaskar : closing this one per no response. See above mentioned unit test for an example on how to do this.
