### ISSUE TITLE
Feature request : Add the capability to approve permission requests like m365 cli `m365 spo serviceprincipal permissionrequest approve`

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#1096]
Feature request :
Add the capability to approve permission requests like m365 cli
`m365 spo serviceprincipal permissionrequest approve`

We are able to use pnpcore to deploy SPFx app to app catalog. However, the app request permission to call Graph API. 
The only step we couldn't automate is the permission requests approval step.

_Originally posted by @larry-lau in https://github.com/pnp/pnpcore/issues/897#issuecomment-1419680527_

**Comment by mloitzl** [comment]
@jansenbe I had a quick look at it.

- The CSOM queries could be taken straight from the m365 cli project
- I am not quite sure where this should go... -  I reckon somewhere in `PnP.Core.Admin`, but this would need a new Model... probably `ServicePrincipal` or `SPOServicePrincipal` and at least some functionality for PermissionRequests list, approve and deny? I never extended model before...

**Comment by jansenbe** [comment]
@mloitzl : yes, this would require a new model in `PnP.Core.Admin`, think that's the easiest and most reusable approach. Regarding the CSOM queries: in cli they are quite hardcoded, in PnP Core SDK we use a different model, one that allows to batch CSOM queries. If there's no REST/Graph equivalent for the API calls then CSOM has to be used by using our model. See https://github.com/pnp/pnpcore/tree/dev/src/sdk/PnP.Core.Admin/Services/Core/CSOM/Requests/Tenant for some sample CSOM operations.

**Comment by mloitzl** [comment]
@jansenbe Did't have so much time this week... but here's a draft
https://github.com/pnp/pnpcore/pull/1100

**Comment by jansenbe** [comment]
@mloitzl : awesome! Thanks for helping out 💪🚀Will review the PR early next week.

**Comment by jansenbe** [comment]
@mloitzl : just reviewed and merged your PR, great job! Thanks a lot for your contribution to PnP Core SDK!!!

@larry-lau: please try this feature with the next nightly release (version 1.8.107 or higher).  See https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-apps.html#list-approve-or-reject-the-permissions-requests-for-an-app for the docs.

Will close this issue now, please create new issue if things are not working @larry-lau, thank you @mloitzl for building the feature.

**Comment by larry-lau** [comment]
Thank you for implementing the feature so quickly.  However, the ServicePrincipal class is internal so I am not able to instantiate.

**Comment by mloitzl** [comment]
Oops... that's a very obvious one 😆
I'll come up with a fix during the weekend

**Comment by jansenbe** [comment]
@larry-lau : thanks for spotting that one @larry-lau and thanks for the fix @mloitzl . Our test project can see the internals of PNP Core SDK, hence this passed our checks.

**Comment by larry-lau** [comment]
Thanks! Which nightly build would have the new getter on IAppManager so I can test this out?

**Comment by jansenbe** [comment]
The one out now

**Comment by larry-lau** [comment]
I have tested the API. Looking good.  I would suggest renaming  IPermissionRequest.PackageApproverName to RequesterName
