### ISSUE TITLE
Implement model for SP Users

### ISSUE THREAD

**Issue by ypcode** [pnp/pnpcore#110]
## Category

- [x] Domain model extension

## Describe the domain model extension

Get the users of a site, is also used as property values in several other entities (`CreatedBy`, `CheckedOutTo`, ...)

### Model

Model: __User__
Properties: __Web.SiteUsers__, __Web.CurrentUser__, ...

### APIs

API :  
`https://graph.microsoft.com/v1.0/users`  (If needed)
`https://<tenant>.sharepoint.com/sites/<site>/_api/web/SiteUsers/`

### Additional Information

Inherits `IPrincipal` : should probably implement this base model

[Microsoft Official CSOM Doc](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee540236(v%3doffice.15))

**Comment by ypcode** [comment]
Hi guys, taking this one :)

**Comment by jansenbe** [comment]
Linked discussion: #111

**Comment by ypcode** [comment]
I think this one can be closed since #139 was created.
