### ISSUE TITLE
GetFileByServerRelativeUrl and 400 error when multiple large file versions exist

### ISSUE THREAD

**Issue by therealsupercarl** [pnp/pnpcore#1110]
https://github.com/pnp/pnpcore/blob/2f632e19a4e9e8b52863835d12448df55950f778/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/Web.cs#L588

Has anyone run into problems trying to get file information when there are excessively large versions in play? For example, I'm using a call that looks like this on a document that has 2 versions that are 3.9GB each:

file = await _context.Web.GetFileByServerRelativeUrlAsync(this.FileRef, f => f.Properties, f => f.MajorVersion, f => f.ServerRelativeUrl, f => f.Versions);

The underlying SharePoint api call "_api/Web/getFileByServerRelativePath" throws a SharePoint Rest service exception:

HttpResponseCode: 400
Code: System.InvalidOperationException
Message: Operation is not valid due to the current state of the object.

I've had an open case with Microsoft about the underlying API call going on 9 weeks now. I've even going so far as replicating the issue in our environment using Postman to call the API directly.

Is there another call I can use in the pnpcore 1.8 release that might work instead of "GetFileByServerRelativeUrl"?

**Comment by jansenbe** [comment]
@therealsupercarl : you can try with `GetFileById`, but I'm afraid the result will be the same. You see the same issue when you skip loading the versions?

**Comment by therealsupercarl** [comment]
@jansenbe: Sadly, I need the list of versions so that we can strategically prune them to help control storage costs. We've found that file versions in our active Teams (SharePoint) file content is about half of the storage being consumed.

Thanks for the GetFileById suggestion which we'll look into. If I come up with a different approach or make some headway with MS support I'll post back here.

**Comment by jansenbe** [comment]
@therealsupercarl : maybe using Graph you can get to the file versions for these very large files (https://learn.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&tabs=http). Once you have a file version, how do you plan to prune it?

**Comment by jansenbe** [comment]
@therealsupercarl : as this is not an SDK issue I plan to close this one unless you think otherwise?

**Comment by therealsupercarl** [comment]
@jansenbe: Once I get the version info, I'm using the ```DeleteAll``` and```DeleteByLabel``` SharePoint API calls similar to this:

```
string apiRelativeUrl = $"_api/web/getFileById('{this.Id}')/versions/DeleteByLabel('{fileVersion.VersionLabel}')";

var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, apiRelativeUrl , body, headers);
response = await _context.Web.ExecuteRequestAsync(apiRequest);
```

I hadn't seen GetFileById since it wasn't exposed in v1.8. I did try GetFileById with a recent nightly build and that failed as well. I'm finally getting traction with MS Support, so, maybe they'll fix the underlying issue in the SharePoint APIs. I may still pursue the Graph route depending on the timeline MS Support comes back with.

Thanks for the suggestions.
