### ISSUE TITLE
Feature enable or disable service principal

### ISSUE THREAD

**Issue by mloitzl** [pnp/pnpcore#1118]
## Category

- [x] Feature request

## Describe the feature

> Enable or disable the Service Principal like in `m365 spo serviceprincipal set ...`

## Describe the solution you'd like

> Enable or disable the service principal

**Comment by mloitzl** [comment]
See: https://github.com/pnp/pnpcore/pull/1117

**Comment by jansenbe** [comment]
Thanks a lot @mloitzl , nice addition! Just merged this one.
