### ISSUE TITLE
why the IListItem does not have a method to MoveTo() a folder

### ISSUE THREAD

**Issue by mvcsharepointdev** [pnp/pnpcore#1124]
## Category

- [x] Feature request

## Describe the feature

If we want to move a custom list item to a folder within the list the IListItem does not have a method to Move()

## Describe the solution you'd like

We need the IListItem to have a MoveTo() method similar to the IFile..

**Comment by jansenbe** [comment]
@mvcsharepointdev : technically speaking this is possible, it's just not implemented in PnP Core SDK. https://michelcarlo.com/2019/03/04/microsoft-flow-how-to-move-sharepoint-online-list-items-to-folders/ and it's comments contains some good pointers. If you need this urgently you can implement the needed API calls yourself using our custom API calling option (see https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request). 

Let's add this request to the backlog for future addition.

**Comment by mloitzl** [comment]
@jansenbe I figured it out how this works, I can implement it during this or probably the next weekend.
😎

**Comment by jansenbe** [comment]
That would be awesome @mloitzl !! Thanks for helping out with PnP Core SDK 👍

**Comment by mloitzl** [comment]
https://github.com/pnp/pnpcore/pull/1146

**Comment by jansenbe** [comment]
Thanks a ton @mloitzl !

@mvcsharepointdev : the feature is in our next nightly (and soon to be released version 1.9). Closing this issue now, let me know if you still have issues with this.
