### ISSUE TITLE
Support for .Net Framework 4.7

### ISSUE THREAD

**Issue by 3baaady07** [pnp/pnpcore#1128]
## Category

- [x] Feature request

## Describe the feature

> Support for .Net Framework 4.7

## Describe the solution you'd like

> I keep getting this error. 

```
The primary reference "myReference" could not resolve 
because it had an indirect dependency on assembly "AngelSharp, Version=0.14.0.0" 
which was build against the ".NETFramework,Version=4.7.2" framework. 
```

## Additional context

> I'm locked to this version of.NETFramework as I'm using SSIS and they don't support higher versions. See screen shot
![image](https://user-images.githubusercontent.com/18297214/223044401-b35746cd-8856-48a7-a8f2-ff9d88947056.jpeg)

**Comment by jansenbe** [comment]
@3baaady07 : the library ships as .NET Standard 2.0 version, which can be used in .NET Framework 4.7 applications. See https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0 or below screenshot from that page:

![image](https://user-images.githubusercontent.com/7451219/223080432-e4c61624-a864-474b-85b2-4ad5c58daf91.png)
