### ISSUE TITLE
Feature add, revoke and list permission grants of the service principal

### ISSUE THREAD

**Issue by mloitzl** [pnp/pnpcore#1133]
## Category

- [x] Feature request

## Describe the feature

> Add, list, revoke grants like in `spo serviceprincipal grant add|list|revoke`

## Describe the solution you'd like

> Add, list, revoke grants like in `spo serviceprincipal grant add|list|revoke`

**Comment by mloitzl** [comment]
@jansenbe See https://github.com/pnp/pnpcore/pull/1132

**Comment by jansenbe** [comment]
Perfect PR, thanks a lot @mloitzl !!
