### ISSUE TITLE
Functionality to move/change the position of a field/column in a list view.

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpcore#1144]
## Category

- [x] Feature request

## Describe the feature

I'm proposing the PnP Core SDK to have the functionality to move/change the position of a field/column in a list view. This is something similar to what we have in [PnPjs](https://pnp.github.io/pnpjs/sp/views/#move).

## Describe the solution you'd like

I'm looking for a solution like this or something similar
```
// Get Documents list with views via title
var myList = await context.Web.Lists.GetByTitleAsync("Documents", p => p.Views);

// Get the view to update
var viewToUpdate = myList.Views.AsRequested().FirstOrDefault(p => p.Title == "All Documents");

// Update the view
await viewToUpdate.MoveFieldAsync(FieldInternalName, index);
```

## Additional context

Currently, since we do not have this functionality in the PnP Core SDK, I have to make Custom SPO Rest Request as in [here](https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request).

Here is what I had to do to move a field in the default view using the SPO Rest endpoint.

```
var apiRequest = new ApiRequest(new HttpMethod(WebRequestMethods.Http.Post), ApiRequestType.SPORest, $"{siteUrl}/_api/web/lists('{spList.Id}')/defaultView/viewfields/moveviewfieldto", $"{{\"field\":\"{FieldInternalName}\",\"index\":3}}");

await spList.ExecuteRequestAsync(apiRequest);
```

**Comment by jansenbe** [comment]
@NewGHUser4321 : that's nice addition to add, thanks for sharing the API call you've used, this will make it easier to include the feature!

**Comment by jansenbe** [comment]
@NewGHUser4321 : I've implemented this + also added support to add/remove a field from an existing view. Docs are processing now and will appear in https://pnp.github.io/pnpcore/using-the-sdk/lists-views.html.
