### ISSUE TITLE
SensitivityLabelId in TeamSiteWithoutGroupOptions and TeamSiteOptions is not shown in PS after creating the sites.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpcore#1145]
## Category

- [x] Bug

## Describe the bug
Sites created with `SensitivityLabelId = new Guid("cec2e4f9-2863-47dc-820f-72a095f8793c"),` do not show they have Sensitivity Label
## Steps to reproduce

1. See code 
`var teamSiteToCreate = new TeamSiteOptions(siteName, "Demo Team site")
            {
                Description = "PnP Core SDK demo Team site",
                Language = Language.English,
                SensitivityLabelId = new Guid("cec2e4f9-2863-47dc-820f-72a095f8793c"),
                Owners = new[] { owner }, 
                Members =  myMemebers
            };
            var newSiteContext = await pnpContext.GetSiteCollectionManager().CreateSiteCollectionAsync(teamSiteToCreate))
` 
Or 
`
 var noTeamSiteToCreate = new TeamSiteWithoutGroupOptions(new Uri($"https://{pnpContext.Uri.DnsSafeHost}/sites/{siteName}"), "Demo No Team site")
            {
                Description = "PnP Core SDK demo site",
                Language = Language.English,
                Owner = $"i:0#.f|membership|{owner}",
                SensitivityLabelId = new Guid("cec2e4f9-2863-47dc-820f-72a095f8793c")
            };
            var newSiteContext = await pnpContext.GetSiteCollectionManager().CreateSiteCollectionAsync(noTeamSiteToCreate)          
`
## Expected behavior
create the sites OK and PowerShell should verify it.

PS
`
$projectConn = Connect-PnPOnline -Url $projectURL -ClientId $ClientId -Tenant $tenant -CertificateBase64Encoded $env:CertificatePFX -CertificatePassword $certPass -ReturnConnection
$sLable = Get-PnPSiteSensitivityLabel -Connection $projectConn
`
returns null

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **SDK version**: [1.8.0 ]
- **OS**: [ Windows 11]
- **SDK used in**: [Azure Function]
- **Framework**: [ .NET 7 ]
- **Tooling**: [ VS Code + Visual Studio 2019]

Could it be that I have to wait for the label to be added later? 

Thank you

**Comment by jansenbe** [comment]
@Ofer-Gal : did the labels in the end show up or is this still not working?

**Comment by Ofer-Gal** [comment]
Now it is showing everywhere. Thanks.
Closing
