### ISSUE TITLE
Detailed documentation for using using event hub with multithreading

### ISSUE THREAD

**Issue by manjunathreddy1** [pnp/pnpcore#1147]
## Category

- [x] Feature request

## Describe the feature

Since the documentation for event hub is very short. I'm not getting the clear idea for using it with multithreading to handle throttling. Will it be possible to provide some additional information on this topic.
https://pnp.github.io/pnpcore/using-the-sdk/basics-eventhub.html

## Describe the solution you'd like

Detailed documentation for event hub to handle throttling.

**Comment by jansenbe** [comment]
@manjunathreddy1 : I agree that documentation is a bit thin, the idea for the events is that you get notified and/or can take action on an event. We support throttling (documented) and ratelimiting (not documented). I would suggest you check the Microsoft 365 Assessment code base as I've integrated all of this in there. A key class to check is this one: https://github.com/pnp/pnpassessment/blob/classic/src/PnP.Scanning/PnP.Scanning.Core/Services/ScanManager.cs

**Comment by manjunathreddy1** [comment]
> @manjunathreddy1 : I agree that documentation is a bit thin, the idea for the events is that you get notified and/or can take action on an event. We support throttling (documented) and ratelimiting (not documented). I would suggest you check the Microsoft 365 Assessment code base as I've integrated all of this in there. A key class to check is this one: https://github.com/pnp/pnpassessment/blob/classic/src/PnP.Scanning/PnP.Scanning.Core/Services/ScanManager.cs

@jansenbe Many thanks for sharing the sample code of ratelimit implementation. I will go through the code and come back if any additional clarifications are needed. Thanks again.

**Comment by jansenbe** [comment]
@manjunathreddy1 : did the sample code unblock you? Can we close this issue?

**Comment by manjunathreddy1** [comment]
@jansenbe Yes I have the required clarification and this issue can be closed now. Thanks.
