### ISSUE TITLE
Authentication with ClientId & ClientSecret: AuthenticationManager not available?

### ISSUE THREAD

**Issue by Schoof-T** [pnp/pnpcore#1150]
Hi

We are setting up a new solution where we have to download a file from sharepoint, we are download the file from a .NET 6 WEB API.
I have managed to get this working using the PnP.Framework with the following code:

```
            using (var cc = new PnP.Framework.AuthenticationManager().GetACSAppOnlyContext(siteUrl, "APPID", "APPSECRET"))
            {
                var file = await GetFileByUrl("URL", cc);

                ClientResult<Stream> fstream = file.OpenBinaryStream();
                cc.ExecuteQuery();
                var fs = fstream.Value;

                using (FileStream fileStream = new FileStream(@"D:\\test.pdf", FileMode.Create, System.IO.FileAccess.Write))
                {
                    fs.CopyTo(fileStream);
                }
            };
```

However I was looking into the differences between PnP.Core and PnP.Framework, and [it was suggested to use PnP.Core for new projects](https://github.com/pnp/pnpframework/issues/620). I then started looking for ways to authenticate and download a file using PnP.Core, but I did not succeed. All the samples seem to use Certificate Authentication or Identity Authentication.

What is the recommended way to do this?

**Comment by jansenbe** [comment]
Hi @Schoof-T ,

Same question came in as a discussion today (https://github.com/pnp/pnpcore/discussions/1148). Long story short, since Azure ACS is a legacy auth system we've no OOB support for that. The recommendation is used Azure AD based auth.

**Comment by Schoof-T** [comment]
Thank you @jansenbe! I'm a little confused on what to do now then, do you mean that client id & secret is not something we should use any more? Or does Azure AD based auth still support (and will continue supporting) client id & secret authentication? Is there an example somewhere to do this?

**Comment by jansenbe** [comment]
@Schoof-T : you should use Azure AD auth, but for SharePoint API calls that requires a clientid + certificate (Graph calls can do with client+secret, but Core SDK also requires SharePoint API calls). We've plenty of samples (https://pnp.github.io/pnpcore/demos/README.html), a tutorial (https://pnp.github.io/pnpcore/tutorials/azurefunctions/v4processisolatedapponly.html) and a Polyglot notebook (https://github.com/pnp/pnpcore/blob/dev/docs/polyglot/Getting%20started%20-%20application%20permissions.ipynb) that show how to do so.

**Comment by jansenbe** [comment]
@Schoof-T : I think this one can be closed?

**Comment by Schoof-T** [comment]
> @Schoof-T : I think this one can be closed?

Yes indeed, thank you for the thorough reply!
