### ISSUE TITLE
BreakRoleInheritance method is not present for list item or file level but the whole list

### ISSUE THREAD

**Issue by mohammadamer** [pnp/pnpcore#1171]
## Category

- [x] Bug

## Describe the bug

I wanted to BreakRoleInheritance for specific file in site pages library but didn't find the method with list item
I was able to do that but for the whole library

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. See code `code...` 
```
           var sitePages = await Ctx.Web.Lists.GetByTitleAsync("Site Pages");
            await sitePages.BreakRoleInheritanceAsync(true, false);

            //Get the role definitions
            var roleDefinitions = (await Ctx.Web.GetAsync(p => p.RoleDefinitions)).RoleDefinitions;
            var readRole = roleDefinitions.AsRequested().FirstOrDefault(p => p.Name == "Read");
            var editRole = roleDefinitions.AsRequested().FirstOrDefault(p => p.Name == "Edit");
            var fullControlRole = roleDefinitions.AsRequested().FirstOrDefault(p => p.Name == "Full Control");

            // Get Owners group
            await Ctx.Web.LoadAsync(p => p.AssociatedOwnerGroup);
            await Ctx.Web.LoadAsync(p => p.SiteGroups);
            foreach (var group in Ctx.Web.SiteGroups.AsRequested())
            {
                // Add read role definition to the owners group
                await sitePages.AddRoleDefinitionAsync(group.Id, readRole);
                // remove full control role definition from the owners group
                await sitePages.RemoveRoleDefinitionAsync(group.Id, fullControlRole);
            }
```

   

## Expected behavior

I except to be able to do the same for specific file in a SharePoint library.

## Environment details (*development & target environment*)

- **SDK version**: [1.7.0 ]
- **OS**: [e.g. Windows 10 ]
- **SDK used in**: [ ASP.Net Web app ]
- **Framework**: [ .NET Core v6.x ]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | Visual Studio 2022]

### Additional context

The main aim is to be able to break permission inheritance for specific file in site pages library then update role definitions for the site associated site default groups.

**Comment by jansenbe** [comment]
@mohammadamer : `IListItem` implements `ISecurableObject` which on it's turn has all the needed methods (https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Core/Public/ISecurableObject.cs). When you've an `IFile` you need to have `ListItemAllFields` loaded as that's an `IListItem` that then provides you with the needed methods (see sample here: https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#updating-file-metadata).

**Comment by jansenbe** [comment]
@mohammadamer : are you good with closing this?

**Comment by mohammadamer** [comment]
@jansenbe 
of course, You can close it. I just wanted to add the changes make sure that everything works.
