### ISSUE TITLE
Handle datetime fields in OData queries

### ISSUE THREAD

**Issue by NicolaiLassesen** [pnp/pnpcore#1173]
## Category

- [x] Feature request

## Describe the feature

Currently ODataUtilities (PnP.Core\QueryModel\OData\ODataUtilities.cs) is not able to correctly format DateTime values when filtering on such.

## Describe the solution you'd like

DateTime values (and DateTimeOffset values) should be converted to UTC and correctly formatted in ISO format. Adding these cases to the switch in the ConvertToString method would solve this problem:
```csharp
                case DateTime dt:
                    return $"datetime'{dt.ToUniversalTime():yyyy-MM-ddThh:mm:ssZ}'";
                case DateTimeOffset dto:
                    return $"datetime'{dto.UtcDateTime:yyyy-MM-ddThh:mm:ssZ}'";
```

**Comment by jansenbe** [comment]
Thanks for using PnP Core SDK and providing feedback @NicolaiLassesen. I'll make the necessary changes for this.

**Comment by jansenbe** [comment]
@NicolaiLassesen : I've implemented this change, will be part of the next nightly build (version 1.9.42 or higher). I'm closing this issue now, but feel free to re-open or create a new one in case the created fix is not working for you.
