### ISSUE TITLE
Typo in SiteCollectionCreator.cs

### ISSUE THREAD

**Issue by SebaLenny** [pnp/pnpcore#1176]
## Category

- [x] Typo

## Description

In file **SiteCollectionCreator.cs** there is typo in line **151**: communicaiton 
`throw new ClientException(ErrorType.Unsupported, "You need to set an owner when using Application permissions to create a communicaiton site");`

**Comment by jansenbe** [comment]
Thanks for spotting this @SebaLenny , I've just fixed the typo.
