### ISSUE TITLE
Updating Content types should be possible

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#1177]
## Category

- [x] Feature request

## Describe the feature

Currently the ContentType-Property of a IListItem is readonly.
However, in many scenarios it is practical if the content type could be changed. 
For example: Changing a folder to a document set.

Did I miss anything in the docs or is this feature not available yet?

In the PNP JS version updating the content type seems to be possible already:

https://github.com/SharePoint/PnP-JS-Core/issues/808

Also the Graph API provides something.
Its possible like this:

  ```
var listItem = new ListItem();
listItem.ContentType = new ContentTypeInfo();
listItem.ContentType.Id = contentTypeId;

  await _graphServiceClient
                          .Sites[siteId]
                          .Lists[listName]
                          .Items[itemId]
                          .Request()
                          .UpdateAsync(listItem);
```

But also in the C# version of PnP Core?

## Describe the solution you'd like

Add a setter to the IListItem's ContentType property.

**Comment by jansenbe** [comment]
@web265p3 : did you try setting the `ContentTypeId` field with the needed value? See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-list-items on instructions on how to update list items

**Comment by web265p3** [comment]
Field are metadata I think - Content type should be some other setting.

If I try this:
`        photoFolder["DocumentTypeId"] = "0x0120D52000F1D3C3AA10473E48A2CBE4....";`

or this:

`        photoFolder.Values["DocumentTypeId"] = "0x0120D52000F1D3C3AA10473E48A2C...";`

I get this error message: "Message: Column 'DocumentTypeId' does not exist. It may have been deleted by another user. "

This makes sense to me. ContentTypeId is not a metadata field...
