### ISSUE TITLE
Updating taxonomy value of DocumentSet throws Exception

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#1178]
## Category

- [x] Bug

## Describe the bug

The following lines of code should update the taxonomy value of a Document set:

```
        var list = await pnpContext.Web.Lists.GetByTitleAsync("MyList");
        await list.LoadAsync(prop => prop.All);
        await list.Items.LoadAsync(item => item.Folder.QueryProperties(file => file.Name));
        var docSet = list.Items.AsRequested().FirstOrDefault(item => item.Folder.Name == "MyDocumentSet");
        await docSet.LoadAsync(item => item.Properties);
        (docSet["DocumentKind"] as IFieldTaxonomyValue).TermId = new Guid("d898f315-6631-4272-850a-08c0e79b01f0");
        await docSet.UpdateAsync();
```

This is the [place in the docs](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#taxonomy-fields).

However, the following line throws an Exception:
`        (docSet["DocumentKind"] as IFieldTaxonomyValue).TermId = new Guid("d898f315-6631-4272-850a-08c0e79b01f0");`

**PnP.Core.ClientException: 'Property DocumentKind does not exist in this entity'**

The Exception gets thrown, even _before_ the server is contacted.

If I inspect the item itself, I can definetely see that it contains a Metadata field "DocumentKind".

docSet => Properties => Values => DocumentKind => "THE CURRENT GUID"

Either, the docs are missing some "load" command, to load complex properties or there is a bug.
How should the cast to a IFieldTaxonomyValue take place exactly?

- **SDK version**: 1.9.0
- **OS**: Windows 11
- **SDK used in**:  .NET 6
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x ]

**Comment by jansenbe** [comment]
@web265p3 : how are you loading the list items in the first place? Is `DocumentKind` a custom field you've added?

**Comment by web265p3** [comment]
Correct, DocumentKind is a custom metadata field that can store taxonomy data.
I'm loading the properties with: docSet.LoadAsync(item => item.Properties)

**Comment by web265p3** [comment]
Like in my example above shown:

var docSet = list.Items.AsRequested().FirstOrDefault(item => item.Folder.Name == "MyDocumentSet");

**Comment by jansenbe** [comment]
@web265p3 : sorry, should be more specific, how did you load `list.Items`? Since you're using `AsRequested` the data was already loaded.

**Comment by web265p3** [comment]
Oh sorry! 
I updated my code above:

This is the way I get the list:

        var list = await pnpContext.Web.Lists.GetByTitleAsync("Sales_HFMG");
        await list.LoadAsync(prop => prop.All);
        await list.Items.LoadAsync(item => item.Folder.QueryProperties(file => file.Name));
