### ISSUE TITLE
Method CreateSiteCollectionAsync throws exception in Azure App service: SiteStatus = 0

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#1181]
I am using the following code to create a new site collection.
I am creating a Teamsite that has no group connection:

```
        PnPContext pnpContext = await _pnPContextFactory.CreateAsync(new Uri("https://myorg.sharepoint.com"), _x509CertificateAuthenticationProvider);

        var siteToCreate = new TeamSiteWithoutGroupOptions(new Uri("https://ourOrg.sharepoint.com/sites/testSite"), "The name of my site")
        {
            Description = "My description",
            Language = Language.English,
            Owner = "email@ourOwner.com"
        };
        SiteCreationOptions siteCreationOptions = new()
        {
            WaitForAsyncProvisioning = true,
        };
        using (var newSiteContext = await pnpContext.GetSiteCollectionManager().CreateSiteCollectionAsync(siteToCreate, siteCreationOptions))
        {
                 //do some work
        }
```

This code runs well on my computer. The creation of the Teamsite works and takes 1-2 minutes.

If I deploy my solution to an Azure Webjob, the code from above throws an PnP.Core.ClientException:

`The site creation for site https://ourOrg.sharepoint.com/sites/testSite did not succeed. Returned siteStatus = 0`

Pnp seems to use the SharePoint Rest interface to create the site, so I think that [this endpoint](https://learn.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest#create-a-modern-site) is used.

A status code that is successful should be 2, not 0 like in my case.

Do you have any idea what could be the difference between the Azure App service and my local computer? 
I checked already the timeout of the httpClient of .NET, but it is 230 for Azure App service and this should be far enough to create the site.

There must be some infrastructure setting or something I cannot think of what causes this problem. Any idea?

**Comment by jansenbe** [comment]
@web265p3 : It repeatedly fails or  sometimes?

**Comment by web265p3** [comment]
It always fails, sorry to not mention that

**Comment by jansenbe** [comment]
@web265p3 : are you sure auth is correctly configured and working when running in a function? If you're using the same app and certificate as when locally guess that's fine, otherwise cross check that. 

Looking at the code it seems the call to `_api/SPSiteManager/Create` fails when running from inside a deployed Azure function, not returning 1 or 2.

**Comment by jansenbe** [comment]
@web265p3 : also, if you set logging level to `Trace` then the response headers from each http request are logged, if you can get me the correlationid, tenantname and timestamp of the failing `_api/SPSiteManager/Create` I can see if there's something going server side (which I doubt). If will also log your access token, so you can use https://jwt.ms/ to inspect if the token contains the expected roles (assuming you're using application permissions).

**Comment by web265p3** [comment]
> @web265p3 : are you sure auth is correctly configured and working when running in a function? If you're using the same app and certificate as when locally guess that's fine, otherwise cross check that.
> 
> Looking at the code it seems the call to `_api/SPSiteManager/Create` fails when running from inside a deployed Azure function, not returning 1 or 2.

Yes - I am using exactly the same certificate and clientid like locally. What do you mean by "running in a function"?
Yes, the _api/SPSiteManager/Create endpoint is used, but I am using Webjobs, not Azure functions

**Comment by web265p3** [comment]
> @web265p3 : also, if you set logging level to `Trace` then the response headers from each http request are logged, if you can get me the correlationid, tenantname and timestamp of the failing `_api/SPSiteManager/Create` I can see if there's something going server side (which I doubt). If will also log your access token, so you can use https://jwt.ms/ to inspect if the token contains the expected roles (assuming you're using application permissions).

I will now try to change the logging level. I am using application permissions, yes. But I have definetely enough permissions... the access token should be fine. I am using this app already in many scenarios where I need elevated permissions. It would be interesting to be able to log the HTTP Traffic that is going on within my App Service. Maybe there is a setting in Azure where I can also log this (like in fiddler locally)...?

**Comment by web265p3** [comment]
[05/17/2023 19:24:31 > 997ef2: INFO]       GET https://myOrg.sharepoint.com/_api/Web?$select=Id%2cUrl%2cRegionalSettings%2f*%2cRegionalSettings%2fDateFormat&$expand=RegionalSettings%2cRegionalSettings%2fTimeZone
[05/17/2023 19:24:31 > 997ef2: INFO] dbug: PnP.Core.Services.PnPContext[0]
[05/17/2023 19:24:31 > 997ef2: INFO]       GET https://myOrg.sharepoint.com/_api/Site?$select=Id%2cGroupId
[05/17/2023 19:24:32 > 997ef2: INFO] dbug: PnP.Core.Services.PnPContext[0]
[05/17/2023 19:24:32 > 997ef2: INFO]       POST https://myOrg.sharepoint.com/_api/SPSiteManager/Create
[05/17/2023 19:24:32 > 997ef2: INFO] dbug: PnP.Core.Services.PnPContext[0]
[05/17/2023 19:24:32 > 997ef2: INFO]       {"request":{"Title":"CO 700005555x - Sydney - Test - Myhorizons","Lcid":1033,"ShareByEmailEnabled":false,"Url":"https://myOrg.sharepoint.com/sites/CO700005555xSydneyTestMyhorizons","Classification":"","Description":"description","WebTemplate":"STS#3","WebTemplateExtensionId":"00000000-0000-0000-0000-000000000000","Owner":"ouradmin@org.com","HubSiteId":"00000000-0000-0000-0000-000000000000"}}
[05/17/2023 19:24:32 > 997ef2: INFO] Unknown error. Message has to stay.The site creation for site https://myOrg.sharepoint.com/sites/CO700005555xSydneyTestMyhorizons did not succeed. Returned siteStatus = 0

**Comment by web265p3** [comment]
@jansenbe I read in the docs, that there is a flag in the creation options, that determines that the async call should wait for the site creation to be complete.

For this reason I enabled this in my example above:

        SiteCreationOptions siteCreationOptions = new()
        {
            WaitForAsyncProvisioning = true,
        };

Now the creation of my site takes 1-2 minutes what is okay.

However, if I do not use this flag, the calls returns a lot faster (5 seconds)
I can also work with the newly created page in  both scenarios.

Where is the difference? Maybe I can just leave out this flag? I thought it gives me more trust that the site creation is done, but it seems to just take longer? What happens in the additional minute?

**Comment by jansenbe** [comment]
@web265p3 : site creation in SharePoint is fast because we essentially "copy" a ready one and perform minimal sync updates, followed by some other "async" updates (e.g. rename the created SharePoint groups in line with the site name). The later part can be an issue for your code depending on what you're doing (e.g. if you want to work the groups and name changes mid way you've an issue). If in your testing your code is fine without the wait then you can certainly skip that.

Are you testing this locally or is the problem also gone when deployed as Azure function?

**Comment by jansenbe** [comment]
@web265p3 : hope you've enjoyed your break :-) Any update on this issue?

**Comment by jansenbe** [comment]
@web265p3 : are you good with closing this one?

**Comment by jansenbe** [comment]
@web265p3 : I'm going to close this one, if needed please re-open and additional context.
