### ISSUE TITLE
ConnectGroupToSiteAsync For application permissions

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1187]
## Category

- [x] Feature request

## Background

I'm building a tool that creates team sites. But I want to do this with application permissions for multiple tenants and change the language of a site op creation. So currently i'm creating Team site without a group to set the language and then I whant to use the "ConnectGroupToSiteAsync" to make it a Site with group.

## Describe the feature

The feature I want to request is ConnectGroupToSiteAsync for Application permissions

**Comment by jansenbe** [comment]
@danielpastoor : this is not supported via app-only, you need to be either a SharePoint tenant admin or site collection admin (depending on the settings). See https://github.com/pnp/pnpcore/issues/1000 for more context. I'll make some changes to the docs to clarify this for future use.
