### ISSUE TITLE
PnP, Site Scripts and Enterprise Content Types vs SiteManager

### ISSUE THREAD

**Issue by Pieter-Veenstra** [pnp/pnpcore#1192]
## Category

- [x] Feature request

## Describe the feature

In Site Scripts you can add content types to lists, however Enterprise Content Types are not supported. ( see note https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#addcontenttype). What is the purpose of addContentTypesFromHub to add Enterprise Content types to a site if they can't be used in lists and libraries afterwards one may ask.

Then I tried the /_api/SPSiteManager/create endpoint and posting the Site  Design G'UID using the WebTemplateExtensionId and now I'm getting weird behaviours. As the site is created, however in the site the Content Type Gallery shows that the source of the content type is my site rather than the Content Type Hub. It looks like the SPSiteManager is working around the issue of Enterprise Content Types.

## Describe the solution you'd like

I would like to see Enterprise Content Types being fully supported by site scripts and PnP as Invoke-PnPSiteDesign ( and the other related Cmdlets that do a similar thing) are all affected by thing.

## Additional context

Not sure where to report this, so I chose Feature request.

**Comment by jansenbe** [comment]
@Pieter-Veenstra : this appears to be more a feature request for the SharePoint team versus an issue in PnP Core SDK. I'll transfer this request to sp-dev-docs as I think that's better suited.

**Comment by jansenbe** [comment]
@Pieter-Veenstra : per above closing the issue in PnP Core SDK
