### ISSUE TITLE
Setting Default Column Values with SetDefaultColumnValuesAsync() Causes FileNotFoundException

### ISSUE THREAD

**Issue by adamfisher** [pnp/pnpcore#1194]
## Category

- [x] Bug

## Describe the bug

I have code like this:

```csharp
private async Task SetFolderDefaultValues(IFolder folder, MyData data)
{
	var defaultColumnValues = new List<DefaultColumnValueOptions>()
	{
		new()
		{
			FolderRelativePath = folder.ServerRelativeUrl,
			FieldInternalName = "Project_Number",
			DefaultValue = data.ProjectId
		},
		new()
		{
			FolderRelativePath = folder.ServerRelativeUrl,
			FieldInternalName = "Project_Description",
			DefaultValue = data.ProjectName
		}
	};
	var list = await _sharePointContext.Web.Lists.GetByServerRelativeUrlAsync(folder.ServerRelativeUrl);
	await list.SetDefaultColumnValuesAsync(defaultColumnValues);
}
```

When calling `list.SetDefaultColumnValuesAsync(defaultColumnValues)` I get this error:

```shell
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      HttpResponseCode: 404
      Code: System.IO.FileNotFoundException
      Message: File Not Found.
      ClientRequestId: 3499b8a0-f038-3000-a365-e1b0a8d52061
      SPClientServiceRequestDuration: 16
      X-SharePointHealthScore: 3
      X-SP-SERVERSTATE: ReadOnly=0

      PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
         at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
         at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
         at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
         at PnP.Core.Model.BaseDataModel`1.BaseRetrieveAsync(ApiCall apiOverride, Func`2 fromJsonCasting, Action`1 postMappingJson, Expression`1[] expressions)
         at PnP.Core.Model.SharePoint.Web.GetFolderByServerRelativeUrlAsync(String serverRelativeUrl, Expression`1[] expressions)
         at BigCorp.MyProject.Worker.SetDefaultColumnValuesAsync(List`1 defaultColumnValues) in C:\Source\BigCorp.MyProject\Worker.cs:line 252
         at BigCorp.MyProject.Worker.SetFolderDefaultValues(IFolder folder, MyData data) in C:\Source\BigCorp.MyProject\Worker.cs:line 182
         at BigCorp.MyProject.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Source\BigCorp.MyProject\Worker.cs:line 80
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

I see the error is happening at this line inside the `SetDefaultColumnValuesAsync()` method:

```csharp
// Get the folder to add the defaults file to
 var formsFolder = await _sharePointContext.Web.GetFolderByServerRelativeUrlAsync($"{listInfo.RootFolder.ServerRelativeUrl}/Forms", p => p.Files).ConfigureAwait(false);
```

The URL in that first parameter has the value `"/sites/FileStructureSandbox/Forms"` but that's not the folder path I passed into the individual options when I set the `DefaultColumnValueOptions.FolderRelativePath`. Shouldn't it be the specific folder where the default options are going to be set? I'm not sure why this line is failing. The folder does exist because I used `EnsureFolderAsync()` which completed successfully.

## Environment details (*development & target environment*)

- **SDK version**: 16.1.23710.12000
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET Core v3.x
- **Browser(s)**: Chrome v79
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@adamfisher : can you cross check the passed in `FolderRelativePath` are relative to the list and not relative to the server. See https://pnp.github.io/pnpcore/using-the-sdk/lists-intro.html#setting-default-values for an example

**Comment by adamfisher** [comment]
I did see something else interesting. The list that gets resolved for that `formsFolder` variable having the `/Forms` part appended incorrectly. Once that extra slash is removed it would be a valid URL (I can load that path in the browser) but it still gives me the `FileNotFoundException`.

![image](https://github.com/pnp/pnpcore/assets/1834711/fe4e26ce-43aa-4d0a-abce-64716181ccd5)

**Comment by adamfisher** [comment]
The folder relative path I pass into each `DefaultColumnValueOptions` is the actual folder (`/site/FilStructureSandbox/Folder1` for example) but that's not the path we are talking about here. This path is just taking the root folder for the path. Maybe that's ok for getting the "forms folder" even though each default field is further down in that path.

**Comment by adamfisher** [comment]
I get the list using `var list = await _sharePointContext.Web.Lists.GetByServerRelativeUrlAsync(folder.ServerRelativeUrl);`

**Comment by adamfisher** [comment]
That was it. The subtle difference in the folder paths was tripping me up. Thank you!
