### ISSUE TITLE
Unable to Set Default Meta Data on Columns for a Specific Folder

### ISSUE THREAD

**Issue by adamfisher** [pnp/pnpcore#1198]
## Category

- [x] Bug

## Describe the bug

This method:

```csharp
/// <summary>
/// Sets the specified meta data on this folder and all child files and folders based on the default column values already set.
/// Useful for setting meta data after a copy operation since SharePoint doesn't make copied items inherit default meta data values.
/// </summary>
/// <param name="targetFolder">The folder to set meta data for.</param>
/// <returns></returns>
private async Task SyncDefaultMetaDataAsync(IFolder targetFolder)
{
	var queue = new Queue<IListItem>();
	queue.Enqueue(targetFolder.ListItemAllFields);

	var list = await _sharePointContext.Web.Lists.GetByServerRelativeUrlAsync(targetFolder.ServerRelativeUrl);
	var defaultColumnValues = await list.GetDefaultColumnValuesAsync();

	while (queue.Count > 0)
	{
		var listItem = queue.Dequeue();

		await listItem.LoadAsync(
			li => li.All,
			li => li.Id,
			li => li.UniqueId,
			li => li.File.QueryProperties(li => li.ListItemAllFields),
			li => li.Folder.QueryProperties(li => li.ListItemAllFields));

		if (await listItem.IsFolderAsync())
		{
			var folder = listItem.Folder;
			(await QueryableExtensions.ToListAsync(folder.Folders)).ForEach(i => queue.Enqueue(i.ListItemAllFields));
			(await QueryableExtensions.ToListAsync(folder.Files)).ForEach(i => queue.Enqueue(i.ListItemAllFields));
		}

		foreach (var defaultColumnValue in defaultColumnValues)
		{
			listItem[defaultColumnValue.FieldInternalName] = defaultColumnValue.DefaultValue;
		}

		await listItem.SystemUpdateAsync();
	}
}
```

Produces this error:

```shell
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      HttpResponseCode: 200
      Message: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
      ClientRequestId: ae8bbaa0-c03e-3000-ab1e-2faaa09ace25
      ErrorTypeName: "System.FormatException"

      PnP.Core.CsomServiceException: CSOM service exception
         at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
         at PnP.Core.Services.BatchClient.ExecuteCsomBatchAsync(Batch batch)
         at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
         at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
         at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
         at PnP.Core.Model.SharePoint.ListItem.SystemUpdateAsync()
         at BigCorp.MyProject.Worker.SyncDefaultMetaDataAsync(IFolder targetFolder) in C:\Source\BigCorp.MyProject\Worker.cs:line 176
         at BigCorp.MyProject.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Source\BigCorp.MyProject\Worker.cs:line 72
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

## Steps to reproduce

1. Copy/paste this method into a sample project.
2. Try passing an IFolder instance into it.
3. See `await listItem.SystemUpdateAsync();` produce the above stack trace error.

## Expected behavior

Expecting the fields of the list item to be updated and show up in the SharePoint columns.

## Environment details (*development & target environment*)

- **SDK version**: 16.1.23710.12000
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET Core v3.x
- **Browser(s)**: Chrome v79
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@adamfisher : thanks for reporting this @adamfisher . I assume you're using a recent version of PnP Core SDK?

Why are you trying to set the column defaults via code, I hoped (but need to verify via a test) these were set automatically when you add the new item, even if done via code.

**Comment by adamfisher** [comment]
I'm using the latest version. Just installed it last week. I set the default column values for this specific folder in another method (although those values do not show up in the default column settings screen in SharePoint UI but I can still call `GetDefaultColumnValuesAsync()` and get them back successfully so SP stores them somewhere internally but I can't see them. That's another problem I need to solve).

But essentially I have a folder consisting of child files and child folders and I use the copy method elsewhere to copy that folder:
 
```csharp
await templateFolder.CopyToAsync(relativePath, new MoveCopyOptions() { RetainEditorAndModifiedOnMove = true });
```
The copy works perfectly. However we found in testing that only newly uploaded files receive default values set on a folder. But _copied_ items do not contain the default values. So I have to retroactively go back and manually iterate through these files and force them to "inherit" the values of the parent. 

![image](https://github.com/pnp/pnpcore/assets/1834711/3805e5d3-3d72-4963-a4f0-bf106b555a7f)

**Comment by jansenbe** [comment]
@adamfisher : let me add a test case that mimics your approach and see if I can repro and fix.

**Comment by jansenbe** [comment]
@adamfisher : I've tested your code and for me it works (see https://github.com/pnp/pnpcore/commit/8cf24eaf0cc822bcf574437ae81ca62de2b76a67 for the new test case). I see the initial default values appear in the UI (_layouts/15/ColumnDefaults.aspx, via List Settings --> Column default value settings) and also update in the UI when I update them. 

Can you cross check you see the values in the UI before/after updating? Also, makes sense to do a Fiddler trace and check what's send across the wire. 

Alternatively you can also step through the code yourself via our Source Link support, see https://pnp.github.io/pnpcore/using-the-sdk/basics-debug.html to learn more

**Comment by jansenbe** [comment]
@adamfisher : did the feedback I shared help? If you've a fiddler trace then feel free to share via bjansen@microsoft.com

**Comment by adamfisher** [comment]
Hey thanks Bert for your input on this. I don't remember there being any traffic at the time I was running Fiddler but could be due to how I was loading the domain models. 

**I did get it working for default values however and I'll post it below for others that may be interested.** I think part of the problem was `client_LocationBasedDefaults.html` is very temperamental and some old folder paths or old field names that no longer exist but are still present in that file caused some of the issue with default values coming through. This code will lookup the current fields defined for the content type to ensure we only try to set default values for fields that exist and also fall back to the current default values if we don't have a value for an existing field. It seems to work much better now:

```csharp
/// <summary>
/// Sets the default meta data on a folder. Any items uploaded under this folder will inherit this meta data automatically.
/// </summary>
/// <param name="folder">The folder to set meta data for.</param>
/// <param name="data">The event data to set.</param>
/// <returns></returns>
private async Task SetFolderDefaultValuesAsync(IFolder folder, MyData data)
{
	var list = await _sharePointContext.Web.Lists.GetByServerRelativeUrlAsync(folder.ServerRelativeUrl, 
		p => p.Fields, p => p.FieldDefaults, 
		p => p.ContentTypes.QueryProperties(p => p.Name, p => p.Description,
			ctfl => ctfl.FieldLinks.QueryProperties(ctflp => ctflp.Name, p => p.FieldInternalName),
			ctf => ctf.Fields.QueryProperties(ctfp => ctfp.InternalName)));
	var folderRelativePath = folder.ServerRelativeUrl.Replace(WorkingDirectoryRootRelativePath, string.Empty);

	var columns = new List<DefaultColumnValueOptions>()
	{
		new()
		{
			FieldInternalName = "Project_Number",
			DefaultValue = data.ProjectId,
			FolderRelativePath = folderRelativePath
		},
		new()
		{
			FieldInternalName = "Project_Description",
			DefaultValue = data.ProjectName,
			FolderRelativePath = folderRelativePath
		}
	};

	// Retain existing value if a value is null because it will result in an ArgumentException from SP
	var existingColumns = await list.GetDefaultColumnValuesAsync();
	foreach (var column in columns.ToList())
	{
		if (string.IsNullOrWhiteSpace(column.DefaultValue))
		{
			var existingColumn = existingColumns.FirstOrDefault(ec => ec.FieldInternalName == column.FieldInternalName);
			if (existingColumn != null)
			{
				columns.Remove(column);
				columns.Add(existingColumn);
			}
			else
			{
				columns.Remove(column);
			}
		}
	}

	// Only assign based on available fields defined in the content type
	var availableFields = list.ContentTypes.AsRequested()
		.Where(ct => ct.Name == "Document")
		.SelectMany(ct => ct.Fields.AsRequested())
		.Select(f => f.InternalName);
	columns.RemoveAll(c => !availableFields.Contains(c.FieldInternalName));

	// Never call this without a non-zero collection or it will clear ALL default values across the site.
	if (columns.Count > 0)
	{
		await list.SetDefaultColumnValuesAsync(columns);
	}
}
```

**Comment by adamfisher** [comment]
I did some more research and experimentation on how SharePoint stores default values inside that **client_LocationBasedDefaults.html**. I [came across this article](https://learn.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits?redirectedfrom=MSDN#managed-metadata-limits) discussing limits on how many defaults can be stored within this file. Granted the article is for SP 2013 and I couldn't find an equivalent one for SP Online but I'd be surprised if the cloud is more lenient on storage/limits than on-prem installations. It mentions:

> When the number of folders in the data file exceeds 1,000, or the data file size exceeds 256 Mb, default values added for additional folders will be ignored.

**We will have way more than 1,000 folders in need of default values so I think for now we are going to have to abandon setting default values on items** and just move toward just setting values on folders during the initial creation and then possibly look into setting up a Power Automate event receiver trigger to listen for the creation of new files and folders that will look at the parent and just pull the values down into the fields from the parent item for the newly created item for lack of a better approach on that front.
