### ISSUE TITLE
Consider having tokens at multiple levels

### ISSUE THREAD

**Issue by PaoloPia** [pnp/pnpcore#12]
Consider supporting multiple hierarchies of tokens. (Parent.Parent.Parent.Id)

**Comment by jansenbe** [comment]
Up until now there was no need for this feature, let's keep it on hold until we bump into limitations around this

**Comment by jansenbe** [comment]
All calls so far where able without this, this also introduces extra complexities with linq queries that would depend on such tokens. Closing the issue for that reason.
