### ISSUE TITLE
[FEATURE] Add ability to delete list item / file versions

### ISSUE THREAD

**Issue by gautamdsheth** [pnp/pnpcore#1200]
## Category

- [x] Feature request

## Describe the feature

Currently we only have the ability to retrieve the list item version.
Would be great to also have the ability to delete a particular version as well.

## Describe the solution you'd like

The solution would look something like this:

```
var itemVersions = item.Versions.AsRequested().ToList();
iteVersions[0].Delete()
```

## Additional context

NA

**Comment by jansenbe** [comment]
@gautamdsheth : done, will be part of the next nightly. you can use any of the Delete methods on an IListItemVersion instance to delete it.
