### ISSUE TITLE
Getting default site groups generating invalid request

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpcore#1206]
## Category

- [x] Bug

## Describe the bug

Attempting to get the default associated groups for a web incorrectly creates a `getbyid` URL, which then contains an unresolved token for the ID.

This affects `AssociatedOwnerGroup`, `AssociatedMemberGroup`, and `AssociatedVisitorGroup`.

```
PnP.Core: Unresolved tokens found in API call 
https://<tenant>.sharepoint.com/sites/test/_api/Web/sitegroups/getbyid({Id})
```

## Steps to reproduce

1. Run code snippet below
1. Experience error

```cs
var context = await _contextFactory.CreateAsync(new Uri("https://<tenant>.sharepoint.com/sites/test"));

// using `context.Web` directly and omitting this makes no difference.
var web = await context.Web.GetAsync();
var members = await web.AssociatedVisitorGroup.GetAsync();
```

## Expected behavior

The generated URL correctly points to the associated group, and the data is fetched without error.

eg:
```
/sites/test/_api/web/associatedMemberGroup
```

## Environment details (*development & target environment*)

- **SDK version**: 1.9.72-nightly
- **OS**: Windows 11, and whatever Azure Functions runs on
- **SDK used in**: Azure Functions
- **Framework**: .NET 6
- **Tooling**: Jetbrains Rider

**Comment by jansenbe** [comment]
@JakeStanger : can you try the below:

```csharp
var web = await context.Web.GetAsync(p => p.AssociatedVisitorGroup.QueryProperties(p=>p.Users), p => p.AssociatedMemberGroup.QueryProperties(p => p.Users));

foreach(var user in web.AssociatedMemberGroup.Users.AsRequested())
{

}
```

**Comment by JakeStanger** [comment]
I appreciate the workaround, but I disagree that the issue should be closed, since getting the properties directly (as in my repro) still causes an error. I'd argue if this is 'intended', at the very least this should be documented.
