### ISSUE TITLE
LoadItemsByCamlQueryAsync multiple times retrieves same results

### ISSUE THREAD

**Issue by mjonila** [pnp/pnpcore#1209]
## Category

- [x] Bug

## Describe the bug

Simple list `Contacts` has only `Title` field. In this list there are 3 rows with `Item1`, `Item2` and `Item3`.

Executing this code second and third iteration displays the same result as first:

```
var contactList = await ctx.Web.Lists.GetByServerRelativeUrlAsync($"{ctx.Uri.PathAndQuery}/Lists/Contacts", p => p.Title,
                                                     p => p.Fields.QueryProperties(p => p.All));

for (int i = 1; i < 4; i++) {
   string query = $"<View><Query><Where><Eq><FieldRef Name='Title'/><Value Type='Text'>{"Item"+i}</Value></Eq></Where></Query></View>";

  await contactList.LoadItemsByCamlQueryAsync(new CamlQueryOptions()
      {
          ViewXml = query
      });

   if (contactList.Items.AsRequested().Count() > 0)
    {
        foreach (var item in contactList.Items.AsRequested())
        {
            Console.WriteLine(item.Title);
        }
    }
}
```

I suppose the problem here is `AsRequested()`, which does not reload after each iteration.
What am I doing wrong ?

**Comment by jansenbe** [comment]
When you call `LoadItemsByCamlQueryAsync` multiple times you're effectively loading and adding list items to the items collection, so if you then iterate over the collection using `foreach (var item in contactList.Items.AsRequested()` you also see the previously loaded items. If you don't want to see the previous loads you need to clear the Items collection inbetween each load via `contactList.Items.Clear();`. The paging docs for `LoadItemsByCamlQueryAsync` explain this as well as when you're paging over huge amounts of rows you want to process them, clear the in memory list, and get the next batch of items. See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-paging-with-loaditemsbycamlquery for more details.

That being said, you should aim at loading as much items using a single `LoadItemsByCamlQueryAsync` to ensure performance.
