### ISSUE TITLE
The property 'LookupField' does not exist on type 'SP.Field'

### ISSUE THREAD

**Issue by ionbesleaga** [pnp/pnpcore#1214]
## Category

- [x] Bug

## Describe the bug
I'm trying to update the reference field for a lookup column, and I get this error:
`The property 'LookupField' does not exist on type 'SP.Field'. Make sure to only use property names that are defined by the type.`

## Steps to reproduce

`field.LookupField = "newFieldInternalName";`
`await field.UpdateAsync();`

## Expected behavior

Field is updated, like it happens from the SP site in edit field UI.

## Environment details (*development & target environment*)

SharePoint online.

### Note:
When I try to load these properties, also getting no result and an error if tried to be read:
`await field.LoadAsync(field => field.LookupField, field => field.LookupList, field => field.LookupWebId);`

**Comment by ionbesleaga** [comment]
> @ionbesleaga : just trying to understand the ask, you have an existing lookup column showing `fieldA` from the looked up list item but now you want to show `fieldB`?

yes.
The lookup field was created referencing `fieldA`, and now (using the API calls mentioned) I try to change it to `fieldB`.
When you create a lookup field, you put the list's field to look at using `FieldLookupOptions.LookupFieldName = "fieldA"`.
When you update, you do it as `IField.LookupField = "fieldB"`. Or am I using a wrong API call ?

**Comment by jansenbe** [comment]
@ionbesleaga : for that you need to update the `SchemaXml` property of the field (see https://github.com/pnp/pnpcore/discussions/1003 for a thread on this). When you do a Fiddler trace from doing this in the SharePoint UI you'll see it's doing that as well.

**Comment by ionbesleaga** [comment]
okay, somehow didn't come across that thread during my research.
Thank you very much for pointing out and quick replies!
