### ISSUE TITLE
Updating multiple propertybag values doesn't work

### ISSUE THREAD

**Issue by ronaldvanhelden** [pnp/pnpcore#1218]
## Category

- [x] Bug

## Describe the bug

When updating multiple web properties, only the first will be executed.

using this snippet, only the first gets created.

```cs
var web = await context.Web.GetAsync(x => x.AllProperties);
web.AllProperties["value1"] = "test";
web.AllProperties["value2"] = "test";
await web.AllProperties.UpdateAsync();
```

When I compare the request created from CSOM and PnP.Core, you can see that instead of multiple calls for SetFieldValue like CSOM there is a single call SetFieldValue with multiple parameters and that doesnt seem to work when updating multiple properties in a single update.

![PNP](https://github.com/pnp/pnpcore/assets/105484799/763182b2-1e2d-4dd4-8ae9-ae31a669a5c0)
![CSOM](https://github.com/pnp/pnpcore/assets/105484799/640c0904-97ad-4eb4-aa8f-01ee4f2c59a5)

And in the source in `src/sdk/PnP.Core/Services/Core/CSOM/Requests/Web/UpdatePropertyBagRequest.cs`, I see the following snippet for creating the request, and I think this loop should produce multiple `ActionObjectPath` instead of a single with multiple parameters

```cs
public List<ActionObjectPath> GetRequest(IIdProvider idProvider)
        {
            int updateActionId = idProvider.GetActionId();
            IdentityPath = idProvider.GetActionId();
            int propertiesId = idProvider.GetActionId();

            List<Parameter> parameters = new List<Parameter>();
            foreach (CSOMItemField field in FieldsToUpdate)
            {
                parameters.AddRange(field.GetRequestParameters());
            }

            return new List<ActionObjectPath>()
            {
                new ActionObjectPath()
                {
                    Action = new MethodAction()
                    {
                        Id = updateActionId,
                        Name = "SetFieldValue",
                        ObjectPathId = propertiesId.ToString(),
                        Parameters = parameters
                    },
                    ObjectPath = new Property()
                    {
                        Id = propertiesId,
                        ParentId = IdentityPath,
                        Name = PropertyName
                    }
                },
                new ActionObjectPath()
                {
                    Action = new MethodAction()
                    {
                        Id = updateActionId,
                        ObjectPathId = IdentityPath.ToString(),
                        Name = "Update",
                        Parameters = new List<Parameter>()
                    },
                    ObjectPath = new Identity()
                    {
                        Id = IdentityPath,
                        Name = $"121a659f-e03e-2000-4281-1212829d67dd|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:{SiteId}:web:{WebId}{ObjectId}"
                    }
                }
            };
        }
```

## Steps to reproduce

Execute this snippet

```cs
var web = await context.Web.GetAsync(x => x.AllProperties);
web.AllProperties["value1"] = "test";
web.AllProperties["value2"] = "test";
await web.AllProperties.UpdateAsync();
```

## Expected behavior

When executing the snippet to update multiple web properties in a single call like CSOM would do.

## Environment details (*development & target environment*)

- **SDK version**: Lastest
- **OS**: Windows 11
- **SDK used in**: Console app
- **Framework**: .Net 7
- **Tooling**: LinqPad / VS

**Comment by jansenbe** [comment]
Thanks for using PnP Core SDK and reporting this @ronaldvanhelden. I've been able to reproduce and create a fix + corresponding test case for this. This change will be part of the next nightly release, as such I'm closing this issue now. If you still face issues when using the next nightly then please re-open or create a new issue.
