### ISSUE TITLE
Exception web calling Web.GetFileByLinkAsync

### ISSUE THREAD

**Issue by CodingJarod** [pnp/pnpcore#1226]
## Category

- [x] Bug

## Describe the bug
Calling the function Web.GetFileByLinkAsync with a valid full url throws the following exception:

PnP.Core.MicrosoftGraphServiceException: 'Microsoft Graph service exception'

The method Web.GetFileByServerRelativeUrlAsync (using the server relative url) works as expected

## Expected behavior

The method call should return the correct File object

## Environment details (*development & target environment*)

Permissions on Azure:

![image](https://github.com/pnp/pnpcore/assets/113518675/a36cfdb5-6844-4c71-aca5-7d876e8c7d0f)

Thanks for the support

**Comment by jansenbe** [comment]
@CodingJarod : can you catch the exception in code and see what the actual error is? See https://pnp.github.io/pnpcore/using-the-sdk/basics-errorhandling.html#catching-a-pnp-core-sdk-exception-and-getting-the-exception-details for some details on how to do that. Alternatively do a Fiddler trace and share the failing request + response.

**Comment by CodingJarod** [comment]
Hi @jansenbe, after checking againt (after some hour of sleep :) ) there was a misconfiguration on the app registration side.
Thanks for the support.
