### ISSUE TITLE
Microsoft 365 "POL" GeoLocation Missing

### ISSUE THREAD

**Issue by Sean-LM** [pnp/pnpcore#1232]
## Category

- [x] Bug

## Describe the bug

> The `POL` `GeoLocation` is missing.

## Steps to reproduce

1. Reference the Microsoft Documentation here: https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide#microsoft-365-multi-geo-availability
2. Reference the PnP Core `GeoLocation` enum here: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Admin/Model/Microsoft365/Public/Enums/GeoLocation.cs
3. Observe that `POL` is missing in the PnP Code enum.

## Expected behavior

The `POL` GeoLocation should be present and available for operations in the library.

## Environment details (*development & target environment*)
n/a

### Additional context
n/a

Thank you! If this is as simple as adding an entry to the `GeoLocation` enum (I don't see any specific country mentions in the code, but did not dig deeply), I can open a PR. I do not know the side-effects internally of such an addition.

**Comment by jansenbe** [comment]
Thanks for raising this @Sean-LM , I've added a fix which will be part of the next nightly build, closing the issue now.
