### ISSUE TITLE
EnsureAsync - Wrong UniqueId in Followup Queries

### ISSUE THREAD

**Issue by randellhodges** [pnp/pnpcore#1236]
## Category

- [x] Bug

## Describe the bug

Let's say I have the following path created in my sharepoint list

/Folder1

Run this code

```
var folder = await List.RootFolder.EnsureFolderAsync("Folder1/Folder2");
await folder.EnsurePropertiesAsync(f => f.Properties);
```

The properties loaded are not for "Folder2" but for the last folder that wasn't created, in this case "Folder1".

I verified this by looking at the url in the debugger:

https://URL/sites/SITE/_api/Web/getFolderById('eda92902-5a83-44d8-abcc-466774812d14')?$select=UniqueId%2cProperties&$expand=Properties

eda92902-5a83-44d8-abcc-466774812d14 = Folder1

I did add a debug before the EnsurePropertiesAsync call to look at the UniqueId on folder and it is correct.

If I run the code a second time, everything works (because EnsureFolderAsync didn't create a folder).

I even tried folder.LoadAsync and still had the same issue.

Note: I'm not sure the SharePoint api supports it, but it would be nice to also include the properties to return at the time of creation.

## Expected behavior

That the properties load for the folder specified

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows 11
- **SDK used in**:  Web App
- **Framework**:  NET Core v6
- **Browser(s)**: Chromium Edge
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@randellhodges : it's currently not possible to immediately request the folder properties to load, but making a call after works fine. While checking your approach I've found a bug which I'll fix, but with the current bits below works

```csharp
// Ensure the folder hiararchy
var addedFolder = await parentFolder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5");

// Load the properties you need : WORKS
addedFolder = await context.Web.GetFolderByIdAsync(addedFolder.UniqueId, p => p.Properties);

// FAILS today, but will be fixed
await addedFolder.LoadAsync(p => p.Name, p => p.Properties);
await addedFolder.EnsurePropertiesAsync(p => p.Properties);
```

Thanks for using PnP Core SDK and reporting this.

**Comment by jansenbe** [comment]
@randellhodges : a fix has been added, with tomorrow's nightly build you'll be able to use the other approaches as well. Will close this issue now, please re-open or create a new one whenever things are still not working for you
