### ISSUE TITLE
Expose `LongRunningOperation`

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpcore#1237]
## Category

- [x] Feature request

## Describe the feature

Currently the `LongRunningOperation` class is marked as `internal`. There are some cases where it is desirable to be able to create an instance manually. For example, you may wish (or need) to serialize the job location and query it elsewhere (such as with Azure Functions).

## Describe the solution you'd like

The easiest solution would just be to mark the class as `public`, but it may be preferable to have some helper/factory method on the context to avoid passing the context into the `LongRunningOperation` constructor manually.

## Additional context

It is currnetly possible to query the job using Graph directly, but a solution through PnP Core would be ideal.

I'd be happy to take this on since it's a small job - just let me know what the thoughts are on how it should be done :)

**Comment by jansenbe** [comment]
Thanks for the issue and linked PR @JakeStanger ! You are right that it indeed makes sense to allow public usage of the LongRunningOperation class. I'll have a look at your PR.

**Comment by jansenbe** [comment]
@JakeStanger : merged your PR, fix will be part of the next nightly.
