### ISSUE TITLE
Error creating PnP context using VisualStudioCredential

### ISSUE THREAD

**Issue by milkyware** [pnp/pnpcore#1246]
## Category

- [x] Error

## Describe the bug

Hi. I'm trying to extend the example of using [managed identities](https://pnp.github.io/pnpcore/demos/Demo.AzFunction.ManagedIdentity/README.html) to authenticate to SPO. In the sample, it uses a customised **ChainedTokenCredentials** to default to prioritising managed identity credentials.

``` csharp
public async Task<string> GetAccessTokenAsync(Uri resource, string[] scopes)
{
    ArgumentNullException.ThrowIfNull(resource);
    ArgumentNullException.ThrowIfNull(scopes);

    var credential = new Azure.Identity.ChainedTokenCredential(
                 new ManagedIdentityCredential(),
                 new EnvironmentCredential()
                 );
    var accessToken = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(scopes));

    return accessToken.Token;
}
```

However, after some further reading of Azure.Identity [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential) I noticed that the default chain included a **[VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#authenticate-via-visual-studio)** which makes use of a VS extension to authenticate as _you_ in Azure.Identity which would greatly simplify the local debugging process. When using the below token chain (based on the example) in the custom provider:

``` csharp
public async Task<string> GetAccessTokenAsync(Uri resource, string[] scopes)
{
    ArgumentNullException.ThrowIfNull(resource);
    ArgumentNullException.ThrowIfNull(scopes);

    var credential = new ChainedTokenCredential(new VisualStudioCredential());

    var accessToken = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(scopes));

    return accessToken.Token;
}
```

... I get the error:

```
Process "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS65002: Consent between first party application '04f0c124-f2bc-4f59-8241-bf6df9866bbd' and first party resource '00000003-0000-0ff1-ce00-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
```

With both this VS token service extension and SharePoint being owned by Microsoft I'm trying to work out where this issue would best be placed. Any suggestions would be welcome.

## Steps to reproduce

1. Swap the ChainedTokenCredential credentials to use VisualStudioCredential
2. Sign into Tools > Options > Azure Service Authentication
3. Create a new PnPContext from context factory

## Expected behaviour

The context is created successfully

## Environment details (*development & target environment*)

- **SDK version**: 7.0.306
- **OS**: Win 11
- **SDK used in**: Function App v4
- **Framework**: .NET 6
- **Tooling**: VS 2022

**Comment by milkyware** [comment]
@jansenbe No, still having issues. Interestingly the TokenService does work with the Dataverse SDK. Any suggestions would be appreciated

**Comment by jansenbe** [comment]
@milkyware : I'm closing this one as there's no other asks for this feature.
