### ISSUE TITLE
HTTP 409 on upload of file to Sharepoint

### ISSUE THREAD

**Issue by gopland-pinc** [pnp/pnpcore#1247]
## Category

- [x] Bug

## Describe the bug

I have a created a program that uses PnP.Core library to upload 150MB files to Sharepoint more than a hundred times a day, but the program runs sequentially and is always ever only uploading one file at a time.  This program has been running without issue for a couple years.  Recently, within the past year and perhaps coinciding with updating PnP.Core to a particular version (we are currently using version 1.8.0), maybe 10-15 times per day when we attempt to upload one of the files, I receive the following exception:

HttpResponseCode: 409
Code: Microsoft.SharePoint.SPException
Message: Save Conflict

Your changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes.
ClientRequestId: 999eeee9-999e-9999-999e-eee9ee9e999e
SPClientServiceRequestDuration: 6869
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.SharePoint.FileCollection.ChunkedFileUpload(File newFile, Stream content, Boolean overwrite)
   at PnP.Core.Model.SharePoint.FileCollection.AddAsync(String name, Stream content, Boolean overwrite)
   at PnP.Core.Model.SharePoint.FileCollection.Add(String name, Stream content, Boolean overwrite)
...

I can often re-run the same upload a couple minutes later and the upload completes successfully without the above exception.
 
## Steps to reproduce

1. See code
  `context.Web.LoadAsync(p => p.RootFolder).GetAwaiter().GetResult();
  var targetfolder = context.Web.RootFolder.EnsureFolderAsync(pathToFolder).GetAwaiter().GetResult();
  if (targetfolder != null)
  {
      targetfolder.Files.Add(fileName, fileStream);
  }` 

## Expected behavior

Expect the file upload to complete successfully every time.

## Environment details (*development & target environment*)

- **OS**: Windows Server 2019
- **SDK used in**: Console App
- **Framework**: Microsoft.NETCore.App 6.0.18
- **Browser(s)**: N/A

### Additional context

Again, this problem is intermittent.  The code uploads many, many files without exception and the exception only started happening within the past year.

**Comment by jansenbe** [comment]
@gopland-pinc : this feels like either a backend/network issue or a versioning issue, the code doing the upload for large files hasn't changed since it was added in August 2020.

Are you overwriting existing files or adding new files? Are there possibly workflow/rules defined on the target libraries that can interact with the file during it's upload?

**Comment by gopland-pinc** [comment]
@jansenbe : I really appreciate the response.  When you say "backend/network issue" does "backend" refer to Sharepoint Online?  By "network" are you referring to a potential network issue on my application's network?

We are only adding new files.  There is a process that can read these uploaded files, but that process cannot be aware of the path to these uploaded files until a successful email is sent out AFTER a successful upload (which is obviously not getting sent in these 409 error cases).  I do have one other daily Power Automate flow on this library that purges old files but it only runs once a day for 30 seconds and these 409 errors occur at completely different times than when this Power Automate flow runs.

I was really hoping someone else would have at least experienced this issue at some point, receiving a 409 error with no other process interacting with the file because it does seem to me like it must be something outside my application's control.  One other detail I neglected to mention is that, when this 409 error occurs, we end up with a 0 byte file in Sharepoint.

**Comment by jansenbe** [comment]
Hey @gopland-pinc ,

I've found a similar open issue and linked this GitHub issue with it, but if you've the option to open up a support ticket with us I would recommend doing so. This clearly is not an issue in PnP Core SDK and the guidance for product issues is to open official support tickets.

**Comment by jansenbe** [comment]
Closing as this is not related to PnP Core SDK
