### ISSUE TITLE
Impossible to unlock site collection after PnP.Core.Admin 1.9.0

### ISSUE THREAD

**Issue by SPWizard01** [pnp/pnpcore#1251]
## Category

- [x] Bug

## Describe the bug

It is impossible to unlock site collection after upgrading PnP.Core.Admin to 1.9.0 or later, you get ErrorCode=-2130575247 in ProcessQuery

## Steps to reproduce
Downgrade to 1.8.0 and check the code below works properly, upgrade to 1.9.0 or above and see that site can no longer be unlocked.

    var context = pnpContextFactory.Create(new Uri(rootSiteUrl));
    var sitemgr = context.GetSiteCollectionManager();
    var siteProps = sitemgr.GetSiteCollectionProperties(new Uri(targetSiteUrl));
    siteProps.LockState = "NoAccess";
    siteProps.Update();
    siteProps.LockState = "Unlock";
    //it will fail here in version 1.9.0 or above, it will lock the site though.
    siteProps.Update();

## Expected behavior

Site should be unlocked without issues

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET Core v7.x
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022 Preview 6
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

I have noticed that in XML payload in version 1.9.0 and above it adds additional properties such as: SetProperty [ Id=4 ObjectPathId=1 Name=ExcludedBlockDownloadGroupIds ] which i think could be a culprit, because site is Locked/ReadOnly so it cannot write these properties beforehand.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@SPWizard01 : I was able to repro and fix this. Using the next nightly should work, therefore I'm closing the issue now.
