### ISSUE TITLE
pre-generated classes for HomeSite

### ISSUE THREAD

**Issue by PBLPointwork** [pnp/pnpcore#1252]
## Category

- [x] Domain model extension

## Describe the domain model extension

I would like to update the domain model with HomeSiteDetails, so I'm able to extend pnpCore with support for HomeSite
 
[ScriptType("SP.HomeSitesDetails", ValueObject = true, ServerTypeId = "{50f9f050-ff91-4f66-bfb7-a8ffd5317d5f}")]
    public class HomeSitesDetails : ClientValueObject

### Model

Model: HomeSitesDetails
Properties:

### APIs

Microsoft.SharePoint.Client - SP.HomeSitesDetails

API :

### Additional Information

Microsoft.SharePoint.Client - SP.HomeSitesDetails

**Comment by jansenbe** [comment]
@PBLPointwork : Did you manage to extend PnP Core SDK in this way? If so, feel free to contribute this as PR

**Comment by jansenbe** [comment]
Closing: old issue and have not seen other asks for this one. Please us the custom API support for now to deal with this one.
