### ISSUE TITLE
PNP Core SDK - Blazor Sample does not work.

### ISSUE THREAD

**Issue by Scottlis26** [pnp/pnpcore#1258]
## Category

- [x] Bug

## Describe the bug

PNP Core SDK - Blazor Sample
There was an error logging you in.

## Steps to reproduce

1) Cloned the project and Updated appsettings.json:
From:
  "SharePoint": {
    "SiteUrl": "https://bertonline.sharepoint.com/sites/prov-1"
  },
  "AzureAd": {
    "Authority": "https://login.microsoftonline.com/d8623c9e-30c7-473a-83bc-d907df44a26e",

To (substituted {tenant} and {tenant_id} with a Microsoft 365 Sandbox subscription tenant id:

SharePoint": {
    "SiteUrl": "https://{tenant}.sharepoint.com/sites/pnpcoresdktestgroup/"
  },
  "AzureAd": {
    "Authority": "https://login.microsoftonline.com/{tenant_id}",

2) F5 to run, the site loads in localhost

3) Click Site from the left menu

4)  2 factor authentication dialog appears and accepts valid credentials 

5)  There was an error logging you in. Tried this various times including with the browser in In Private mode and it did not work. There did not appear to be any useful error codes in DevTools other than authentication failed and login.microsoft.com ... returned 400 Bad Request.

## Expected behavior

Expected to see a list of SharePoint sites. 

## Environment details (*development & target environment*)

- **SDK version**: [e.g. 0.1.2005.0 ]
- **OS**: [e.g. Windows 10 
- **SDK used in**: [e.g. Console App | ASP.Net Web app | Blazor WebAssembly]
- **Framework**: net7.0
- **Browser(s)**: Chromium Edge 115.0.1901.203
- **Tooling**:  Visual Studio 2022
- **Additional details**:  Microsoft 365 Sandbox E5 subscription

**Comment by jansenbe** [comment]
@Scottlis26 : did you follow the steps described in here: https://pnp.github.io/pnpcore/demos/Demo.Blazor/README.html#register-and-configure-an-aad-app. Especially the app id portion and admin consent flow

**Comment by Scottlis26** [comment]
Yes, the app id was updated and the admin consent flow was granted. It's pretty easy to spin up a free MS 365 Sandbox subscription. Possibly installing the app in the free environment will allow you to reproduce the error.

**Comment by jansenbe** [comment]
@Scottlis26 : this sample will work with a free tenant (although I did not test that). I just tried the sample from my end and it worked, then I upgraded the sample to use the latest PnP.Core library and it still works. Still think something is missing in your auth setup

**Comment by scottlis** [comment]
Yes. Here is a screen shot of the permissions that have been granted: 
![image](https://github.com/pnp/pnpcore/assets/17594663/53cdc011-e4c4-4ec7-8e22-4958c37f88ce)

**Comment by scottlis** [comment]
And the callback: 
![image](https://github.com/pnp/pnpcore/assets/17594663/182440a9-6f5a-4c50-b00a-b0a766488149)

**Comment by jansenbe** [comment]
@scottlis : why do you have those other settings in the AzureAD node? I only have this:
![image](https://github.com/pnp/pnpcore/assets/7451219/3e6b3c50-6084-4165-b848-b462f3204c15)
The d8... one is my tenant id.

For call back I've listed https://localhost:5001/authentication/login-callback

**Comment by scottlis** [comment]
Ok, changed the redirect and put the tenant in the Authority attribute. Still fails. Using "In Private" to force auth. Here is a screen:
![image](https://github.com/pnp/pnpcore/assets/17594663/1f621a92-e9f4-40fa-bc57-9f3867a7e0a8)

**Comment by jansenbe** [comment]
Can you configure a "single-page application" with that redirect URI, not a "web" one

![image](https://github.com/pnp/pnpcore/assets/7451219/e4c8c9d2-c497-449e-8a1b-06542f6a31a4)

**Comment by scottlis** [comment]
That works. Thanks!
![image](https://github.com/pnp/pnpcore/assets/17594663/e7961bf5-92da-4a49-a6ea-f9eb58d6e601)

**Comment by wfrf92** [comment]
@jansenbe  Please update the README.md
