### ISSUE TITLE
PnP Core and Method not found 

### ISSUE THREAD

**Issue by sonomirco** [pnp/pnpcore#1264]
Hi there, 
This is not a PnP Core Bug, but I am trying to get more information to see how I can solve the current problem I am having.
I am trying to implement some `SharePoint` functionalities for Dynamo Revit which is a Visual Scripting environment for 3D modelling.
I am currently using the PnP Core library; the problem is that I have this error when I set the `HostService`.
![image_2023-08-28_12-37-58|542x286](upload://gJ8OdDv1sKdCxRJE5DyC0sQLtEv.png)

This is how the host is implemented, nothing different from how the PnP documentation suggests.
![image_2023-08-28_19-18-36|534x500](upload://avKYnfgwTb0U2zxjwrLJ2J63DI9.png)

From some research, the error could be caused by old Dlls versions.
https://stackoverflow.com/questions/8058832/system-missingmethodexception-method-not-found

Any ideas? Or suggestions?
Thanks

**Comment by jansenbe** [comment]
@sonomirco : the images with code you've pasted on not showing up at my side, you paste them again?

**Comment by sonomirco** [comment]
I definitely think is a dependency problem.
https://forum.dynamobim.com/t/pnp-core-and-method-not-found/93275/2

**Comment by jansenbe** [comment]
@sonomirco : PnP Core SDK ships with 3 binary versions, .NET Standard 2.0, .NET 6 and .NET 7 and each of these uses different versions of those assemblies (see https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/PnP.Core.csproj#L45-L79). Seems like the platform you're loading your plug-in into is still using [.NET Core 3.1, which is out of support](https://dotnet.microsoft.com/en-us/download/dotnet/3.1). What you could try is using our .NET Standard 2.0 binaries, these are compatible with .NET Core 3.1 and might work.

**Comment by sonomirco** [comment]
The platform is targeting framework .48

**Comment by jansenbe** [comment]
@sonomirco : that you must use our .NET Standard 2.0 bits, these work with .NET Framework 4.8

**Comment by sonomirco** [comment]
@jansenbe I am targeting standard but the problem is the dependency versions clashing.

**Comment by jansenbe** [comment]
@sonomirco : you're screenshot is showing version 7.0.0.0 being used for Microsoft.Extensions.DependencyInjection.Abstractions while the .NET Standard 2.0 version uses version 2.2.0.0. So feels like somehow the wrong binaries are included in your solution.

![image](https://github.com/pnp/pnpcore/assets/7451219/0ed4aba0-1e8a-4282-9a92-5d3b456eae56)

**Comment by sonomirco** [comment]
Thanks @jansenbe 
What is strange is that all the errors come from the host and dependencies that it uses.
![image](https://github.com/pnp/pnpcore/assets/57708659/9ea7a676-75c2-42c9-933b-b8a876e121bc)
