### ISSUE TITLE
Set LockState to Unlock

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#1271]
## Category

- [x] Bug

## Describe the bug

Update LockState to Unlock is not working. To set the SitecollectionProperties LockSate to ReadOnly works fine. But to go back to Unlock not working. 

## Steps to reproduce

var siteProps = adminContext.GetSiteCollectionManager().GetSiteCollectionProperties(new Uri(siteUrl));
siteProps.LockState = "ReadOnly";
siteProps.Update();
                    
Waiting

var siteProps = adminContext.GetSiteCollectionManager().GetSiteCollectionProperties(new Uri(siteUrl));
siteProps.LockState = "Unlock";
siteProps.Update();

Error  : CSOM service exception "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"
                    
## Expected behavior

Unlock to site again. similar like set-pnpsite -LockState Unlock -Identity "URL"

## Environment details (*development & target environment*)

PNPO.Core.Admin 1.10.0

**Comment by jansenbe** [comment]
@raclettierer : this should have been fixed already (see #1251). Can you test with recent nightly and see if you still can reproduce?

**Comment by raclettierer** [comment]
Works with 1.10.76-nightly
