### ISSUE TITLE
Lately getting intermittent error "The Specified program requires a newer version of windows" when adding fields to a list.

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpcore#1272]
## Category

- [x] Bug

## Describe the bug

Since couple of days getting intermittent error "The Specified program requires a newer version of windows" when adding fields to a list using `AddFieldAsXmlAsync()` or `AddFieldAsXmlBatchAsync()`. Sometimes it works and sometimes it doesn't. The above code has been working for a long time in PROD. Surprised to see it is failing now. Did not test the `AddTextAsync()` though.

Update: `AddTextAsync()` too fails intermittently. After all, this calls `AddFieldAsXmlAsync()` internally.

## Steps to reproduce

Try adding a field to a list like below

`await list.Fields.AddFieldAsXmlAsync($"<Field DisplayName=\"TestField\" Type=\"Text\" Required=\"FALSE\" Name=\"TestField\" Version=\"1\" />", true);`
OR
`await list.Fields.AddFieldAsXmlBatchAsync($"<Field DisplayName=\"TestField\" Type=\"Text\" Required=\"FALSE\" Name=\"TestField\" Version=\"1\" />", true);`

## Expected behavior

When adding a field, we should not see any errors.

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: Windows
- **Framework**: .NET Core v6.0
- **Tooling**: Visual Studio 2019

**Comment by jansenbe** [comment]
@NewGHUser4321 : I'm guessing there's some network proxy/security device that sees the XML and acts on it. This does not seem to be a bug in the library, nor an issue within the SharePoint service. Can you reproduce this in another network setup?

**Comment by NewGHUser4321** [comment]
@jansenbe: My spfx app directly connects to the azure app service where this code is executed. I got the same error when I tried outside of my company network as well. This is the stack trace I'm getting when using the `AddTextAsync()`
![image](https://github.com/pnp/pnpcore/assets/105061286/2ba00517-40f4-4da4-accb-1621dfc87e6a)

I'll try using `list.ExecuteRequestAsync()` with the SharePoint Endpoint to add the fields and see if I get any errors.

**Comment by jansenbe** [comment]
@NewGHUser4321 : does it happen for all field XML?

**Comment by NewGHUser4321** [comment]
@jansenbe Yes, I just tried it and it is failing for other fields as well. I also tried directly calling the SharePoint endpoint like below to create a field, but it is still failing with the same error. I'm creating and adding at-least 15 fields to the list. Looks like something wrong with the endpoint itself when trying to create lot of fields within a short time span? It worked all this while for the past six months and suddenly starts failing.
```
var fields = GetListFields();
string endpointUrl = $"{siteUrl}/_api/web/GetList(@a1)/Fields/CreateFieldAsXml?@a1='{list.RootFolder.ServerRelativeUrl}'";
foreach (var field in fields)
{
    if (field.FieldType == FieldType.DateTime)
    {
        var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, endpointUrl, $"{{\"parameters\":{{\"__metadata\":{{\"type\":\"SP.XmlSchemaFieldCreationInformation\"}},\"SchemaXml\":\"<Field DisplayName='{field.InternalName}' Type='{field.FieldType}' Required='FALSE' Name='{field.InternalName}' Format='{field.DisplayFormat}'></Field>\",\"Options\":{(field.AddToView ? 16 : 0)}}}}}");
        await list.ExecuteRequestAsync(apiRequest);
    }
    else if (field.FieldType == FieldType.Note)
    {
        var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, endpointUrl, $"{{\"parameters\":{{\"__metadata\":{{\"type\":\"SP.XmlSchemaFieldCreationInformation\"}},\"SchemaXml\":\"<Field DisplayName='{field.InternalName}' Type='{field.FieldType}' Required='FALSE' Name='{field.InternalName}' NumLines='{field.NumLines ?? 6}' RichText='{field.RichText ?? false}'></Field>\",\"Options\":{(field.AddToView ? 16 : 0)}}}}}");
        await list.ExecuteRequestAsync(apiRequest);
    }
    else if (field.FieldType == FieldType.Calculated || field.InternalName == CPIPatentFields.TitleField)
    {
        continue;
    }
    else if (field.FieldType == FieldType.URL)
    {
        var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, endpointUrl, $"{{\"parameters\":{{\"__metadata\":{{\"type\":\"SP.XmlSchemaFieldCreationInformation\"}},\"SchemaXml\":\"<Field DisplayName='{field.InternalName}' Type='{field.FieldType}' Required='FALSE' Name='{field.InternalName}'></Field>\",\"Options\":{(field.AddToView ? 16 : 0)}}}}}");
        await list.ExecuteRequestAsync(apiRequest);
    }
    else
    {
        var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, endpointUrl, $"{{\"parameters\":{{\"__metadata\":{{\"type\":\"SP.XmlSchemaFieldCreationInformation\"}},\"SchemaXml\":\"<Field DisplayName='{field.InternalName}' Type='{field.FieldType}' Required='FALSE' Name='{field.InternalName}'></Field>\",\"Options\":{(field.AddToView ? 16 : 0)}}}}}");
        await list.ExecuteRequestAsync(apiRequest);
    }
}
```

**Comment by NewGHUser4321** [comment]
@jansenbe This looks like a SharePoint Service issue. I tried using the same endpoint to add fields to a list using the frontend javascript. It is failing intermittently with the same error.
I also tried `_api/web/lists/getByTitle('Test List')/fields/createfieldasxml` endpoint with the body as below. Still getting the same error intermittently.
![image](https://github.com/pnp/pnpcore/assets/105061286/e27ee866-45d0-4a5f-93a9-321f30ff94c8)

**Comment by jansenbe** [comment]
@NewGHUser4321 : do you (or your customer) have an option to log a support ticket for this? I can see what I can find from my end, but if it's a service issue then the best approach is going via the official support channels

**Comment by NewGHUser4321** [comment]
@jansenbe Yes, I have the option to open a support ticket. Will do. Thanks.

**Comment by jansenbe** [comment]
@NewGHUser4321 : I've found this thread (https://github.com/pnp/pnpjs/issues/172) which also talks about a timing issue. Did you try with adding some more time in between each field creation request?

**Comment by NewGHUser4321** [comment]
@jansenbe Thanks for checking. Yes, I saw that post and I tried adding a 100ms wait between each field creation request and I get the same error.

**Comment by jansenbe** [comment]
@NewGHUser4321 : is this problem still around?

**Comment by NewGHUser4321** [comment]
@jansenbe Yes, Microsoft is working on the ticket. They got the necessary failure logs they needed and they are going through them.

**Comment by jansenbe** [comment]
@NewGHUser4321 : did you manage to get this resolved (via support)?

**Comment by NewGHUser4321** [comment]
@jansenbe No. After bunch of back and forth communication, they say it is not a bug and we have to wait at least 1 sec before adding another field. I switched my code to CSOM. It worked when I got a new context for every new field. You can close this issue.
