### ISSUE TITLE
IFolder.MoveTo with RetainEditorAndModifiedOnMove

### ISSUE THREAD

**Issue by randellhodges** [pnp/pnpcore#1273]
## Category

- [x] Bug

## Describe the bug

```
            var options = new MoveCopyOptions
            {
                ResetAuthorAndCreatedOnCopy = false,
                RetainEditorAndModifiedOnMove = true
            };

            await item.Folder.MoveToAsync(destination, options);
```

The RetainEditorAndModifiedOnMove  option isn't being used:

https://github.com/pnp/pnpcore/blob/e2e579f001a9dcaf1277303dc9ccc0876a197271/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/Folder.cs#L264-L270

Here is what was posted:

`/sites/ap/_api/SP.MoveCopyUtil.MoveFolderByPath()`

Note: I am moving within the same site and same list. Just moving into a subfolder.

```
{
	"destPath": {
		"__metadata": {
			"type":"SP.ResourcePath"
		},
		"DecodedUrl":"<URL>/<FOLDER>"
	},
	"srcPath":{
		"__metadata":{
			"type":"SP.ResourcePath"
		},
		"DecodedUrl":"<URL>/<FOLDER>/<SUBFOLDER>"
	},
	"options":{
		"__metadata":{
			"type":"SP.MoveCopyOptions"
		},
		"KeepBoth":false,
		"ResetAuthorAndCreatedOnCopy":false,
		"ShouldBypassSharedLocks":false
	}
}
```

## Expected behavior

Editor/Edited should be retained (and Author/Authored)

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows 11
- **SDK used in**: ASP.Net Web app
- **Framework**:  .NET Core v36
- **Browser(s)**: Chromium Edge
- **Tooling**: Visual Studio 2022

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by randellhodges** [comment]
I just tried a copy/paste of the source code but added in that flag, and unless I did something wrong, it seems the SPO api doesn't respect it? I'm still playing around with it.

On a side note, is there a good source of documentation for these rest endpoints. Seems hit or miss looking around Microsofts site.

**Comment by jansenbe** [comment]
@randellhodges , sorry but there's no proper documentation of most REST calls. In general when setting editor/modified fields one needs the proper permissions (see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-the-list-item-author-editor-created-and-modified-system-properties). What permission scope is your app using?

**Comment by randellhodges** [comment]
It has full permissions. If I store the author/authored/editor/edited values, perform the move, and then set them back after the move with a UpdateOverwriteVersionAsync call, I can confirm they are changed back. 

Without the UpdateOverwriteVersionAsync call and just a MoveTo (even with my modified version of that method that does pass the RetainEditorAndModifiedOnMove flag) I noticed it resets the Editor/Edited values.

Not working:
1) Look at the item in SharePoint, note the Modified By/Modified
2) Load the item
3) Call MoveTo (with options setting RetainEditorAndModifiedOnMove)
4) Verify that Modified By/Modified was not retained after the move

Working
1) Look at the item in SharePoint, note the Modified By/Modified
2) Load the item
3) Grab the Created/Modified values
4) Call MoveTo
5) Set Created/Modified
6) Call UpdateOverwriteVersionAsync

I am going to do a little more testing today, just to be 100% sure it isn't something stupid I'm missing.

Here is the modification of the Pnp.Core MoveToAsync method I attempted to make

```
        public static async Task CustomMoveToAsync(this IFolder folder, string destinationUrl, MoveCopyOptions options = null)
        {
            // This workaround is only if we have MoveCopyOptions
            if (options == null || options.RetainEditorAndModifiedOnMove == false)
            {
                await folder.MoveToAsync(destinationUrl, options);
                return;
            }

            var contextUri = folder.PnPContext.Uri.EnsureTrailingSlash();

            var dstUri = new Uri(contextUri, destinationUrl);
            var srcUri = new Uri(contextUri, folder.ServerRelativeUrl);

            // If options are specified, use the CopyByPath API endpoint
            var parameters = new
            {
                destPath = new
                {
                    __metadata = new { type = "SP.ResourcePath" },
                    DecodedUrl = dstUri.ToString()
                },
                srcPath = new
                {
                    __metadata = new { type = "SP.ResourcePath" },
                    DecodedUrl = srcUri.ToString()
                },
                options = new
                {
                    __metadata = new { type = "SP.MoveCopyOptions" },
                    options.KeepBoth,
                    options.ResetAuthorAndCreatedOnCopy,
                    options.RetainEditorAndModifiedOnMove,
                    options.ShouldBypassSharedLocks
                }
            };

            var body = JsonConvert.SerializeObject(parameters);

            var req = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, "_api/SP.MoveCopyUtil.MoveFolderByPath()", body);
            var res = await folder.PnPContext.Web.ExecuteRequestAsync(req);
        }
    }
```

which produced a payload like:

```
{
    "destPath": {
        "__metadata": {
            "type": "SP.ResourcePath"
        },
        "DecodedUrl": "<URL>/<FOLDER>/<SUBFOLDER>"
    },
    "options": {
        "__metadata": {
            "type": "SP.MoveCopyOptions"
        },
        "KeepBoth": false,
        "ResetAuthorAndCreatedOnCopy": false,
        "RetainEditorAndModifiedOnMove": true,
        "ShouldBypassSharedLocks": false
    },
    "srcPath": {
        "__metadata": {
            "type": "SP.ResourcePath"
        },
        "DecodedUrl": "<URL>/<FOLDER>"
    }
}
```

And even that didn't retain the Editor/Edited (It did perform the move, so I know at least I didn't completely mess it up). So, it might be a SPO API issue.

**Comment by jansenbe** [comment]
@randellhodges : good to hear you've a workaround via the `UpdateOverwriteVersion` methods. I've also found this to be interesting: https://github.com/pnp/pnpjs/issues/2474. Did you consider the `ISite.CreateCopyJobs` methods (https://pnp.github.io/pnpcore/using-the-sdk/sites-copymovecontent.html#copyingmoving-multiple-files) as alternative?

**Comment by jansenbe** [comment]
@randellhodges : what you see is not an issue with PnP Core SDK, hence I'm going to close this issue. I would recommend checking out the `ISite.CreateCopyJobs` methods as alternative and see if they can help with your case.
