### ISSUE TITLE
Getting file versions returns "Operation is not valid due to the current state of the object" on files > 2Gb

### ISSUE THREAD

**Issue by lasyan3** [pnp/pnpcore#1274]
## Category

- [x] Bug

## Describe the bug

I think there is an issue with files bigger than at least 1.10 Gb : I'm unable to get versions of such files, I always get an "Operation is not valid due to the current state of the object". For files less than that is OK.

## Steps to reproduce

Try to get versions of big file using :
```
await context.Web.GetFileByServerRelativeUrlAsync($"{context.Uri.PathAndQuery}/path", f => f.Versions);
```

## Expected behavior

No error.

## Environment details (*development & target environment*)

- **SDK version**: 1.10.81-nightly
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022
- **Additional details**: connection using certificate

**Comment by lasyan3** [comment]
Example of code with failure (taken from the documentation):
```
using (var scope = host.Services.CreateScope())
{
    // Ask an IPnPContextFactory from the host
    var pnpContextFactory = scope.ServiceProvider.GetRequiredService<IPnPContextFactory>();

    // Create a PnPContext
    using (var context = await pnpContextFactory.CreateAsync(new Uri(siteUrl)))
    {
        // Load the Title property of the site's root web
        await context.Web.LoadAsync(p => p.Title);
        Console.WriteLine($"The title of the web is {context.Web.Title}");

        var file = await context.Web.GetFileByServerRelativeUrlAsync($"{context.Uri.PathAndQuery}/Shared Documents/General/marketing/SAUVEGARDE SIG/Sauvegarde Kevin" +
            $"/24scales_8.0compatibility/HE-SM-M18-FX_cua.gcm"
            , f => f.Versions);
    }
}
```

**Comment by jansenbe** [comment]
@lasyan3 : so you do have a workaround or are you still blocked?

**Comment by lasyan3** [comment]
I found a workaround but the issue is still there 😉
