### ISSUE TITLE
Error in ListDataAsStreamHandler when previously requested items are present

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/pnpcore#1276]
## Category

- [x] Bug

## Describe the bug

When loading list items multiple times, on the same `PnPContext`, this throws as the keys are already present for the file instance:

https://github.com/pnp/pnpcore/blob/41eb7f575d79a985849b1a8e9292c105567a6324/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/ListDataAsStreamHandler.cs#L210-L211

I suppose `AsRequested()` is serving previously loaded items:

https://github.com/pnp/pnpcore/blob/41eb7f575d79a985849b1a8e9292c105567a6324/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/ListDataAsStreamHandler.cs#L84

## Steps to reproduce

Don't have specific steps to reproduce. I stumbled over this behavior while optimizing around in PnP.Framework, reusing a PnPContext where it has not been reused before.

## Expected behavior

I'd expect above lines not to throw.

This could be a fix:

```csharp
(file as IMetadataExtensible).Metadata[PnPConstants.MetaDataRestId] = uniqueId.ToString();
(file as IMetadataExtensible).Metadata[PnPConstants.MetaDataType] = "SP.File";
```

But I'd sleep better if somebody looked over this and found it to be the right thing to do.

## Environment details (*development & target environment*)

- **SDK version**: 1.10
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**: .NET Core 6

## Additional notes:

Might be relevant here as well:

https://github.com/pnp/pnpcore/blob/41eb7f575d79a985849b1a8e9292c105567a6324/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/ListDataAsStreamHandler.cs#L229-L230

**Comment by jansenbe** [comment]
@heinrich-ulbricht : what you is by design currently, if you want to reuse the context then you can always clear the items collection upfront. This approach has been documented here: https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-paging-with-listdataasstream (second code snippet in that section).

**Comment by heinrich-ulbricht** [comment]
@jansenbe I can accept that ^^

Although the docs don't match what I am doing. I'm deliberately reading the same page again. The docs refer to optimizations when paging. For my mental modal not an immediate match.

But the code that does this is in a test case. So no worries. It just looked like it could've been a bug.

**Comment by jansenbe** [comment]
@heinrich-ulbricht : I'll add a note to the docs explaining that you need to clear the items collection if you want to reuse it across loads
