### ISSUE TITLE
Add support for ISite.GetMigrationJobStatus

### ISSUE THREAD

**Issue by joymon** [pnp/pnpcore#1277]
## Category

- [x] Feature request

## Describe the feature

> site.GetMigrationJobStatus() method is missing

## Describe the solution you'd like

> Add the method to ISite

## Additional context

> This method can be used to check high-level status of CreateCopyJobs by just giving the JobId.

**Comment by jansenbe** [comment]
Hey @joymon ,

We currently haven't implemented support for the migration APIs in PnP Core and this is also not on our plans for the moment. The recommendation is to keep using CSOM for this specific feature, you can use PnP Framework as that brings interop between PnP Core SDK and CSOM (see https://pnp.github.io/pnpcore/using-the-sdk/basics-pnpframework.html#using-pnp-framework-when-the-pnp-core-sdk-was-already-configured) or you can just use CSOM like you've done in the past.

**Comment by joymon** [comment]
Thanks @jansenbe for acknowledging the gap and the workaround. Hope this can be kept open till the feature is implemented.

**Comment by jansenbe** [comment]
@joymon , I'm going to close this is we've no intent to bring the migration APIs to this library, they're too much of niche scenario and we recommend to keep using CSOM for that. Hope you can understand, thanks for reaching out and using PnP Core SDK.
