### ISSUE TITLE
The list item could not be added or updated because duplicate values were found in one or more fields in the list.

### ISSUE THREAD

**Issue by Gareth064** [pnp/pnpcore#1280]
## Category

- [x] Bug

## Describe the bug

Received an error when uploading file to SPO

_HttpResponseCode: 500
Code: Microsoft.SharePoint.SPException
Message: The list item could not be added or updated because duplicate values were found in one or more fields in the list.
ClientRequestId: 805dd9a0-f091-7000-3a57-b47cd9144141
SPClientServiceRequestDuration: 628
X-SharePointHealthScore: 1
X-SP-SERVERSTATE: ReadOnly=0_

This happened when uploading a brand new file (It was a word document.) to a SPO site library.

I understand that the error message is suggesting that something to do with that document is causing unique value violations. But at this stage of the upload, I had just saved the file to SPO. I hadn't added any metadata field values to it. And I know the document doesn't exist in the SPO Site Library already.

I raised this directly wit MS Support, since it looked like a proper SharePoint API error. But they won't help. I just want them to tell me what fields was causing the duplicate, but because I am using this pnpCore library to upload the document, and told me to post the issue here instead.

Can anyone here shed any light on how I would troubleshoot such an issue?

I thought by giving MS the _ClientRequestId_, they would be able to check telemetry at their end and tell me the fields but they are reluctant (at least their first line support) to do anything at all.

**Comment by jansenbe** [comment]
@Gareth064 : does the document have duplicate metadata properties set in the document itself? Also, regarding support, if you can repro this with a basic REST query then you're taking PnP Core SDK out of the story.

**Comment by Gareth064** [comment]
Hey @jansenbe I assume I will need to look through the PnP Core SDK source code to see what API's it was using to upload a document? Or do you know and can link me direct to it :)

**Comment by jansenbe** [comment]
@Gareth064 : https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/FileCollection.cs#L74-L154

**Comment by Gareth064** [comment]
OK thanks. I will try to test this in the coming week and report back

**Comment by jansenbe** [comment]
@Gareth064 : did you manage to get this one resolved?
