### ISSUE TITLE
Make "Add Cloud storage" option in Teams channel available

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#1283]
## Category

- [x] Feature request

## Describe the feature

It would be helpful to have the "Add cloud storage" option available in the PnP Library.
![image](https://github.com/pnp/pnpcore/assets/20642406/63f6cb47-e740-44f5-9d7c-6e8523a1d710)

Not sure if this is even possible via any of the APIs. I found a short comment in the feedback portal:

https://feedbackportal.microsoft.com/feedback/idea/535387f2-25fd-ec11-a81b-6045bd7d68ae

Sorry that my screenshot is in German. The English Option is "Add cloud storage" and this adds a reference to another document library to the Files tab.

But there are almost no replies.

**Comment by jansenbe** [comment]
@web265p3 : doesn't this work for that purpose: https://pnp.github.io/pnpcore/using-the-sdk/teams-channel-tabs.html#creating-channel-tabs ?

**Comment by web265p3** [comment]
Unfortunately not. The cloud storage option is for many users important, because if you reference files from within Teams, you cannot reference a tab. You can just reference channels.

For example when referencing a file from within the discussions:

![image](https://github.com/pnp/pnpcore/assets/20642406/86ade2cc-f025-4c37-a6f5-dd8bc1ee5672)

You can only chose files from Teams channels, not from other SharePoint locations. Adding cloud storage resolves this.
But there seems to be no way how to programmatically do this... or is there?

**Comment by jansenbe** [comment]
@web265p3 : I don't think there's an official API for this, did some digging and couldn't find anything. Feel free to raise this via official support channels, but for now I'm gonna close this one in PnP Core SDK as it's not an issue with the SDK
