### ISSUE TITLE
SharePoint App only principal (Client Credential Grant) shows "couldn't resolve user.." error

### ISSUE THREAD

**Issue by xeroOrex** [pnp/pnpcore#1285]
## Category

- [x] Bug

## Describe the bug

I am trying to use SharePoint App-Only principal to add an external user in a SharePoint site which is external facing. though I am using direct rest api to perform the operation , same can be done using pnp core sdk as well as per my understanding.  PFB the rest api endpoint

{your sharepoint site}/_api/SP.Web.ShareObject?$expand=UsersWithAccessRequests,GroupsSharedWith

The app principal is granted full control permission in site collection level and using client credential grant I am generating the access token using below endpoint.

https://accounts.accesscontrol.windows.net/{tenant id}/tokens/OAuth/2

Now , when I call the rest api with the access token ,it shows me the error
"Couldn't resolve user user.ch88_gmail.com#EXT#@mytenant.onmicrosoft.com."

The user is not added in our Azure AD , we are directly trying to add the user in our SharePoint site. I am not sure if the error I am getting is the expected behavior or not. 

## Steps to reproduce
1. Generated the app only access token using below URL as reference 
https://global-sharepoint.com/sharepoint/in-4-steps-access-sharepoint-online-data-using-postman-tool/?expand_article=1
2. In Post man call the endpoint "{your sharepoint site}/_api/SP.Web.ShareObject?$expand=UsersWithAccessRequests,GroupsSharedWith" with access token generated in previous step
3. add the Body
`{
    "url": "{your sharepoint site}/_layouts/15/aclinv.aspx",
    "peoplePickerInput": "[{\"Key\":\"i:0#.f|membership|userName.ch88_gmail.com#EXT#@yourtenant.onmicrosoft.com\",\"Description\":\"userName.ch88@gmail.com\",\"DisplayText\":\"UserName\",\"EntityType\":\"User\",\"ProviderDisplayName\":\"Tenant\",\"ProviderName\":\"Tenant\",\"IsResolved\":false,\"EntityData\":{\"MobilePhone\":\"\",\"Email\":\"userName.ch88@gmail.com\",\"Department\":\"\",\"Title\":\"userName.ch88@gmail.com\",\"PrincipalType\":\"GUEST_USER\"},\"MultipleMatches\":[]}]",
    "roleValue": "group:5",
    "groupId": 0,
    "propagateAcl": false,
    "sendEmail": true,
    "includeAnonymousLinkInEmail": false,
    "emailSubject": "User XX is inviting you to collaborate on Sample Team Site",
    "emailBody": null
}`
followed below URL to create the peoplepickerInput value.
https://learn.microsoft.com/es-es/archive/blogs/vesku/external-sharing-api-for-sharepoint-and-onedrive-for-business

## Expected behavior
As the app is having full control permissions and also the site is external facing , it should add the user in the group. This same api works when I use Power Automate SharePoint HTTP rest api service using user credentials.

## Environment details (*development & target environment*)
SharePoint Online

### Additional context

I am not using pnp core yet but as I think underlying APIs are same, same issue will happen using pnp core sdk as well.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@xeroOrex : PnP Core SDK uses the Microsoft Graph sharing APIs (https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http), did you test those APIs?

**Comment by xeroOrex** [comment]
@jansenbe  Thank you so much for this quick response. Really appreciate it as we have some dependency on this!!

I am not exactly trying to share a link with external user. I am trying to share the site itself with the user. So the user will be added as guest in the azure ad behind the scene. Does "https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http" also do the same thing?

I am trying to replicate what `ShareSiteWithPeoplePickerValue` method does here in https://github.com/pnp/PnP/blob/master/Samples/Core.ExternalSharing/Core.ExternalSharingWeb/ExternalSharingExtensions.cs 

Is there any other way around?

**Comment by jansenbe** [comment]
@jansenbe : the Graph API cannot be used to directly share a site, they are at file level. What you can try is:
- check if the a file can be shared with an external user (ensure the site is configured to allow sharing with new external users, see tenant admin)
- if that works, there should be a new user in the "User information list", using `IWeb.EnsureUser` you can get a reference to it and then you can add it to one of the SharePoint Groups (assuming you're not also want to share access via the possibly linked Microsoft 365 Group).

**Comment by xeroOrex** [comment]
@jansenbe Thanks again for looking into this. One last query from my side before I close this.

1. Reg the first point , it's already configured. Our site is allowed to be shared with external users.
2.  Reg the second point, we had already tired. That `ensureUser()` method returns an error saying something like "Could not resolve user. User id is not unique ..."  something like that. Again, just to emphasize, the user is external and doesn't exist in our Azure AD of the tenant where the SharePoint site exists.

We thought of adding the user using the app only policy of the app but this https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly says, "The use of the Microsoft.SharePoint.Client.Web.ShareObject() API was not tested with app-only permissions and may not work consistently. The recommendation is to use it only with an app+user context."

Just want to know if there is other way around?? My goal is simple. Add an external user to a site using App-Only context and that external user doesn't exist in the Azure AD of tenant as guest or something.

**Comment by jansenbe** [comment]
@xeroOrex : I actually forgot to mention one thing, first try to share a file in the site with the external user and then check via EnsureUser. Using EnsureUser to add a new guest account does not work, hoping it works once the user was used once

**Comment by xeroOrex** [comment]
@jansenbe Thanks , I will check and get back to you.
I can use the graph api suggested by you previously or any other SharePoint rest services you want to suggest?

**Comment by jansenbe** [comment]
@xeroOrex : you can use the sharing support in PnP Core SDK which uses the Graph API or you can directly call Graph yourselves

**Comment by jansenbe** [comment]
@xeroOrex : closing per no response
