### ISSUE TITLE
Search Refinement Filters

### ISSUE THREAD

**Issue by TroyHostetter** [pnp/pnpcore#1289]
## Category

- [x] Bug

## Describe the bug

It seems like using multiple RefinementFilters does not work. A single one does, but the moment you add multiple, it stops working.  For example, this multiple filter works if you use them separately, but if you combine them into a single filter, it returns 0 rows.

`RefinementFilters = new List<string>() { "FileType:equals('pdf')", "Created:range(2019-01-01T00:00:00Z,2023-10-04T23:59:59Z)" }`

## Steps to reproduce

Simply add the above to a query

## Expected behavior

The filter should be applied

## Environment details (*development & target environment*)

`<Project Sdk="Microsoft.NET.Sdk">`
`  <PropertyGroup>`
`    <OutputType>Exe</OutputType>`
`    <TargetFramework>net6.0</TargetFramework>`
`    <ImplicitUsings>enable</ImplicitUsings>`
`    <Nullable>enable</Nullable>`
`  </PropertyGroup>`
`  <ItemGroup>`
`    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />`
`    <PackageReference Include="PnP.Core" Version="1.10.0" />`
`    <PackageReference Include="PnP.Core.Auth" Version="1.10.0" />`
`  </ItemGroup>`
`</Project>`

A simple vs.code console app

- **SDK version**: 1.10
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**: 6.0
- **Browser(s)**: Edge
- **Tooling**: vs.code
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@TroyHostetter : did some checking and for using multiple RefinementFilter you should combine them yourselves like this: `and(filetype:equals("pptx"),Created:range(2021-01-01T00:00:00Z,2023-10-04T23:59:59Z))` and then add that combined one as first entry to the list.

**Comment by jansenbe** [comment]
@TroyHostetter : closing per no response

**Comment by TroyHostetter** [comment]
I was able to get this going, and thank you for your help!!!

It appears you can't use, or at least it may be limited use, of KQL syntax. Using [FQL syntax](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/fast-query-language-fql-syntax-reference), I was able to use multiple Search Refinement filters. Here's an example that worked:

`        SearchOptions searchOptionsTroy = new("contenttypeid:0x010100*")
        {
            TrimDuplicates = false,
            SelectProperties = new List<string>() { "Path", "Url", "Title", "ListId", "Created" },
            RefinementFilters = new List<string>() { 
                "Created:range(2023-01-01T00:00:00Z,2023-10-09T23:59:59Z)",
                "FileType:equals(\"pdf\")",
                "or(Path:starts-with(\"https://troyathp.sharepoint.com/sites/IMTest/*\"),Path:starts-with(\"https://troyathp.sharepoint.com/sites/CogSearchDemo/*\"))"
            }
        };`

Also, I believe the refinement filters are treated as AND, so if you need OR logic, it must be in the individual filter.

**Comment by jansenbe** [comment]
Thanks for sharing the outcome @TroyHostetter , this will help others that bump into the same
