### ISSUE TITLE
Create fields with different internal and title property 

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#1293]
## Category

- [x] Feature request

## Describe the feature

When we want to create field we like to add them  with a specific internal name with prefix. The Title but should be readable for users.

## Describe the solution you'd like

We like to have two parameters for field creation: internalname and title  
`
 var fieldCounter = await web.Fields.AddTextAsync("sfprCounter", "Counter", new FieldTextOptions
                {`

**Comment by jansenbe** [comment]
@raclettierer : can you try the `AddFieldOptionsFlags.AddFieldInternalNameHint` option and see if that works for you?

**Comment by jansenbe** [comment]
@raclettierer : did the above get you unblocked?

**Comment by jansenbe** [comment]
Closing per no response anymore
