### ISSUE TITLE
Add site column to list

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#1294]
## Category

- [x] Feature request

## Describe the feature

Method to add an existing site column to a list

## Describe the solution you'd like

```
var fieldCounter = await web.Fields.AddTextAsync("sfprCounter", new FieldTextOptions
                    {...
                    
list.Fields.AddField(fieldCounter);
```

**Comment by dabaker6** [comment]
If I can help, I came across this last week, whilst trying to add site fields to lists and there is the functionality now to achieve this.

After getting a current site field, you can get the xml definition of the field. Returned in the xml is the sourceID which indicates that the new list field is based on a site field. The new field can then be added using one of the AddFieldAsXml methods (I was adding as a batch, and also needed to enforce the internal name via the FieldOptionsFlags).

```c#                           
//get site field
IField field = await context.Web.Fields.Where(f => f.InternalName == siteFieldToAdd).FirstOrDefaultAsync();
//get field xml
string xml = field.SchemaXml;
//add site field to list
await list.Fields.AddFieldAsXmlBatchAsync(batch, xml, true, AddFieldOptionsFlags.AddFieldInternalNameHint);
```

https://learn.microsoft.com/en-us/sharepoint/dev/schema/field-element-field

**Comment by jansenbe** [comment]
@raclettierer : did the above get you unblocked?

**Comment by jansenbe** [comment]
Closing per no response anymore
