### ISSUE TITLE
List item that has a multifield with a user that has left the company doesn't save or throw a error.

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/pnpcore#1302]
## Category

- [x] Bug

## Describe the bug

I'm trying to update a multifield User field on a list item from a function app. But one of the persons in the field has left the company.
I can ensure the user, since it was already ensured in the site previously. 
When I do the itemUpdate there is no error message but the list item is not updated.

## Steps to reproduce

```
private static async Task<IFieldValueCollection> fillUserCollection(dynamic fieldValue, IFieldValueCollection listItemField, IField field, PnPContext ctx) {
    if (fieldValue != null && fieldValue.Count > 0) {
        listItemField.Values.Clear();
        foreach (var member in fieldValue) {
            var user = await ctx.Web.EnsureUserAsync((string)member);
            listItemField.Values.Add(field.NewFieldUserValue(user));
        }
    } else {
        listItemField = null;
    }
    return listItemField;
}

```
## Expected behavior

It should save the list item with the user that left the company since this is the default behavior from Microsoft even if the user has left.

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows 10
- **SDK used in**: Azure Function app
- **Framework**: NET Framework v6.0
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@Dangerous-Mind : we've options to verify whether a user is valid (see https://pnp.github.io/pnpcore/using-the-sdk/security-users.html#validating-users). If you're updating the field I think it's expected that an invalid user is not accepted, are you saying that in the UI you can edit that multi user list item field and save it with leaving the user that left the company inside the field?

**Comment by Dangerous-Mind** [comment]
I'm pretty sure the users that are already saved in the field are not removed when it's saved again.
Rest calls to update the item saves it without a problem and keeps the user.
Ui acts the same way.

We can't add that user in the field, but if it's already in the field it saves without a problem. 

Also there is not error when updating using pnp but it doesn't save.

**Comment by Dangerous-Mind** [comment]
@jansenbe 
Reconfirmed again. The old users are kept if the item is saved using the SharePoint UI.
I remembered this from 2010, also thought it was a dumb option from Microsoft. But that how it still works.
Basically the field is just a lookup to the site collection user's list. It doesn't care what's on the AD.

**Comment by jansenbe** [comment]
@Dangerous-Mind : can you verify if the `UpdateOverwriteVersion` or `SystemUpdate` also do not update the field? For the `Update` call would it be possible to capture the network request (e.g. using Fiddler) and send me the request/response information. Please anonymize the user names and tenant name before pasting.

**Comment by Dangerous-Mind** [comment]
@jansenbe: SystemUpdate and UpdateOverwriteVersion works fine. The list Item is saved and the fields are updated.
I won't be able to install Fiddler in this machine. The company won't allow it.

**Comment by jansenbe** [comment]
Closing this one as checking the output of the `ValidateUpdateListItem` API call is needed to understand how this can be handled. There's workarounds available for the mentioned `UpdateOverwriteVersion` and `SystemUpdate` methods.
