### ISSUE TITLE
SetSiteCollectionAdminsAsync does not consistently work for Groupified sites

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#1307]
## Category

- [x] Bug

## Describe the bug

If you try to apply one security group to a Groupified SharePoint site using the sharePointAdminLoginNames parameter, the site collection admin is skipped.

## Steps to reproduce
When running the code on a Groupified site, the site collection admin is not applied.
```
ISiteCollectionManager siteCollectionManager = context.GetSiteCollectionManager();
// add the group as admin
string groupClaim = $"c:0t.c|tenant|{securityGroupId}";
List<String> groupAdmin = new()
{
    groupClaim
};
await siteCollectionManager.SetSiteCollectionAdminsAsync(context.Uri, groupAdmin);
```

## Expected behavior

The first entry is not skipped

## Environment details (*development & target environment*)

Latest official SDK version

### Additional context

Seems that there is a loop that skips the first application of a Group. A workaround is assigning the group twice.

```
ISiteCollectionManager siteCollectionManager = context.GetSiteCollectionManager();
// add the group as admin
string groupClaim = $"c:0t.c|tenant|{securityGroupId}";
List<String> groupAdmin = new()
{
    groupClaim,
    groupClaim
};
await siteCollectionManager.SetSiteCollectionAdminsAsync(context.Uri, groupAdmin);
```

Thank you for your help

**Comment by mloitzl** [comment]
@plamber @jansenbe I'll have a look into this, since I worked on that part in the past

**Comment by plamber** [comment]
Hi @mloitzl,
thank you.

Br,
Patrick

**Comment by jansenbe** [comment]
That would be great @mloitzl :-)

**Comment by mloitzl** [comment]
@plamber A quick update

A workaround would be to pass `null` as the first group admin:

```cs
ISiteCollectionManager siteCollectionManager = context.GetSiteCollectionManager();
// add the group as admin
string groupClaim = $"c:0t.c|tenant|{securityGroupId}";
List<String> groupAdmin = new()
{
    null,
    groupClaim
};
await siteCollectionManager.SetSiteCollectionAdminsAsync(context.Uri, groupAdmin);
```

But anyways, `SetSiteCollectionAdmins` doesn't handle group connected sites consistently.

@jansenbe I will try to figure out a fix.

**Comment by plamber** [comment]
Hi @mloitzl,
your suggestion for a workaround is definitely better than mine. Thank you for sharing.

Best regards,
Patrick

**Comment by mloitzl** [comment]
Hi @jansenbe and @plamber,

I created https://github.com/pnp/pnpcore/pull/1323

It also contains a new unit test `SetSiteCollectionAdminsGroupifiedSiteAddOnly_Async` that should cover the issue.

Have a nice weekend! :-)

Martin
