### ISSUE TITLE
Make it possible to share the AuthN/AuthZ context in ASP.NET Core

### ISSUE THREAD

**Issue by PaoloPia** [pnp/pnpcore#131]
## Category

- [x] Feature request

## Describe the feature

It would be great to being able to rely on the AAD/MSAL authentication context of an ASP.NET Core application, without providing any credentials, simply using the current context and accessing resources on the current tenant.

## Describe the solution you'd like

I think we need a new AuthenticationProvider type for this kind of scenario.

## Additional context

I'll work on it ...

**Comment by jansenbe** [comment]
Let's see if we can align with the auth strategy used by the Microsoft Graph .Net SDK's...

**Comment by jansenbe** [comment]
This will now be possible via the ExternalAuthenticationProvider provider, this issue can be closed.
