### ISSUE TITLE
Unable to set proper internal name when creating a new list field

### ISSUE THREAD

**Issue by ivonool** [pnp/pnpcore#1317]
## Category

- [x] Bug

## Describe the bug
Unable to set list field internal name properly, Tried to add a new text field to existing list with proper internal name and readable display name. Field's internal name was set based on display name e.g. space was replaced with _x0020_
Also, it seems that there is no property in CommonFieldOptions class to set DisplayName which would be useful also.

## Steps to reproduce

Use the code snippet provided in documentation:
``` code
IField myField = await myList.Fields.AddFieldAsXmlAsync(@"<Field Type=""Text"" Name=""ADDEDFIELD"" DisplayName=""ADDED FIELD""/>", true);
```

## Expected behavior

Expecting field's internal name to be ADDEDFIELD.

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **SDK used in**: Azure Function
- **Framework**: .NET 7]

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@ivonool : did you consider using `AddFieldOptionsFlags.AddFieldInternalNameHint`, see https://github.com/pnp/pnpcore/issues/1294 for more details

**Comment by ivonool** [comment]
@jansenbe yes, I found this comment by accident and at the moment I was able to resolve issues in the code.
Anyway, is there a good reason why this flag is necessary?

**Comment by jansenbe** [comment]
I'll update the docs (https://pnp.github.io/pnpcore/using-the-sdk/fields-add.html) to clarify this, it's indeed not so obvious when coming from CSOM.

**Comment by jansenbe** [comment]
@ivonool / @raclettierer: See https://github.com/pnp/pnpcore/commit/71319071bb717b70f3b1435111c1df7f19e26674 and https://github.com/pnp/pnpcore/commit/55405e216a577cf6484bc75d94c78410790007c6
