### ISSUE TITLE
Unit Testing with IPnPContextFactory >> PnPContext

### ISSUE THREAD

**Issue by PeteCooney** [pnp/pnpcore#1318]
## Category

- [x] Bug

## Describe the bug

The IPnPContextFactory interface has create methods returning concretions and, as discussed elsewhere, PnPContext only has internal constructors meaning that setting up responses for Create calls is problematic. 

## Steps to reproduce

For example, the following snippet will fail:

```
var contextFactoryMock = new Mock<IPnPContecxtFactory>();
var contextMock = new Mock<IPnPContext>();
_contextFactoryMock.Setup(f => f.CreateAsync(It.IsAny<string>(), It.IsAny<PnPContextOptions>())).ReturnsAsync(contextMock.Object);
```
## Expected behavior

As PnPContext implements the IPnPContext interface, I would expect the Create method calls on IPnPContextFactory to return abstractions and not concretions thereby allowing for unit testing of code consuming these classes.

## Environment details (*development & target environment*)

N/A

### Additional context

N/A

**Comment by jansenbe** [comment]
Hi @PeteCooney , this is something we're tracking for v2 as it's a breaking change. See https://github.com/pnp/pnpcore/issues/1170 for more context. Maybe you can workaround in code like @MartinHatchL365 did?

**Comment by jansenbe** [comment]
Closing per no feedback anymore.
