### ISSUE TITLE
Add an extension method to load system lists via Microsoft Graph

### ISSUE THREAD

**Issue by PaoloPia** [pnp/pnpcore#132]
## Category

- [x] Feature request

## Describe the feature

Being able to load system lists, like we do with SPO REST, but using Graph.

## Describe the solution you'd like

Add an extension method to instruct Microsoft Graph to return all the system/hidden lists.

## Additional context

I'll take care of this ...

**Comment by jansenbe** [comment]
That should already work for regular loads, I've not done the work for Linq based queries

**Comment by jansenbe** [comment]
Fixed!
