### ISSUE TITLE
FindFiles methods returns nothing

### ISSUE THREAD

**Issue by FlorianLabranche** [pnp/pnpcore#1320]
## Category

- [x] Bug

## Describe the bug

I tried to use FindFilesAsync method as described [here](https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#finding-files) to get assets files (header, logo,...). 
But no files are returned.

```
IFolder folder = await PnPContext.Web.Folders.Where(f => f.Name == "SiteAssets").FirstOrDefaultAsync();

List<IFile> foundFiles = await folder.FindFilesAsync("__extendedHeaderBackgroundImage__");
```

## Steps to reproduce

1. Set a header image in your SharePoint site to ensure a file is created in the asset library (\_\_extendedHeaderBackgroundImage\_\_\<filename\>.\<extension\>)
2. Try the above code snippet to get your file.

## Expected behavior

File should be found.

## Environment details (*development & target environment*)

- **SDK version**: 1.10
- **OS**: Windows 10
- **SDK used in**: Azure Function
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022

### Additional context

I also tried to remove the double underscores in the searched filename without success.

**Comment by jansenbe** [comment]
@FlorianLabranche : is using search to find the files an option for you? The method you're using is based on enumeration and will not scale on larger libraries. For using search see https://pnp.github.io/pnpcore/using-the-sdk/search-intro.html. To scope the search to a site or specific library you can use the `path` property, e.g. `path:\"{context.Uri}\"`

**Comment by FlorianLabranche** [comment]
@jansenbe the library will not contain a lot of files. I'm targeting a site used as template.
So, this is weird _FindFilesAsync()_ does not work.

I used the following method:
```
IFolder folder = await PnPContext.Web.Folders.Where(f => f.Name == "SiteAssets").FirstOrDefaultAsync();
await folder.LoadAsync(p => p.Files);

var file = folder.Files.AsRequested()
    .FirstOrDefault(_ => _.Name.Contains(match));
```

**Comment by jansenbe** [comment]
@FlorianLabranche: did some quick testing and your new code works (as it's not using the FindFiles method)...FindFiles fails because it uses a regex to match and that fails. Will do some more checking here

**Comment by jansenbe** [comment]
@FlorianLabranche : you need to use a * to indicate the wildcards in your search string. So in your case below should work:

```csharp
ist<IFile> foundFiles = await folder.FindFilesAsync("__extendedHeaderBackgroundImage__*");
```

**Comment by jansenbe** [comment]
@FlorianLabranche : I'm closing the issue as using the wildcard (*) this works + docs have been updated.

**Comment by FlorianLabranche** [comment]
@jansenbe Many thanks for the quick response and update 🥇
