### ISSUE TITLE
TaxonomyFieldValue label property not correctly loaded.

### ISSUE THREAD

**Issue by gerrylaenen** [pnp/pnpcore#1324]
## Category

- [x] Bug

## Describe the bug

I am using PnP.Framework 1.13 and PnP.Core 1.10 running on .NET 6 LTS.

When getting a list item that contains a managed metadata field, the value of the label is not correctly retrieved. The Id of is correctly populated.

Instead of a string value that shows the term label, I get a number ("19") for the label property. The term is not translated and has no additional custom properties. 

## Steps to reproduce

using (var ctx = this.GetPnPClientContextForUrl(siteUrl).Result)
{

    IList list = null;
    try
    {
        ctx.Web.EnsureProperties(w => w.ServerRelativeUrl);
        ctx.Execute();
        string listServerRelativeUrl = ctx.Web.ServerRelativeUrl + this._settings.RequestListUrl;
        list = ctx.Web.Lists.GetByServerRelativeUrl(listServerRelativeUrl);
    }
    catch (Exception ex)
    {
        throw new ConfigurationErrorsException("Unable to retrieve request list", ex);
    }

    try
    {
        IListItem listItem = list.Items.GetById(id, p => p.All, p => p.FieldValuesAsText);
        ctx.Execute();

       requestItem.AgreementCategory = listItem[Constants.Fields.fldAgreementCategory] == null ? "" : ((FieldTaxonomyValue)listItem[Constants.Fields.fldAgreementCategory])?.Label.ToString();

      //  requestItem.AgreementCategory == "19" instead of "Standard Training"

        return requestItem;
    }
    catch (Exception ex)
    {
        //_logger.LogError($"Error while updating request item with ID '{requestItem.Id}'. Error: {ex.Message}");
        throw;
    }
}

## Expected behavior

TaxonomyFieldValue should retrieve the correct Label.

## Environment details (*development & target environment*)

I am using PnP.Framework 1.13 and PnP.Core 1.10 running on .NET 6 LTS.

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by FlorianLabranche** [comment]
I hope you did find the solution by now.

If not, can you try loading the list fields as described in the doc [here](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#reading-list-items) ?

As you are loading the _'FieldValuesAsText'_ property, another approach could be:
``
var label = listItem.FieldValuesAsText.Values["YourField"]?.ToString();
``

Also, using Execute() is useless here because it 'executes' PnP context default batch but you are not using batching here.

**Comment by jansenbe** [comment]
@gerrylaenen : are you still blocked by this?

**Comment by gerrylaenen** [comment]
No, I implemented a workaround with CSOM. Have you been able to replicate
the issue?

Thanks!

Op vr 15 mrt 2024 om 16:16 schreef Bert Jansen ***@***.***>:

**Comment by jansenbe** [comment]
@gerrylaenen : I just replicated the issue, let me check things

**Comment by jansenbe** [comment]
@gerrylaenen : doing some checking on what SharePoint provides as response I see that the ID is returned as label for single value taxonomy fields...so not something that goes wrong in the SDK. For that reason I'm going to close this issue, hope you understand.

![image](https://github.com/pnp/pnpcore/assets/7451219/5989820d-b1ef-4601-9c9f-5ac1753f4453)

**Comment by dgusoff** [comment]
Workaround: A CAML query will return items with the label properly populated https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#c-getting-list-items-via-the-loaditemsbycamlquery-approach
