### ISSUE TITLE
Access Token Log Not Formatted Correctly

### ISSUE THREAD

**Issue by randellhodges** [pnp/pnpcore#1328]
## Category

- [x] Bug

## Describe the bug

The access token log entry looks like it isn't formatted correctly.

Text:
![image](https://github.com/pnp/pnpcore/assets/7727467/53734d4b-8f33-49d2-8e0f-bbc4f9ed36d9)

JSON:
![image](https://github.com/pnp/pnpcore/assets/7727467/582c5f53-5681-4036-a312-f0ea3af655d1)

It seems like 0 and 2 are backwards (maybe this is a Serilog problem?) and the scope needs the leading ", " trimmed.

Code in question:
https://github.com/pnp/pnpcore/blob/e2e579f001a9dcaf1277303dc9ccc0876a197271/src/sdk/PnP.Core.Auth/Confidential/X509CertificateAuthenticationProvider.cs#L193-L195

## Steps to reproduce

1) Use Serilog
2) Use Certificate Authentication
3) Set log for Information

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows
- **SDK used in**: Net Core 6 Web Api
- **Framework**: .Net Core 6
- **Tooling**: Visual Studio 2022

### Additional context

Secondary question: Can we have a way to turn off those messages? I still want to leave the log level for Information because I need to watch for throttling messages and other things, but my logs are flooded with these access token entries. Maybe some sort of property on the PnpCoreAuthenticationOptions?

**Comment by jansenbe** [comment]
@randellhodges : the ordering is seems to be something with Serilog. When we bump serilog versions this might get fixed, but don't see this a breaking thing. 

Regarding the default log level for the "access token" messages you've a point. I changed those to default to `debug` level.

Changes will appear in the next nightly.
