### ISSUE TITLE
Issue enumerating folder with more than 5000 files in it, receive threshold error

### ISSUE THREAD

**Issue by stevepresley** [pnp/pnpcore#1338]
## Category

- [x] Bug

## Describe the bug

I'm struggling to find a way to accomplish the paging of files in a folder. I am receiving the threshold exception.  I have paging set to 1000 items via the appsettings entry, however none of the code samples that I can seem to find (and have tried to alter) will allow me to reference the items in a folder as list items, I only get .Files (which doesn't work as mentioned below for Folders or Files).  When I try  

```csharp
await folder.LoadAsync(p => p.Files);
```
I also get the same exception when trying to enumerate over folder.Files(). I was under the impression that by loading it Async and enumerating with an await foreach, it would do the paging for me.  Upon further reading below, I tried the list example, but trying to load the folder with the UniqueID using
```csharp
var fld = context.Web.GetFolderById(folder.UniqueId);
```
I still get the same result, and again only the .Files collection, no Items collection.

If I can get a sample of how to do this, will be glad to update the documentation (as the methods listed there do not mention paging, only on the Lists page, and that code doesn't seem to work either for Files).

For context, I am reading the SharePoint Online Document libraries of customer site(s), so cannot go and create views, or reorganize the files to get around the 5000 item limit.

If I could get something similar to this as an example, as mentioned above, I'd be glad to update the documentation.  I have tried to alter this code, but my folder is a sub-folder of the Shared Documents list (and could be at any level), so not sure how to adapt it to get the folder I need based on the UniqueID of the folder.

```csharp
var library = await context.Web.Lists.GetByTitleAsync("PNP_SDK_TEST_LargeFolderLibrary");

await foreach (var listItem in library.Items.QueryProperties(p => p.Folder, p => p.All).AsAsyncEnumerable())
{
    // Do something with the list item
    if (listItem["ContentTypeId"].ToString().StartsWith("0x0120"))
    {
        // take action
        Debug.WriteLine(listItem.Folder.ServerRelativeUrl);
    }
}
```

By default it pages per 100 items, but this can be changed via configuration if you want that. See `PnPCore:HttpRequests:SharePointRest:DefaultPageSize` in https://pnp.github.io/pnpcore/using-the-sdk/basics-settings.html

_Originally posted by @jansenbe in https://github.com/pnp/pnpcore/issues/797#issuecomment-1076740393_
            
## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. Create a folder named "Lots of Files" in the Shared Documents list of a SharePoint Online site
1. Go to "Lots of Files"
1. Add more than 5,000 files to the folder (there is a unit test to add >5000k files here: https://github.com/pnp/pnpcore/issues/797#issuecomment-1076745927)
1. Using PnP.Core library, get a reference to the site, start enumerating the folders for the site
1. When folder "Lots of Files" is loaded, and try to enumerate the folder.Files collection, the following error is returned immediately:
```
Microsoft.SharePoint.SPQueryThrottledException
Message: The attempted operation is prohibited because it exceeds the list view threshold.
```

## Expected behavior

folder.Files should enumerate over the items automatically using the paging that is built into the framework.

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0
- **OS**: Windows Server 2019 17763.5206
- **SDK used in**: WPF app built off of PnP.Core SDK WPF sample
- **Framework**: .NET 7.0
- **Browser(s)**: Chrome (doesn't apply really)
- **Tooling**: Visual Studio 2022 Pro
- **Additional details**: SharePoint online

### Additional context

This is borderline BUG / Documentation / Question as noted above.  Appreciate any insight!

**Comment by stevepresley** [comment]
Bump - still haven't figured out how to get around this.  Any suggestions would be appreciated.

**Comment by jansenbe** [comment]
@stevepresley : I did not yet have the time to try to repro this, but to get you unblocked, did you try one of the other list enumeration methods (see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#you-need-to-read-system-properties-like-fileleafref-filedirref-or-you-need-to-filter-list-items-or-you-want-to-define-the-returned-fields-or-you-want-to-get-lookup-column-properties)

**Comment by jansenbe** [comment]
@stevepresley : are you still blocked with this or did the alternatives work?

**Comment by jansenbe** [comment]
@stevepresley : let's close for now. Please open new issues with specific new problems or a discussion item when it's more a question than an issue
