### ISSUE TITLE
Viva Announcement Library Result in GetPages Failed

### ISSUE THREAD

**Issue by RogerZhang-CatapultSystems** [pnp/pnpcore#1343]
## Category

- [x] Bug

## Describe the bug
We have ViVa Enabled in root site collection, then announcement library will be automatically created. 
![image](https://github.com/pnp/pnpcore/assets/46333165/96238e75-217f-49d5-a27e-0cfed1f871dd)
When we run Get Page cmdlets, it always give us not exists error, but actually there have 13 pages
![image](https://github.com/pnp/pnpcore/assets/46333165/90a82120-15b7-442c-a406-585ead5c7ecf).
After investigation I found the PnP core code logics:  Based on the site pages filter expression, announcements library match it. And in line 587, if have multiple results, it will take the first one. In my scenario, the announcements will be returned, which result in can't find pages in announcement library.
![image](https://github.com/pnp/pnpcore/assets/46333165/3ea963d5-53cb-48b0-8efe-fd424a88edb0)

I have tested the get pages cmdlets in PnP.Powershell module from 1.12.0 to latest, the issue always repro.

**Comment by jansenbe** [comment]
@RogerZhang-CatapultSystems : thanks for reporting this, I've just pushed a fix. The next nightly builds of PnP Core SDK and PnP PowerShell will have this fix. I'll close the issue, but please re-open or create a new one in case you still experience issues.
