### ISSUE TITLE
ListItemCollection AddAsync not working with modern calendar

### ISSUE THREAD

**Issue by 4ndri** [pnp/pnpcore#1349]
## Category

- [x] Bug

## Describe the bug

similar to #1009 

if a events-list is created with the webpart, the rootfolder of the list is `/sites/testsite/Events`. if i try to add a item to this list, the request jsonpayload looks like this:
```json
{
  "listItemCreateInfo": {
    "FolderPath": {
      "DecodedUrl": "https://sample.sharepoint.com/sites/testsite/lists/Ev"
    },
    "UnderlyingObjectType": 0
  },
  "bNewDocumentUpdate": false,
  "formValues": [
    {
      "FieldName": "Title",
      "FieldValue": "hello world"
    },
    {
      "FieldName": "EventDate",
      "FieldValue": "2024-01-15 08:00:00"
    },
    {
      "FieldName": "EndDate",
      "FieldValue": "2024-01-15 10:00:00"
    }
  ]
}
```

## Steps to reproduce

1. create a calendar with the events-webpart
![image](https://github.com/pnp/pnpcore/assets/6054195/a8f273ed-147b-4752-904a-bbae7fe3ea3b)
2. try to add an event with pnp-core ListCollection.AddAsync
3. see error
```
Invalid file name.

The file name you specified could not be used.  It may be the name of an existing file or directory, or you may not have permission to access the file.
```

## Expected behavior

list item should be added to calendar list. the folderpath of the itemcreationinfo should be `https://sample.sharepoint.com/sites/testsite/Events` (same as rootfolder).

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0, 1.11.37-nightly
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**: net7.0
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | Chromium Edge v79]
- **Tooling**: Visual Studio 2022, JetBrains Rider

### Additional context
while debugging i came across [`ListMetaDataMapper.cs` line 54](https://github.com/pnp/pnpcore/blob/bcceed230c548884558aa82a34fdbd48a09a1588/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/ListMetaDataMapper.cs#L54) where the folderpath is calculated from `EntityTypeName`. it is assumed that the EntityTypeName of the list has a suffix `List`, this assumption is wrong in this case. the folderpath must be taken from the serverrelativeurl of the rootfolder (like in [`ListItem.cs` line 132](https://github.com/pnp/pnpcore/blob/bcceed230c548884558aa82a34fdbd48a09a1588/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/ListItem.cs#L132)).

**Comment by jansenbe** [comment]
@4ndri : nice catch! I've pushed a fix that will deal with this case. This fix will be part of the next nightly build, so please give that a go tomorrow and report back.

**Comment by 4ndri** [comment]
@jansenbe thank you for this quick fix. It works now for me. But if i look at the code, i see other issues with folderpath:
### mixing of relative and absolute Uri:
according to documentation the folderpath Uri should be absolute: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#request-property-details

|Property|Description|
|---|---|
|`listItemCreateInfo`|Information about the list and folder where the item should be created|
|`listItemCreateInfo.FolderPath.DecodedUrl`|Absolute URL of the folder where the item should be created|
|`listItemCreateInfo.UnderlyingObjectType`|Type of item to create. For more information, see [FileSystemObjectType](https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537053(v=office.14))|
|`formValues`|Array of field names and values to set on the newly created item|
|`bNewDocumentUpdate`|Set to `false` to create a list item|

I'm wondering why the `folderPath` is needed at all. If no `folderPath` is set, the listitem will be created in rootfolder. Is there a case where this doesn't work?

If the consumer wants to create the item in a specific folder, he can do this by using the `folderPath` parameter. Then there should be some checks for this path:
- is absolute (starts with http): take it as it is
- is site-relative: starts the same as web-siterelative url
	- `UrlUtility.MakeAbsoluteUrl(PnPContext.Uri, folderPath).ToString();`
- else -- assumption that it is relative to the list
	- `"{rootFolderAbsoluteUrl}/{folderPath}"`
	- in this case it's not a big performance issue to ensure the rootfolder (additional request). the consumer can make his code more performant in using absolute folderpath.

I added these suggestions in PR #1353

**Comment by jansenbe** [comment]
Closing this one as the root issue has been fixed and there's a PR to track the broader fix. Thanks for helping out!
