### ISSUE TITLE
GetUserEffectivePermissions not working with External accounts

### ISSUE THREAD

**Issue by FlorianLabranche** [pnp/pnpcore#1350]
## Category

- [x] Bug

## Describe the bug

Working in a SharePoint tenant (@contosodev.com) with External users from a second tenant (@contoso.com).
When I use GetUserEffectivePermissionsAsync() with an External user, I get 0 as High and Low permission mask.

## Steps to reproduce

All requests are executed on tenant contosodev.sharepoint.com

1. Using External User primary UPN (florian.labranche@contoso.com)
    - I can get the user using `EnsureUserAsync("florian.labranche@contoso.com")`
    ![image](https://github.com/pnp/pnpcore/assets/23434632/5d42ccf8-796e-47a3-83cb-e46ed323afb9)
    - But when I request `GetUserEffectivePermissionsAsync("florian.labranche@contoso.com")` I got 0 as High and 0 as low :
    ![image](https://github.com/pnp/pnpcore/assets/23434632/6bb7a800-67bc-4f37-9f62-bf370e3cbb2e)

2. Using External User UPN (florian.labranche_contoso.com#ext#@contosodev.onmicrosoft.com)
    - When I request `GetUserEffectivePermissionsAsync("florian.labranche_contoso.com#ext#@contosodev.onmicrosoft.com")` I have the following error:
    `The expression "web/getusereffectivepermissions('i:0#.f|membership|florian.labranche_contoso.com" is not valid.`

## Expected behavior

- GetUserEffectivePermissionsAsync should work using either upn from principal account (florian.labranche@contoso.com) or using the UserPrincipalName returned from EnsureUserAsync("florian.labranche@contoso.com") => "florian.labranche_contoso.com#ext#@contosodev.onmicrosoft.com".
- Response should contain valid High and Low permission mask.

## Environment details (*development & target environment*)

- **SDK version**: 1.10 and 1.11
- **OS**: Windows 10
- **SDK used in**: Azure function apps
- **Framework**: .NET 6

**Comment by jansenbe** [comment]
@FlorianLabranche : did you verify if calling the _api/web/getusereffectivepermissions(user UPN | User ID) does work for external accounts?

**Comment by FlorianLabranche** [comment]
Just tried SP API.

* Using `florian.labranche@contoso.com` (address from main tenant), it returns
`The user does not exist or is not unique.`
* Using `florian.labranche_contoso.com#ext#@contosodev.onmicrosoft.com` (External UPN) returns 
`The expression "web/getusereffectivepermissions('florian.labranche_contoso.com" is not valid.`
Expression seems truncated, so I tried encoding the "#" but, again it returns `The user does not exist or is not unique.`

But I tried using the SP LoginName `i:0#.f|membership|florian.labranche_contoso.com#ext#@contosodev.onmicrosoft.com` encoded and it returns me the high and low permission masks.
![image](https://github.com/pnp/pnpcore/assets/23434632/e45e4437-97bf-4cb1-8c4c-5f98fc5b884d)

I looked into your code and saw that you build the SP LoginName but the UPN is not encoded.
![image](https://github.com/pnp/pnpcore/assets/23434632/8e0d9eb8-693f-4e6c-a70b-034abbeab6f9)

I finally tested by encoding the UPN when calling `GetUserEffectivePermissionsAsync()` and it works.
```
var user = await PnPContext.Web.EnsureUserAsync("florian.labranche@contoso.com");
await PnPContext.Web.GetUserEffectivePermissionsAsync(HttpUtility.UrlEncode(user.UserPrincipalName))
```
Note: UPN is the External one with #EXT#. Those '#' are the cause of the issue.

**Conclusion:**
I have a working fix on my side but I don't know if UPN should be encoded in PnPCore method or if PnPCore should call EnsureUser() to get the "true" UPN and the encode it.

**Comment by jansenbe** [comment]
@FlorianLabranche : I've implemented a fix, now using the UPN value for external users works directly with the method:

```csharp
var basePermissions = await context.Web.GetUserEffectivePermissionsAsync("bert_contoso.com#ext#@fabrikam.onmicrosoft.com");
```

**Comment by jansenbe** [comment]
Will appear in the next nightly, closing this issue now

**Comment by FlorianLabranche** [comment]
Thank you!

**Comment by Thibaultce** [comment]
Hi @jansenbe 
We have the same issue for the List, the fix you did should probably be also done [here](https://github.com/pnp/pnpcore/blob/c978a3596672bcb92ce7cbbe2fdfa5ce6f7247f6/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/List.cs#L1417).
Thanks for your help !
