### ISSUE TITLE
Sensitivity label not being assigned when creating team site

### ISSUE THREAD

**Issue by bricenocar** [pnp/pnpcore#1352]
## Category

- [x] Bug

## Describe the bug
I am using the following options for team site creation:

var teamSiteToCreate = new TeamSiteOptions(StringUtilities.NormalizeSiteAlias(alias), title)
{                    
    Description = description,
    Language = language,                    
    SensitivityLabelId = sensitivityLabel,
    WelcomeEmailDisabled = true,
    IsPublic = isPublic
};

using var newSiteContext = await context.GetSiteCollectionManager().CreateSiteCollectionAsync(teamSiteToCreate, siteCreationOptions)

The site does not get the sensitivity label id set. However, it functions seamlessly if I create a communication site.

## Expected behavior

The site gets the label assigned

## Environment details
- **SDK version**: PnP.Core (1.10.0)
- **OS**: Windows 11

### Additional context

I did a quick check and it looks like the error might be in the file: pnpcore\src\sdk\PnP.Core.Admin\Model\SharePoint\Core\Internal\SiteCollectionCreator.cs
In line: 255. The graph group creation option is being set with the key "SensitivityLabel", maybe it has been udated/changed in graph.

**Comment by jansenbe** [comment]
Thanks for reporting this @bricenocar. Would it be possible use Fiddler and create a site in the UI using a sensitivity label and then check for the payload used to create the site. This will validate you're using the correct label id. I assume (did not cross check) that the UI is calling a REST API, we however are calling a Graph API. 

In your code, are you using application permissions or delegated?

**Comment by bricenocar** [comment]
Hello @jansenbe,

I have done some tests on both a team site (with group) and a communication site (without group). The creation of a communication site via the SharePoint (SP) REST API proceeds smoothly, and the sensitivity label is assigned without any issues.

However, the creation of a team site involves a slightly different process. During site creation, the group is assigned the sensitivity label via Microsoft Graph. I verified this by inspecting the Graph request in the local debugging session of my Azure Function. Despite the successful Graph request, the sensitivity label is not assigned.

To troubleshoot, I attempted to create the site using the Graph Explorer with a POST request to https://graph.microsoft.com/v1.0/groups. This time, I included the sensitivity label in the payload:

```
{
    "displayName": "Just a test",
    "mailEnabled": true,
    "mailNickname": "library",
    "securityEnabled": true,
    "groupTypes": [
        "Unified"
    ],
    "assignedLabels": [
        {
            "labelId": "e0f5f7cd-0254-4430-a0f2-a7139dffb529"
        }
    ]
}
```

It worked seamlessly, and the label was correctly assigned during the group's creation. This indicates that the issue may be related to the sensitivity label assignment in the Graph request payload used by the PnP Core SDK, which might be outdated or deprecated.

To address this, I implemented a workaround by sending a PATCH request after the site creation with the payload:

```
{
    "assignedLabels": [
        {
            "labelId": "e0f5f7cd-0254-4430-a0f2-a7139dffb529"
        }
    ]
}
```

While effective, it's worth noting that there is a delay in the SharePoint (SP) site information GUI reflecting the label. This delay is due to a timer job that syncs the group label and SP site label. Despite this delay, the workaround successfully assigns the label to the group.

Feel free to ask for more information if needed! :)

**Comment by bricenocar** [comment]
Hello @jansenbe, I am now closing this issue :), I was using version 1.10 of the package, just noticed that you released 1.11 one month ago, I was able to debug and see that you had already fixed the issue in 1.11 :). Thanks anyway

**Comment by bricenocar** [comment]
Ok, I had to reopen the issue. The label is assigned and the site gets it, but after some seconds, it gets removed. Can you try to reproduce it? @jansenbe

**Comment by wilecoyotegenius** [comment]
@bricenocar I had the same issue. I have noticed that it actually works better to apply sensitivity label not by passing it within `creationOptions` array of the POST creation payload, but rather apply the label just after the group is created via updating associated site properties. I took this solution from PnP.PowerShell Set-PnPTenantSite cmdlet's code. This method makes the applied label visible in both SPO Admin and Graph Api/Azure Portal almost immediately (and more important, label stays there 😊 ).

I have created a pull request with a change: #1389.

It is still in draft as I have not written any unit tests - PnP.Core unit tests with mocking mechanism are beyond my level of understaning (I somehow cannot make them work). I have however tested my code with delegated (InteractiveAuthenticationProvider) and application/app-only (PnPCoreAuthenticationCredentialConfigurationOptions with certificate) permissions.

If for some reason my PR never makes it, you may create a site without a sensitivity label and update the properties just after site is created. Below is a very simplified code that gets the job done. 

```
using (var scope2 = host.Services.CreateScope())
{
    var pnpContextFactory = scope2.ServiceProvider.GetRequiredService<IPnPContextFactory>();

    using (var context = await pnpContextFactory.CreateAsync("Default"))
    {
         var teamSiteToCreate = new TeamSiteOptions("team41", "team-41") {
              Owners = new [] {owner}
         };
         using (var newSiteContext = await context.GetSiteCollectionManager().CreateSiteCollectionAsync(teamSiteToCreate))
         {
              await newSiteContext.Site.LoadAsync(p => p.Url);
              var props = context.GetSiteCollectionManager().GetSiteCollectionProperties(newSiteContext.Site.Url, null);
              props.SensitivityLabel2 = labelId;
              await props.UpdateAsync(null).ConfigureAwait(false);
          }
    }
}
```

**Comment by bricenocar** [comment]
Thanks a lot @wilecoyotegenius. I tried setting the property bag and it worked very well. I hope that your PR gets approved and implemented in the next release :). @jansenbe let me know if you need any details about the workaround setting the property value (SensitivityLabel2).

**Comment by jansenbe** [comment]
@bricenocar : the change from @wilecoyotegenius has been merged, this indeed works perfect with both delegated as application permissions. This will be part of the next nightly, closing this issue now.
