### ISSUE TITLE
GetWssIdForTermAsync returns wrong WssId if used multiple times on the same PnPContext instance 

### ISSUE THREAD

**Issue by FlorianLabranche** [pnp/pnpcore#1355]
## Category

- [x] Bug

## Describe the bug

Using the same instance of PnPContext, if we call GetWssIdForTermAsync multiple times for different Term Ids, it will return the lowest WssId.

## Steps to reproduce

* Call GetWssIdForTermAsync for a term id
`var wssId = await PnPContext.Web.GetWssIdForTermAsync("9a75fe52-df53-4308-ad8d-dde6ee58376c");`
This term returns a WssId of 19
![image](https://github.com/pnp/pnpcore/assets/23434632/6139e722-d884-488e-98cc-def479692ae1)
* Call GetWssIdForTermAsync for a term having a WssId greater than the first one
`var wssId = await PnPContext.Web.GetWssIdForTermAsync("fd24f190-c115-4258-b337-7997f8e00a6c");`
This term will still returns a WssId of 19 despite it should be 20.
![image](https://github.com/pnp/pnpcore/assets/23434632/01b611e0-b13a-4977-be02-6ca1a1242d19)

## Expected behavior

GetWssIdForTermAsync should return the correct WssId.
Issue is caused by the implementation still having previous listItems cached.
![image](https://github.com/pnp/pnpcore/assets/23434632/6e78f29a-3dbe-4efa-9298-0f8c962005d6)

## Environment details (*development & target environment*)

- **SDK version**: 1.10 and 1.11
- **OS**:Windows 10
- **SDK used in**: Azure Function Apps
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022

**Comment by FlorianLabranche** [comment]
I temporary fixed this by cloning the context.
`var wssId = await (await PnPContext.CloneAsync()).Web.GetWssIdForTermAsync(term.Id);`

**Comment by jansenbe** [comment]
@FlorianLabranche : just pushed a fix, will be part of the next nightly. Please test tomorrow and close this issue if things work for you.

**Comment by FlorianLabranche** [comment]
@jansenbe tested and approved, next time, I should try to do a PR 😀 
Thanks for the quick support !
