### ISSUE TITLE
ViewType2 updating error

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1360]
## Category

- [x] Bug

## Describe the bug

I get this error when I try to change the ViewType2
 Cannot convert a primitive value to the expected type 'Edm.String'. See the inner exception for more details.

## Steps to reproduce
var viewToUpdate = myList.Views.AsRequested().FirstOrDefault(p => p.Title == "All Documents");

viewToUpdate.ViewType2 = ViewType2.TILES;

await viewToUpdate.UpdateAsync();

## Environment details (*development & target environment*)

- **SDK version**: 1.10.152-nightly
- **OS**: MacOS
- **SDK used in**: ASP.Net Web app
- **Framework**: .net 8.0

**Comment by jansenbe** [comment]
Thanks for reporting this @danielpastoor , I've just pushed a fix which will appear in the next nightly. Will close this issue already, but please re-open or create a new one in case it's not working for you as of tomorrow.

**Comment by danielpastoor** [comment]
Thank you
