### ISSUE TITLE
Ability to specify "expand" parameter for RenderListDataAsStream

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1362]
## Category

- [x] Feature request

## Describe the feature

I'm using IList.LoadListDataAsStreamAsync( ) but there's no ability to specify ?$expand=FieldValuesAsText in the query string, which is needed in order to be able to read the FieldValuesAsText dictionary (e.g. to get a pre-formatted value for FileLeafRef etc.)

## Describe the solution you'd like

Some way of specifying that FieldValueAsText is required when calling IList.LoadListDataAsStreamAsync (and variants thereof)

## Additional context

Have confirmed everything works as expected if I manipulate the query string in the debugger. Have checked source and even via reflection I can't see how to override this readily. Instead I've had to write my own version of LoadListDataAsStreamAsync, which is a fair bit of code.

**Comment by wizofaus** [comment]
BTW, I did actually eventually figure out how to do it by creating a batch first, modifying it VIA REFLECTION (as ApiCall is "internal"), then executing it. But as it happens it didn't do what I expected. So far I've yet to find a way of getting all the functionality I need from RenderListDataAsStream (particularly the paging logic), as well as getting the FieldValuesAsText information, though I'm pretty confident it is actually possible.

**Comment by jansenbe** [comment]
@wizofaus : did you manage to manually craft a REST RenderListDataAsStream query that does what you need? If so, please share here as that will help speed up the needed research.

**Comment by wizofaus** [comment]
Have to admit I haven't, I'm sure at one point I was able to get that API to return me FieldValuesAsText info but no luck on retrying. It definitely does have other parameters that are set by the SPO web interface itself when it calls it though.
I will say it's also problematic trying to extract some of the "special" fields it returns with . in the name - PnP itself discards them mostly, though they can be extracted manually from the JSON response.  In some cases they're quite important.

**Comment by jansenbe** [comment]
@wizofaus : you can also directly call the REST/Graph endpoints yourselves using PnP Core SDK: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request shows how this works. This way you get the full JSON in return

**Comment by wizofaus** [comment]
I somewhat suspect now what happened is that I'd previously called a different API, then called LoadListDataAsStream - and it didn't replace the "Items" with what had been previously loaded. Which seems quite unexpected behaviour to me (I know you can always call "Clear()" first).

**Comment by jansenbe** [comment]
@wizofaus : yes, at this is a "Load" operation it adds to the loaded collection unless you clear the Items collection yourselves. Does  doing so fix your issue?

**Comment by wizofaus** [comment]
No, I need a way to perform a single load operation that acts as per LoadListDataAsStream *and* includes FieldValuesAsText.  But if the underlying API really doesn't support it then so be it, this can be closed.

**Comment by jansenbe** [comment]
@wizofaus : did you consider using a CAML query (see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#c-getting-list-items-via-the-loaditemsbycamlquery-approach). This works with FieldValuesAsText, see at the bottom on this thread https://github.com/pnp/pnpcore/issues/607

**Comment by wizofaus** [comment]
Yes, but that doesn't return back the same level of detail that RenderListDataAsStream does.  Anyway, like I said, it does seem to be an underlying API limitation, so it's fine to close this.
But I do have a similar concern with LoadItems and not being able to specify that particular calculated fields should be selected (as they're not returned if you don't explicitly select them).

**Comment by wizofaus** [comment]
> @wizofaus : you can also directly call the REST/Graph endpoints yourselves using PnP Core SDK: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request shows how this works. This way you get the full JSON in return

If I do this how do I get it to update the model with the response though? If it doesn't do that much I'm not sure what I gain from using PnP.Core at all...

**Comment by jansenbe** [comment]
> Yes, but that doesn't return back the same level of detail that RenderListDataAsStream does. Anyway, like I said, it does seem to be an underlying API limitation, so it's fine to close this. But I do have a similar concern with LoadItems and not being able to specify that particular calculated fields should be selected (as they're not returned if you don't explicitly select them).

@wizofaus: Can you create new issue describing this

**Comment by jansenbe** [comment]
> > @wizofaus : you can also directly call the REST/Graph endpoints yourselves using PnP Core SDK: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request shows how this works. This way you get the full JSON in return
> 
> If I do this how do I get it to update the model with the response though? If it doesn't do that much I'm not sure what I gain from using PnP.Core at all...

That option is meant for giving folks a way to code things which are (not yet) supported in PnP Core SDK. In most cases there's no get, nor update scenario in PnP Core SDK and then you'd handle these manually. In this case it's more complicated as you'd be using this for an alternative GET, depending on your use case this might not make sense.

**Comment by jansenbe** [comment]
@wizofaus : I've done some research here, but when using the RenderListDataAsStream API call there's no option to use FieldValuesAsText. When needing fields using this method it's best to describe the needed fields, including system fields, as part of the CAML query and then they'll be returned with rich content (e.g. the person field is expanded). 

Given this is an API limitation I'm going to close this issue.
