### ISSUE TITLE
Add "Groups" property to ISharePointUser and allow fetching list via request to load Web

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1363]
## Category

- [x] Feature request

## Describe the feature

Currently can't find a straightforward way to get list of SharePoint SiteGroups that the user belongs to.  It's simple in the PNP JS library (web.currentUser.groups()).

## Describe the solution you'd like

ISharePointUser should have a Groups property (that you can choose to expand while loading a web/user etc.)

**Comment by jansenbe** [comment]
@wizofaus : that makes sense, Groups is an expandable property of SP.User in REST.

**Comment by wizofaus** [comment]
I'm not opposed to contributing a fix to this if I get the time, given I need the functionality (I think I have a workaround but not sure it works in all cases).

**Comment by jansenbe** [comment]
@wizofaus : the `Groups` property has been added to `ISharePointUser`. This change will appear in the next nightly, closing this issue now.

**Comment by wizofaus** [comment]
Thanks!

**Comment by wizofaus** [comment]
BTW when is the next planned nuget release?
