### ISSUE TITLE
LoadListDataAsStreamAsync: System.InvalidOperationException (The requested operation requires an element of type 'String') when view contains Image field data

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1365]
## Category

- [x] Bug

## Describe the bug

Exception thrown calling LoadListDataAsStream(Async) when the document library has image columns and rows with data for such columns.
The data returned by the SPO REST API RenderListDataAsStream looks like:
```
{"fileName":"filename.jpg","serverRelativeUrl":"/sites/TestUser/SiteAssets/Lists/eda0a08f-8db5-4ad3-81d6-cc2e66357fa3/filenamejpg","id":"1b813e01-5d0d-4c2e-8eca-a72e718d61ce","serverUrl":"https://tenant.sharepoint.com","thumbnailRenderer":{"spItemUrl":"https://tenant.sharepoint.com:443/_api/v2.1/drives/...","fileVersion":1,"sponsorToken":"..."}
```
But PnP.Core (ListDataAsStreamHandler.Deserialize) is trying to parse it as a string.

## Repro steps

Create a document library with an image column and add at least one document with a valid image for said column.

Call as per:

```
                var output = await lib.LoadListDataAsStreamAsync(new RenderListDataOptions()
                {
                    RenderOptions = RenderListDataOptionsFlags.None,
                    MergeDefaultView = true,
                    AddRequiredFields = true,
                }).ConfigureAwait(false);
```
 

## Expected behavior

No exception should be thrown, and image data available in item values.
(I'd also say, if there really *were* an issue parsing the JSON response, I wouldn't expect it to be an InvalidOperationException...)

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0
- **OS**: Windows 10 
- **SDK used in**: ASP.Net (Core) Web app 
- **Framework**: .NET Core v8.0
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by wizofaus** [comment]
Happy to contribute a fix for this if needed, how long would it take typically to get included in the next NuGet release?  Though if someone can see a workaround, even if it's just to ensure such data is ignored and not returned (I can live without it for now), that'd be good.

**Comment by wizofaus** [comment]
I have a fix for this but it uses `propertyValue.ToObject<System.Dynamic.ExpandoObject>();` (when propertyValue.ValueKind == JsonValueKind.Object) which isn't unreasonable but not ideal because the individual properties are of type JsonElement rather then underlying raw type (string etc.).  There's currently no FieldImageValue type defined (or associated interface).

**Comment by wizofaus** [comment]
Oh sorry just realised I commented on the wrong issue, but I was planning to put up on PR for both Image and Location columns. Also would like to know when the next nuget release is planned?

**Comment by jansenbe** [comment]
@wizofaus :We plan to release a new version by end of the week (or I can push this out to next week), would be good to get the PR committed before so it can be included.

**Comment by jansenbe** [comment]
@wizofaus : can I assign this one to you?

**Comment by wizofaus** [comment]
I can try to put up a PR today or tomorrow, but it won't have a "complete"/independent unit test that will work with any live site

**Comment by jansenbe** [comment]
@wizofaus : your PR was merged, closing this now
