### ISSUE TITLE
Feature: Support AOT compilation

### ISSUE THREAD

**Issue by mcshaz** [pnp/pnpcore#1370]
## Category

- [x] Feature request

## Describe the feature

Support Publishing Ahead Of Time (AOT). 

## Describe the solution you'd like

- This would involve avoiding system.reflection whenever JSON is serialized/deserialized by the library to a known type. This would involve using source generator APIs or explicitly configure the `JsonSerializerOptions.TypeInfoResolver` property.
- There is a `JsonSerializer.IsReflectionEnabledByDefault` flag to determine which method to use to serialize JSON
- further info can be found at https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/reflection-vs-source-generation?pivots=dotnet-8-0 and https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0

## Additional context

The effect on the speed of this library would be small given the rate limiting step will be waiting for network traffic, _however_ consuming applications may well download files and then perform very computationally expensive operations on those files. In these scenarios, speed benefits would be great.

**Comment by jansenbe** [comment]
@mcshaz : thanks for using the library and raising this idea. Supporting AOT will be a significant investment, even if we only support that for the .NET 8 version, as reflection is used on some key places across the library. In theory all of these could be replaced by source generation, but more research is needed. The (current) main use case of the library is within server side code where AOT has less benefits, but looking forward code in the browser and containers based upon AOT are growing, so the ask definitely makes sense.

Is this something you can prototype?
