### ISSUE TITLE
The method 'Contains' is not supported

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpcore#1371]
## Category

- [x] Bug

## Describe the bug
context.Site.RootWeb.AssociatedVisitorGroup.Users.Contains and .Any are not a compile error but not supported at run time.
## Steps to reproduce

1. See code 
```   
await context.Web.LoadAsync(p => p.AssociatedMemberGroup, p => p.AssociatedOwnerGroup,
                p => p.AssociatedVisitorGroup, p => p.SiteGroups.QueryProperties(u => u.Users));
            var everyOne = context.Site.RootWeb.EnsureEveryoneExceptExternalUsers();

    if (!context.Site.RootWeb.AssociatedVisitorGroup.Users.Contains(everyOne)) // Here comes the error
    {
        await context.Site.RootWeb.AssociatedVisitorGroup.AddUserAsync(everyOne.LoginName);                                                                                             
    } 
``` 
## Expected behavior
Since the intelicese suggest the "Any" and "Contains" I expected it to be supported.
## Environment details (*development & target environment*)
- **SDK version**: [1.11.0 ]
- **OS**: [ Windows 11]
- **SDK used in**: [Azure Function]
- **Framework**: [.NET 8 ]
- **Tooling**: [Visual Studio 2022]

### Additional context
Is there a more elegant to check existing members before adding them?
Thanks

**Comment by jansenbe** [comment]
@Ofer-Gal : as you've already loaded the users with the previous statement you need to use AsRequested() on the loaded users, then you can use the OOB LINQ expressions like `Contains`. So something like this (not tested your code):

```csharp
await context.Site.RootWeb.LoadAsync(p => p.AssociatedMemberGroup, p => p.AssociatedOwnerGroup,
                p => p.AssociatedVisitorGroup, p => p.SiteGroups.QueryProperties(u => u.Users));

var everyOne = context.Site.RootWeb.EnsureEveryoneExceptExternalUsers();

if (!context.Site.RootWeb.AssociatedVisitorGroup.Users.AsRequested().Contains(everyOne))
{
      await context.Site.RootWeb.AssociatedVisitorGroup.AddUserAsync(everyOne.LoginName);                                                                                             
} 
```

**Comment by Ofer-Gal** [comment]
AsRequested()  Did it!

Now Any and Contains works fine.
Thank you much
