### ISSUE TITLE
.Site.RootWeb.AssociatedOwnerGroup.AddUserAsync("c:0o.c|federateddirectoryclaimprovider|xxxxxx") does nothing

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpcore#1372]
## Category

- [x] Bug

## Describe the bug
Can't add 365 group to the AssociatedOwnerGroup

## Steps to reproduce

Code `
siteOwners = "c:0o.c|federateddirectoryclaimprovider|xxxxxx"
await context.Site.RootWeb.AssociatedOwnerGroup.AddUserAsync(siteOwners);` does nothing

## Expected behavior
add the group to the owners SharePoint group
- **SDK version**: [1.11.0 ]
- **OS**: [e.g. Windows 11]
- **SDK used in**: [Azure Function]
- **Framework**: [e.g. .NET 8]
- **Tooling**: [ Visual Studio 2022]

Thanks

**Comment by jansenbe** [comment]
@Ofer-Gal : I've just below code and that worked fine for me:

```csharp
                await context.Web.LoadAsync(p => p.AssociatedMemberGroup, p => p.AssociatedOwnerGroup,
                p => p.AssociatedVisitorGroup, p => p.SiteGroups.QueryProperties(u => u.Users));
                var everyOne = context.Site.RootWeb.EnsureEveryoneExceptExternalUsers();

                await context.Web.AssociatedVisitorGroup.AddUserAsync(everyOne.LoginName);

```


![image](https://github.com/pnp/pnpcore/assets/7451219/53e00f6c-1238-4762-ae7f-39101c4d970a)

**Comment by Ofer-Gal** [comment]
Everyone works fine for me too.
The problem is adding a 365 group 
Such as `siteOwners = "c:0o.c|federateddirectoryclaimprovider|xxxxxx"`  To the Owneres Group
`context.Site.RootWeb.AssociatedOwnerGroup.AddUserAsync(siteOwners);`   Does not error but does not add.
When I added a normal user it worked fine too.

After a while  It showed

![image](https://github.com/pnp/pnpcore/assets/5054931/51c6a875-7a3e-40ac-862c-d7199f4ca832)

Thank you!
