### ISSUE TITLE
Improved mockability

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1373]
## Category

- [x] Feature request

## Describe the feature

It should be straightforward to write unit tests for code that makes use of IPnPContextFactory/IPnPContext etc. 

## Describe the solution you'd like

IPnPContextFactory should be easily mockable to create mock IPnPContext objects that return mock IBatchResult objects that have mock errors etc.

Instead the PnP.Core library makes uses extensive use of concrete and internal-only types that can't readily be mocked. Some example types: PnPContext, BatchResult, TransientDictionary, ServiceError etc.

Using Moq (for example), I'd expect to just be able to use write

```
            var list = new List<BatchResult>();
            AddMockedBatchResults(list);
            var context = Mock.Of<IPnPContext>();
            Mock.Get(context).Setup(c => c.ExecuteAsync(false)).ReturnsAsync(list);
            var factory = Mock.Of<IPnPContextFactory>();
            Mock.Get(factory).Setup(f => f.CreateAsync(It.IsAny<Uri>(), It.IsAny<PnPContextOptions>())).ReturnsAsync(context);
```

But in fact it's impossible to do this with a lot of hoop-jumping, due to BatchResult only having an internal constructor (and ServiceError only having internal setters for key properties like Message), and the fact that IPnPContextFactory.CreateAsync( ) returns Task<PnPContext> (which can't be mocked at all).
            
IListItem is also very difficult to mock because the key "Values" property uses an unmockable internal type (TransientDictionary).

## Additional context

N/A

**Comment by jansenbe** [comment]
@wizofaus : labelled to inspect this one when building v2, for now I'm gonna close it to keep the issue list clean.
