### ISSUE TITLE
Better way to match BatchResult with request

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1374]
## Category

- [x] Feature request

## Describe the feature

Would like the ability to reliably/safely determine which BatchResult (as returned by IPnPContext.ExecuteQuery) matches with the corresponding BatchRequest.

## Describe the solution you'd like

Something like
```
foreach (var id in idsToRecycle)
    idMap[id] = (await list.Items.RecycleByIdBatchAsync(id)).RequestId;

var batchResults = await pnpContext.ExecuteAsync(false);
foreach (var id in idsToRecycle)
    if (pnpContext.FindByRequestId(idMap[id]) is BatchResult result)
       ;// handle appropriately according to id 
```

Alternatively I'd be quite happy if `RecycleByIdBatchAsync` (and similar functions) returned back a BatchRequest object from which the BatchResult info was available explicitly after calling ExecuteAsync( ):

```
foreach (var id in idsToRecycle)
    idMap[id] = await list.Items.RecycleByIdBatchAsync(id);

var batchResults = await pnpContext.ExecuteAsync(false);
foreach (var id in idsToRecycle)
    if (idMap[id].Result is BatchResult result)
       ;// handle appropriately according to id 
```

## Additional context

Currently have to do it by assuming that the BatchResult.ApiRequest string happens to match a particular pattern (e.g. `/items(<id>)/recycle` in this case).

**Comment by jansenbe** [comment]
@wizofaus : `BatchRequest` is for the most part an internal class, only few properties are exposed to enable custom API calling to use batching. The `BatchResult` class returns all the information needed to understand the failed request and that information is copied from the starting BatchRequest. 

As the various 'batch' methods return different types (adding a list item returns an IListItem, deleting an item returns nothing) there's no way for you capture the id of the created internal `BatchRequest`, therefore making it hard to later on link back to the `BatchRequest`.  

What information in `BatchRequest` do you feel is missing for being able to realize your scenario?

**Comment by wizofaus** [comment]
Just some way of matching reach Batch result with the corresponding batched request so I can tell which ones have failed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jansenbe** [comment]
@wizofaus : What I can do is make the Id of the `BatchRequest` public and make that Id also appear in the `BatchResult`. This then allows you to track whatever you want for a given `BatchRequest` and after the batch execution link the failing requests back to that information. Something along these lines:

```csharp
var batch = context.NewBatch();

// Sample on how to track additional information for a batch request
Dictionary<Guid, int> deletedListItemIds = new();

for (int i = 1; i <= 150; i++)
{
    await myList.Items.DeleteByIdBatchAsync(batch, i);
    deletedListItemIds.Add(batch.Requests.Last().Value.Id, i);
}

// Execute the batch without throwing an error, should get a result collection back
var batchResponse = await context.ExecuteAsync(batch, false);                

// Find the corresponding batch requests
foreach (var errorResult in errorResults)
{
    var failedListItemIdDelete = deletedListItemIds.FirstOrDefault(p=> p.Key == errorResult.BatchRequestId).Value;
}
```

**Comment by jansenbe** [comment]
@wizofaus : just pushed the change that enables this

**Comment by wizofaus** [comment]
I can see this Id is public now, but just to confirm, I have to rely on knowing the order of the request in the current batch to match them with my input data? (i.e. I can't just associate my own data with each request).
