### ISSUE TITLE
Unnecessary type guard in QueryableExtensions.cs?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/pnpcore#1376]
## Category

- [x] Bug - but not really

## Describe the bug

The issue might be a copy and paste oversight in `QueryableExtensions.cs`. I'm not sure where to put this, so I'm opening a ticket.

Here's the method in question:

https://github.com/pnp/pnpcore/blob/d2adbd6c5a5e2042381a7dd6db409f6e1cee79f2/src/sdk/PnP.Core/QueryModel/Linq/QueryableExtensions.cs#L600-L614

Is this type guard here really needed?

https://github.com/pnp/pnpcore/blob/d2adbd6c5a5e2042381a7dd6db409f6e1cee79f2/src/sdk/PnP.Core/QueryModel/Linq/QueryableExtensions.cs#L608-L611

Shouldn't this be sufficient instead (which compiles fine):

```
return (IEnumerable<TSource>)source.RequestedItems;
```

Also, the exception thrown on a failed cast is strange. It says `Exception_InvalidOperation_NotAsyncQueryableSource` - but there is no async queryable involved in this method. There are other methods higher up in the file where a lot of async stuff is going on. But not this one. Thus my suspicion that this might be a copy and paste thing.

So I'm wondering if I can replace this:

```csharp
if (source is BaseQueryableDataModelCollection<TSource> enumerable)
{
    return (IEnumerable<TSource>)enumerable.RequestedItems;
}
```

with this:

```
return (IEnumerable<TSource>)source.RequestedItems;
```

But I am hesitant since this is deep in the core and hasn't been touched for years. And there might be expectations further down the road that need this type check, although this is not visible here.

### Additional context

Why am I bothering? I'm currently trying to mock enough PnP types via their interfaces to accomplish something. But those hard type guards (here the check for BaseQueryableDataModelCollection) sabotage this. There are other places like this and they might make my approach fail. But I have not given up, yet.

**Comment by wizofaus** [comment]
Mocking PnP types is not straightforward - at least not using a library like Moq that can only do interfaces. I've already raise a ticket for that: https://github.com/pnp/pnpcore/issues/1373

**Comment by heinrich-ulbricht** [comment]
@wizofaus Yes, I can confirm that. I have something working, but it is not pretty. Appreciate the ticket - seems like we had the same pain at the same time :D

**Comment by jansenbe** [comment]
@heinrich-ulbricht : did you test above approach or it's only from "observation"?

**Comment by heinrich-ulbricht** [comment]
I implemented that and for me it's running fine.

**Comment by jansenbe** [comment]
@heinrich-ulbricht : thanks for the test confirmation. I've committed this change, closing this now.
