### ISSUE TITLE
PnP.Core.ClientException: Property Url was not yet loaded when trying to create context from a SitePages page URL

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1379]
## Category

- [x] Bug

## Describe the bug

Calling  `await pnpContextFactory.CreateAsync(uri, authenticationProvider, options);` when uri is something like "https://contoso.sharepoint.com/sites/testsite/SitePages/test.aspx" results in an unexpected/unhelpful error - PnP.Core.ClientException "Property Url was not yet loaded".

## Steps to reproduce

Execute the code

`await pnpContextFactory.CreateAsync(uri, authenticationProvider, options)`

where uri is the address of a page in the site's SitePages collection.

## Expected behavior

Would expect this to either just work (but I accept that's tricky as there's no completely straightforward way to know that the "/SitePages/test.aspx" should be removed by appending _api/Web) or to throw a more helpful error, e.g. some sort of "unexpected response" error (or JsonException, which is what you get for other page addresses, e.g. AllItems.aspx). 
In fact the server does (strangely) seem to be returning back a JSON response from the request to
https://contoso.sharepoint.com/sites/testsite/SitePages/test.aspx/_api/Web
but it doesn't have any of the data normally associated with that _api call.

## Environment details (*development & target environment*)

- **SDK version**: [e.g. 0.1.2005.0 ]
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **SDK used in**: [e.g. Console App | ASP.Net Web app | Blazor WebAssembly]
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x ]
- **Browser(s)**: [e.g. Chrome v79 | Safari v22 | FireFox v31 | Chromium Edge v79]
- **Tooling**: [e.g. VS Code | Visual Studio 2019]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide any other context about the problem.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@wizofaus : the URI is meant to be a site (SPWeb) URI, not an URI to a site asset. Can't you write the needed code to check the passed URI before using it with PnP Core SDK? Trying to understand the use case where you would use this?

**Comment by wizofaus** [comment]
It was just something that came up during testing. Not a high priority at all.

**Comment by jansenbe** [comment]
I'm gonna close this one @wizofaus, think there's other issues to focus on that bring more value.
