### ISSUE TITLE
Retrieving Role Assignment details throws exception with Sharing Links

### ISSUE THREAD

**Issue by JarodAI** [pnp/pnpcore#1386]
## Category

- [x] Bug

## Describe the bug

When I try to retrieve the role assignments of a file an exception is thrown if there is a Sharing link.
The error is the following:

HttpResponseCode: 404
Code: System.ArgumentException
Message: Can not find the principal with id: 27.
ClientRequestId: af5209a1-407b-8000-0bec-4440f98dde8d
SPClientServiceRequestDuration: 23
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0

the id 27 in the example matches the assigned id of the sharing link

![image](https://github.com/pnp/pnpcore/assets/148989709/0deaeb03-74b4-4a1f-a8fe-5c4ca041962d)

## Steps to reproduce

See code:
I want to extract permissions that includes a specific permission kind
```csharp
var listItem = file.ListItemAllFields;
await listItem.LoadAsync(
    w => w.HasUniqueRoleAssignments,
    w => w.RoleAssignments.QueryProperties(
         p => p.PrincipalId,
         p => p.RoleDefinitions.QueryProperties(
             rd => rd.Id,
             rd => rd.Name,
             rd => rd.BasePermissions)));
var ras = listItem.RoleAssignments;
PermissionKind permissionKind = PermissionKind.ViewListItems; 
//The following line throws the exception
List<IRoleAssignment> filteredRoles = ras.AsRequested().Where(
               ra => ra.RoleDefinitions.ToList().Any(
                   rd => rd.BasePermissions.Has(permissionKind))).ToList();
```

## Expected behavior

No exception thrown and have access to the required roles assignments

## Environment details (*development & target environment*)

- **SDK version**: 1.11
- **OS**: Windows 11 
- **SDK used in**: Console App
- **Framework**: .NET Core v8 
- **Tooling**: Visual Studio 2022

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@JarodAI : For me this works, you were missing a `.AsRequested()` when querying the `RoleDefinitions`. See below code for working version. I'll close this issue now, but feel free to reopen in case you can't get this to work on your end.

```csharp
                var file = await context.Web.GetFileByServerRelativeUrlAsync("/sites/prov-1/graph/document.docx", p=>p.All, p=>p.ListItemAllFields);

                var listItem = file.ListItemAllFields;
                await listItem.LoadAsync(
                    w => w.HasUniqueRoleAssignments,
                    w => w.RoleAssignments.QueryProperties(
                         p => p.PrincipalId,
                         p => p.RoleDefinitions.QueryProperties(
                             rd => rd.Id,
                             rd => rd.Name,
                             rd => rd.BasePermissions)));
                var ras = listItem.RoleAssignments;
                PermissionKind permissionKind = PermissionKind.ViewListItems;
                //The following line throws the exception
                List<IRoleAssignment> filteredRoles = ras.AsRequested().Where(
                               ra => ra.RoleDefinitions.AsRequested().ToList().Any(
                                   rd => rd.BasePermissions.Has(permissionKind))).ToList();

```
