### ISSUE TITLE
CreateCopyJobsAsync creating duplicates of nested folders with content in root

### ISSUE THREAD

**Issue by mortenfa** [pnp/pnpcore#1392]
## Category

- [x] Bug

## Describe the bug

When using CreateCopyJobsAsync with folders the nested folders are also created in the root folder

## Steps to reproduce

foreach (string url in jobUris)
{

    var jobUri = new string[] { url };
   var  copyJobs = await pnpCoreContext.Site.CreateCopyJobsAsync(jobUri, destinationAbsoluteUrl, new PnP.Core.Model.SharePoint.CopyMigrationOptions
    {
        AllowSchemaMismatch = true,
        IgnoreVersionHistory = false,
        IsMoveMode = false,
        BypassSharedLock = true,
        MoveButKeepSource = true,
        ExcludeChildren = false,
        NameConflictBehavior = SPMigrationNameConflictBehavior.Replace
    });
}

## Expected behavior

Folders and content should only be in the nested folders

## Environment details (*development & target environment*)

- **SDK version**: 1.9.0 and 1.11.0
- **OS**: Windows Server 2016 and Windows 11
- **SDK used in**:  ASP.Net Web app
- **Framework**:  .NET Core 7.0
- **Browser(s)**:  Edge Version 121.0.2277.112 (Official build) (64-bit)
- **Tooling**:  Visual Studio 2022 17.8.7

**Comment by jansenbe** [comment]
@mortenfa : can you explain what you copy from where to where? PnP Core SDK is simply calling the REST API (see https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/Site.cs#L437-L447), so this might be a SharePoint API issue?

**Comment by jansenbe** [comment]
@mortenfa : this feels like a SharePoint API bug and not something in PnP Core SDK. I would recommend you or your customer to open a support ticket as from the PnP Core SDK side we can't do that.

**Comment by mortenfa** [comment]
Thanks @jansenbe I will try that
