### ISSUE TITLE
Ability to batch FileCollection.AddSync

### ISSUE THREAD

**Issue by wizofaus** [pnp/pnpcore#1397]
## Category

- [x] Feature request

## Describe the feature

Would like the ability to easily upload multiple files in parallel or as a batch via FileCollection.AddAsync( ).

## Describe the solution you'd like

There doesn't seem to be any reason the /files/addusingpath API can't be done as part of a batch (though I'd agree for very large files it would be problematic), but at any rate it's definitely useful for a client to be able to efficiently upload multiple files (esp. if they have a particular folder structure, e.g. sync-ing an entire local directory to SharePoint) without having to do them one by one. This is in fact exactly what the SharePoint frontend does (I haven't checked if the JS PnP library supports this).

Ideally just the ability to specify a list of server-relative url and + binary content stream pairs, and some straightforward way of waiting for all uploads to complete and collate any errors that might occur.

However, I would also like the ability to update column values for a just-uploaded document as part of a batch operation (I don't want the document to be visible to any event receivers or other applications until the column values are updated).  CSOM can do this using FileCreationInformation so I assume it's possible using the REST API.

**Comment by jansenbe** [comment]
@wizofaus : file uploads via addusingpath using batching is not supported by SharePoint, hence it's also not available in this SDK. The CSOM approach were you batch the upload and then set the metadata indeed can work, but this is not possible with SharePoint REST. We could investigate having a dedicated CSOM based operation in the SDK, however it still will not be optimal for migration related tasks, for that it's best use migration specific APIs like these: https://learn.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview

**Comment by wizofaus** [comment]
I'm not doing migration, this is to support a tool that allows users to perform the same sorts of operations normally available on a document library but that adds an additional layer of processing while doing so.

**Comment by jansenbe** [comment]
@wizofaus : as we do not want to use more CSOM than strictly needed I'm going to close this issue. If you want this you can simply use CSOM together with PnP Core SDK as shown in our interop documentation (https://pnp.github.io/pnpcore/using-the-sdk/basics-pnpframework.html#using-pnp-framework-when-the-pnp-core-sdk-was-already-configured). If you don't want to use PnP Framework as easy way to switch a PnPContext to a CSOM ClientContext you can check this for creating a ClientContext using an access token: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard#getting-an-access-token-from-azure-ad-and-using-that-in-your-csom-for-net-standard-based-application. To get the access token from a PnPContext you use one of the `GetAccessTokenAsync` methods of the connected `IAuthenticationProvider`

**Comment by wizofaus** [comment]
It's fine, I'm no longer working in a role where I have use for this library.
