### ISSUE TITLE
Missing Fields when using CAML Query and LoadListDataAsStreamAsync

### ISSUE THREAD

**Issue by mortenfa** [pnp/pnpcore#1402]
## Category

- [x] Bug

## Describe the bug

When using CAML query and LoadListDataAsStreamAsync the result is missing fields. Looks like the same problem as https://github.com/pnp/pnpcore/issues/396  But the solution is not working for me.

The result only contains list custom fields. Not system fields . Specifically the FileLeafRef and FileRef fields.

I've also tried with LoadItemsByCamlQueryAsync with the same result

![image](https://github.com/pnp/pnpcore/assets/3520607/9d29d474-650c-4d4f-acb4-27d819867dd3)

## Steps to reproduce

This code

` $@"<View Scope='RecursiveAll'>
                     <ViewFields><FieldRef Name='FileRef' /><FieldRef Name='FileLeafRef' /></ViewFields>
                      <Query>
                         <Where>
                             <Gt>
                                 <FieldRef Name='ID' />
                                 <Value Type='Number'>10</Value>
                             </Gt>
                         </Where>
                     </Query>
                 </View>";`

`
var output = await sourceList.LoadListDataAsStreamAsync(new PnP.Core.Model.SharePoint.RenderListDataOptions()
 {
     ViewXml = viewXml,
     RenderOptions = RenderListDataOptionsFlags.ListData
 });

 foreach (var listItem in sourceList.Items.AsRequested())
 {
     if (listItem.FileSystemObjectType == PnP.Core.Model.SharePoint.FileSystemObjectType.File)
     {
         files.Add(listItem);
     }
 }`

## Expected behavior

Access to the item fields including system fields

## Environment details (*development & target environment*)

Windows 11, Visual Studio 2022, .NET 7 web api

- **SDK version**:  1.14.0
- **OS**: Windoes 11
- **SDK used in**:  ASP.Net Web app
- **Framework**: .NET 7
- **Browser(s)**:  Chrome/Edge
- **Tooling**:  Visual Studio 2022
- **Additional details**: Also tested in v. 

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@mortenfa : using the current version of PnP Core SDK I'm seeing both fields returned for my test list


Using LoadListDataAsStream:
![image](https://github.com/pnp/pnpcore/assets/7451219/a27a0df7-1403-4ae8-b320-5b0fdb27799c)

Using LoadItemsByCamlQuery:
![image](https://github.com/pnp/pnpcore/assets/7451219/8f07a07e-ffdf-4316-a5c6-a6704d94c10b)

**Comment by jansenbe** [comment]
@mortenfa : also tested this with a doc library and there both methods do return these fields as well. Do you see the same on smaller lists/libraries?

**Comment by mortenfa** [comment]
Strange. Yes, I am testing on a small doc lib with 150 items. I haven't implemented the Expression<func> is this necessary?

**Comment by jansenbe** [comment]
@mortenfa : Expression is not required for the CAML query and not possible for the LoadListDataAsStream method. With "smaller" I meant returning only a few columns versus the 60+ from the screenshot

**Comment by mortenfa** [comment]
Ahh ok, I'll check 👍

**Comment by mortenfa** [comment]
@jansenbe : You're right, Just created an empty doc lib w/o content types enabled, Same query gives this

![image](https://github.com/pnp/pnpcore/assets/3520607/58db53f5-8b22-4776-b8fd-9f91d8e1ed5d)

I may have to go another way since all our sites have the content types enabled. 

Thanks

**Comment by jansenbe** [comment]
I don't think this is an SDK issue, it more feels like a limitation of the used APIs...you're good with closing this one for now @mortenfa ?

**Comment by mortenfa** [comment]
I think you're right, and sure, thanks again 👍
