### ISSUE TITLE
Loading Team Tabs fails with error "System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."

### ISSUE THREAD

**Issue by nicolaor** [pnp/pnpcore#1407]
## Category

- [x] Bug

## Describe the bug

When trying to load team tabs using PnPContext we get the following exception:  
- System.FormatException:Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

## Steps to reproduce

This is the code we are executing (the exception happens on line 83)
![image](https://github.com/pnp/pnpcore/assets/89914175/c8fcdebb-fcc4-4ff9-88d7-5b0ff5c2217d)

Here is the Stacktrace:

> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
> at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
> at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
> at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
> at System.Guid.Parse(ReadOnlySpan`1 input)
> at System.Guid.Parse(String input)
> at PnP.Core.Services.JsonMappingHelper.GetJsonFieldValue(IDataModelWithContext pnpObject, String fieldName, ApiResponse apiResponse, JsonElement jsonElement, Type propertyType, Boolean useCustomMapping, Func`2 fromJsonCasting)
> at PnP.Core.Services.JsonMappingHelper.FromJsonGraph(TransientObject pnpObject, EntityInfo entity, ApiResponse apiResponse, Func`2 fromJsonCasting)
> at PnP.Core.Services.JsonMappingHelper.FromJson(TransientObject pnpObject, EntityInfo entity, ApiResponse apiResponse, Func`2 fromJsonCasting)
> at PnP.Core.Model.BaseDataModel`1.ProcessResponseAsync(ApiResponse apiResponse, Expression`1[] expressions)
> at PnP.Core.Services.JsonMappingHelper.FromJsonGraph(TransientObject pnpObject, EntityInfo entity, ApiResponse apiResponse, Func`2 fromJsonCasting)
> at PnP.Core.Services.JsonMappingHelper.FromJson(TransientObject pnpObject, EntityInfo entity, ApiResponse apiResponse, Func`2 fromJsonCasting)
> at PnP.Core.Services.JsonMappingHelper.MapJsonToModel(BatchRequest batchRequest)
> at PnP.Core.Services.BatchClient.ProcessGraphRestBatchResponse(Batch batch, String batchResponse)
> at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphBatchRequestAsync(Batch batch)
> at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphBatchAsync(Batch batch)
> at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
> at PnP.Core.Model.BaseDataModel`1.BaseRetrieveAsync(ApiCall apiOverride, Func`2 fromJsonCasting, Action`1 postMappingJson, Expression`1[] expressions)
> at CN365Common.Validation.Validators.CN365Template.ChannelTabs.Validate(PnPContext pnpContext, String channelId) in /home/vsts/work/1/s/CN365Common/Validation/Validators/CN365Template/ChannelTabs.cs:line 83

Based on the PnP model of **TeamChannelTab**, the Id is expected to be a Guid, but in our case we have multiple Channels where the Tab-Id seems to be an Integer.
Here the results from the Graph Request
![image](https://github.com/pnp/pnpcore/assets/89914175/c7ed4bb4-3d22-4385-b07e-3066c2d7bbb3)

Definition in PnP Model
![image](https://github.com/pnp/pnpcore/assets/89914175/20510116-098e-41da-a1ac-3352140c8dd5)

## Expected behavior

Teams Tabs can be loaded into PnP model even if the Tab-Id is not a Guid

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0
- **OS**: Linux 
- **SDK used in**: Azure Function
- **Framework**: .NET 6.0

### Additional context
This behavior seems to affect only older teams, newly created Teams always have use Guids for the Tab Ids
The above Team was created in April 2020.

**Comment by jansenbe** [comment]
Thanks for using PnP Core SDK @nicolaor and reporting this issue. The underlying used graph API indeed returns a string as id, I'll update this in the SDK (will be a small breaking change for folks using this, but will mention this in the release notes).
