### ISSUE TITLE
Documentation Issue - Working with folders / Property Bag

### ISSUE THREAD

**Issue by IllumiC** [pnp/pnpcore#1417]
In a rush.. but just a slight oversight I noticed in the documentation related to folders / property bag line 11.

`folder["myPropertyKey"] = "Some value";` should be changed to `folder.Properties["myPropertyKey"] = "Some value"; `

https://pnp.github.io/pnpcore/using-the-sdk/folders-intro.html#the-folder-property-bag

**Comment by jansenbe** [comment]
Thanks for reporting this @IllumiC , just updated the docs
