### ISSUE TITLE
GetPagesAsync not providing Page.Controls for SitePage library that has more than 5000 items

### ISSUE THREAD

**Issue by ahamedfazil** [pnp/pnpcore#1427]
## Category

- [x] Bug

## Describe the bug

I am using `GetPagesAsync()` [method ](https://pnp.github.io/pnpcore/using-the-sdk/pages-intro.html#load-all-the-pages-on-a-site) to get all the pages from a Site. Once I fetch the pages I loop through each item and get page `Controls`. When I fetch all items (where SitePages has more than 5k item) I get all the pages but Controls give 0 items. 

If I fetch the same site with page name like `GetPagesAsync('abc.aspx')` then I can see the controls. I noticed this issue only for the site which has more than 5k items

## Steps to reproduce
1. Fetch site pages which has more than 5k pages using `GetPagesAsync()` 
1. Loop through fetched pages and access page.Controls

## Expected behavior
GetPagesAsync method should return page items with page controls even for the SitePages which has more than 5k pages.

- **SDK version**: [PnP.Core 1.11.0 ]
- **OS**: [e.g. Windows 11]
- **SDK used in**: [Microsoft.NET.Sdk.Functions 4.3.0]
- **Framework**: [e.g. .NET v6 ]
- **Tooling**: [e.g. Visual Studio 2022]

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@ahamedfazil : I checked the code and don't see an obvious reason to explain what you see. The only reason I can come up with that the SharePoint API call is somehow not including the needed fields in your 5K+ case. To further validate that scenario, can you grab a Fiddler trace of a `GetPagesAsync` call on a 5K+ pages library and one one a smaller pages library and get them to me (bjansen@microsoft.com).

**Comment by jansenbe** [comment]
@ahamedfazil : checking if you can provide the debug information? Or is the issue not reproducible?

**Comment by jansenbe** [comment]
@ahamedfazil : closing this per no response. If this still is relevant then please provide the needed information.
