### ISSUE TITLE
Failed to field of type Term (Managed Metadata)

### ISSUE THREAD

**Issue by IllumiC** [pnp/pnpcore#1454]
## Category

- [x] Bug

## Describe the bug

I have a column of type managed metadata that is configured to accept any term within a specific term set in my site.
The column is used in various custom content types, of type (a) item, (b) document set, (c) document.

When creating an item via GUI, the term is applied successfully across all 4 content type scenarios.

When creating an item via Powershell PnP, the term is applied successfully across all 4 content type scenarios.

When creating an item via Core SDK PnP, I am experiencing difficulty.

### Item
- I make use of `IList.Items.AddAsync()` and supply a dictionary. For the entry related to the term column, I use GUID.toString() for formatting.
- The following exception occurs: **_SharePointRestServiceException: There was an exception while writing field MSD_Entity_Type. Verify you're using the correct InternalName value for the field you want to write to._**
- I have verified that the internal name is correct. Upon changing the field to an incorrect name purposefully, the error message changes to: **_Column 'MSD_Entity_Type2' does not exist. It may have been deleted by another user._**
- Upon removing the term column from the dictionary, the code works as expected, assigning values to all other columns.
### Document Set
- I make use of setting the keys of `IFolder.Properties`, followed by `IFolder.Properties.UpdateAsync()`.
- No exception occurs, however the term column is not populated. All other columns are populated.
### Document
- I have success by setting the keys of `IFile.ListItemAllFields`, followed by `IFile.ListItemAllFields.UpdateOverwriteVersionAsync()`.

### Item
1. Attempt to add a list item using `IList.Items.AddAsync()`
2. Receive the error **_SharePointRestServiceException: There was an exception while writing field MSD_Entity_Type. Verify you're using the correct InternalName value for the field you want to write to._**

### Document Set
1. Attempt to edit document set properties using `IFolder.Properties["Term_Internal_Name"]`, followed by `IFolder.Properties.UpdateAsync()`

## Expected behavior

The term field is populated upon edit.

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0
- **OS**: Windows 10
- **SDK used in**: Azure Web Job
- **Framework**: .NET Core 6.0
- **Tooling**: Visual Studio 2022
- **Additional details**: I have tried different versions of formatting the GUID, however since the format works with Document, I am led to believe that it is not a format issue. The GUIDs are being obtained dynamically via code, and I can ensure that the dictionary is populated with their GUID.

**Comment by jansenbe** [comment]
@IllumiC : did you check this https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#taxonomy-fields?

**Comment by IllumiC** [comment]
@jansenbe Thank you for your quick reply.
I solved my issue with the help of the article you suggested.

# Solution

### Item
- Making use of `IList.Items.AddAsync()`, pass key values of type (string, FieldTaxonomyValue).

### Document Set
- Do not use the keys of `IFolder.Properties[]`, and instead use the keys of `IFolder.ListItemAllFields[]` to pass a FieldTaxonomyValue
