### ISSUE TITLE
ServerRedirectedEmbedUrl and LinkingUrl Values Inconsistent or Incomplete

### ISSUE THREAD

**Issue by sguidos** [pnp/pnpcore#1455]
## Category

- [x] Bug

## Describe the bug

The ServerRedirectedEmbedUrl attribute returns a valid URL for files of type .PDF, .DOCX, .DOC, .PPTX, .PPT and .XLSX, but returns an empty string with .XLS (!) and other formats that are viewable in SharePoint by simply clicking on the file in the Documents view  (.TXT, .JPG, .PNG, .GIF, etc).

Ironically, the URL returned in the Parent.LinkingUrl is empty for .PDF but valid for .XLS file types.

## Steps to reproduce

```
            using (var context = await pnpContextFactory.CreateAsync(Program.SharePointSiteAuthConfigName)) // name must match the site configuration name created in Program.cs
            {
                var site = await context.Site.GetAsync(site => site.ServerRelativeUrl);
                string targetFolderName = site.ServerRelativeUrl + "/Shared%20Documents/" + txtNamedFolder.Text;
                IFolder namedFolder = context.Web.GetFolderByServerRelativeUrl(targetFolderName);

                IFile addedFile = await namedFolder.Files.AddAsync(Path.GetFileName(txtFileToUpload.Text),
                  System.IO.File.OpenRead(txtFileToUpload.Text), true);

                var addedFileProps = addedFile.ListItemAllFields;
                addedFileProps.Load(l => l.ServerRedirectedEmbedUrl, l => l.UniqueId, l => l.Parent);
                string embedUrl = addedFileProps.ServerRedirectedEmbedUrl;
                if ((string.IsNullOrEmpty(embedUrl)) && (addedFileProps.Parent != null) && (addedFileProps.Parent is IFile))
                {
                    IFile parentFile = (IFile)addedFileProps.Parent;
                    embedUrl = parentFile.LinkingUrl;
                }
                if (string.IsNullOrEmpty(embedUrl))
                {
                    MessageBox.Show($"Cannot Preview {Path.GetFileName(txtFileToUpload.Text)} in SharePoint", "Warning");
                }
                else
                {
                    DisplayDocumentInBrowser(embedUrl);
                }
            }
```

## Expected behavior

A valid ServerRedirectedEmbedUrl and LinkingUrl value is returned for all recognized file types.  Any file type that I can "click and preview" in the Documents list should return a valid ServerRedirectedEmbedUrl and LinkingUrl value.

## Environment details (*development & target environment*)

- **PnP.Core SDK version**: 1.12.0
- **PnP.Framework version** 1.15.0
- **OS**: Windows 10
- **SDK used in**: WinForms App
- **Framework**: .NET 6.0
- **Browser(s)**: Chrome 124.0.6367.63
- **Tooling**: Visual Studio Pro 2022

### Additional context

I am simply trying to let a user upload a file to our SharePoint Online instance and then Preview what was uploaded in their browser.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@sguidos : this is not an issue in PnP Core SDK as we simply return what the SharePoint API returns. Taking a quick peek at the internal SharePoint source I think this will only return a valid URL for the files that can be edited using Office online editors (Word, Excel, PowerPoint,...)

If you want to get a thumbnail it's best to use the respective GetThumnbails method (see https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#getting-thumbnails-for-a-file) or GetPreview method (https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#getting-an-embeddable-preview-url).

**Comment by sguidos** [comment]
GetPreview() is exactly what I was looking for, and is working with a wide variety of file types.  Thanks!
