### ISSUE TITLE
Visibility HiddenMembers and custom properties creating a Team Site

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1461]
## Category

- [x] Feature request

## Describe the feature

My feature request is that a Team Site with group also can have the visibility HiddenMembers instead of only public and private.

The enum already supports the value but the model needs to change I think for TeamSiteCreation because of the IsPublic property.

Also it would be handy if we could add custom properties to the TeamSiteWithGroup Creation model. Like a dictionary called additionalData to support as example Education Class groups/Teams. Then you need to add a custom property to the group before creating the Teams to it.

**Comment by jansenbe** [comment]
Closing as the PR is merged. Thanks @danielpastoor
