### ISSUE TITLE
CreateCopyJobs Deprecated

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1484]
I found this notification on the CreateCopyJob documentation and I was thinking does Pnp.Core use the new variant?

<img width="712" alt="image" src="https://github.com/pnp/pnpcore/assets/28786031/09dfb8bc-743a-44a8-98d0-a2adc332d5c2">

**Comment by jansenbe** [comment]
@danielpastoor : We use "CreateCopyJob**s**", it's "CreateCopyJob" that's deprecated (and should throw an error when you try to use it)

**Comment by danielpastoor** [comment]
Thank you for you quick answer. 

I do have an other question related to the "CreateCopyJobs".

Is there a blockage for moving the "General" directory when it is connected to a channel?

**Comment by jansenbe** [comment]
That could be as that directory is tied to the Teams files tab for the channel

**Comment by danielpastoor** [comment]
Thank you
