### ISSUE TITLE
Getting owshiddenversion field value via IList.Items.GetById

### ISSUE THREAD

**Issue by rpohomenko-bpa** [pnp/pnpcore#1486]
## Category

- [x] Feature request

## Describe the feature

Rest API does not allow to get a list item by id with **owshiddenversion** value by default

## Describe the solution you'd like

Is it possible to make the request  _/_api/web/lists('{list}')/items({id})?$select=*,owshiddenversion_ using PNP Core?

**Comment by jansenbe** [comment]
@rpohomenko-bpa : when you load All properties of the list item it's included.

![image](https://github.com/user-attachments/assets/56bf7910-c886-45a5-9c8a-b8351807acc1)

**Comment by jansenbe** [comment]
Closing per no reply, please re-open if still relevant @rpohomenko-bpa
