### ISSUE TITLE
[Feature] SharePoint page sections - collapsible sections

### ISSUE THREAD

**Issue by mkm17** [pnp/pnpcore#1497]
## Category

- [x] Feature request

## Describe the feature

Add collapsible options to SharePoint page sections.

## Additional context

Some time ago, I proposed extending the PnP.Powershell [Add-PnPPageSection](https://github.com/pnp/powershell/issues/4008) cmdlet to include collapsible section options.

I have reviewed the current [capabilities in PnP.Core](https://pnp.github.io/pnpcore/using-the-sdk/pages-intro.html#configuring-page-sections), and it appears that the existing code allows setting it up. However, the effect is not visible on the page.

During my tests, it seems that making the changes in [my branch](https://github.com/mkm17/pnpcore/tree/page_section_options) would be enough to achieve the desired effect.

I'm new to contributing to PnP.Core. Could you please guide me on what I should do next?
Have you encountered similar issues with collapsible sections?

Looking forward to receiving any tips.

**Comment by jansenbe** [comment]
@mkm17 : please submit your updates as a PR, I can then test and merge.

**Comment by jansenbe** [comment]
@mkm17 : as mentioned in your PR in my testing this just works. Anyhow, feel free to further discuss this via the still open PR.
