### ISSUE TITLE
Unable to get Author/Editor details.

### ISSUE THREAD

**Issue by FlorianLabranche** [pnp/pnpcore#1498]
## Category

- [x] Bug

## Describe the bug

When I try to access Author or Editor, inner properties are not loaded.

![image](https://github.com/user-attachments/assets/f408633f-ae8f-4689-898d-6b7da7b802cc)

## Steps to reproduce

Below code can be used to reproduce the error:
```
await list.LoadAsync(p => p.Items, p => p.Fields);
// grab first item
var firstItem = list.Items.AsRequested().FirstOrDefault();
if (firstItem != null)
{
    var author = firstItem.Values["Author"] as IFieldUserValue;
    // Accessing author.Principal here throw an exception.
    var principal = author.Principal;
}
```

## Expected behavior

Principal property of user should be loaded.

Maybe we have some additional step to do to load the properties. If you can show me the way to load the UserPrincipalName of the Author and editor, it would be great.

## Environment details (*development & target environment*)

- **SDK version**: 1.12.0
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 6

**Comment by jansenbe** [comment]
@FlorianLabranche : you can use `IWeb.GetUserByIdAsync` to load additional user details.

**Comment by FlorianLabranche** [comment]
@jansenbe that's what we did but we were hoping to do it in the same call.
Thanks for confirming the approach.
