### ISSUE TITLE
SetSiteCollectionAdmins adds first user in list as PrimarySiteCollectionAdmin

### ISSUE THREAD

**Issue by yesh-rajawat-robomq** [pnp/pnpcore#1501]
## Category

- [x] Bug

## Describe the bug
While adding list of user as site collection admin we found that first user in that list was being added as primary site collection administrator. What if i need to add them as secondary site collection admin and not primary.
 
![image](https://github.com/user-attachments/assets/429ddc45-7f95-4108-8beb-6f4bd55da5e4)
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/72572838-6df6-48cd-8a68-e8c1d2b4e7c0">

## Expected behavior
Only Add user of users as Secondary Site Collection Admin.
## Additional Information
We already have method to add user as Primary Site Collection Admin
![image](https://github.com/user-attachments/assets/4e377722-e2f8-4722-8a45-72d09d85c7d0)

## Environment details (*development & target 
 
- **SDK version**:["PnP.Core" Version="1.12.0", "PnP.Framework" Version="1.15.0", "Microsoft.Identity.Client" Version="4.56.0" ]
- **OS**: [MacOS 10.15.x]
- **SDK used in**: [Console App ]
- **Framework**: [ .NET Core 8.0]
- **Tooling**: [Intellij Rider]

**Comment by jansenbe** [comment]
@yesh-rajawat-robomq : you then first query the existing admins and ensure the current site collection primary admin is the first in the list, followed by the ones you need to add as secondary admins. I'm open for a PR that brings a specific feature to set secondary admins.

**Comment by jansenbe** [comment]
closing per no feedback and there's a workaround. Still open for a PR for a specific method to set secondary admins
