### ISSUE TITLE
Add parameter "SharingCapabilities" when creating new site/site collection

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#1505]
## Category

- [x] Feature request

## Describe the feature

Each site has a flag if the site can be shared externally or not (SharingCapabilities).
This can be set to Disabled, Existing Guests, New and existing guests in the Admin center.

It would be great if this parameter also existed in the SiteCreationOptions or TeamSiteWithoutGroupOptions interfaces to control weather new sites can be shared or not.
Currently there seems to be no option to update this flag.
For the Powershell-version this seems to work already:

https://github.com/pnp/powershell/issues/661

**Comment by jansenbe** [comment]
@web265p3 : PowerShell sets this after the site creation is done (see https://github.com/pnp/powershell/blob/dev/src/Commands/Admin/NewTenantSite.cs#L71-L82). You could do something similar with PnP Core SDK using the admin module (see https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#getting-and-setting-site-collection-properties).

**Comment by web265p3** [comment]
I found a solution that works now.
I am just using the REST-endpoint.

For this I also use the PnP.Core.SDK:

```

    public async Task SetSharingCapabilitiesOfSite(string siteId, Uri siteUrl, SharingCapability sharingCapability)
    {

        var body = @"{
                            ""__metadata"": {
                            ""type"": ""Microsoft.Online.SharePoint.TenantAdministration.SiteProperties""
                            },
                            ""SharingCapability"": " + (int)sharingCapability + @"
                         }";
        
        var headers = new Dictionary<string, string>()
        {
            { "X-HTTP-Method", "MERGE" },
            { "Content-Type", "application/json;odata=verbose" },
            { "accept", "application/json;odata=verbose" }
        };
        var apiRequest = new ApiRequest(HttpMethod.Post, ApiRequestType.SPORest, $"https://{your-org}-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.Tenant/Sites('{siteId}')", body, headers);
        apiRequest.HttpMethod = HttpMethod.Post;
        var ctx = await _pnPContextFactory.CreateAsync(siteUrl);
        var response = await ctx.Web.ExecuteRequestAsync(apiRequest);
    }
```
