### ISSUE TITLE
Cannot query Fields from a list with linq methods

### ISSUE THREAD

**Issue by rvhelden** [pnp/pnpcore#1512]
## Category

- [x] Bug

## Describe the bug

When trying to query on a field of a list using the method WhereAsync or FirstOrDefaultAsync it fails with the following message

`Expression x.Values.get_Item("ProjectNummer") is invalid. Only calls to methods String.Contains, String.StartsWith are supported`

## Steps to reproduce

Execute the following

```cs
var list = context.Web.Lists.GetByTitle("listProjecten");
var item = await list.Items.FirstOrDefaultAsync(x => x.Values["ProjectNummer"] == "130653004");
```

But the following works

```cs
var list = context.Web.Lists.GetByTitle("listProjecten");
var item = await list.Items.FirstOrDefaultAsync(x => (x as IProjectItem).ProjectNummer == "130653004");

interface IProjectItem 
{ 
   string ProjectNummer { get; } 
}
```

## Expected behavior

I think this should work when reading the source, because it checks if it is a transient dictionary, but when this is translated to a Expression `Values["ProjectNummer"]`, it is translated to a PropertyExpression and not a method call, resulting in the GetMember function to return the name of the member, which is in this case `Values` instead of going down the path of TransientDictionary

https://github.com/pnp/pnpcore/blob/36fe03d649056f5644183e5dc605d8a203ef4b97/src/sdk/PnP.Core/QueryModel/Query/DataModelQueryTranslator.cs#L344

## Screenshot of the resulting ExpressionTree

![image](https://github.com/user-attachments/assets/9441ff7b-ae0c-4fc0-8c06-708f670ebe99)

## Environment details (*development & target environment*)

- **SDK version**: 1.14.8-nightly
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**: .NET 8
- **Tooling**: Linqpad / Rider / VS

**Comment by SPWizard01** [comment]
Not sure if you found it but you basically have to convert it to to appropriate type first
```
var item = await list.Items.FirstOrDefaultAsync(x => (x.Values["ProjectNummer"] as string) == "130653004");
```

Also make sure you query proper internal name and type because it might be different.

**Comment by jansenbe** [comment]
Thanks for the details @SPWizard01, @rvhelden : can you check if that unblocks you?

**Comment by jansenbe** [comment]
Closing as there's an easy workaround available.

**Comment by rvhelden** [comment]
I will check tomorrow, if it does work, would a PR to let it work with the Values without a cast be welcome with maybe some documentation for the site?

**Comment by zbend** [comment]
I'm using folders but this is still happening for me . . 

benList.RootFolder.Folders.QueryProperties(x => x.ListItemAllFields, x => x.Name, x => x.Properties).Where(fd => (fd.Properties["ClientNumber"] as string) == "123456")
