### ISSUE TITLE
Unable to create a Quick Launch LABEL

### ISSUE THREAD

**Issue by metkhoo** [pnp/pnpcore#1513]
## Category

- [x] Bug

Cannot create a quick launch "LABEL" item when passing in an empty Url.  The method ALWAYS creates a Quick Launch LINK.

## Steps to reproduce

After getting a context
...
                        newQlNode = await context.Web.Navigation.QuickLaunch.AddAsync(new NavigationNodeOptions
                        {
                            Title = "My Label",
                            Url = string.Empty,
                        });

## Expected behavior

Expect this code to create a Quick Launch "LABEL" instead of a Quick Launch "LINK"

## Environment details (*development & target environment*)

- **SDK version**: 1.14.0
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**: .NET 8.0
- **Browser(s)**: Edge Version 128.0.2739.42 (Official build) (64-bit)
- **Tooling**: Visual Studio 2020 17.11
- **Additional details**:

**Comment by metkhoo** [comment]
**Found a workaround...** 
Set the url to 
http://linkless.header/
This wil then set the navigator item as a "LABEL" instead of creating a "LiNK"

**Comment by MrRCG5** [comment]
The "http://linkless.header/" only works in PowerShell NOT in the JSON Site Script.

**PowerShell:** 
`Add-PnPNavigationNode -Location "QuickLaunch" -Title "Nav Label" -Url "http://linkless.header/"`
The last '/' is required and it does not work without it.

**JSON does NOT work:**

```
{
      "verb" : "addNavLink",
      "url" : "http://linkless.header/", <-- The last '/' is required and it gets removed when template is applied.
      "displayName" : "Administration",
      "navComponent":"QuickLaunch",
      "isWebRelative": true
}
```
