### ISSUE TITLE
Cannot update web Title (Name)

### ISSUE THREAD

**Issue by EdAlexander** [pnp/pnpcore#1522]
## Category

- [x] Bug Updating a web title throws rest error, permission denied.  User can manually go to SharePoint admin center and update the site name, url, etc.

## Describe the bug

Cannot rename a site/web.  

## Steps to reproduce
`    var caseWeb = await context2.Web.GetAsync(w => w.Title, w => w.Description, w => w.Url, w => w.MasterUrl);

    if (caseWeb.Title != SelectedCase.caseName)
        {
            caseWeb.Title = SelectedCase.caseName;
            await caseWeb.UpdateAsync();
        }`

## Expected behavior

web title should be updated

- **SDK version**: PnPCore 1.14
- **OS**: Windows 11
- **SDK used in**: .netMaui
- **Framework**: .Net Framework 8
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
If the user in question is a tenant admin but does not have the proper permissions on the site collection to make the changes as a site user there will be a permission denied error. Using the admin api's indeed is the solution here.
