### ISSUE TITLE
'No service for type 'PnP.Core.Services.IPnPContextFactory' has been registered.' while creating sharepoint context

### ISSUE THREAD

**Issue by manjunathreddy1** [pnp/pnpcore#1526]
## Category

- [x] Bug

## Describe the bug

I'm trying to create SharePoint context using custom authentication provider for azure ad app authentication but getting error as 'No service for type 'PnP.Core.Services.IPnPContextFactory' has been registered.' while creating sharepoint context in code   var pnpContextFactory = host1.Services.GetRequiredService<IPnPContextFactory>();
         

## Steps to reproduce

1. Add the following code to .net8 console app
        public async Task GetData()
        {
            string clientId = "clientid";
            string tenantId = "tenantid";
            string clientSecret = "clientsecret";
            string sharepointSiteUrl = "siteurl";
            var host1 = Host.CreateDefaultBuilder()
 .ConfigureServices(async (context, services) =>
 {
     services.AddLogging();
     var accessToken = await GetAccessTokenAsync(clientId, clientSecret, tenantId);

     services.AddPnPCore(options =>
{
options.DefaultAuthenticationProvider = new CustomClientCredentialsProvider(accessToken);
});
 })
 .UseConsoleLifetime()
 .Build();

       
            var pnpContextFactory = host1.Services.GetRequiredService<IPnPContextFactory>();
        }
2.customauthentication provider code.
using Microsoft.Identity.Client;
using PnP.Core.Auth;
using PnP.Core.Services;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

public class CustomClientCredentialsProvider : IAuthenticationProvider
{
    private readonly string _clientId;
    private readonly string _tenantId;
    private readonly string _clientSecret;
    private const string MicrosoftGraphScope = "Sites.Read.All";
    private const string SharePointOnlineScope = "Sites.Read.All";
    private readonly string _accessToken;
    private string[] GetRelevantScopes(Uri resourceUri)
    {
        if (resourceUri.ToString() == "https://graph.microsoft.com")
        {
            return new[] { $"{resourceUri}/{MicrosoftGraphScope}" };
        }
        else
        {
            //string resource = $"{resourceUri.Scheme}://{resourceUri.DnsSafeHost}";
            //return new[] { $"{resource}/{SharePointOnlineScope}" };

            string resource = $"{resourceUri.Scheme}://{resourceUri.DnsSafeHost}";
            return new[] { $"{resource}/.default" };
        }
    }
    public CustomClientCredentialsProvider(string accessToken)
    {
        _accessToken = accessToken;
    }

    public static async Task<string> GetAccessTokenAsync(string clientId, string clientSecret, string tenantId)
    {
        var authority = $"https://login.microsoftonline.com/{tenantId}";
        var scope = new[] { "https://yourtenant.sharepoint.com/.default" };

        var confidentialClient = ConfidentialClientApplicationBuilder
            .Create(clientId)
            .WithClientSecret(clientSecret)
            .WithAuthority(new Uri(authority))
            .Build();

        var authResult = await confidentialClient.AcquireTokenForClient(scope).ExecuteAsync();
        return authResult.AccessToken;
    }

    public Task AuthenticateRequestAsync(Uri uri, HttpRequestMessage request)
    {
        // Add the Authorization header to the request
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _accessToken);
        return Task.CompletedTask;
    }

    // Authenticate the request by setting the Authorization header with the access token.
    public Task AuthenticateRequestAsync(HttpRequestMessage request)
    {
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _accessToken);
        return Task.CompletedTask;
    }

    // Retrieve the access token for the given scopes.
    public async Task<string> GetAccessTokenAsync(Uri uri, string[] scopes)
    {
        var app = ConfidentialClientApplicationBuilder.Create(_clientId)
            .WithClientSecret(_clientSecret)
            .WithAuthority(new Uri($"https://login.microsoftonline.com/{_tenantId}"))
            .Build();

        var result = await app.AcquireTokenForClient(scopes).ExecuteAsync();
        return result.AccessToken;
    }

    // Convenience method to retrieve the access token using default scopes.
    public async Task<string> GetAccessTokenAsync(Uri resource)
    {
        if (resource == null)
        {
            throw new ArgumentNullException(nameof(resource));
        }

        return await GetAccessTokenAsync(resource, GetRelevantScopes(resource));
    }
}

## Expected behavior

pnpContextFactory object is created

## Environment details (*development & target environment*)

- **SDK version**: [pnp core 1.14.0]

**Comment by jansenbe** [comment]
Hey @manjunathreddy1 ,

See https://github.com/pnp/pnpcore/blob/dev/samples/Demo.PersistentTokenCache/README.md for a sample where a custom authentication provider is used in a console app. Let me know if that helps

**Comment by jansenbe** [comment]
@manjunathreddy1 : did you manage to get things working based upon the sample?
