### ISSUE TITLE
Add `BaseType` to `SP.IList`

### ISSUE THREAD

**Issue by viceice** [pnp/pnpcore#1532]
## Category

- [x] Domain model extension

## Describe the domain model extension

Please add `BaseType` to `SP.IList`.

### Model

Model: IList
Properties: BaseType

### APIs

API : `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/baseType`

### Additional Information

https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms436057(v=office.14)

**Comment by jansenbe** [comment]
@viceice : just implemented this, please check the next nightly to use this property. I'm closing the issue now, but feel free to re-open in case you can't get it work.
