### ISSUE TITLE
PnP docs site upgrade

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#154]
## Category

- [x] Feature request

## Describe the feature

- Alignment of the website to the standard of the other PnP Sites
- Incorporation of the new branding logos
- Ensure accessible/responsive

On initial investigation, the other sites use a mkdocs/material ui skin, have seen a docfx material ui skin, will see how much would to align both.

**Comment by pkbullock** [comment]
pls assign to me

**Comment by jansenbe** [comment]
Thanks @pkbullock , nice work!
