### ISSUE TITLE
Missing Nuget Package PnP.Core.Auth

### ISSUE THREAD

**Issue by ahollandusc** [pnp/pnpcore#155]
## Category

- [x] Bug

## Describe the bug

Missing Nuget Package PnP.Core.Auth

Not sure if this is an issue with the build to nuget package manager or the doco needs correcting.

In [Getting started with the PnP Core SDK documentation](https://pnp.github.io/pnpcore/articles/consumer/readme.html#where-is-the-code)  
It links to [PnP.Core.Auth nuget package](https://www.nuget.org/packages/PnP.Core.Auth) 
This nuget package is missing (404 error) on nuget page.

## Steps to reproduce

1. Use browser to go to links in documentation as mentioned above
or
2. Use Package manager in visual studio
PM> Install-Package PnP.Core.Auth
Install-Package : Unable to find package 'PnP.Core.Auth'
At line:1 char:1
+ Install-Package PnP.Core.Auth
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPa 
   ckageCommand
 

## Expected behavior

The nuget package PnP.Core.Auth should exist

## Environment details (*development & target environment*)

- **SDK version**: 0.1.2009.77-preview2
- **OS**: Windows 10
- **SDK used in**: Azure Function V3
- **Framework**: .NET Core v3.1
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2019

### Additional context

Non

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Hi @ahollandusc , we've just coded the auth package and will indeed also publish this one as nuget package. Should be done by end of the week.

**Comment by jansenbe** [comment]
Hi @ahollandusc, 

I've done the work for this, nuget packages are available now:
![image](https://user-images.githubusercontent.com/7451219/94188817-34aefc80-feaa-11ea-9521-de15f7cf6dfe.png)

**Comment by ahollandusc** [comment]
Thanks Bert, that works 😊
You’re a champ!

**Comment by jansenbe** [comment]
Cool!

As this project is brand new (we've not yet made a ton of noise about it) you might still run into things. If so please provide feedback so that we can make this better. If feel like contributing to it that would be great as well, there are development opportunities but also documentation/sample options.

**Comment by jansenbe** [comment]
Closing this issue now.
