### ISSUE TITLE
Saving page causing duplicate page header

### ISSUE THREAD

**Issue by tom-daly** [pnp/pnpcore#1550]
## Category

- [x] Bug

## Describe the bug

All I want to do is save a page. If the page header was removed it will add it back. 

![image](https://github.com/user-attachments/assets/2997409b-2305-48cd-8b84-4320da48c72b)

![image](https://github.com/user-attachments/assets/df18db79-6d93-4272-bd63-e89a99f1622f)

## Steps to reproduce

I'm using PnP PowerShell 2.12.0 but the issue is in the .Save of the Page

1) Get a page: $page = Get-PnPPage -Identity "My-Title.aspx"
2) Save the page

Write-Host "Saving Page"
        $page.Save()
        $page.Publish("Content Updated by: $User")
        Write-Host "Saved Page"

Here I remove all the webparts + page header, add only 1 OOTB text editor, get the page, save then publish and the header will come right back.
https://github.com/user-attachments/assets/1d3c986c-4eb5-4d1e-bd3d-a60b748f09e6

Even stranger behavior is if I empty the page, save + publish it -  it will add the header back AND when you click edit the entire page is like the default home page.  

https://github.com/user-attachments/assets/f21295ad-1ccf-4741-bedd-debe93262e0f

## Expected behavior

I would expect the page header to be in the exact same status that it was before the .Save()

## Environment details (*development & target environment*)
- **SDK version**: PnP PowerShell 2.12.0 [the version that is tied with this] 
- **OS**: Windows 11
- **SDK used in**: PowerShell 7.0 terminal
- **Framework**: .NET Core
- **Browser(s)**: Chrome 
- **Tooling**: PowerShell 7.0
- **Additional details**: using the latest stable PowerShell 2.12.0

### Additional context

no additional details

*Thanks for your contribution! Sharing is caring.*

**Comment by nils-a** [comment]
Have you tried this in the nightly? Pages are (for me at least) very, very buggy since Rodmap feature 386904 has been active in the tenant.

**Comment by tom-daly** [comment]
I just tried the PnP.PowerShell nightly 2.12.23-nightly. It still puts the header back on if it was previously removed. 
I'm not sure how to tell what version of PnP.Core is in PnP.PowerShell

**Comment by jansenbe** [comment]
@tom-daly : I could reproduce your issue...it's related to the new page header model that SharePoint introduced

**Comment by tom-daly** [comment]
I just want to say thank you for fixing this!! highly appreciated
