### ISSUE TITLE
SiteUsers properties are not loaded if requested individually

### ISSUE THREAD

**Issue by GrubenPete** [pnp/pnpcore#1553]
## Category

- [x] Bug

## Describe the bug

While iterating SiteUsers and loading properties for each single User neither the expected requests are made, nor are the User objects populated with the retrieved data.

## Steps to reproduce

```c#
await _pnpContext.Web.SiteUsers.LoadAsync(user => user.Id); // --> 1, 2, 3

foreach (var pnpUser in _pnpContext.Web.SiteUsers.AsRequested()) {
    await pnpUser.LoadAsync(user => user.LoginName);
    Console.WriteLine(pnpUser.LoginName); // --> Exception
}
```

results in:

```jsonc
//foreach (var pnpUser in _pnpContext.Web.SiteUsers.AsRequested()) {
//    await pnpUser.LoadAsync(user => user.LoginName);
//}

//results in 3 times same request for whole SiteUsers collection
_api/Web/SiteUsers?$select=Id%2cLoginName
_api/Web/SiteUsers?$select=Id%2cLoginName 
_api/Web/SiteUsers?$select=Id%2cLoginName 

//and 3 times same result
--> {
  "value": [
    { "Id": 1, "LoginName": "..."},
    { "Id": 2, "LoginName": "..."},
    { "Id": 3, "LoginName": "..."}
  ]
}
```

```jsonc
//Console.WriteLine(pnpUser.LoginName);
PnP.Core.ClientException: Property LoginName was not yet loaded
```

## Expected behavior

3 distinct requests are made:
```jsonc
//foreach (var pnpUser in _pnpContext.Web.SiteUsers.AsRequested()) {
//    await pnpUser.LoadAsync(user => user.LoginName);
//}

_api/Web/siteusers/getbyid(1)?$select=Id%2cLoginName --> { "Id": 1, "LoginName": "..."}
_api/Web/siteusers/getbyid(2)?$select=Id%2cLoginName --> { "Id": 2, "LoginName": "..."}
_api/Web/siteusers/getbyid(3)?$select=Id%2cLoginName --> { "Id": 3, "LoginName": "..."}
```

property is loaded:
```jsonc
//Console.WriteLine(pnpUser.LoginName);
```

also the expected behavior can be verified with SiteGroups
```c#
await _pnpContext.Web.SiteGroups.LoadAsync(group => group.Id);

foreach (var pnpGroup in _pnpContext.Web.SiteGroups.AsRequested()) {
    await pnpGroup.LoadAsync(group => group.LoginName);
    Console.WriteLine(pnpGroup.LoginName);
}
```

## Environment details (*development & target environment*)

- **SDK version**: 1.14.0
- **OS**: Windows 11
- **SDK used in**:  ASP.NET Core Web API 
- **Framework**: .Net 8
- **Tooling**: Visual Studio 2022

### Additional context

-

**Comment by jansenbe** [comment]
@GrubenPete : that's indeed a bug, the REST query issued when loading the user property is not correct. That being said, it's much more efficient to just load the extra properties in the initial request. Below line loads all you need with a single roundtrip:

```csharp
await context.Web.SiteUsers.LoadAsync(user => user.Id, user => user.LoginName);
```

**Comment by jansenbe** [comment]
@GrubenPete : I've also fixed the issue, will be part of the next nightly build. I however strongly recommend to use the approach I suggested as it's easier and much faster
