### ISSUE TITLE
[BUG] Set-PnPPage translation a full width section page

### ISSUE THREAD

**Issue by TycoMoon** [pnp/pnpcore#1554]
## Issue Reference

I am experiencing an issue related to the function **Set-PnPPage** for translation with a full width section page. For more details, please refer to my existing issue:

- [GitHub Issue #4382](https://github.com/pnp/powershell/issues/4382)

### Code Reference

The specific part of the code that seems to have the issue is located here:

- [PageWebPart.cs - Line 614](https://github.com/pnp/pnpcore/blob/5eccb981a9773fb9a8104a8ee4c18ebae99d2102/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/PageWebPart.cs#L614)

**Comment by jansenbe** [comment]
@TycoMoon : can you verify the properties of the image web part on the source page you're translating from? You can pull the page json from the CanvasContent1 field of the page in the sitepages library.

**Comment by TycoMoon** [comment]
Same error in a different context:
```powershell
     $null = set-PnPPage -Identity $NamePage -Publish
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed
```
In this case, it is the default TopicHome.aspx page from the Default Template, which uses the full-width hero web part when creating a site, causing this bug.

**Comment by JamesDerrickHH** [comment]
Thanks to jackpoz for linking my issue in.
Same error for me but when using a different cmdlet
If the page has a full-width section with anything other than a banner webpart, I can't add a new section programmatically

**Comment by Lou-i3** [comment]
Hello, 
Any news on this issue? I'm having the same problem. 
Thanks a lot.

**Comment by jansenbe** [comment]
@Lou-i3 / @JamesDerrickHH / @TycoMoon : I added support to always set the isFullWidth property to true for image, hero, banner and countdown web parts in case it was not specified as part of the markup. This hopefully will already partly help with some of the issues mentioned in this thread

**Comment by jansenbe** [comment]
@jackpoz : with this, and other recent changes, I could successfully add sections to pages that already have a full width section. For pages in team sites there's only one full width section allowed that only can contain the banner web part, for pages in communication sites there can be multiple fullwidth sections with banner, image, hero and countdown as first party web parts + optionally third-party ones as well. In all cases I could add additional sections in my testing from PnP Core SDK. 

I'll now close this issue, please raise a new one in case things still don't work whenever this change gets included into PnP PS, which should happen automatically
