### ISSUE TITLE
ListItem.Versions not returning all versions, only latest version

### ISSUE THREAD

**Issue by nozzrangar** [pnp/pnpcore#1556]
## Category

- [x] Bug

## Describe the bug

When trying to get all the versions on a list item I only get the latest version, not all the versions of the list item.
I get the list item by id with query properties li => li.All, li => li.Versions to get all properties and versions.

## Steps to reproduce

I get the list and list item and load versions.
```c#
list = await context.Web.Lists.GetByIdAsync(listId,
    l => l.Title,
    l => l.RootFolder.QueryProperties(
        lr => lr.ServerRelativeUrl),
    l => l.Fields.QueryProperties(
        lf => lf.InternalName,
        lf => lf.FieldTypeKind,
        lf => lf.TypeAsString,
        lf => lf.Title));

listItem = await list.Items.GetByIdAsync(itemId,
    li => li.All,
    li => li.Versions);

var x = listItem.Versions.AsRequested();
``` 
x only includes 1 version, which is the newest version of the item. All the older versions are missing.
Here is the output from x:
![image](https://github.com/user-attachments/assets/2c0145a9-6f1a-41c0-ae45-cc9a6db91e7d)

## Expected behavior

![241015-210__msedge](https://github.com/user-attachments/assets/ee0f7ab6-3465-4b75-a45b-032205b20ace)

I expect all the versions of the list item (see versions above) to be returned when loading listitem.Versions.AsRequested(); like the documentation says.
https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#getting-list-item-versions

## Environment details (*development & target environment*)

- **SDK version**: 1.14.0
- **OS**: Windows 11
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 8
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022
- **Additional details**: N/A

### Additional context

I'm pretty sure this is a new issue. I think this has worked before but I'm going through logs in my application to see if I can see if it was working before and when it stopped working.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@nozzrangar : I can reproduce this by running our test case as "live"...so this clearly used to work but now isn't anymore. Did this work for you before and recently stopped working or are you just now trying this?

**Comment by jansenbe** [comment]
Thanks @nozzrangar : when you say recently, can you be more precise?


Doing some checking on the query I notice that in case of expanding versions the $top statement is respected on the expand and therefore only the last version is returned

`_api/web/lists(guid'8bcad63f-db6f-4a54-99e6-511bd1883a66')/items?$select=Id%2cVersions%2c*&$expand=Versions&$filter=Id+eq+1&$top=1`

While doing a similar approach on expanding items on the list collection still works as expected and returns all items

`_api/web/lists?$select=Id%2cItems%2c*&$expand=Items&$filter=Id+eq+guid'e083c5b2-9a36-48db-86ec-9a697be704ea'&$top=1`

**Comment by nozzrangar** [comment]
@jansenbe Looking quickly through my logs I can see it is working normally on 16/09/2024 but then I see errors coming because of this starting on 18/09/2024.

The error is coming because in my code I'm checking if the version label of the current version is greater than 1.0 and if it is I assume there is a collection of versions I can iterate through, that's where my error shows up

Looking at the path of the queries in my logs they look the same on the 16th and on the 18th. 

The path on the 16th where I get the collection of versions

`_api/web/lists(guid'ef17ced5-440c-4dc9-8d44-c5c53ff1e9a7')/items?$select=Id%2cVersions%2c*&$expand=Versions&$filter=Id+eq+11&$top=1`

And here is the path on the 18th when it has stopped working

`_api/web/lists(guid'ef17ced5-440c-4dc9-8d44-c5c53ff1e9a7')/items?$select=Id%2cVersions%2c*&$expand=Versions&$filter=Id+eq+11&$top=1`

**Comment by jansenbe** [comment]
@nozzrangar : I've been digging into this and there was a change done that makes $top be used by the Versions expand...I'm checking with the team on the why as this now is a deviation on how REST works. In the short term you should be able to load the versions one by one via PnP Core SDK, there's a slight perf hit as you need to do a roundtrip per item you're loading versions for.

Depending on the outcome of my talks with engineering I'll either try to fix this in PnP Core SDK or engineering will implement this change differently.

**Comment by jansenbe** [comment]
@nozzrangar : we've reverted the change, in my testing the previous behavior now works again. Can you check from your side?

**Comment by nozzrangar** [comment]
@jansenbe : I can confirm that I'm now getting all the versions, not just the newest one
`_api/web/lists(guid'f5cabc7d-0301-42cb-918f-c11362562985')/items?$select=Id%2cVersions%2c*&$expand=Versions&$filter=Id+eq+5&$top=1`

![image](https://github.com/user-attachments/assets/6622cd09-6d9a-4574-a9ce-2adf5019a4b5)

**Comment by jansenbe** [comment]
Closing the issue now, thanks again for bringing this to our attention!
