### ISSUE TITLE
Upgrade System.Text.Json to version 8.0.5

### ISSUE THREAD

**Issue by ZiLin3** [pnp/pnpcore#1580]
## Category

- [x] Feature request

## Describe the feature

We have identified a vulnerability in PnP.Core.Admin 1.14.0, which uses System.Text.Json 8.0.4. Is there a plan to upgrade to System.Text.Json 8.0.5?

![image](https://github.com/user-attachments/assets/dea8954a-b272-4aca-a80a-f8ecde304667)

## Describe the solution you'd like
Upgrade the version to 8.0.5 for System.Text.Json

**Comment by gautamdsheth** [comment]
hi @ZiLin3 , we have updated this dependency in the latest nightly releases.
It will be part of the next major release for sure. We dont have ETA for that, but you can use the nightly releases which contains the updated dependencies.
