### ISSUE TITLE
IRetryEvent.WaitTime will be incorrect when the delay time is greater than 59 seconds

### ISSUE THREAD

**Issue by Amwins-Vault-Boy** [pnp/pnpcore#1590]
## Category

- [x] Bug

## Describe the bug

When the calculated WaitTime exceeds 59 seconds this line will only return the seconds component of the `TimeSpan`:
https://github.com/pnp/pnpcore/blob/2ad6f2b0b57dc1f7b572abb7f09931211ca4c86b/src/sdk/PnP.Core/Services/Core/Http/RetryHandlerBase.cs#L165

For example, if the calculated delay time `TimeSpan` is 120 then the `Seconds` property value will be zero.

Using the `TotalSeconds` property instead will fix this issue.

## Steps to reproduce

1. In the `AddPnPCore` configuration set the delay time for either `SharePointRest` or `MicrosoftGraph` to a value greater than 59 seconds, e.g. `options.HttpRequests.SharePointRest.DelayInSeconds = 60;`.
2. Add the [EventHub ](https://pnp.github.io/pnpcore/using-the-sdk/basics-eventhub.html?q=EventHub) handler to capture the retry event and log the value of the `WaitTime` property.
3. Execute a request that will be handled by the retry mechanism. 
4. Examine the log entry from the EventHub execution.

## Expected behavior

The value of the `IRetryEvent.WaitTime` property in the EventHub ought to be `120`. The actual value is `0`.

## Environment details (*development & target environment*)

- **SDK version**: [1.14.0 ]
- **OS**: [Windows 10]
- **SDK used in**: [ASP.Net WebApi app]
- **Framework**: [.NET Core v8.0 ]
- **Browser(s)**: [Chromium Edge v79]
- **Tooling**: [VS Code]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Nice catch @Amwins-Vault-Boy ! I'll fix this asap

**Comment by jansenbe** [comment]
And fixed.
