### ISSUE TITLE
Use CSOM to implement IRM settings update

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#169]
## Category

- [x] Feature request

## Describe the feature

IRM can be enabled using REST and List and File IRM settings can be retrieved, however one cannot update IRM settings via REST (so it seems). Do more research, but most likely using CSOM is required here.

**Comment by jansenbe** [comment]
Verify if IRM settings are something we want to proceed with...moving to backlog

**Comment by DaleyKD** [comment]
+1, please.  We would at least like to be able to enable IRM.

**Comment by DaleyKD** [comment]
EDIT: Whoops, IRM is "Information Rights Management".  I thought it was "In Place Records Management."

Never mind.  I don't need IRM today. :)

**Comment by jansenbe** [comment]
https://docs.microsoft.com/en-us/archive/blogs/fromthefield/office-365-automating-the-configuration-of-information-rights-management-irm-using-csom shows this via CSOM.

**Comment by jansenbe** [comment]
Closing this issue as IRM is legacy...no point anymore in spending time to add CSOM based support.
