### ISSUE TITLE
DefaultConfiguration is required from preview 3, but the WPF sample code is still dummy

### ISSUE THREAD

**Issue by RYO-4947123** [pnp/pnpcore#181]
## Describe

After updating the version to the latest
When I run the WPF demo, I get the following exception:

```
Unhandled exception. PnP.Core.ClientError
PnP.Core.ClientException: Invalid configuration name 'CredentialManager' for IAuthenticationProvider creation!
   at PnP.Core.Auth.Services.AuthenticationProviderFactory.Create(String name)
   at PnP.Core.Auth.Services.AuthenticationProviderFactory.CreateDefault()
   at PnP.Core.Auth.Services.Builder.Configuration.AuthenticationProvidersOptionsConfigurator.Configure(PnPCoreOptions options)
...
```

The cause is
DefaultConfiguration is required from preview 3, but the WPF sample code is still dummy(`CredentialManager`).

I changed it to `InteractiveFlow` and it worked.

## Environment details (*development & target environment*)

- **SDK version**: 0.3.0-preview3 or later
- **SDK used in**: DEMO.WPF

I'm translating English, so I'm sorry if I make a mistake.

**Comment by jansenbe** [comment]
Thanks for reporting this @RYO-4947123 . We'll check the samples and update them

**Comment by jansenbe** [comment]
The DefaultConfiguration indeed was wrong for this sample. This previously worked as we did not read the DefaultConfiguration, but we fixed that recently, which made this issue appear. Issue has been fixed, thanks for informing us.
