### ISSUE TITLE
Get List by URL 

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#184]
## Category

- [x] Feature request

## Describe the feature

Usually we access the lists via URL because the title ( pnpContext.Web.Lists.GetByTitleAsync() ) can always change. The **GetList** method on the Web object is missing.

## Describe the solution you'd like
In CSOM Core I use actually following Code 
```csharp
Web web = clientContext.Web;
clientContext.Load(web);
clientContext.ExecuteQuery();
var webUrl = web.ServerRelativeUrl;
var listUrl = webUrl + "/Lists/tenders/";
var list = web.GetList(listUrl);
```

## Additional context

Is there a possibility to use CSOM in PNP.Core until PNP.Core is feature complete?

**Comment by jansenbe** [comment]
Thanks for reporting this @raclettierer, getting by URL indeed should be added. We'll add it the coming days and given we have nightly nuget releases you'll get the feature the day after. I'll update this issue once done.

**Comment by jansenbe** [comment]
@raclettierer : we've implemented a GetByServerRelativeUrl method as shown in below test case. This method will show up in the updated nuget package tomorrow, so just bump to the latest nuget and give it a try. Also keep letting us know what things you're missing.

![image](https://user-images.githubusercontent.com/7451219/95444987-be58d280-095e-11eb-8a2b-61ee4478f1a4.png)

**Comment by jansenbe** [comment]
Hi @raclettierer , If you can confirm the GetListByServerRelativeUrl works for you then feel free to close this issue.

**Comment by raclettierer** [comment]
Works well, I tested it in an Azure Function

**Comment by raclettierer** [comment]
@jansenbe I think is cleaner, if we can pass only the relative url of the web. Because you can't access other lists outside of the current web
var list = ctx.Web.Lists.GetByRelativeUrl("/Lists/tenders/");
