### ISSUE TITLE
SecurityExtensions missing

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#185]
## Category

- [x] Feature request

## Describe the feature

For many applications or processes we need to grant or remove permissions on different levels (List or Listitem).  In the past, I use the AddPermissionLevelToGroup or AddPermissionLevelToUser method from SecurityExtensions.

Are this expansion already planned?

## Describe the solution you'd like

Code: https://github.com/pnp/PnP-Sites-Core/blob/013eae4dffbed44af5e9c7610cb6fb53f855bf9b/Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs

**Comment by jansenbe** [comment]
Linked to #213

**Comment by jansenbe** [comment]
Implemented
