### ISSUE TITLE
Want to connect to multiple SharePoint sites

### ISSUE THREAD

**Issue by RYO-4947123** [pnp/pnpcore#187]
## Category

- [x] Bug

## Describe the bug

I want to access multiple SharePoint sites, but it stops after the second authentication.

## Steps to reproduce

I made the following settings to access multiple SharePoint sites.

Based on DEMO.WPF.

appsettings.js
```
"Sites": {
      "Site_A": {
        "SiteUrl": "https://my.sharepoint.com/sites/msteams_a",
        "AuthenticationProviderName": "InteractiveFlow"
      },
      "Site_B": {
        "SiteUrl": "https://my.sharepoint.com/sites/msteams_b",
        "AuthenticationProviderName": "InteractiveFlow"
      }
    }
```

MainWindow.xaml.cs
```
internal async Task SiteInfoAsync()
{
    using (var context = await pnpContextFactory.CreateAsync("Site_A"))
    {
        var web = await context.Web.GetAsync(w => w.Title, w => w.Description, w => w.MasterUrl);
        ~
    }
    using (var context = await pnpContextFactory.CreateAsync("Site_B"))
    {
        var web = await context.Web.GetAsync(w => w.Title, w => w.Description, w => w.MasterUrl);
        ~
    }
}
```

A deadlock occurs after the second authentication.

## Expected behavior

If possible, I would like to authenticate once and access multiple SharePonit sites.

## Environment details (*development & target environment*)

- **SDK version**: 0.3.6-preview3
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET 5
- **Browser(s)**: Microsoft Edge 85.0.564.70
- **Tooling**: VS Code

I'm translating English, so I'm sorry if I make a mistake.

**Comment by jansenbe** [comment]
Thanks for reporting this @RYO-4947123 . I've checked our authentication handler code and we accidently left a few GetAwaiter().GetResult() calls in there which results in a blocking thread. These issues have been fixed and I've tested your scenario with the latest bits and things do work as expected. 

There will be a nightly nuget package update, so if you tomorrow update to the latest nuget then this should work. I might even release an intermediate nuget during the day, and then I'll let you know in this thread.

**Comment by RYO-4947123** [comment]
The deadlock has been resolved. Thank you.
However, I have to log in multiple times for each site. Is it possible to log in only once?

**Comment by jansenbe** [comment]
You don't need to re-authenticate each time again, as that's quite inconvenient when using interactive auth. Once you've authenticated to one site you can simply "clone" that PnPContext to other PnPContext instances for other sites as shown in below snippet. So you could grab a context once at application start and then keep that to clone new contexts from for the sites you want to access.

![image](https://user-images.githubusercontent.com/7451219/95561483-181ed280-0a1b-11eb-99e6-00c287e76e2b.png)

**Comment by RYO-4947123** [comment]
"InteractiveFlow" in appsettings.js is used in `Create` method from `AuthenticationProviderFactory` class .
Is it possible to cache the provider generated by this method?
If it is generated from the same parameter, you will get the same result.
I think this will result in one authentication.
If you dare to separate the authentication, you can define it as "AnotherInteractiveFlow".

I'm sorry if I made a mistake.

**Comment by jansenbe** [comment]
When you use Clone() we'll just take over the AuthenticationProvider from the source PnPContext,

**Comment by RYO-4947123** [comment]
I was able to confirm that the desired thing can be achieved with Clone().
However, I think that there is a problem that the setting is not completed in appsettings.js and the URI appears in the source.

**Comment by jansenbe** [comment]
You can get the configuration information yourself as shown below, but I'll also add an overload to the Clone method that takes a configuration instead of an Uri, think that's a good feature to have.

![image](https://user-images.githubusercontent.com/7451219/95608941-30641100-0a5e-11eb-8db6-830e53d9fb49.png)

**Comment by jansenbe** [comment]
Tomorrow (after nightly nuget update) you can do Clone("DemoSite2") on the PnPContext: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Services/Core/PnPContext.cs#L373

**Comment by RYO-4947123** [comment]
I think adding an overload to the Clone method is the best idea to reduce the impact.
I don't want to put you in trouble, so I'm wondering if that's okay.
However, there is a concern that the client code will be dirty, such as extra nesting of using, and if you want to access another site for each event, you will get a useless context first.
Structurally in the appsettings, it seemed possible to share only the AuthenticationProvider.

**Comment by jansenbe** [comment]
What about then using the CreateAsync overload on the context factory that takes in an authentication provider:

![image](https://user-images.githubusercontent.com/7451219/95612352-8edfbe00-0a63-11eb-9e61-3932335a32ea.png)

**Comment by RYO-4947123** [comment]
Thank you for your quick suggestion despite your busy schedule.
I think the ability to share AuthenticationProvider is very good.

`using (var context2 = await pnpContextFactory.CreateAsync("DemoSite2", authProvider)`
Now you don't even need siteConfing.

If i get AuthenticationProvider for the first time, i can save it myself and refer to it from the next time.
It's a compromise between impact and convenience.
Ideally, I would like to get the context with the AuthenticationProvider already shared.
(DemoSite2 is acquired in the shared state if it has the same AuthenticationProviderName as DemoSite in appsettings.)

**Comment by jansenbe** [comment]
ok, seems you've a solution. Let's close this issue. Please create new issues for the other things you encounter :-)
