### ISSUE TITLE
If the AuthenticationProviderName is the same, I want to share the AuthenticationProvider

### ISSUE THREAD

**Issue by RYO-4947123** [pnp/pnpcore#189]
## Category

- [x] Feature request

## Describe the feature

Currently, even if the AuthenticationProviderName of appsettings.json is the same, AuthenticationProvider refers to another instance.
In the following case, SiteA and SiteB have the same "InteractiveFlow" but refer to different AuthenticationProvider instances.

appsettings.json
```
"Credentials": {
    ~
    "InteractiveFlow": {
        "ClientId": "b87659ce-1c11-440b-812b-0b35217d9e83",
        "TenantId": "b8765c9e-30c7-473a-83bc-d907df44a26e",
        "Interactive": {
            "RedirectUri": "http://localhost"
        }
    }
},
"Sites": {
    "Site_A": {
        "SiteUrl": "https://contoso.sharepoint.com/sites/siteA",
        "AuthenticationProviderName": "InteractiveFlow"
    },
    "Site_B": {
        "SiteUrl": "https://contoso.sharepoint.com/sites/siteB",
        "AuthenticationProviderName": "InteractiveFlow"
    }
}
```

If the AuthenticationProviderName is the same, the initialization parameters in the Credentials are also the same and should be instances in the same state.
The problem is that because the instance is different, the information logged in with SiteA is not carried over to SiteB, and you need to login again.
Of course, since the ClientId and TenantID are the same, the same authentication will be performed.

## Describe the solution you'd like

If the AuthenticationProviderName is the same, I want to share the AuthenticationProvider.

Even if you execute the following code, it will be possible to process with one login.
Also, you can login once regardless of the execution order of Event1 and Event2.

```
async Task Event1()
{
    using (var context = await pnpContextFactory.CreateAsync("Site_A"))
    {
        var web = await context.Web.GetAsync(w => w.Title, w => w.Description, w => w.MasterUrl);
        ~
    }
    using (var context = await pnpContextFactory.CreateAsync("Site_B"))
    {
        var web = await context.Web.GetAsync(w => w.Title, w => w.Description, w => w.MasterUrl);
        ~
    }
}
async Task Event2()
{
    using (var context = await pnpContextFactory.CreateAsync("Site_B"))
    {
        var web = await context.Web.GetAsync(w => w.Title, w => w.Description, w => w.MasterUrl);
        ~
    }
}
```

## Additional context

AuthenticationProviderName is used in Create method from AuthenticationProviderFactory class .
How about adding a method like CreateIfAbsent instead of Create and caching it to return the same instance the next time the same name comes in?

**Comment by RYO-4947123** [comment]
I'm sorry. CreateIfAbsent was a silly idea.
It's weird to cache each implementation.
You should control the initialization side of PnPCoreOptions.

How about modifying it as follows?

Configure() method from AuthenticationProvidersOptionsConfigurator class
```
public void Configure(PnPCoreOptions options)
{
    if (options == null)
    {
        throw new ArgumentNullException(nameof(options));
    }

    var providerCache = new Dictionary<string, IAuthenticationProvider>();
    providerCache.Add(
        authenticationOptions.Credentials.DefaultConfiguration,
        authenticationProviderFactory.CreateDefault());

    // For each site configuration we create the configured Authentication Provider
    //foreach (var (siteKey, siteValue) in authenticationOptions.Sites)
    foreach (var siteOption in authenticationOptions.Sites)
    {
        var siteKey = siteOption.Key;
        var siteValue = siteOption.Value;

        // We use the default provider and configuration if a specific configuration is missing
        if (string.IsNullOrEmpty(siteValue.AuthenticationProviderName))
        {
            options.Sites[siteKey].AuthenticationProvider =
                providerCache[authenticationOptions.Credentials.DefaultConfiguration];
        }
        // We use the cache provider
        else if (providerCache.ContainsKey(siteValue.AuthenticationProviderName))
        {
            options.Sites[siteKey].AuthenticationProvider = providerCache[siteValue.AuthenticationProviderName];
        }
        // We use the configuration provided by name, if any
        else
        {
            // and we set it into its settings
            var provider = authenticationProviderFactory.Create(siteValue.AuthenticationProviderName);
            options.Sites[siteKey].AuthenticationProvider = provider;
            providerCache.Add(siteValue.AuthenticationProviderName, provider);
        }
    }

    // Configure the default IAuthenticationProvider instance
    options.DefaultAuthenticationProvider = providerCache[authenticationOptions.Credentials.DefaultConfiguration];;
}
```

**Comment by jansenbe** [comment]
@PaoloPia : what do you think about "reusing" the IAuthenticationProvider across multiple configurations if the name is the same? Given the settings belong to the authentication provider I do not see anything bad with doing this, but wanted your opinion as well

**Comment by ypcode** [comment]
IMHO it might lead to "static instances" of services which we probably don't want to enable by default for all providers. But definitely in the case of interactive auth flow, it should probably be shared for the application to prevent the need to reauth multiple times

**Comment by PaoloPia** [comment]
Hi,
I completely understand the need. At the same time, we need to think carefully about the scope of the authentication provider. If you want to share the same Authentication Provider across multiple instances of PnPContext you can already do that. You simply need to create the Authentication Provider in code and assign it to the _AuthenticationProvider_ property of the site in the _PnPCoreOptions_ when you invoke _services.AddPnPCore_. Something like:


```csharp
    // Add the PnP Core SDK services
    services.AddPnPCore(options => {

        options.DefaultAuthenticationProvider = authenticationProvider;

        options.Sites.Add("SiteA",
            new PnP.Core.Services.Builder.Configuration.PnPCoreSiteOptions
            {
                SiteUrl = customSettings.DemoSiteUrl,
                AuthenticationProvider = authenticationProvider
            });
        options.Sites.Add("SiteB",
            new PnP.Core.Services.Builder.Configuration.PnPCoreSiteOptions
            {
                SiteUrl = customSettings.DemoSiteUrl,
                AuthenticationProvider = authenticationProvider
            });
    });
})

```

In the previous code excerpt, the _authenticationProvider_ variable is an instance of your preferred Authentication Provider (for example the InteractiveAuthenticationProvider).
What we do, when we create instances based on the config file, is to guarantee that every single site will be "isolated" from any other, to preserve the consistency of scopes and avoid concurrency issues.
Of course, we can think about changing this default behavior.

**Comment by ypcode** [comment]
@PaoloPia I think we could have a `AddSharedPnPCoreAuthenticationProvider<TProvider>()` 
This would register the auth provider as singleton.
That would make sense for Console, WPF or Blazor apps, but definitely should not be the default to prevent issues in ASP.NET, Azure Functions that would be very common use cases and should have by default isolated scopes, And Most likely those won't have interactive auth.

**Comment by RYO-4947123** [comment]
In the case of ASP.NET and Azure Functions, you cannot simply share the AuthenticationProvider, and you need an instance for each user (session).
Is my perception correct?
I thought it was better not to share by default.
I want you to be able to specify sharing arbitrarily instead.
By the way, the fact that AuthenticationProvider is ʻAddTransient` in ASP.NET seems to have another problem of authenticating multiple times.

**Comment by ypcode** [comment]
Hello @RYO-4947123 ,

You're correct; Shared (static) scope is something that should ideally be avoided by default and used only on very specific cases. I think interactive auth in these cases of client apps (WPF, Console,...) is such a case. So allowing to change the scope in config is probably something we could do. However we aim for the SDK to be really easy to use so, IMHO, we probably don't want to create config overhead for those particular cases where config should be tweaked. 

Probably a special config builder is necessary for those cases (console, wpf,...) and then guidance for tweaking config in other more particular cases

What do you think @jansenbe @PaoloPia ?

**Comment by jansenbe** [comment]
There are a couple of workarounds for in case folks want to ensure the same IAuthenticationManager instance is used:
- Create the IAuthenticationManager yourselve and then pass that into the PnPContextFactory
- Use the Clone() method on an existing PnPContext

Not sure if we already at this point need to do additional work for this, I'm more in favor for waiting and seeing if there's more demand.

**Comment by jansenbe** [comment]
Thanks for your feedback @RYO-4947123 , it resulted in a good discussion about this feature. For now we think the offered workarounds are sufficient, so I'll be closing this issue. Keep the feedback coming!
