### ISSUE TITLE
SharePoint Add-in Auth context

### ISSUE THREAD

**Issue by tbithell** [pnp/pnpcore#194]
## Auth

- [x] Feature request

## Describe the feature

> Could be I'm missing it, but I'm not seeing a way to use an Add-in like we can with the framework or pnp site core library.  

## Describe the solution you'd like

> I'd like the same functionality that is in Framework for use of the add-in auth context to be in pnp core sdk 

## Additional context

> Because MS hasn't made the graph auth more granular, I can't use Graph in the app context.  I'm certain I'm not the only one with a security team who doesn't want auth to be to all site collections or none.  I realize that isn't going to be solved here, but it'd be ideal if I could provide all of the values needed in order for the library to make the determination which api it'll use.  Maybe a graph option value that indicates graph calls can only be done in the user's context and any app only context calls would default to CSOM or REST.

**Comment by jansenbe** [comment]
hi @tbithell ,

We (being Microsoft in this case) do understand this need and hopefully there will be a solution in the near future that addresses this. Can't provide anymore details and for now the recommendation is to start developing with the current authentication model.

**Comment by jansenbe** [comment]
The question as such has been answered, so closing the issue. A similar issue is still open in the PnP Framework repo, let's use that for additional discussion
