### ISSUE TITLE
How to add folder to SharePoint document library?

### ISSUE THREAD

**Issue by piteerus** [pnp/pnpcore#195]
## Category

- [x] Bug

## Describe the bug

```
[2020-10-14T06:39:35.203] Error while processing change
[2020-10-14T06:39:35.204] PnP.Core: Unresolved tokens found in API call https://{tenant}.sharepoint.com/sites/{sitecollection}/_api/Web/getFolderById('{Parent.Id}')/Folders/Add('2020-10sdfs').

```
## Steps to reproduce

```
public async Task<string> EnsureFolder(string folderName)
{
    _logger.LogInformation($"Creating folder={folderName}");
    using (var ctx = await _pnpContextFactory.CreateAsync(new Uri(_absSiteUrl)))
    {
        var list = await ctx.Web.Lists.GetByTitleAsync("Site Pages");
        var folder = await list.RootFolder.AddFolderAsync(folderName + "sdfs");
        return folder.ServerRelativeUrl;
    }
}
```
## Expected behavior

The new folder should be created.

## Environment details (*development & target environment*)

- **SDK version**: 0.3.11.0
- **OS**: Windows
- **SDK used in**: Azure Function
- **Framework**: .NET Core v3.x
- **Tooling**: Visual Studio 2019
- **Additional details**: 

*Thanks for your contribution! Sharing is caring.*

**Comment by ypcode** [comment]
Hello @piteerus,

Thanks for reporting this, I think we may probably address that issue making sure the RootFolder is properly loaded and initialized in the AddFolderAsync method. We'll need to think about the best way to handle it ( cc @jansenbe ).

In the meantime, you may want to specify the Root folder to be explicitly loaded.
Something like 
```csharp
 await context.Web.Lists.GetByTitleAsync("Site Pages", l => l.RootFolder);
```

AFAIK, that would help :) 
Let us know how it is going!

Again, thanks for trying out the PnP Core SDK !

Regards,
Yannick

**Comment by piteerus** [comment]
This one works for me:
```
using (var ctx = await _pnpContextFactory.CreateAsync(new Uri(_absSiteUrl)))
{
	var list = await ctx.Web.Lists.GetByTitleAsync("Site Pages");
	var rootFolder = await list.RootFolder.GetAsync();
	var folder = await rootFolder.AddFolderAsync(folderName);
	return folder.ServerRelativeUrl;
}

**Comment by jansenbe** [comment]
See also #196 , that should work as well and save you a server roundtrip...but we first need to fix it :-)

**Comment by jansenbe** [comment]
Closing this one as there are multiple ways to achieve this
