### ISSUE TITLE
TeamChannel.GetByDisplayName does not work as $top=1 is not valid in the Graph query

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#198]
## Category

- [x] Bug

## Describe the bug

GetByDisplayName  constructs a query like /teams/b32780e9-df70-4548-a735-4e7f055415a1/channels?$filter=displayName eq 'General'&$top=1 which does not work. Leaving $top out works in this case.

Related to #38

**Comment by pkbullock** [comment]
From testing this issue only affect Async e.g. (GetByDisplayNameAsync) calls to the graph. There must be a reasonable difference there - or an indication the non-async calls under hood is missing something making this by chance a working call.

**Comment by jansenbe** [comment]
Both were using different implementations in this case, with the new series of Get methods on collections and the rewrite of the GetBy... methods to use those new collection get methods this issue has been resolved.
