### ISSUE TITLE
Create models for navigation

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#212]
## Category

- [x] Feature request

## Describe the feature

- Add the ability to call the  APIs relating to Navigation, including Site, Hub, Footer navigation elements
- Unit Tests for calling the APIs
- If there are special requirements or permissions with this model, add to the documentation

## Contributing

We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: [https://pnp.github.io/pnpcore/articles/contributor/readme.html](https://pnp.github.io/pnpcore/articles/contributor/readme.html)

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by MathijsVerbeeck** [comment]
Hi @jansenbe, I'd like to work on this issue if possible.

**Comment by jansenbe** [comment]
Excellent @MathijsVerbeeck! If you need help then don't hesitate to reach out.

**Comment by jansenbe** [comment]
@MathijsVerbeeck : thanks for providing this feature to PnP Core SDK! Closing this issue now, let's follow-up possible additions via new issues when the need arises.
