### ISSUE TITLE
Create model for enabling support for Checked Out Files

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#222]
## Category

- [x] Feature request

## Describe the feature

- Add the ability to call the APIs relating to Checked Out Files
- Unit Tests for calling the APIs
- If there are special requirements or permissions with this model, add to the documentation

## Contributing

We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: [https://pnp.github.io/pnpcore/articles/contributor/readme.html](https://pnp.github.io/pnpcore/articles/contributor/readme.html)

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by jansenbe** [comment]
We do have full support for checkin/checkout/undocheckout/publish/unpublish/approve and all the related list settings
