### ISSUE TITLE
Create models for Site Creation

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#223]
## Category

- [x] Feature request

## Describe the feature

- Add the ability to call the APIs for creating modern sites, Groups, Comm Sites etc. 
- Unit Tests for calling the APIs
- If there are special requirements or permissions with this model, add to the documentation

## Contributing

We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: [https://pnp.github.io/pnpcore/articles/contributor/readme.html](https://pnp.github.io/pnpcore/articles/contributor/readme.html)

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by Maddisan** [comment]
Will this allow the ability to create new Site Collections?

**Comment by jansenbe** [comment]
@Maddisan : yes, that's the plan

**Comment by jansenbe** [comment]
Started working on this, will be part of the PnP.Core.Admin library

**Comment by jansenbe** [comment]
Implemented as part of PnP.Core.Admin
