### ISSUE TITLE
Error: Task Canceled when downloading from Sharepoint "big" files >= 2GB

### ISSUE THREAD

**Issue by RicardoCostaDev** [pnp/pnpcore#228]
https://github.com/pnp/pnpcore/blob/4c38c88659bd60429f0ad73e0be415ea1e2db6e8/src/sdk/PnP.Core/Model/SharePoint/Core/Public/IFile.cs#L191

I'm getting TaskCanceled exception on file.GetContent() and file.GetContentBytes() when trying to download "big" files , >= 2GB.
This issue doesn't happend when trying to download smaller files.

**Comment by jansenbe** [comment]
Thanks for reporting this @RicardoCostaDev, we'll investigate this

**Comment by jansenbe** [comment]
See https://github.com/SharePoint/sp-dev-docs/issues/5247 for more background

**Comment by jansenbe** [comment]
@RicardoCostaDev : this issue has been fixed. If you tomorrow use our latest nightly nuget package you need to make a few tweaks to your config/code:

- Configure the HttpClient timeout settings by setting the Timeout configuration setting. See https://pnp.github.io/pnpcore/articles/consumer/pnp%20core%20settings.html#sample-settings-file 
- Indicate you want to stream the content (to avoid the full file size being loaded in memory) you need to specify that when calling GetContentAsync or GetContent.

Below example shows how to read a 2GB file from SharePoint as a continuous stream and write the output to a file on the file system. Using this streaming approach your process never consumes a lot of memory.

```csharp
                IFile fileToDownload = await context.Web.GetFileByServerRelativeUrlAsync(fileUrl);

                // Download the content
                Stream downloadedContentStream = await fileToDownload.GetContentAsync(true);

                var bufferSize = 2 * 1024 * 1024;  // 2 MB buffer
                using (var content = System.IO.File.Create("d:\\temp\\largetestfiles\\2gb.test.downloaded"))
                {
                    var buffer = new byte[bufferSize];
                    int read;
                    while ((read = await downloadedContentStream.ReadAsync(buffer, 0, buffer.Length)) != 0)
                    {
                        content.Write(buffer, 0, read);
                    }
                }

```

**Comment by jansenbe** [comment]
I'm closing this issue, if you still experience issues then please create a new one with the error messages you're seeing
