### ISSUE TITLE
SharePoint Online authentication manager - SharePoint App-Only permissions

### ISSUE THREAD

**Issue by paveldanilchyk** [pnp/pnpcore#238]
## Add old authentication mechanism to .Net Standard library.

- [x] Feature request

## Describe the feature
PnP-Sites-Core library provides ability to get ClientContext using SharePoint App-only permissions (Azure Access Control (ACS)).
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs.
PnP core library uses a MSAL.Net for authentication.
Could we add a support of Azure Access Control (ACS) approach too. Description why it can be useful below.

## Describe the solution you'd like
Microsoft provides 2 ways to use app-only permissions for SharePoint.
1. SharePoint App-only permissions.
2. Azure AD App-only permissions.

I would like to suggest to move authentication mechanism as additonal option in PnP-core.
## Additional context
Work case:

I figure out one technical blocker with using  CSOM .Net standard library.
When I use MSAL.Net Confidential Application and client credentials flow I must setup SharePoint permissions in Azure AD app registration.
The biggest permissiion - _**Sites.FullControl.All**_
Using these permission I can get access to any site collection.
BUT I need to work with Tenant Administration.

```
var tenant = new Tenant(ctx);
var filter = new SPOSitePropertiesEnumerableFilter();
filter.IncludePersonalSite = PersonalSiteFilter.Exclude;
filter.IncludeDetail = false;
sitesChunk = tenant.GetSitePropertiesFromSharePointByFilters(filter);
ctx.Load(sitesChunk);
ctx.ExecuteQuery();
```

If I'll execute this code using CSOM/ MSAL.net and client credential flow , I will get an error - 401 Unauthorized.
Another requests work fine.
As additonal checking I used the same certificate for PnP Powershell. It works fine too.
I guess it's related with scope of permissions.

Also, I have done some investgation and a couple of articles about CSOM .Net standard contain the similar comments about this blocker.

As workaround for my Function App v3 I reused Token helper and integrated in with my code which uses common CSOM library now.

**Comment by jansenbe** [comment]
Hi @paveldanilchyk ,

Current PnP Core SDK does not support any tenant level operations and we do not directly support ACS app-only. If you tenant level API calls using the CSOM Tenant object the please use [PnP Framework](https://github.com/pnp/pnpframework) as that still depends on CSOM and also has support for Azure ACS app-only. If you don't need tenant API's you can use our custom authentication model to bring in ACS support...essentially we do have an option allowing you to just provide an access token that you've obtained via your code (e.g. your TokenHelper class usage). You can do this by using our `ExternalAuthenticationProvider` as shown in below mockup and in our [ASP.NET CORE sample](https://pnp.github.io/pnpcore/demos/Demo.ASPNetCore/README.html).

```csharp
pnpContextFactory.CreateAsync(siteUrl,
                            new ExternalAuthenticationProvider((resourceUri, scopes) =>
                            {
                                return tokenHelper.GetAccessToken(resourceUri);
                            }
                            ));
```

Alternatively you can code a custom authentication provider yourselves, see https://pnp.github.io/pnpcore/articles/consumer/custom-authentication-provider.html for some more details and https://pnp.github.io/pnpcore/demos/Demo.Blazor/README.html for an example using a custom authentication provider.

**Comment by paveldanilchyk** [comment]
This question/suggestion is irrelevant now. 

MSAL client credential flow works for my case.
For this case need to worry about scope.
https://github.com/SharePoint/sp-dev-docs/issues/6498

Thank you,
