### ISSUE TITLE
Experiment: Tag unit tests as samples so examples are testable

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#255]
## Category

- [x] Feature request

## Describe the feature

Investigate if the sample code can be tagged in a way from unit tests to ensure that when we make a change to the underlying code, the example code is proven to work.

**Comment by jansenbe** [comment]
Cleaning up the issue list: think this one is quite hard to implement plus it might limit how sample code is presented in docs. We can revisit later on
