### ISSUE TITLE
Support using cookiecontainer and networkcredentials in PnP Core SDK to support usage from PnP PowerShell and future page transformation tech porting

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#274]
## Category

- [x] Feature request

## Describe the feature

Resources:

- https://stackoverflow.com/questions/59684127/add-cookies-to-dependancy-injected-httpclient-in-asp-net-core
- https://d-fens.ch/2016/12/27/howto-set-cookie-header-on-defaultrequestheaders-of-httpclient/
- https://gist.github.com/bryanbarnard/8102915

**Comment by PaoloPia** [comment]
It's now implemented and under test.

**Comment by jansenbe** [comment]
We've confirmed this works, closing the issue.
