### ISSUE TITLE
Adding items to list throws exception

### ISSUE THREAD

**Issue by erwinvanhunen** [pnp/pnpcore#275]
## Category

- [x] Bug

## Describe the bug

Adding an item to a list throws an exception

## Steps to reproduce

```csharp
var batch = context.NewBatch();
var list = context.Web.Lists.GetById(listid, l => l.Fields.LoadProperties(f => f.Id, f => f.Title, f => f.InternalName, f => f.TypeAsString));
list.Items.AddBatch(batch,myValues);
```

Exception thrown: Please first fetch this list from SharePoint before doing operations on it.

This works:
```csharp
var batch = context.NewBatch();
var list = context.Web.Lists.GetById(listid);
list.Get(l => l.Fields.LoadProperties(f => f.Id, f => f.Title, f => f.InternalName, f => f.TypeAsString));
list.Items.AddBatch(batch,myValues);
```
## Expected behavior

Most likely it's because some required values are not loaded by default to able for PnP Core to successfully add the request to the batch. These values should be loaded by default, besides the one in the expression above.

- **SDK version**: [e.g. 0.4.17-beta1 ]
- **OS**: [Windows 10]
- **SDK used in**: [PnP PowerShell]
- **Framework**: [ .NET Core v3.x ]

**Comment by jansenbe** [comment]
Fixed. Optimized behavior is there when the initial list load goes like this, including RootFolder:

```csharp
var list = context.Web.Lists.GetById(listid, l => l.RootFolder, l => l.Fields.LoadProperties(f => f.Id, f => f.Title, f => f.InternalName, f => f.TypeAsString));
```

If RootFolder is not loaded it will be loaded on demand but above approach saves one roundtrip
