### ISSUE TITLE
Update InteractiveAuthenticationProvider to use a default RedirectUri if not provided + use InteractiveAuthenticationProvider as default if nothing set

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#283]
## Category

- [x] Feature request

## Describe the feature

InteractiveAuthenticationProvider can default to the http://localhost redirecturi if nothing (no appid, tenant) was specified as we then can fall back to the PnP Management shell app. With this in place we can also allow to configure the SDK with a simple AddPnPCore() as we can default to InteractiveAuthenticationProvider using the PnP management shell multi tenant app.

This needs to be clearly documented as well.

**Comment by PaoloPia** [comment]
Done!
