### ISSUE TITLE
Invoke-PnPSiteTemplate is ignoring ClientSidePages

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpcore#286]
**Command:** 
Invoke-PnPSiteTemplate

**Actual behavior:** 
When using this command to apply site pages to the site, it ignores the page. If I use the old library with the command: **Apply-PnPProvisioningTemplate** it will work fine. With the new command, it shows the page was modified recently (like 2 minutes ago). But it doesn't actually apply any template to it. 

**Expected Behavior**
I'd expect both commands to work the same way by applying the template to the site. 
 
**Version Used:** 
0.3.31

**OS:** 
Windows 10

Link to template snippet I'm using: https://gist.github.com/derhallim/5474952d9b54caf54aab8c497fc0d909

**Comment by jansenbe** [comment]
@derhallim : for the page header alignment you need to fix the template (your template contains TextAlignment="Center"). We used to have a bug in the previous version where there was a mismatch in enums but this has been fixed in the new SDK. I'll have a look at the preview image

**Comment by derhallim** [comment]
@jansenbe yep just noticed it. Works after removing the whole tag and it defaults to left. 
Thanks for having a look at the previews.

**Comment by derhallim** [comment]
@jansenbe I've got this: https://gist.github.com/derhallim/5474952d9b54caf54aab8c497fc0d909

**Comment by jansenbe** [comment]
The page you've shared is not set to be a template page and does not have a header with an image...so I can't repro this issue here. Can you share the actual page you're testing with.

**Comment by derhallim** [comment]
@jansenbe here's an example of 2 pages that appear in the preview panel: 
https://gist.github.com/derhallim/13e20e9b76450679d6496951c8a391f1

**Comment by jansenbe** [comment]
@derhallim : this issue has been fixed in the beta2 release of PnP Core SDK and as such it will appear in tomorrow's nightly build from PnP PowerShell and PnP Framework

**Comment by derhallim** [comment]
Awesome! Thanks @jansenbe
