### ISSUE TITLE
Applying template with ClientSidePages in template definition fails

### ISSUE THREAD

**Issue by adzero** [pnp/pnpcore#288]
## Category

- [x] Bug

## Describe the bug

Using the PnP.Powershell preview module, I try to apply a template with the new  `Invoke-PnPSiteTemplate` command. 
Provisionning is done but fails at the end with ClientSidePages (I actually have only one quite simple Home page definition) and raises a NullReferenceException. 
If I comment the ClientSidePages in my xml file, no error.
If I use the (soon-to-be) legacy `Apply-PnPProvisionningTemplate`  command, template is applied without error. 

## Steps to reproduce

Use `Invoke-PnPSiteTemplate` to apply a template with ClientSidePages node. 

## Expected behavior

Template applied without errors. 

## Environment details (*development & target environment*)

- **OS** Windows 10
- **Additional details** : Using PnP.PowerShell 0.3.33-nightly

**Comment by jansenbe** [comment]
@adzero : can you share a template with a failing page and the authentication method used in PnP PowerShell?

**Comment by adzero** [comment]
@jansenbe : here's the content of ClientSidePages node. 

```
<pnp:ClientSidePages>
      <pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="false" Overwrite="true" Layout="Home" EnableComments="false" Title="Accueil" ThumbnailUrl="" PageName="Home.aspx">
        <pnp:Header Type="Default" LayoutType="FullWidthImage" TextAlignment="Center" ShowTopicHeader="false" ShowPublishDate="false" TopicHeader="" AlternativeText="" Authors="[]" AuthorByLine="[]" AuthorByLineId="-1" />
        <pnp:Sections>
          <pnp:Section Order="1" Type="OneColumn">
            <pnp:Controls>
              <pnp:CanvasControl WebPartType="List" JsonControlData="{&quot;id&quot;: &quot;f92bf067-bc19-489e-a556-7fe95f508720&quot;, &quot;instanceId&quot;: &quot;8e502904-d558-41b5-b745-bdc1e7de02c7&quot;, &quot;title&quot;: &quot;List&quot;, &quot;description&quot;: &quot;List&quot;, &quot;dataVersion&quot;: &quot;1.0&quot;, &quot;properties&quot;: {&quot;isDocumentLibrary&quot;:false,&quot;filterBy&quot;:{},&quot;selectedViewId&quot;:&quot;Microsoft.SharePoint.Client.View&quot;,&quot;selectedListId&quot;:&quot;{listid:Supports de formation}&quot;,&quot;selectedListUrl&quot;:&quot;/sites/formation-modele-espace/supports&quot;,&quot;webpartHeightKey&quot;:2,&quot;webRelativeListUrl&quot;:&quot;/supports&quot;}, &quot;serverProcessedContent&quot;: {}, &quot;dynamicDataPaths&quot;: {}, &quot;dynamicDataValues&quot;: {}}" ControlId="f92bf067-bc19-489e-a556-7fe95f508720" Order="1" Column="1" />
            </pnp:Controls>
          </pnp:Section>
        </pnp:Sections>
      </pnp:ClientSidePage>
</pnp:ClientSidePages>
```
I noticed this first with another template on Januray 4th after updating PnP module, but this one is even simpler with only a library control. 

I'm connecting and applying template to the site like this : 

```
$pnpSiteConnection = Connect-PnPOnline -Url $currentSiteUrl -Credentials $Credentials -ReturnConnection

...

Invoke-PnPSiteTemplate -Path $PnpTemplatePath -TemplateId "TEMPLATE-ID" -OverwriteSystemPropertyBagValues -Handlers All -Parameters @{SOME PARAMS} -Connection $pnpSiteConnection -ErrorAction Stop
```

**Comment by jansenbe** [comment]
@adzero : Can you cross check you're really using the latest PS (e.g. check the loaded module) as this is something I thought we had fixed last week (home pages were not updated, see https://github.com/pnp/pnpframework/issues/73)

**Comment by adzero** [comment]
@jansenbe : I uninstalled the previous PnP.PowerShell version and checked the module version loaded and it is 0.3.33. 

Let me know if I can do something else to help.

**Comment by jansenbe** [comment]
Hi @adzero , when I use your template I can overwrite the home page, both from using PnP Framework code as from the latest PnP PowerShell release (.34). 

![image](https://user-images.githubusercontent.com/7451219/104355139-88e9f500-550a-11eb-9a07-9271a10a4f59.png)

**Comment by adzero** [comment]
Hi @jansenbe, tried again this morning and NullReferenceException still happens. 
If comment the pnp:ClientSidePages node, provisionning ends without error. 

I checked to update PnP.PowerShell to .34-nightly but the last version available is still .33-nightly : [PSGallery](https://www.powershellgallery.com/packages/PnP.PowerShell)

I'll give another try as soon as .34 is available.

**Comment by jansenbe** [comment]
Any feedback here @adzero or can we close this issue?

**Comment by adzero** [comment]
Hi @jansenbe, sorry for the delay. 

I just updated my PnP.PowerShell module to 0.3.40-nightly and applied once again the template. 
Sadly, error still occurs when I uncomment ClientSidePages node.

Here's a screenshot. First with ClientSidePages commented and second uncommented. 

![pnp-template-error](https://user-images.githubusercontent.com/7522988/105008204-32fcdc00-5a39-11eb-8c05-14d709c9fe3b.png)

I forgot to mention that my template was generated using old commands. 
The only noticeable difference is on the Generator attribute : Generator="OfficeDevPnP.Core, Version=3.26.2010.0, Culture=neutral, PublicKeyToken=5e633289e95c321a"

I tried to extract a template from the same site with `Get-PnPSiteTemplate` and it also ends with a NullReferenceException. 

It reminds me of similar errors I encountered a few months ago. It ended up to be related to either the DenyAddAnd CustomizePages state or rights on the term store.
My account is administrator of the SharePoint Service but I added directly as administrator of the term store. 
I also checked that DenyAddAndCustomizePages was set to false. 
Despite these changes, error is still here. 

Trace log of the Invoke command doesn't reveal anything about the error. 
Trace log og the Get command contains details about the error : 

```
powershell.exe Information: 0 : 2021-01-19 09:58:58.7055	[List instances (Export)]	[14]	[Debug]	Code execution scope started	0ms	bd4e5e28-e885-42d8-84b0-ff442daed2e8
powershell.exe Error: 0 : 2021-01-19 09:59:02.0919	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Impossible d’appeler la méthode ou de récupérer la propriété d’un objet null. L’objet renvoyé par la pile des appels suivante est null. « GetWorkflowSubscriptionService
new Microsoft.SharePoint.WorkflowServices.WorkflowServicesManager()
 »
   à Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   à Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   à Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.ClientServiceException
ServerErrorTraceCorrelationId: b3c0a29f-f0ff-2000-9b59-f1a098b7e86a
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Information: 0 : 2021-01-19 09:59:03.4689	[Get Security]	[14]	[Debug]	Code execution scope started	0ms	bd4e5e28-e885-42d8-84b0-ff442daed2e8

```

Maybe the two problems are not the same or related.

What can I do to move forward ?

**Comment by jansenbe** [comment]
@adzero : please call Get-PnPException after the apply of the template fails and share that output here. For the second issue please create a separate issue in the PnP Framework repo (https://github.com/pnp/pnpframework/issues)

**Comment by adzero** [comment]
Here's the output of `Get-PnPException` after `Invoke-PnPSiteTemplate` fails : 

![pnp-template-error2](https://user-images.githubusercontent.com/7522988/105036525-e3300c00-5a5c-11eb-8220-ebbc19856d72.png)

**Comment by GreatTommy** [comment]
I've got the same issue with PnP.PowerShell (1.1.1), and I'm also using Sharepoint in french (maybe that's could be a clue to solve the issue).
I observed the issue comes when Get-PnPSiteTemplate function treats site pages. So I also tried the function Export-PnPPage and indeed I got the same error message.

**Comment by jansenbe** [comment]
@GreatTommy / @adzero: I assume your complete tenant is in French given you get French error messages. My tenant is English, but I'll create a non English site and see if I can repro as well. If that doesn't work, would it be possible for one of you to setup a test user in your tenant, create a test site where that user is site collection admin and then share with me...that way I can debug using your tenant.

**Comment by jansenbe** [comment]
I can simulate the issue with a non English site, thanks for pointing me in the right direction.

**Comment by GreatTommy** [comment]
Ok great, I hope you will be able to identify the problem. Don't hesitate to tell me if there is anything I can do to help.

**Comment by jansenbe** [comment]
@GreatTommy / @adzero : the issue has been fixed. See https://github.com/pnp/pnpcore/commit/dd43f2fa1943495449c0e517419666cc5049e45d for details on the fix. This fix will appear in tomorrow's nightly releases of PnP PowerShell, PnP Framework and PnP Sites Core. Please test tomorrow and let us know if things work for you.

**Comment by jansenbe** [comment]
FYI: We've released version 1.1 from PnP Framework so you've an official release build with this fix. There will also be an new PS release still today.

**Comment by GreatTommy** [comment]
I have tested the new PnP.PowerShell 1.2.0 and it's now working like a charm. Thanks !

**Comment by MarwanSummakieh** [comment]
Hi everyone I have an issue when I use 
Invoke-PnPSiteTemplate -Path $templatePath -Connection $global:siteConnection -Parameters @{"Title"=$title;"Alias"=$alias}

the script is stuck like this and it doesn't proceed, been like this for 3 hours now  

Applying template to https://. [ClientSidePages         ]

what could be the issue
