### ISSUE TITLE
Build a "lightweight" CSOM client that we can use for our required CSOM operations

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#298]
## Category

- [x] Feature request

## Describe the feature

Some operations do require CSOM, currently we've a solution that's based on coming up with the XML payload via string manipulation. This works but has limitations:

- does not support batching of requests
- hard to maintain

What if we'd had a minimal CSOM client implementation that could use information from our model (we can add additional model attributes for this purpose) and then can be used to load data or run methods via CSOM.

**Comment by mgwojciech** [comment]
Thanks! That was fun :)
