### ISSUE TITLE
CAML query getting ignored when querying custom field

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpcore#299]
## Category

- [x] Bug

## Steps to reproduce

Hello, I am trying to get a particular ListItem using the pattern based on the CAML query sample code from this [link ](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#getting-list-items-via-a-caml-query
)

I want to return a List Item where a custom field equals a specific value. When I execute my CAML in a CAML utility against my List, I receive the expected result...

However, when I execute the query using PnP.Core SDK and the sample, I get back all the items in the list. This is not correct, it seems to be ignoring the CAML 
 
```

 using (var context = await SPContext.GetAuthenticationContext(siteUrl, _pnpContextFactory, _tokenAcquisition))
                    {
                        var items = context.Web.Lists.GetByTitle("Notifications", p => p.Title, p => p.Items, p => p.Fields.LoadProperties(p => p.InternalName, p => p.FieldTypeKind, p => p.TypeAsString, p => p.Title));
                        
                        string query = 
                            string.Format(
                                @"<View>" +
                                    "<ViewFields>" +
                                        "<FieldRef Name='bdo_systemId' />" +
                                    "</ViewFields>" +
                                    "<Query>" +
                                        "<Where>" +
                                        "<Eq>" +
                                            "<FieldRef Name='ccu_systemId'/>" +
                                            "<Value Type='text'>{0}</Value>" +
                                        "</Eq>" +
                                        "</Where>" +
                                    "</Query>" +
                                "</View>", 
                                itemupdate.System.SystemMessageId);

 

                        await items.GetItemsByCamlQueryAsync(new CamlQueryOptions()
                        {
                            ViewXml = query,
                            DatesInUtc = true
                        });
```

## Expected behavior
I want to be able to filter by a custom field using CAML query. 

## Environment details (*development & target environment*)
SharePoint Online
- **SDK version**: [[6:19 PM] SDK 0.4.34-beta1]
- **SDK used in**: [ASP.NET Core Web API ]
- **Tooling**: [Visual Studio 2019]

**Comment by jansenbe** [comment]
Thanks for logging this one @derhallim , I'll have a look later today.

**Comment by jansenbe** [comment]
Hi @derhallim ,

This feature works, I've created a test case that creates a list with custom field, populates the list and the queries using the custom field and this works fine. See https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/ListTests.cs#L476 for the actual test.

I think the problem is that you already load all list items with this line as you've included `p => p.Items`. Leaving that out should result in only the needed list items loaded in your list.

```csharp
var items = context.Web.Lists.GetByTitle("Notifications", p => p.Title, p => p.Items, p => p.Fields.LoadProperties(p => p.InternalName, p => p.FieldTypeKind, p => p.TypeAsString, p => p.Title));
```

Alternatively you can call the Clear() method on the Items collection before you perform the CAML query, but you'll have to wait for tomorrow's build for doing that as I've added this feature today.

**Comment by derhallim** [comment]
Thanks a lot, @jansenbe!
