### ISSUE TITLE
Expand supporting more Teams Tab Types

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#311]
## Category

- [x] Feature request

## Describe the feature

- Expand on the current support tab types to include more as per the links referenced below.
- Add tests to validate the feature
- Add documentation with sample usage code

Reference: https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs
and https://docs.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-beta

## Contributing
We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: https://pnp.github.io/pnpcore/contributing/readme.html

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by MathijsVerbeeck** [comment]
Hi @pkbullock, @jansenbe 

I'd like to work on this issue.

**Comment by jansenbe** [comment]
Appreciate the help @MathijsVerbeeck !

**Comment by jansenbe** [comment]
@MathijsVerbeeck added a very complete support. Thanks a lot 🚀💪🎉
