### ISSUE TITLE
Unable to load Items in List with more than 5000 records

### ISSUE THREAD

**Issue by salilpune1** [pnp/pnpcore#315]
## Category

- [x] Bug

## Describe the bug

I have a list having more than 5k+ items. I am using GetItemsByCamlQueryBatch method to load items. I am setting 5000 view limit to avoid threshold error. But unlike CSOM, I am unable to get ListItemCollectionPosition from list.Items. How do I iterate through the list to get all list items?

## Steps to reproduce
 var list = context.Web.Lists.GetByTitle(listTitle);
                var newBatch = context.NewBatch();
                list.GetItemsByCamlQueryBatch(newBatch, new CamlQueryOptions()
                {
                    ViewXml = @"<View Scope='Recursive'><ViewFields>
                                <FieldRef Name='Created' />
                                <FieldRef Name='File_x0020_Type' />
                                <FieldRef Name='FSObjType' />                               
                                </ViewFields><RowLimit>5000</RowLimit></View>",
                });
        
                context.ExecuteAsync(newBatch).GetAwaiter().GetResult();

*Thanks for your contribution! Sharing is caring.*

**Comment by koltyakov** [comment]
Setting top 5000 won't avoid throttling error. The query structure should follow some rules, like a filter should be happening on indexed field to return less than throttling.

**Comment by salilpune1** [comment]
> Setting top 5000 won't avoid throttling error. The query structure should follow some rules, like a filter should be happening on indexed field to return less than throttling.

Its not about throttling. Say List has 8k items and I want to load all of them. In CSOM we used do while loop and use ListItemCollectionPosition  to get all items. I am not able to figure out this is possible in PnPCore.

**Comment by jansenbe** [comment]
We're not allowing to send paging info, will do some updates and post back here once done

**Comment by jansenbe** [comment]
@salilpune1 : This will be the model you can use as of tomorrow:

```csharp
await list2.GetItemsByCamlQueryAsync(new CamlQueryOptions()
{
    ViewXml = "<View><ViewFields><FieldRef Name='Title' /></ViewFields><RowLimit>20</RowLimit></View>"
});
Assert.IsTrue(list2.Items.Count() == 20);
await list2.GetItemsByCamlQueryAsync(new CamlQueryOptions()
{
    ViewXml = "<View><ViewFields><FieldRef Name='Title' /></ViewFields><RowLimit>20</RowLimit></View>",
    PagingInfo = "Paged=TRUE&p_ID=20"
});
Assert.IsTrue(list2.Items.Count() == 40);
Assert.IsTrue(list2.Items.ElementAt(21).Id == 22);
```

**Comment by koltyakov** [comment]
Should be assumed that such paging token only applicable for unordered and unsorted collections. For small lists and applied conditions a token must contain a last value for each sorter field on a previous page, or used a one returned from the API.

**Comment by jansenbe** [comment]
@koltyakov : You've good sample of that, want to include it the docs

**Comment by jansenbe** [comment]
See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-paging-with-caml-queries

**Comment by jansenbe** [comment]
@salilpune1 : maybe using ListDataAsStream is an easier, more flexible and faster approach to retrieve list data. See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-paging-with-listdataasstream for the docs on how to that
