### ISSUE TITLE
Teams Calendar Support

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#319]
## Category

- [x] Feature request

## Describe the solution you'd like

- Add Teams Calendar Support
- Add tests to validate the feature
- Add documentation with sample usage code

Reference: https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0

## Contributing
We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: https://pnp.github.io/pnpcore/contributing/readme.html

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

**Comment by MathijsVerbeeck** [comment]
@jansenbe I'll have a look at this.

**Comment by jansenbe** [comment]
Implemented by @MathijsVerbeeck , thanks a ton @MathijsVerbeeck 👌
