### ISSUE TITLE
Evaluate the option to open up generic REST / Graph clients for SDK users to enable scenarios not foreseen via the SDK

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#324]
## Category

- [x] Feature request

## Describe the feature

See https://github.com/pnp/pnpcore/discussions/320 for some background.

**Comment by VishalMadhvani** [comment]
This would be useful to have. In my case, I needed a Graph client before having a group or site to connect to with PnPContext.
Ended up making use of the AuthenticationProviderFactory.
```csharp
private static IGraphServiceClient GraphServiceClientFactory(IServiceProvider serviceProvider)
{
    var authenticationProviderFactory = serviceProvider.GetService<PnP.Core.Auth.Services.IAuthenticationProviderFactory>();
    var authenticationProvider = authenticationProviderFactory.CreateDefault();
    return new GraphServiceClient(new DelegateAuthenticationProvider((requestMessage) =>
    {
        return authenticationProvider.AuthenticateRequestAsync(new Uri("https://graph.microsoft.com"), requestMessage);
    }));
}
```

**Comment by jansenbe** [comment]
Thanks for sharing this

**Comment by jansenbe** [comment]
@VishalMadhvani : see also https://pnp.github.io/pnpcore/using-the-sdk/basics-graphsdk.html for our documentation on Graph SDK interop we've just added.

**Comment by jansenbe** [comment]
@VishalMadhvani : This is now possible via the new ExecuteRequestAsync/ExecuteRequest methods. See https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html for some early docs.
