### ISSUE TITLE
Possibility to add directly a collection for NewFieldValueCollection

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#325]
## Category

- [x] Feature request

## Describe the feature

At the moment I can only add one newfieldtaxonomyvalue at a time .  
`var taxonomyCollection = myField.NewFieldValueCollection();`
`taxonomyCollection.Values.Add(myField.NewFieldTaxonomyValue(new Guid("108b34b1-87af-452d-be13-881a29477965", "Dutch")));`
`taxonomyCollection.Values.Add(myField.NewFieldTaxonomyValue(new Guid("8246e3c1-19ea-4b22-8ae3-df9cbc150a74", "English")));`

`values.Add("MyField", taxonomyCollection);`

But normaly there are already a model in the solution with a colletion for the terms

## Describe the solution you'd like

I would like to add my keyValuePair colletion to the constuctor or to  addrange as IEnumerable<KeyValuePair<Guid, string>> termValues

`var taxonomyCollection = myField.NewFieldValueCollection(myTaxCollection);`

`taxonomyCollection.Values.AddRange(myTaxCollection);`

## Additional context
https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#multi-taxonomy-fields

**Comment by jansenbe** [comment]
Good suggestion @raclettierer

**Comment by jansenbe** [comment]
Additional constructors have been added on NewFieldValueCollection, they'll be usable as of tomorrow's nightly build

**Comment by raclettierer** [comment]
work fine. thank you
