### ISSUE TITLE
Add Listitem as folder in root - SharePoint REST error 

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#328]
## Category

- [x] Bug

## Describe the bug

If I want to add a item as folder in the root of a List with following code, i get an error. 

` IListItem item = list.Items.Add(values, string.Empty, FileSystemObjectType.Folder);`

After debugging the pnpn.core solution I found out, that they send an slash too much like : 
`https://xxx.sharepoint.com/sites/xxx/lists/myList/`
expected from SharePoint Rest :
`https://xxx.sharepoint.com/sites/xxx/lists/myList`

Extend the decodeurlforder code with follwing or similar line
                       ` else if (string.IsNullOrEmpty(folderPath))`
                        `{`
                          `  decodedUrlFolderPath = serverRelativeUrl;`
                     `   }`

 PnP.Core.Model.SharePoint.ListItem

## Steps to reproduce

` IListItem item = list.Items.Add(values, string.Empty, FileSystemObjectType.Folder);`

## Expected behavior

                var decodedUrlFolderPath = serverRelativeUrl;
                if (keyValuePairs.ContainsKey(FolderPath))
                {
                    if (keyValuePairs[FolderPath] != null)
                    {
                        var folderPath = keyValuePairs[FolderPath].ToString();
                        if (folderPath.ToLower().StartsWith(serverRelativeUrl))
                        {
                            decodedUrlFolderPath = folderPath;
                        }
                        else if (string.IsNullOrEmpty(folderPath))
                        {
                            decodedUrlFolderPath = serverRelativeUrl;
                        }
                        else
                        {
                            decodedUrlFolderPath = $"{serverRelativeUrl}/{folderPath.TrimStart('/')}";
                        }
                    }
                }

## Environment details (*development & target environment*)

SPO, Azure Functions, 
PNP.Core : Commits on Feb 13, 2021

**Comment by jansenbe** [comment]
@raclettierer : you can use AddListFolderAsync to add a folder.

```csharp
var folder = await list.AddListFolderAsync("Folder");
```

**Comment by jansenbe** [comment]
@raclettierer : Also enabled your code as that should also work.
