### ISSUE TITLE
Error when add a Listitem in a Library 

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpcore#329]
## Category

- [x] Bug

## Describe the bug

When I try to add a folder in a doclib with Items.Add the underline url is wrong. 
They concat it fix with **/lists/**, but a library has no **list** in the url 

## Steps to reproduce

`docList.Items.Add(valuesDocFolder, string.Empty, FileSystemObjectType.Folder);`

## Expected behavior

These trick with a fix /lists/ not realy work in all cases ! 

` $"{PnPContext.Uri}/lists/{parentListTitle}".Replace("_x005f_", "_");`

       if (string.IsNullOrEmpty(parentListTitle) || string.IsNullOrEmpty(parentListUri))
        {
            // Fall back to loading the rootfolder propery if we can't determine the list name
            await parentList.EnsurePropertiesAsync(p => p.RootFolder).ConfigureAwait(false);
            serverRelativeUrl = parentList.RootFolder.ServerRelativeUrl;
        }
        else
        {
            // little trick here to ensure we can construct the correct list url based upon the data returned by a default load
            // Ensure the underscore "_" character is not encoded in the FolderPath to use
            serverRelativeUrl = $"{PnPContext.Uri}/lists/{parentListTitle}".Replace("_x005f_", "_");
        }
Better to remove these trick and use only the serverrelativeurl from the rootfolder

      await parentList.EnsurePropertiesAsync(p => p.RootFolder).ConfigureAwait(false);
      serverRelativeUrl = parentList.RootFolder.ServerRelativeUrl;

**Comment by jansenbe** [comment]
Thanks for reporting this one @raclettierer , now fixed

**Comment by raclettierer** [comment]
Not working as expected. I think there are more to do behind

Error:
{
HttpResponseCode: 500
Code: Microsoft.SharePoint.SPException
Message: Invalid item data -- missing FileRef.
ClientRequestId:
}

My code in CSOM looks like follow: Create a Folder in a Folder in a library with a specific contenttype an additional metadata at ones.

            var docList = ctx.Web.GetListByUrl(docUrl);
            ListItemCreationInformation docFolderInfo = new ListItemCreationInformation()
            {
                UnderlyingObjectType = FileSystemObjectType.Folder,
                FolderUrl = parentDocFolderUrl,
                LeafName = obj.Title
            };
            ListItem docFolderItem = docList.AddItem(docFolderInfo);
            docFolderItem["ContentTypeId"] = "0x01200041A481C1BD39604XXXXXXX";
            docFolderItem["Title"] = obj.Title;
            docFolderItem["myCustomField"] = listFolderItem.Id;
            docFolderItem.Update();
            ctx.ExecuteQueryRetry();

Hopfully, you will find a solution, so that I can switch to the new framework.


Von: Bert Jansen <notifications@github.com>
Gesendet: Sonntag, 14. Februar 2021 09:49
An: pnp/pnpcore <pnpcore@noreply.github.com>
Cc: Matthias Z'Brun <matthias.zbrun@softforge.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [pnp/pnpcore] Error when add a Listitem in a Library (#329)


Thanks for reporting this one @raclettierer<https://github.com/raclettierer> , now fixed

**Comment by jansenbe** [comment]
Ah..you're right. I've missed this one as I did test with offline test data when doing my last changes. Have this fixed now, but before committing I'm going to centralize the code that translates list metadata into serverrelativeurl and vice versa is a separate class so I can more easily write test cases for it
