### ISSUE TITLE
Pagefiles with space not supported

### ISSUE THREAD

**Issue by czullu** [pnp/pnpcore#346]
## Category

- [x] Bug

## Describe the bug
In LoadPageAsync the NormalizePageName does replace spaces and the CAML Query does not search for both variants which leads to the issue, that pages with file names like "my topics.aspx" want be found anymore. As it's true that the ui does create files where the space is replaced users or code still can lead to situations where the actual filename is exactly like provided with space.

## Steps to reproduce
Create a Page-File with space in it's name and try to load page - result will be null.

## Expected behavior
Find pages with filename as provided from pnpframework as this is the actualname and needs not fiddling.

## Environment details (*development & target environment*)
Checked with Commit 0011460. 

### Additional context
As it affects provisioning as well, it would be nice to have pnpframework pointing to fixed version as soon as we have a fix..

**Comment by jansenbe** [comment]
@czullu : fixed this, we're not anymore updating the passed name when loading pages....only when saving a page the provided page name might be updated. The save methods now return the used name (after possible updating).

**Comment by czullu** [comment]
@jansenbe thank you for the quick fix. Changing name on save could break ApplyTemplate as well since you might have a link to a page like  {pageuniqueid:[siterelativepath]} or the tokenized url {site}/SitePages/My Page.aspx which can not be resolved. 
Just as a though.

**Comment by jansenbe** [comment]
Good point @czullu , will check that
