### ISSUE TITLE
Teams Chat Messages not working...

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#351]
## Category

- [x] Bug

## Describe the bug

Teams Chat messages does not work - the code relies on some internal objects that is not exposed to the apps.
e.g. example in docs - https://pnp.github.io/pnpcore/using-the-sdk/teams-channel-chat.html#adding-chat-messages-with-cards 

The TeamChatMessageAttachment class and its collection is internal. Will need make some changes to implementation.

Working on it...

**Comment by jansenbe** [comment]
Thanks @pkbullock ! Closing this one now that I've merged your change
