### ISSUE TITLE
EnsureFolderAsync troubles

### ISSUE THREAD

**Issue by pINKmUNster** [pnp/pnpcore#360]
## Category

- [x] Bug

## Describe the bug

I'm trying to use `await folder.EnsureFolderAsync` to create nested folder on the fly before adding files in it.
File are not upload in the good folder.

## Steps to reproduce

You can reproduce with this code.

I'm trying  to upload in list with folder in it.
/MyList/Daily/Today is working
/MyList/Test/Test not working
/MyList/Weekly/Test not working and file are in the second folder.

```
using var context = await _pnpContext.GetContextAsync();
  var folder = (await context.Web.Lists.GetByIdAsync(libraryId, p => p.RootFolder)).RootFolder;
  var suby = await folder.EnsureFolderAsync(CleanFolderName(folderName));
  var subfolder = await context.Web.GetFolderByIdAsync(suby.UniqueId);
await folder.Files.AddAsync(fileName, stream);
```

```
 private static string CleanFolderName(string folderName)
    {
        if (folderName.StartsWith("/"))
        {
            return folderName.Remove(0, 1);
        }
        return folderName;
    }
```

the var suby always return /MyList/Test/Test.

Thank in advance for your help.

**Comment by jansenbe** [comment]
@pINKmUNster : Think you want to add the files in the sub folder, so you should use `await subfolder.Files.AddAsync(fileName, stream);`

**Comment by pINKmUNster** [comment]
Oups sorry , it was wrong copy paste, the following line was from another method.
`await folder.Files.AddAsync(fileName, stream);`

**Comment by pINKmUNster** [comment]
This is my full code 

folderName can be : 

-  /Daily/Today 
-  /Test/Test 
- /Weekly/Test

`public async Task AddFileToSubfolder(Guid libraryId, string folderName, string fileName, Stream stream)
        {
            using var context = await _pnpContext.GetContextAsync();
            var folder = (await context.Web.Lists.GetByIdAsync(libraryId, p => p.RootFolder)).RootFolder;
            var suby = await folder.EnsureFolderAsync(CleanFolderName(folderName));
            var subfolder = await context.Web.GetFolderByIdAsync(suby.UniqueId);
            await AddFile(fileName, stream, subfolder);
        }

        private static string CleanFolderName(string folderName)
        {
            if (folderName.StartsWith("/"))
            {
                return folderName.Remove(0, 1);
            }
            return folderName;
        }

        private static async Task AddFile(string fileName, Stream stream, IFolder folder)
        {
            var addedFile = await folder.Files.AddAsync(fileName, stream);
        }`

**Comment by jansenbe** [comment]
Your code also works for me...

```csharp
                await AddFileToSubfolder(context, "MyList/Weekly/Test", "bert.docx", System.IO.File.OpenRead($".{Path.DirectorySeparatorChar}TestAssets{Path.DirectorySeparatorChar}test.docx"));


        public async Task AddFileToSubfolder(PnPContext context, string folderName, string fileName, Stream stream)
        {
            
            var folder = (await context.Web.Lists.GetByTitleAsync("Documents", p => p.RootFolder)).RootFolder;
            var suby = await folder.EnsureFolderAsync(CleanFolderName(folderName));
            var subfolder = await context.Web.GetFolderByIdAsync(suby.UniqueId);
            await AddFile(fileName, stream, subfolder);
        }

        private static string CleanFolderName(string folderName)
        {
            if (folderName.StartsWith("/"))
            {
                return folderName.Remove(0, 1);
            }
            return folderName;
        }

        private static async Task AddFile(string fileName, Stream stream, IFolder folder)
        {
            var addedFile = await folder.Files.AddAsync(fileName, stream);
        }

```

**Comment by pINKmUNster** [comment]
Yes i work fine if you tried to upload one file in one folder. 
It's gone wrong if you try to upload XYZ.doc to Test/Test  and after upload ABC.doc to Test/Test . 

When i tried my code, i have this :
Test
-> ABC.doc
-> Test
        -> XYZ.doc

But it's must be :  
Test
-> Test
        -> XYZ.doc
        -> ABC.doc

**Comment by jansenbe** [comment]
@pINKmUNster : below approach adds the 3 files in the right folder:

```csharp
                var list = await context.Web.Lists.AddAsync("Bert", ListTemplateType.DocumentLibrary);
                await list.EnsurePropertiesAsync(p => p.RootFolder);

                //var suby = await list.RootFolder.EnsureFolderAsync("Daily/Today");
                //var suby = await list.RootFolder.EnsureFolderAsync("Test/Test");
                var suby = await list.RootFolder.EnsureFolderAsync("MyList/Weekly/Test");

                await suby.EnsurePropertiesAsync(p => p.Files);
                IFile addedFile = await suby.Files.AddAsync("bert.docx", System.IO.File.OpenRead($".{Path.DirectorySeparatorChar}TestAssets{Path.DirectorySeparatorChar}test.docx"));
                IFile addedFile1 = await suby.Files.AddAsync("bert2.docx", System.IO.File.OpenRead($".{Path.DirectorySeparatorChar}TestAssets{Path.DirectorySeparatorChar}test.docx"));
                IFile addedFile2 = await suby.Files.AddAsync("bert3.docx", System.IO.File.OpenRead($".{Path.DirectorySeparatorChar}TestAssets{Path.DirectorySeparatorChar}test.docx"));
```

Using your code however exposed an issue with the EnsureFolderAsync() method, it did not work when ran on an existing folder.  I did not get the same behavior you saw, but adding multiple documents in the same folder failed due to this. I've just pushed a fix (https://github.com/pnp/pnpcore/commit/e1947c191e74189a7e9549779944a402da4bc948) for that, will be part of tomorrow's nightly release.

**Comment by pINKmUNster** [comment]
@jansenbe i try with the nightly release and it works as expected. 👍🏻 
All my file are upload in the correct folder.

Thank a lot, you rock !!
