### ISSUE TITLE
Internal Null Reference error while updating Taxonomy Field

### ISSUE THREAD

**Issue by cpercarb** [pnp/pnpcore#362]
## Category

- [x] Bug

## Describe the bug

I am simply trying to update a taxonomy field value within a page list item. The code pasted below works fine for me except when the item has another multiple taxonomy field with a non empty value. In this case I get an internal null reference while trying to update the item.
I have also seen that apparently it is not related to the type of field I try to update, because even updating the title of the item gives me also the same error.

## Steps to reproduce

Code example:

await demo1List.Fields.LoadAsync();
IField categoryField = demo1List.Fields.AsRequested().First(f=> f.InternalName.Equals("FieldInternalName"));
IFieldTaxonomyValue categoryFieldValue = defaultItem.NewFieldTaxonomyValue(categoryField, Guid.Parse("field-Guid"), "FieldLabel");
defaultItem["FieldInternalName"] = categoryFieldValue;
defaultItem.Update();//--> In this line is where I get the error in case the item has another field of type multitaxonomy with a non empty value

Thanks for your help

**Comment by jansenbe** [comment]
Thx for reporting this @cpercarb , we'll build a test case and try to reproduce and fix. So the issues appears with mixing a taxonomy field with a multi taxonomy field? Can you try if using a SystemUpdate() instead of Update() also results in an error?

**Comment by jansenbe** [comment]
Also see https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/ListItemTests.cs#L1599 for a test case that uses a regular taxonomy field with a multi-value taxonomy field.

**Comment by cpercarb** [comment]
Thank you @jansenbe for your quick response. Yes you are right. If I try with SystemUpdate() it is working fine and is setting the values, but every time I try normal Update() or UpdateAsync() methods, I still receive the error. 

Just to point one thing, it is happening not only when i mix taxonomy filed with multi taxonomy, it is happening to me always that a listitem has a multitaxonomy field with non empty values and I try to update another property or field. For example, trying to update the title of the item if the multitaxonomy field had any value was also giving me the same internal error.

I will take a look at the test you mention. Thanks so much

**Comment by jansenbe** [comment]
Hi @cpercarb ,

Did you manage to get the scenario working based upon the unit test or do you still have an issue when using Update()?

**Comment by jansenbe** [comment]
@cpercarb : are you still facing the issue with the update() method? Did the above recommendations help?

**Comment by jansenbe** [comment]
Closing per no additional feedback
