### ISSUE TITLE
Sample: Explore Power Platform connector sample and PnP Core SDK

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#363]
## Category

- [x] Feature request

## Describe the feature

Explore building a sample that is a custom Power Platform/Logic Apps connector to use PnP Core SDK in combination. This is just an idea, I don't know much about connectors so serves much of a learning piece for myself. 

It maybe this is just a template for others building custom connectors.

**Comment by jansenbe** [comment]
@pkbullock : cleaning up the issue list...you can always re-open if needed.
