### ISSUE TITLE
Unresolved Tokens found in API Calls when requesting team tabs

### ISSUE THREAD

**Issue by BraunJonathan** [pnp/pnpcore#364]
## Category

- [x] Bug

## Describe the bug

When i try to iterate on team tabs for a channel, i got the following error : 
System.Private.CoreLib: Exception while executing function: DeletePixChannels. PnP.Core: Unresolved tokens found in API call teams/4bf9cb9d-3cf4-4b54-b18b-ca541de58888/channels/19:293ca8bd34df422b8642372059e57eb7@thread.tacv2/tabs/{GraphId}.
![image](https://user-images.githubusercontent.com/35366413/111632851-2f958f00-87f5-11eb-9d4b-d91287163924.png)

## Steps to reproduce
` 

            using (var context = await pnpContextFactory.CreateAsync("Default")){

                // Get the Team
                var team = await context.Team.GetAsync(o => o.Channels);

                // Get the channel
                var chan = team.Channels.Where(i => i.DisplayName == "General").FirstOrDefault();

                // Load the tabs in the channel
                chan = await chan.GetAsync(o => o.Tabs);

                // Collection of Tabs
                var tabs = chan.Tabs;

                foreach (var tab in tabs){
                    log.LogInformation($"Tab Name {tab.DisplayName}");
                }
             }

`

## Expected behavior

The foreach should work ;-)
It works if i use the AsRequested() function in the foreach call BUT my point was to delete tabs so using the AsRequested is not an option as the deletion changes the collection...
Of course i found a way to do what i wanted but still wanted to share the problem as it seems that sthere is something wrong in the backend ;-)

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **SDK version**: 1.0.0
- **OS**: Windows 10
- **SDK used in**: Azure function
- **Framework**: .NET Core v3.1
- **Browser(s)**: chrome
- **Tooling**: VS Code

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Thx for reporting this @BraunJonathan , we'll have a look and see if this can be fixed.

**Comment by jansenbe** [comment]
@BraunJonathan : AsRequested() is needed here as otherwise we try to load data from the server. When you want to delete the tabs you should still be able to use AsRequested() in the foreach that deletes the tabs.

**Comment by jansenbe** [comment]
Closing as per design
