### ISSUE TITLE
Cannot perform BreakRoleInheritance on a SP.ListItem

### ISSUE THREAD

**Issue by kentlhastings** [pnp/pnpcore#367]
## Category

- [x] Bug

## Describe the bug

When calling BreakRoleInheritance, the resulting api call string does not begin with the site prefix, it begins with "_api/".  While in Task<Batch> RequestAsync, we get the entityInfo for the request. Inside EntityInfo.GetStaticClassInfo, the type "SP.ListItem" that is retrieved from the cache has its SharepointType property set to null.

Because of this, inside PrefixApiCall, the request is not prefixed with the site prefix.

So when we reach SharePointRestBatchSplitting() in Pnp.Core.Services.Batch.Client, the line "Uri site = new Uri(request.Value.ApiCall.Request.Substring(0, request.Value.ApiCall.Request.IndexOf("/_api/", 0)))" fails, returning an exception about the length.

## Steps to reproduce

Here is the code that is causing this error:

var source = batchContext.Web.GetFolderByServerRelativeUrl(destinationFilePath, x => x.ItemCount, x => x.Folders, x => x.Files, x => x.ListItemAllFields);

source.ListItemAllFields.BreakRoleInheritance(false, true);

source.Update();

## Expected behavior

The method would successfully execute.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **SDK version**: 10.0.14-nightly
- **OS**: Windows 10
- **SDK used in**: .Net Core 3.1 Console App
- **Framework**: .NET Core v3.1
- **Browser(s)**: Chrome
- **Tooling**: Visual Studio 2019 Professional
- **Additional details**: I'm unclear whether I've configured something incorrectly to cause this, or if this is a bug with the BreakRoleInheritance call to a cached SP.ListItem or if this behavior will happen with a SP.ListItem that isn't cached.

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Thanks for logging this @kentlhastings , I'll have a look

**Comment by jansenbe** [comment]
I've written a test that reproduces the issue...next stop, building a fix :-)

**Comment by kentlhastings** [comment]
Thanks Bert! You’re the man!

**Comment by jansenbe** [comment]
@kentlhastings : fix is in, please test with tomorrow's nightly build. If the problem still persists, then just re-open the issue.

Notes: 
- here the test case https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/Security/ListItemSecurityTests.cs#L70
- In your code you call Update...not really needed in case of BreakRoleInheritance
