### ISSUE TITLE
Enrich metadata model to describe supported functionalities

### ISSUE THREAD

**Issue by PaoloPia** [pnp/pnpcore#38]
Make it possible to mark domain model types, properties, and method with requirements (from a security point of view: delegated, app-only, both) and with OData support (like: $select, $filter, $orderby, $top, $skip, $expand, etc.).

**Comment by jansenbe** [comment]
$select/$expand typically works (we could tap into https://github.com/microsoftgraph/msgraph-metadata). $filter and $orderby are more complex ones as some fields work with $filter, some don't.

Required permissions can be fetched from https://github.com/microsoftgraph/msgraph-metadata as well

**Comment by jansenbe** [comment]
Some additional thoughts:
- For $filter then should also define which filter operators work (or which don't)
- Also included metadata to define in app-only (read/write) is supported or not

**Comment by jansenbe** [comment]
TestQueryTeamChannelMessages fails due to $top being added while it's not supported

**Comment by jansenbe** [comment]
Closing this one: a ton of work and the added value will be just cleaner error messages in case of a mission permission or wrongly used query parameter. Also checking on query parameters like $filter is not so obvious, in graph one can filter on some fields but not on all...there's no easy way to understand which fields are filterable and having a check in PnP Core SDK would then mean we always have to keep maintaining this metadata.
