### ISSUE TITLE
@jansenbe Is it possible now or will it be possible at any time to get the underlying client context (for CSOM)? I'm looking for the [GetChanges API](https://github.com/pnp/pnpcore/issues/218) on the lists, and it seems to be "missing" so far.

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#384]
@jansenbe Is it possible now or will it be possible at any time to get the underlying client context (for CSOM)? I'm looking for the [GetChanges API](https://github.com/pnp/pnpcore/issues/218) on the lists, and it seems to be "missing" so far. 

_Originally posted by @olemp in https://github.com/pnp/pnpcore/issues/300#issuecomment-815511397_

**Comment by olemp** [comment]
Cleared my comment in the other issue (#300), as it wasn't really related.

**Comment by jansenbe** [comment]
@olemp : there's a getchanges REST API, I'll have a look to get this implemented

**Comment by wonderplayer** [comment]
It would be great to have it as Microsoft suggests to use exactly this API to get changes after web hook event setup for SharePoint list 😊

**Comment by jansenbe** [comment]
@olemp : tomorrows nightly of PnP Framework has support for translating a PnP Core SDK context into a SharePoint ClientContext. See https://pnp.github.io/pnpcore/using-the-sdk/basics-pnpframework.html for the docs. The implementation of the GetChanges API will come, but this can possibly already unblock you.

**Comment by DaleyKD** [comment]
If you guys are talking about the ChangeLog API from the old CSOM stuff, this is a HUGE need for our current product.  Looking forward to this.

**Comment by jansenbe** [comment]
@DaleyKD : that's indeed the plan.

**Comment by rishu73** [comment]
@olemp - +1 for Pnp Wrapper for GetChanges() 
Is there an idea when PnPCoreSdk.Instance.GetPnPContext() will be moved into latest stable?

Thank you!

**Comment by DaleyKD** [comment]
@jansenbe : If you want to create a discussion on this and maybe give me an idea of where your head is at, I may be able to do a PR for this.

Currently, we pulled in the PnP.Framework in our code to use CSOM, but I REALLY don't want to use that if possible.

This is probably the last piece of the puzzle our code needs to be ready for MVP.

**Comment by jansenbe** [comment]
@DaleyKD : would be great if you could work on this feature 🚀

Pulling in PnP Framework with it's extra dependency on CSOM should not be needed. There's a GetChanges method on SP.List (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.List/func/GetChanges), on SP.Web (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Web/func/GetChanges), on SP.Site (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Site/func/GetChanges), on SP.Folder (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Folder/func/GetChanges) and SP.ListItem (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.ListItem/func/GetChanges).  All these methods return a collection of change objects that have SP.Change  (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Change). Commonly used change object is SP.ChangeItem (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.ChangeItem), but there are also SP.ChangeContentType, SP.ChangeField, SP.ChangeFile,... (filter on SP.Change in https://s-kainet.github.io/sp-rest-explorer/#/entity).

So implementation wise it's best to isolate the change code in a ChangeHandler class inside SharePoint/Core/Internal and then hook it up to the various places where we support getting changes. Happy to setup a call to discuss further.

**Comment by DaleyKD** [comment]
@jansenbe - I started work on this in a VERY simplistic manner.  Once I get a bit further, perhaps we can jump on a call to see if my progress is good or very bad. 😄 

We've got Memorial Day on Monday and PI Planning next week.  I'm not sure what progress is going to be during that week.

**Comment by jansenbe** [comment]
Thanks @DaleyKD , no rush on this...it's a hobby project :-) I've took the liberty to assign your name to this issue, feel free to un-assign if you don't want that.

**Comment by jansenbe** [comment]
@olemp / @wonderplayer / @rishu73 : @DaleyKD did implement this (thanks @DaleyKD) today and I've merged this change. Documentation is still pending, but for example https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/ListTests.cs#L1175 and further shows how to use this feature.

**Comment by DaleyKD** [comment]
Please note, I did not implement any paging, so you'll need to do this yourselves.
