### ISSUE TITLE
[BUG] Get-PnPClientSidePage page does not exist

### ISSUE THREAD

**Issue by 280237** [pnp/pnpcore#386]
Get-PnPClientSidePage is returning page does not exist error when called from an Azure function. The page I am trying to get is in a subfolder in Site Pages library.
I have added PnP.PowerShell='1.*' as a dependency in the app files and I am able to connect to SPO site using Connect-PnPOnline command.
Is this a (known) issue?

**Comment by jansenbe** [comment]
@280237 , @gautamdsheth , @veronicageek : this appeared to be an issue in the PagePipeBind class in PS. I've just pushed a fix, the next nightly should work.
