### ISSUE TITLE
CAML query not adding fields

### ISSUE THREAD

**Issue by wonderplayer** [pnp/pnpcore#396]
## Category

- [x] Bug

## Describe the bug

I would like to get some list item fields by using CAML query, but the fields don't get returned to me, specifically, I'm trying to get FileRef and FileLeafRef fields for list item.
When I execute `await list.LoadItemsByCamlQueryAsync(query)` and iterate over item collection, then I see only these properties in `item.Values` collection:
![image](https://user-images.githubusercontent.com/15668343/114917652-de49e100-9e2e-11eb-8cef-363e2ec708bc.png)
CAML query used to get the result:
```
<View>
    <ViewFields><FieldRef Name='FileRef' /><FieldRef Name='FileLeafRef' /></ViewFields>
</View>
```

Maybe I'm expecting from it what it shouldn't do? If so, then how could I get FileRef field value for my items?

## Steps to reproduce

1. Execute code:
```
using var ctx = await pnpContextFactory.CreateAsync(new Uri(notification.SiteUrl));
var query = @"
<View>
    <ViewFields><FieldRef Name='FileRef' /><FieldRef Name='FileLeafRef' /></ViewFields>
</View>
";
IList list = await ctx.Web.Lists.GetByIdAsync(new Guid(notification.Resource));
await list.LoadItemsByCamlQueryAsync(query);
foreach (var item in list.Items.AsRequested())
{
  var a = item;
}
```
2. Put break point on `var a = item`
3. Inspect `item` variable `Values` property
4. 
![image](https://user-images.githubusercontent.com/15668343/114918406-b8710c00-9e2f-11eb-814e-bcd0b0e4701e.png)

## Expected behavior

I should see under `Values` property FileRef and FileLeafRef as with SharePoint REST API, when you add `?$select=FileRef,FileLeafRef` to the request.

## Environment details

- **SDK version**: 1.1.0
- **OS**: Windows 10
- **SDK used in**: C# Azure Function
- **Framework**: .NET Core v3.1
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2019 Enterprise v16.9.4
- **Additional details**: Project file:
 ```
 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="PnP.Core" Version="1.1.0" />
    <PackageReference Include="PnP.Core.Auth" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

 ```

### Additional context

N/A

**Comment by jansenbe** [comment]
@wonderplayer : Hmm...maybe try using FileLeafRef and FileDirRef...I use this in the Page API implementation and they work: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs#L303

**Comment by wonderplayer** [comment]
Nope, didn't work. Included them _FileDirRef_ in the query as well and can't select any of them
![image](https://user-images.githubusercontent.com/15668343/114975188-7924d880-9e8c-11eb-9395-73610281e6f2.png)
Tried to include _FileLeafRef_ in `Where` element and query did filter results, but I didn't get _FileLeafRef_ back.
```
<View>
    <ViewFields><FieldRef Name='FileRef' /><FieldRef Name='FileLeafRef' /><FieldRef Name='FileDirRef' /></ViewFields>
    <Query>
        <Where>
            <Eq>
                <FieldRef Name='FileLeafRef'/>
                <Value Type='text'>Test.aspx</Value>
            </Eq>
        </Where>
    </Query>
</View>
```

**Comment by jansenbe** [comment]
Can you try with using LoadListDataAsStreamAsync() instead of LoadItemsByCamlQueryAsync()...different API but result will be the same. See https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-the-listdataasstream-approach for an example

**Comment by jansenbe** [comment]
I just confirmed that LoadItemsByCamlQueryAsync() never returns these "system" properties, LoadListDataAsStreamAsync() however does.

**Comment by wonderplayer** [comment]
It worked! This time I got a lot more values and also my custom properties:
```
item.Values.Keys
Count = 27
    [0]: "PermMask"
    [1]: "FSObjType"
    [2]: "HTML_x0020_File_x0020_Type"
    [3]: "UniqueId"
    [4]: "ProgId"
    [5]: "NoExecute"
    [6]: "ContentTypeId"
    [7]: "FileRef"
    [8]: "_UIVersion"
    [9]: "SMTotalSize"
    [10]: "File_x0020_Size"
    [11]: "_CommentFlags"
    [12]: "Site_x0020_news_x0020_flow_x0020_in_x0020_progress"
    [13]: "FileLeafRef"
    [14]: "Modified"
    [15]: "Landing_x0020_site_x0020_news"
    [16]: "ItemChildCount"
    [17]: "FolderChildCount"
    [18]: "A2ODMountCount"
    [19]: "_StubFile"
    [20]: "_ComplianceTag"
    [21]: "owshiddenversion"
    [22]: "_SPSitePageFlags"
    [23]: "ContentVersion"
    [24]: "DocConcurrencyNumber"
    [25]: "_VirusStatus"
    [26]: "Restricted"
```
Thank you, @jansenbe 😊

**Comment by DaleyKD** [comment]
I just noticed, based on the images here, that `LoadItemsByCamlQueryAsync` returns `FileSystemObjectType`, but `LoadListDataAsStreamAsync` returns `FSObjType`.  Interesting.
