### ISSUE TITLE
Provide a method to execute low level REST requests

### ISSUE THREAD

**Issue by PaoloPia** [pnp/pnpcore#41]
Something like a method with at least two overloads:

- Json ExecuteRequest(RESTRequest) => will return the raw json response
- IEnumerable<TResult> ExecuteRequest(RESTRequest) => will return a fully typed collection of entities defined in the domain model

**Comment by jansenbe** [comment]
Related to #3, for graph related linq queries paging should work automatically if the nextlink odata property is returned

**Comment by jansenbe** [comment]
The `BaseRequest/BaseBatchRequest` methods provide this already for internal use, we can open up these methods for public use as well

**Comment by jansenbe** [comment]
Also think about a method to execute a request and return the json without trying to load it into the model, there are cases where this makes sense (eg operations on an model entity)

**Comment by jansenbe** [comment]
Added method for raw requests (`RawRequestAsync` internal only), allowing folks to perform an action (e.g. recycle a list) and get back the resulting json. Docs to follow

**Comment by jansenbe** [comment]
We have now have internal methods (see https://pnp.github.io/pnpcore/articles/contributor/extending%20the%20model%20-%20SharePoint%20REST.html#doing-additional-api-calls). Given we want to extend the model to cover all needs instead of having sdk users start making raw calls themselves I'm moving this off the preview 2 milestone.

**Comment by jansenbe** [comment]
Actually closing this one, this kind of defeats the purpose of building a fluent SDK. If folks need additional calls they'd better request this to us via an issue or submit a PR
