### ISSUE TITLE
IListItem.GetFolder return Parent IFolder instead of the current folder

### ISSUE THREAD

**Issue by seanix99** [pnp/pnpcore#413]
## Category

- [x] Bug

## Steps to reproduce

// get a IListItem from what method you want for a folder 

// Here item represent: http://test.sharepoint.com/sites/test/documents/TestFolder

IListItem item = ....

If (item.IsFolder())
{
  IFolder folder = item.GetFolder(); 
  // here instead of receiving an IFolder object that represent the TestFolder, we receive an IFolder that represent the root folder.
}

## Expected behavior

GetFolder(), should return an IFolder representing the current ListItem when its a folder.

## Environment details (*development & target environment*)

> **DELETE THIS LINE BEFORE SUBMITTING** - Complete the following (*if ignored you'll be prompted for it before we can address your issue... save the time and provide it in your initial submission*).

- **SDK version**: 1.1.0
- **Framework**: .Net Core

**Comment by DaleyKD** [comment]
For what it's worth, if I have any luck, I'm working on a PR that'll include IListItem properties, one of which is Folder.  It would possibly satisfy this issue.

I'll have more info after writing unit tests tomorrow.

**Comment by DaleyKD** [comment]
@jansenbe & @seanix99 , what's the status with this?

If you grab a nightly, you can load the actual Folder object of the ListItem using the `IListItem.Folder` property.  And then you can use `.GetFolder()` to grab the folder to which the listItem belongs based on `FileDirRef`

Should we rename the function to be a bit less confusing?  `GetParentFolder`?  `GetContainerFolder`?  🤷‍♂️

**Comment by jansenbe** [comment]
GetParentFolder makes sense to me...I'm doing the rename, so closing this issue. Thanks raising it again @DaleyKD
