### ISSUE TITLE
Implement cross site collection copy/move

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#414]
Current implementation supports copy/move inside the site collection, cross site collection requires using different APIs. See https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/CopyMover.cs for a sample implementation.

**Comment by DaleyKD** [comment]
Is this a duplicate of #301  ?

**Comment by jansenbe** [comment]
Good point, I'll close #301....one issue less :-)

**Comment by MathijsVerbeeck** [comment]
Hi @jansenbe 

I'd like to assist on this issue.

**Comment by jansenbe** [comment]
All yours @MathijsVerbeeck 🚀

**Comment by MathijsVerbeeck** [comment]
@jansenbe I wanted to look into this, but I noticed that this already has been implemented, however not using the CreateCopyJobs API but using the _api/SP.MoveCopyUtil.CopyFileByPath API call. Do I still have to implement this using the CreateCopyJobs API?

**Comment by jansenbe** [comment]
@MathijsVerbeeck : having a look at things, will reply shortly

**Comment by jansenbe** [comment]
@MathijsVerbeeck : the existing implementation works indeed cross site but is limited to copying a single file (no list items) whereas the CreateCopyJobs API can do files/folders/listitems and can do things in bulk (hence they work async). I would propose to add the needed extension methods at `ISite` to support this feature:

- `CreateCopyJobs` and `CreateCopyJobsAsync`
- `GetCopyJobProgress` and `GetCopyJobProgressAsync`

Would that work for you?

**Comment by MathijsVerbeeck** [comment]
@jansenbe : Seems good to me.

**Comment by jansenbe** [comment]
Thanks once more of this contribution @MathijsVerbeeck ! Just merged it, so closing this issue.
