### ISSUE TITLE
Demo.AzureFunction Run Fails - Microsoft.Identity.Client: Value cannot be null. (Parameter 'certificate')

### ISSUE THREAD

**Issue by master455** [pnp/pnpcore#415]
## Category

- [x] Bug

I downloaded sample Demo.AzureFunction from [offical repository](https://github.com/pnp/pnpcore/tree/dev/samples/Demo.AzureFunction). I followed the steps to [configure application in AAD using PnP PowerShell](https://pnp.github.io/pnpcore/using-the-sdk/configuring%20authentication.html#configuring-the-application-in-azure-ad-1) (it was successful) and configure local.settings.json with application info (TenantId, ClientId, CertificateThumbPrint, WEBSITE_LOAD_CERTIFICATES). I build solution and run project, I receive following error:

 **Microsoft.Identity.Client: Value cannot be null. (Parameter 'certificate').**

**Note:** I'm using visual studio 2019 enterprise version 16.9.2.

**Comment by jansenbe** [comment]
@master455 : What version of Azure Functions are you using? Seems as the thumbprint used to identify the certificate is not found, can you cross check that one?

**Comment by master455** [comment]
@jansenbe Hello thanks for reply, I'm using Azure Function version .Net Core 3.1 (by default in example),  I access to AAD application => Certificates & secrets and verify Thumbprint code, it's similar like 2C51643GH98DTE4B37TG231C546B44554166CF7E. I configure it in local.settings.json:

"CertificateThumbPrint": "2C51643GH98DTE4B37TG231C546B44554166CF7E",
"WEBSITE_LOAD_CERTIFICATES": "2C51643GH98DTE4B37TG231C546B44554166CF7E"

**Comment by jansenbe** [comment]
Are you testing on your local machine or have you deployed the Azure function?

**Comment by master455** [comment]
I am testing on my local machine; do I need make any additional configuration?

**Comment by jansenbe** [comment]
Which cert store did you load the cert in? The local code needs to be able to read it

**Comment by master455** [comment]
Thanks for clue, I understand better now.. I need load .pfx in certificate store and later reference it. Maybe could be obvius, but may a good option specify in official documentation when generate certificate with powershell.

**Comment by Ofer-Gal** [comment]
I am getting the same error in Azure.
```Value cannot be null. (Parameter 'certificate')``` It works fine on the PC
Can I use the PFX file instead of the thumbprint?

**Comment by master455** [comment]
I may recommend If you use windows instance, you must load .pfx (TLS/SSL Settings) and add thumbprint number in configuration.
