### ISSUE TITLE
Add support for setting/reading listitem level retentiontags (= policy labels)

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#417]
See https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.ListItem/func/SetComplianceTag, https://www.rlvision.com/blog/setting-sharepoint-retention-labels-programmatically/ and https://www.c-sharpcorner.com/blogs/add-retention-label-and-retention-start-date-to-sharepoint-document-using-csom for some inspiration

**Comment by DaleyKD** [comment]
Aren't these implemented?  I swear my teammate just tested SetComplianceTag for a SPIKE we had to run. Seemed to work.

**Comment by DaleyKD** [comment]
Side note, it might be nice to have the `SPPolicyStoreProxy` from CSOM here, too.  Things like listing the existing tags, etc.  I'm still baffled there's not a way to programmatically create retention labels.

**Comment by jansenbe** [comment]
The needed support is in place, we have setting compliance tags for list and list items, getting compliance tags for a list and for site, but not for a list item. For getting list item compliance tags one can read the list item and grab the _ComplianceTag field
