### ISSUE TITLE
IListItem Content Type

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#419]
## Category

- [x] Domain model extension

## Describe the domain model extension
Get list item's content type + content type ID

### Model
**Model**: IListItem
**Properties**: ContentTypeId, ContentType

### APIs
API: `https://graph.microsoft.com/v1.0/sites/<siteId>/lists/<listId>/items/<itemId>`
and
API: `https://graph.microsoft.com/v1.0/sites/<siteId>/lists/<listId>/items/<itemId>/contentType`

API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)`
and
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)/contentType`

### Additional Information
[Content Types Microsoft Graph Documentation](https://docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-1.0)

I only specifically need `ID` and `Name` right now, but would like to load it when I load the `IListItemCollection`.

**Comment by DaleyKD** [comment]
Right now, to get the name of the ContentType, I'm having to rely on the entire `Values` bag and use "ContentType".  I'd rather be able to load this explicitly.

**Comment by jansenbe** [comment]
@DaleyKD : I've added support for the loading the content type when using LoadListDataAsStream. It only gets you a content type with name and id properties though. With the other changes you've done I think we now can get the content type populated for all listitem data retrieval approaches...You're good with closing this one or did I miss something?

**Comment by DaleyKD** [comment]
@jansenbe - Initial tests are great.  Closing now.
