### ISSUE TITLE
IListItem FileSystemObjectType and File / IsFile()

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#420]
## Category

- [x] Domain model extension

## Describe the domain model extension
We frequently will load `IListItemCollection` and `.Include()` (sorry for old CSOM) the following:

``` csharp
    item => item.ContentType.Id,
    item => item.ContentType.Name,
    item => item.FileSystemObjectType,
    item => item.Folder.ServerRelativeUrl,
    item => item.File.CheckedOutByUser,
    item => item.File.Exists,
    item => item.File.Name,
    item => item.File.ServerRelativeUrl,
    item => item.File.TimeCreated,
    item => item.File.TimeLastModified,
    item => item.File.Title,
    item => item.File.Length
```

We then condition on the `FileSystemObjectType` to determine if it is a Folder or File (or neither).

### Model
**Model**: IListItem
**Properties**: File, FileSystemObjectType

### APIs
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)`
and
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)/file`

_Not perfect_
API: `https://graph.microsoft.com/v1.0/sites/<siteId>/lists/<listId>/items/<itemId>/driveItem`

### Additional Information
[List Item Microsoft Graph Documentation](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0)

**Comment by DaleyKD** [comment]
Currently having to make an extra call using: `await context.Web.GetFileByServerRelativeUrlAsync(fileUri);`  Since we get a bunch of list items in a single call, having to do this seems expensive (one additional call per item... that hits REST a lot).

**Comment by DaleyKD** [comment]
Playing around with REST right now, it appears that the following works:
`https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)?$select=id,FileSystemObjectType`

Side note: not sure how this would work with using `LoadListDataAsStreamAsync`

**Comment by jansenbe** [comment]
Implemented. See https://github.com/pnp/pnpcore/commit/f4da869d751af29602d47b988dc19a2222367cc7

**Comment by DaleyKD** [comment]
@jansenbe - I appreciate the added functions, but this doesn't fix my actual need.

When loading an `IListItemCollection`, I need to grab the file properties immediately, preventing 10s of thousands of additional REST calls.  How can we add a `File` property so that it does some form of `$expand=file` for the List Item?

**Comment by jansenbe** [comment]
@DaleyKD : with the changes you've done now the following works and I hope this will be good solution for your needs. Note that we do automatically page per 100 using this approach:

```csharp
await foreach(var file in list.Items.QueryProperties(p => p.Id, p => p.Title, p => p.FileSystemObjectType,
                                                     p => p.ContentType.QueryProperties(c => c.Name, c => c.Id),
                                                     p => p.File.QueryProperties(f => f.Name, f => f.UniqueId),
                                                     p => p.Folder.QueryProperties(f => f.UniqueId, f => f.Name)).AsAsyncEnumerable())
{
    if (file.FileSystemObjectType == FileSystemObjectType.File)
    {

    }
}

```

**Comment by DaleyKD** [comment]
Great job.  I'm good with closing this for now.

Working on another PR so that we can do `IListItem.File.LoadAsync()`
