### ISSUE TITLE
FR: Additional Load Properties by Default

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#423]
## Category

- [x] Feature request

## Describe the feature
Currently, when you use the `PnPContextFactory` to create a new `PnPContext`, it calls two endpoints: one for site, and one for web.

The site loads the `ID` and `GroupID`. For my needs, I need the `Url` property, too.  This forces yet a third call, just for an additional, always needed property.

## Describe the solution you'd like
Ideally, there'd be some type of property on `PnPContextFactoryOptions` that would allow us to add properties to load when we "spin up a new context," therefore reducing the number of calls just to "get going."

Thank you for your consideration.

**Comment by DaleyKD** [comment]
#462 addresses this.

**Comment by DaleyKD** [comment]
@jansenbe successfully created a commit for this.  https://github.com/pnp/pnpcore/commit/794e520598986339f9cadead7a93e1c8c8467ec9

I will implement this in my code tomorrow after tonight's nightly.

**Comment by jansenbe** [comment]
I trust this work...if not you can blame me :-)
