### ISSUE TITLE
Where is the GetHubSiteData method located?

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#424]
## Category

- [x] Bug

## Describe the bug
Hello,
I am not sure if this is a bug or just me not able to find the required information. I checked [this](https://pnp.github.io/pnpcore/using-the-sdk/sites-hubsites.html) link explaining that you can retrieve the Hubsite information (URL and Title) by using this code snippet.

```
var hubResult = await context.Site.GetHubSiteData(site.HubSiteId);
var title = hubResult.Title;
var siteUrl = hubResult.SiteUrl;
```

## Steps to reproduce
- asp.net core solution with PnP.Core (1.1.0) and PnP.Core.Auth (1.1.0) installed
- not able to locate the method GetHubSiteData und the site context

## Expected behavior
The GetHubSiteData method is present or the documentation updated to provide the correct sample.

Thank you for your help,
Patrick

**Comment by jansenbe** [comment]
@plamber : that's in our nightly releases, will be part of 1.2 once we ship it.

**Comment by plamber** [comment]
When is the estimated time for that?

By chance can I also use that release?

**Comment by DaleyKD** [comment]
@plamber : https://www.nuget.org/packages/PnP.Core/1.1.34-nightly  (set your NuGet to look for prereleases)

**Comment by plamber** [comment]
@DaleyKD: awesome. Thank you. Will give it a try
