### ISSUE TITLE
IContentType Fields

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#425]
## Category

- [x] Domain model extension

## Describe the domain model extension
I appreciate that `IContentType` has `IFieldLinkCollection` on it. However, I'd do better with `IFieldCollection` on it, too.

### Model

**Model**: IContentType
**Properties**: `public IFieldCollection Fields { get; set; }`

### APIs
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/contentTypes('<contentTypeId'>)/fields`

_I don't see a good equivalent in Graph_

**Comment by jansenbe** [comment]
Thanks for the PR @DaleyKD
