### ISSUE TITLE
IListItem DisplayName + UniqueId

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#428]
## Category

- [x] Domain model extension

## Describe the domain model extension
Specifically, I need DisplayName and UniqueId, but really, I'd love to see `IListItem` fleshed out a bit more, like: https://github.com/pnp/pnpcore/blob/568a61199e11ba640d1fe91ade980225ea5c7be9/src/generated/SP/Internal/ListItem.cs

### Model
**Model**: IListItem
**Properties**: DisplayName, UniqueId

The interesting thing is that UniqueId is in the properties bag, but DisplayName isn't.  When looking at the returns of the REST endpoint, I can see why.

(The truth is, I'd love to see (almost NEED it) `IListItem` fleshed out using the majority of properties that MS.SP.Client.dll has, and that you have here: https://github.com/pnp/pnpcore/blob/568a61199e11ba640d1fe91ade980225ea5c7be9/src/generated/SP/Internal/ListItem.cs)

### APIs
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)?$select=UniqueId`
and
API: `https://<tenant>.sharepoint.com/sites/<site>/_api/web/lists(guid'<listId>')/items(<listItemId>)/displayname`

### Additional Information
[List Item SharePoint REST Documentation](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn531433(v=office.15)?redirectedfrom=MSDN#listitem-properties)

Here's something SUPER crazy:
![image](https://user-images.githubusercontent.com/7206282/117315311-30d65600-ae4d-11eb-96b6-b428d31094e0.png)

The docs say that `DisplayName` is returned as `Title`, but if I request `Title`, it's almost always `null`.

**Comment by jansenbe** [comment]
@DaleyKD : think this one can be closed now, if not then let me know and I reopen

**Comment by jansenbe** [comment]
@DaleyKD : I took a peek at the source code and the docs are not accurate. What is returned depends:

- If a field with internal name "Title" exists and the value is not empty/null that's used
- Special handling for survey, discussion board and link items --> should not be relevant in your case
- Value of the "First field with TitleField="TRUE" in their manifest"

**Comment by DaleyKD** [comment]
@jansenbe - Thank you so much for going the extra mile here.  The best I could do was look at Microsoft.SharePoint.dll (SP2019 w/ May 2021 CU), and see what they were doing for `SPListItem.DisplayName`.  :smile:

Is there a repo I can submit a request to allow `DisplayName` to be in the $select statement for a list item?
