### ISSUE TITLE
Extend authentication providers to support app-only

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#43]
Option to use certificate based auth
Option to use clientid/secret based auth

**Comment by jansenbe** [comment]
Note, option for access token based auth was already added via #44

**Comment by jansenbe** [comment]
Done as part of the auth rewrite

**Comment by ChrTall** [comment]
@jansenbe 
I can not find a way to authenticate with Client Id, Tenant Id and Client Secret.
Only with a Certificate, which is also a bit confusing as you have to enter StoreName and StoreLocation which seems to be Windows only if I am not mistaken. I have generated a certificate with openssl and uploaded it to AAD. Can you explain how I can do this on Linux?

**Comment by jansenbe** [comment]
@ChrTall : can you start a new discussion for this question?

**Comment by ChrTall** [comment]
@jansenbe Yes sorry, I will create a new issue.
