### ISSUE TITLE
RestClient has no authentication header configured

### ISSUE THREAD

**Issue by lennertcc** [pnp/pnpcore#438]
## Category

- [x] Bug

## Describe the bug

I am using PnPContext.RestClient.Client. The documentation describes this as: **connected SharePoint REST client**. 

I want to use this to make calls not supported by the object model, like SharePoint Search (/api/search/postquery).

Using the HttpClient any request with the client results in 403, 'Forbidden'.
Additional info from the response header shows: 
X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.

Using fiddler I found out that no authentication headers are submitted. I would expect it to, because of the description **connected SharePoint REST client**. If I have to configure the client myself, it is not really connected..

## Steps to reproduce

using (var context = await pnpContextFactory.CreateAsync("SiteToWorkWith"))
{
                    var web = await context.Web.GetAsync((web) => web.CurrentUser, (web) => web.Title, (web) => web.Url); //OK, results as expected
                    var client = context.RestClient.Client;
                    var contextInfoUrl = $"{web.Url}/_api/contextinfo";
                    var contextInfo = client.GetAsync(contextInfoUrl).Result; //403, forbidden
}

## Expected behavior

I would expect it to have authentication configured so that the client is ready to use, because of the description **connected SharePoint REST client**. If I have to configure the client myself, it is not really connected..

## Environment details (*development & target environment*)

- **SDK version**: 1.1.0 
- **OS**: Windows 10
- **SDK used in**: Console App 
- **Framework**: .NET Core v3.1
- **Tooling**: Visual Studio 2019

**Comment by lennertcc** [comment]
That is indeed how it works currently. To complete your answer: the token can be retrieved from the authentication provider in the PnPContext.

So to solve this bug: either return the client that is used internally, or update the documentation to state that this returns a new HttpClient.

**Comment by DaleyKD** [comment]
We had this same issue yesterday, and were temporarily using something like what's used in `BatchClient.cs`:
https://github.com/pnp/pnpcore/blob/3bc2ccfab4efe067e7cde2f07e9f65ec30bf588c/src/sdk/PnP.Core/Services/Core/BatchClient.cs#L1305-L1316

**Comment by jansenbe** [comment]
@lennertcc  / @DaleyKD : This is now possible via the new ExecuteRequestAsync/ExecuteRequest methods. See https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html for some early docs.
