### ISSUE TITLE
setuptestenv.ps1: webFullUrl cannot be null

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#443]
## Category

- [x] Bug

## Describe the bug
Fresh tenant, trying to run the `setuptestenv.ps1`.  After prompting for my creds, it gives an error dealing with the `Add-PnPWeb` cmdlet.

``` powershell
PS C:\repos\pnpcore\src\sdk\PnP.Core.Test> .\setuptestenv.ps1
Please enter UPN: kyle@gimmalkyle2.onmicrosoft.com
Please enter password: ***********
Input your tenant name (e.g. contoso): gimmalkyle2
VERBOSE: Acquiring token
VERBOSE: Token acquired
VERBOSE: PnP PowerShell Cmdlets (1.5.0.0)
Add-PnPApp : Value cannot be null.
Parameter name: webFullUrl
At C:\repos\pnpcore\src\sdk\PnP.Core.Test\setuptestenv.ps1:52 char:8
+ $app = Add-PnPApp -Path .\TestAssets\pnpcoresdk-test-app.sppkg
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPApp], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Apps.AddApp
```

## Steps to reproduce
Not sure what all is required to reproduce?  I had a fresh, brand new tenant.  Ran the script, and them it gave me that error.

## Expected behavior
Run the script without error.

## Environment details (*development & target environment*)
- **SDK version**: 1.1.0
- **OS**: Windows 10
- **Tooling**: PowerShell 5 (I also tried PowerShell 7)
- **Additional details**: PnP.PowerShell 1.5.0

### Additional context
I double-checked the `Add-PnPApp` cmdlet, and there is no parameter for `webFullUrl`.

**Comment by DaleyKD** [comment]
... Hoping that it's because I didn't have an App Catalog yet.  Waiting a bit to see if `Get-PnPTenantAppCatalogUrl` will return a URL... will report back in a bit.

**Comment by DaleyKD** [comment]
Yup!  That was it.  Hopefully if someone is as ... forgetful... as me in the future, this issue will remind them: "CREATE AN APP CATALOG!"

**Comment by jansenbe** [comment]
Thanks for letting me know @DaleyKD : wrote a short note in the script to clarify this
