### ISSUE TITLE
EnsureFolderAsync wrong work

### ISSUE THREAD

**Issue by vkorotenko** [pnp/pnpcore#446]
## Category

- [x] Bug

## Steps to reproduce
await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5");
// on this call break with exception sub1 already exist
await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5_1");

## Expected behavior
await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5");
await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5_1");
create folders and subfolder

**Comment by jansenbe** [comment]
@vkorotenko : which version are you using?

**Comment by vkorotenko** [comment]
> @vkorotenko : which version are you using? This should be fixed in version 1.1 or later if I'm not mistaken.
Hi thanks for fast reply, sorry but i not specify version is 1.1.0

http://dl3.joxi.net/drive/2021/05/13/0005/0257/389377/77/dcd34c1118.jpg

All package on a solution

Solution make on Visual studio 2019 latest version, and PnP latest stable version by nuget

**Comment by DaleyKD** [comment]
I can confirm that it does indeed work. No exception thrown.

``` C#
                    IList list = await context.Web.Lists.GetByTitleAsync(parentLibraryName, l => l.RootFolder);

                    var folder = list.RootFolder;
                    await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5");
                    await folder.EnsureFolderAsync("sub1/sub2/sub3/sub4/sub5_1");
```

![image](https://user-images.githubusercontent.com/7206282/118186420-5510d480-b403-11eb-802d-c98a89064f1c.png)

**Comment by jansenbe** [comment]
@vkorotenko : can you provide more details (e.g. stacktrace)? Also checkout the test cases that use EnsureFolderAsync (https://github.com/pnp/pnpcore/blob/3bc2ccfab4efe067e7cde2f07e9f65ec30bf588c/src/sdk/PnP.Core.Test/SharePoint/FoldersTests.cs#L528)

**Comment by jansenbe** [comment]
@vkorotenko : I'm closing this issue as there was no further feedback and our testing indicated this works. If you feel there still is an issue then please re-open or create a new issue with more details. Thanks.
