### ISSUE TITLE
Update "setting up your environment for developing" to clarify using a branch per github change

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#448]
See https://pnp.github.io/pnpcore/contributing/setup.html.

Best to clarify that creating a branch allows for isolating various fixes into different PR's

**Comment by DaleyKD** [comment]
I appreciate this. I can't believe how different Git is from TFS/VSTS/ADO.

**Comment by jansenbe** [comment]
Change done. When I first moved from TFS to Git it took me a while to get started as well, but I now I do prefer Git over TFS
