### ISSUE TITLE
IList GetByIdBatchAsync

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#449]
## Category

- [x] Domain model extension

## Describe the domain model extension
If I want to get a bunch of lists in a single batch, I'd think we should be able to do this.

### Model
Model: **IList**
Functions: **GetByIdBatchAsync**

**Comment by jansenbe** [comment]
@DaleyKD : we do have support for this scenario via the AsBatch() option. Below sample shows a single batch fetching 2 lists with for each lists the title property loaded.


```csharp
var list1 = await context.Web.Lists.Where(p => p.Title == "Documents").QueryProperties(p => p.Title).AsBatchAsync();
var list2 = await context.Web.Lists.Where(p => p.Title == "Site Pages").QueryProperties(p => p.Title).AsBatchAsync();

await context.ExecuteAsync();

Assert.IsTrue(list1.IsAvailable);
Assert.IsTrue(list1.FirstOrDefault().Title == "Documents");
Assert.IsTrue(list2.IsAvailable);
Assert.IsTrue(list2.FirstOrDefault().Title == "Site Pages");
```

**Comment by DaleyKD** [comment]
If there are no objections, can I try a future PR with a function that
makes it a little easier?

Also, question: is there a benefit to using the $filter vs. the
getbytitle('Documents')?

I noticed this earlier when I did GetByIdAsync on a list item... It uses
$filter instead of /items(103).

**Comment by jansenbe** [comment]
@DaleyKD : All flows via our central LINQ provider whichn in the end translates GetByIdAsync() into a $filter...Do you see a performance impact on the current approach?

**Comment by DaleyKD** [comment]
@jansenbe - I'm not sure if there's a performance impact or not.  I was actually hoping you knew. :smile:  My ONE concern is how the `$filter` will/won't work with List View Threshold issues.  If I can find time to load up 5000+ docs, I'll try to test and see if `$filter=title eq 'Documents'` works.

**Comment by DaleyKD** [comment]
I see no need for this anymore.  LVT hasn't been an issue in our current tests, and though it may not fit the code styling approach of using an actual pre-created `Batch`, the `.AsBatchAsync()` is sufficient.

**Comment by jansenbe** [comment]
Thanks for testing this @DaleyKD . AsBatchAsync() also accepts the batch variable if you want to work with a manually created batch

**Comment by luciusbv** [comment]
Well I've tried to use the suggested approach, but the outcome was... not the expected one...
My code we something like:
` private async Task<List<IListItem>> GetNewInfomails(List<IChangeItem> changes, IList changedList, PnPContext pnpContext, ILogger log)
        {
			var result = new IEnumerableBatchResult<IListItem>[changes.Count];

			for (var index = 0; index < changes.Count; index++)
			{
				var changeItem = changes[index];
				result[index] = await changedList.Items.Where(a => a.Id == changeItem.ItemId).AsBatchAsync();
			}
			await pnpContext.ExecuteAsync();`

The batch request is properly sent, but also for each component of the batch an extra call to get source list fields is sent afterwards. 
![image](https://user-images.githubusercontent.com/45073117/153289053-d2edd5e2-19aa-4d4c-98c3-0eb85373c004.png)

@jansenbe  Any idea what I might have missed? Its worth noting the "Fields" member was already loaded on changedList instance before entering in the method.
Thanks!

**Comment by jansenbe** [comment]
@luciusbv : fields are loaded automatically when needed, in this scenario it's probably best to load the once for each list before loading the list items via the batch endpoint. The code will see the loaded fields and not load then again.

**Comment by luciusbv** [comment]
Thank you for your answer, Just some additional remarks, I hope it will help someone:
As mentioned above, I was already loading the Fields collection before executing the code above by doing something like:
`IList changedList = await pnpContext.Web.Lists.GetByIdAsync(listId, p => p.Id, p => p.Title, a => a.Fields.QueryProperties(f => f.InternalName, f => f.TypeAsString, f => f.FieldTypeKind, f => f.Title));`

However this does not work, my assumption is there is something broken to the mechanism that checks if the fields are already loaded. 

One somehow related problem I found is the following:

`public async Task<IList<IChange>> GetListItemChanges(IList list, DateTime stardDate,
			bool includeAddChanges = false,
			bool includeUpdateChanges = false,
			bool includeDeleteChanges = false)
		{
			var lastChangeToken = new ChangeTokenOptions(string.Format("1;3;{0};{1};-1", list.Id, (stardDate.ToUniversalTime().Ticks + 1).ToString()));

			IList<IChange> changes = await list.GetChangesAsync(new ChangeQueryOptions()
			{
				Item = true,
				Folder = false,
				Add = includeAddChanges,
				Update = includeUpdateChanges,
				DeleteObject = includeDeleteChanges,
				ChangeTokenStart = lastChangeToken,
				FetchLimit = 1000
			});

			return changes;
		}`

the "list" instance has the set of fields loaded before executing the above code, After the call to GetChangesAsync the "Fields" collection gets gets erased and I have to reload it.
