### ISSUE TITLE
FR: Delete or Recycle Item without GET of IList first

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#450]
## Category

- [x] Feature request

## Describe the feature
One of our product requirements is to delete (or recycle) list items.  However, we do it way late in the pipeline, all by itself.

I realize I can do the following:
``` C#
using (var context = await GetPnPContextAsync(webUrl))
{
    // TODO: How to make this a singular REST call?
    var list = await context.Web.Lists.GetByIdAsync(listID);
    await list.Items.DeleteByIdAsync(listItemID);
}
```

But that's at minimum a GET for a site, a GET for a web, a GET for the list, and then a POST (delete) for the list item.  We know that, for this scenario, I don't need the first three GETs.

## Describe the solution you'd like
I don't have an answer on how to go about this.  Do we give the PnPContextFactory a parameter that would allow us to bypass the web/site GETs?  Then, how do we set up a function or function chain to let us do (which skips a list GET):

``` C#
await context.Web.Lists.GetByIdAsync(listID).Items.DeleteByIdAsync(listItemID);
```

Ideally, that should compose a POST like:
``` http
POST https://{site_url}/_api/web/lists(guid'')/items(157)
Authorization: "Bearer " + accessToken
Accept: "application/json;odata=verbose"
Content-Type: "application/json"
If-Match: "{etag or *}"
X-HTTP-Method: "DELETE"
```

## Additional context
I'm just trying to find ways to minimize HTTP calls to help optimize our product, and HOPEFULLY reduce those BLASTED 429s.

**Comment by jansenbe** [comment]
@DaleyKD : probably the easiest option would be to construct the delete call yourselves as shown here: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request.

**Comment by jansenbe** [comment]
@DaleyKD : building your own REST request will for sure work and is the only solution I can think of. Closing this issue, but feel free to re-open or create a new one if using a custom REST request does not work for you.
