### ISSUE TITLE
Documentation Requirement: Taxonomy Administrator

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#458]
## Category

- [x] Bug

## Describe the bug
When trying to run all the Unit Tests with `Mock = false`, the Taxonomy Tests will fail if you aren't a Term Store Admin.

## Steps to reproduce
I used the provided .ps1 to setup my environment.  It was pure and clean.

## Expected behavior
Either the .ps1 adds the credentials as a Term Store Admin, or the documentation needs to give us a heads up.

**Comment by DaleyKD** [comment]
Also, you need to add Dutch as a Working Language.

**Comment by jansenbe** [comment]
Updated, thanks for letting us know.
