### ISSUE TITLE
Ability to use ApiRequest in Batch

### ISSUE THREAD

**Issue by czullu** [pnp/pnpcore#460]
## Category

- [x] Feature request

## Describe the feature
It would be nice if APIRequest could be added to a Batch for example when working with planner.

## Describe the solution you'd like

 ```
var myBatch = context.NewBatch();
await context.Site.LoadBatchAsync(myBatch, s => s.GroupId);
var plannerRequest = new ApiRequest(ApiRequestType.Graph, $"groups/{context.Site.GroupId}/planner/plans");
await context.Group.LoadBatchAsync(myBatch, plannerRequest);
await context.ExecuteAsync(myBatch);
 ```

**Comment by jansenbe** [comment]
@czullu : started working on this, will be part of 1.2 soon

**Comment by czullu** [comment]
> @czullu : started working on this, will be part of 1.2 soon

Thank you, i have tried it but got kind of lost within all the Interfaces and therefore put it beside in the hope off a quite moment.

**Comment by jansenbe** [comment]
This will be the way to use it:

```csharp

var batch = context.NewBatch();
var webResponse = context.Web.ExecuteRequestBatch(batch, new ApiRequest(ApiRequestType.SPORest, "_api/web"));
Assert.IsTrue(webResponse.IsAvailable == false);
var siteResponse = context.Web.ExecuteRequestBatch(batch, new ApiRequest(ApiRequestType.SPORest, "_api/site"));
Assert.IsTrue(siteResponse.IsAvailable == false);

await context.ExecuteAsync(batch);

Assert.IsTrue(webResponse.IsAvailable);
Assert.IsFalse(string.IsNullOrEmpty(webResponse.Result.Value));
Assert.IsTrue(siteResponse.IsAvailable);
Assert.IsFalse(string.IsNullOrEmpty(siteResponse.Result.Value));

```

**Comment by DaleyKD** [comment]
NICE!  I assume it returns a raw response?

**Comment by jansenbe** [comment]
yes, you'll get the json string back

**Comment by jansenbe** [comment]
@czullu / @DaleyKD : implemented. See https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#batching-custom-api-requests for instructions.
