### ISSUE TITLE
Invoke-PnPSiteTemplate: Does not create the page templates folder with correct name from XML

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#466]
Using Get-PnpSiteTemplate to get PageContents and Pages on a site with Swedish default language
Get-PnPSiteTemplate -IncludeAllClientSidePages -Handlers PageContents,Pages -out c:\temp\templates.xml

XML extract =>
<pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="true" Overwrite="true" Title="news" ThumbnailUrl="" PageName="Mallar/news.aspx">

Using Invoke-PnPSiteTemplate the page templates are created under folder Templates not Mallar as in XML extract.
Invoke-PnPSiteTemplate -Connection $targetConnection -Path c:\temp\templates.xml

Does the Invoke-PnPSiteTemplate always create page templates in hardcoded folder "Templates"? and not the using the path in XML => PageName="Mallar/news.aspx" ?

Thanks in advance

**Comment by jansenbe** [comment]
Hi @matsla : I've been able to reproduce this, there was a bug in detecting the current "templates" folder.

**Comment by jansenbe** [comment]
Fix is in. Should work with tomorrow's nightly PS build
