### ISSUE TITLE
Extend the SharePoint model for Content Types and Fields

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#47]
## Category

- [x] Domain model extension

## Describe the domain model extension

Extending the SharePoint model to work for Content Types and Fields

**Comment by jansenbe** [comment]
Thanks @ypcode for the content type updates. I'll create a new issue to track the need for CSOM to create content types with a given ID (or alternatively we need to inspect if Graph can do this somehow)

**Comment by ypcode** [comment]
Was also my second guess... that if Graph handles it better we might not need the CSOM mimicking altogether for that purpose. But that needs to be checked :)

**Comment by jansenbe** [comment]
Done now, thanks a ton @ypcode !
