### ISSUE TITLE
Invalid data with in list item properties do not update item. Neither throw exception nor response message nor succeed to upload on SharePoint

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#477]
IF I add dummy data under the property of item under batch.
like "ABC" under DateTime property, it neither throws exception nor gives the response message, neither update on SharePoint itself.
Just completed as a successful commit.

Please help

**Comment by jansenbe** [comment]
@gopaldahal : list item properties are usable like other property bags in SharePoint, there's no explicit docs on the ListItem usage, but we have for usage of the property bag on a web: https://pnp.github.io/pnpcore/using-the-sdk/webs-intro.html#web-property-bag. Can you use the documented approach and check if that resolves your problem?

**Comment by gopaldahal** [comment]
@jansenbe, This is the sample of code I am running.

                var parentList = await context.Web.Lists.GetByTitleAsync("AddTest", l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
                var parentWeb = await context.Web.GetAsync(s => s.Language, s=>s.Url);
                var parentFields = parentList.Fields.ToList();

                List<Dictionary<string, object>> propertiesToUpdate = new List<Dictionary<string, object>>();
                var prop = new Dictionary<string, object>();
                prop.Add("Title", "My title 1");
                prop.Add("Created", "abc");
                propertiesToUpdate.Add(prop);
                var prop2 = new Dictionary<string, object>();
                prop2.Add("Title", "My title 2");
                propertiesToUpdate.Add(prop2);

                var uploadedListItems = new List<IListItem>();
                foreach (var propItem in propertiesToUpdate)
                {     
                    try
                    {
                        var item = await parentList.Items.AddBatchAsync(propItem);
                        uploadedListItems.Add(item);
                    }
                    catch(Exception ex)
                    {
                    }
                }
                var batchResponses = await context.ExecuteAsync(false);

                await uploadedListItems.First().LoadAsync(d => d.All);

                foreach (var batchResponse in batchResponses)
                {

                }

**Comment by jansenbe** [comment]
@gopaldahal : the issue in your code is with the `uploadedListItems` collection, you don't need to manually add a listitem, this is done automatically when the request added via AddBatchAsync() is executed (via context.ExecuteAsync()). Below code works in my testing:

```csharp
var parentList = await context.Web.Lists.GetByTitleAsync("BertTest", l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
var parentWeb = await context.Web.GetAsync(s => s.Language, s => s.Url);
var parentFields = parentList.Fields.ToList();

List<Dictionary<string, object>> propertiesToUpdate = new List<Dictionary<string, object>>();
var prop = new Dictionary<string, object>();
prop.Add("Title", "My title 1");
propertiesToUpdate.Add(prop);
var prop2 = new Dictionary<string, object>();
prop2.Add("Title", "My title 2");
propertiesToUpdate.Add(prop2);

foreach (var propItem in propertiesToUpdate)
{
    var item = await parentList.Items.AddBatchAsync(propItem);
}
var batchResponses = await context.ExecuteAsync(false);

await parentList.Items.AsRequested().First().LoadAsync(d => d.All);
```

**Comment by jansenbe** [comment]
@gopaldahal : the issue in your code is with the `uploadedListItems` collection, you don't need to manually add a listitem, this is done automatically when the request added via AddBatchAsync() is executed (via context.ExecuteAsync()). Below code works in my testing:

```csharp
                var parentList = await context.Web.Lists.GetByTitleAsync("BertTest", l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
                var parentWeb = await context.Web.GetAsync(s => s.Language, s => s.Url);
                var parentFields = parentList.Fields.ToList();

                List<Dictionary<string, object>> propertiesToUpdate = new List<Dictionary<string, object>>();
                var prop = new Dictionary<string, object>();
                prop.Add("Title", "My title 1");
                propertiesToUpdate.Add(prop);
                var prop2 = new Dictionary<string, object>();
                prop2.Add("Title", "My title 2");
                propertiesToUpdate.Add(prop2);

                foreach (var propItem in propertiesToUpdate)
                {
                    var item = await parentList.Items.AddBatchAsync(propItem);
                }
                var batchResponses = await context.ExecuteAsync(false);

                await parentList.Items.AsRequested().First().LoadAsync(d => d.All);
```

**Comment by gopaldahal** [comment]
Thank you @jansenbe for the code.
Unfortunately, "parentList.Items.AsRequested().First().LoadAsync(d => d.All)" do no load all the item.Values. Only limited property values are being loaded. Item that is being uploaded to list has more than 70 fields, but "d.All" just loads around 10-15 values.
But I need to refresh/need all the fields.

Besides, my problem is with the assignment of invalid data. 
Eg Assignment of DateTime with dummy string as example above.

**Comment by jansenbe** [comment]
The most flexible approach to load list items with all the fields you need is doing a CAML query, like shown here via the ListDataAsStream option: https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#using-the-listdataasstream-approach

**Comment by jansenbe** [comment]
Please create a new issue with the specific issues using the ListDataAsStream method in case you can't get that to work, in the meantime I'll close this issue.
