### ISSUE TITLE
IListItem - Versions

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#479]
https://s-kainet.github.io/sp-rest-explorer/#/entity/Collection(SP.ListItemVersion)
https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.ListItemVersion

@jansenbe - Would you assign this to me?  I'll try to get to it this week.  Looks like this was missing and we'll need it for our product soon.

**Comment by jansenbe** [comment]
Thanks for the great work @DaleyKD , just merged your PR so closing the issue
