### ISSUE TITLE
FileVersion GetContent Using Invalid URL

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#482]
## Category

- [x] Bug

## Describe the bug
Right now, `FileVersion` is using `$"{PnPContext.Uri}/_layouts/15/download.aspx?SourceUrl={Url}";`, which may work great for a file that is NOT a `FileVersion`, but if the URL is `_vti_history/512/MyDocLib/wordTest.docx`, you actually get this from SharePoint:
![image](https://user-images.githubusercontent.com/7206282/121571408-97203c80-c9e8-11eb-8fce-ff8ab155287f.png)

## Proposed Resolution
@jansenbe - If you have no issues with it, I'd rather use the [OpenBinaryStream](https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.FileVersion/func/OpenBinaryStream) function.  If you're good with this, feel free to assign this to me, as I need to get this fixed ASAP for our team.

## Side Question
What kind of download size limitations are we going to hit?

**Comment by DaleyKD** [comment]
Gee golly willikers.

The actual URL is simply: `$"{PnPContext.Uri}/_vti_history/512/MyDocLib/wordTest.docx`, aka `$"{PnPContext.Uri}/{Url}`

I'm not sure which way is better, but I'm ok with using this way if it satisfies my team's testing.

**Comment by jansenbe** [comment]
Using download.aspx is recommended as it's the most stable approach, so ideally we keep using that. But seems you've got it working now?

**Comment by DaleyKD** [comment]
Well, no.  I don't.  PnP.Core still has a bug.

My bug is still accurate.  You can't use `IFileVersion.GetContentAsync()`.  If you look at `GetFileVersionContentAsyncTest-2-00003.response`, you'll see that it's the HTML markup for the Error page in my screenshot above.  IOW, `download.aspx` does **not** work for use with the `_vti_history` URLs.

It seems that the proper use to get these binaries is to either:
- Replace the code in `IFileVersion.GetContentAsync()` to use the OpenBinaryStream function that is on `IFileVersion`
- Replace the code in `IFileVersion.GetContentAsync()` to literally just do a GET on `$"{PnPContext.Uri}/_vti_history/512/MyDocLib/wordTest.docx`

**Comment by jansenbe** [comment]
OK, that clarifies... Don't have a specific preference given the "regular" download will not be updated. You might want to test with some larger files, but assume both approaches will work

**Comment by DaleyKD** [comment]
Welp, looks like `_vti_history` doesn't like using bearer tokens. 🙄 Getting a 401 when I try to use that URL.

Going to convert to using GetContentAsync for now.  May have to use that temporarily until I can come back and do large file tests.

**Comment by jansenbe** [comment]
Thanks for fixing this, just merged your PR so closing the issue
