### ISSUE TITLE
List Item Attachments Operation missing!

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#492]
## Category

- [x] Feature request

## Describe the feature

Didn't find the list item Attachments operations.
Rest Provided operations are available on the shared link
https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.ListItem

## Describe the solution you'd like

It would be great to have the List Item Attachments support soon.
Since we are already working on Batch operations and are supported on most of the cases, It would add more spice, if the support is available on Batch operations too.

## Additional context

Sharing is Caring! Thank you!

**Comment by jansenbe** [comment]
@gopaldahal : listing/deleting the list attachments can work in batch, adding them will require a roundtrip per attachment to add, same applies to downloading the actual attachments

**Comment by jansenbe** [comment]
Closing this one as it was answered via #495

**Comment by gopaldahal** [comment]
Hi @jansenbe, I don't know how this item is related to the batch upload of attachments Since we don't have any feature neither using batch. 

Please correct me if I am wrong, but I didn't see any method that supports just a single upload of attachment on the dataitem.
And it is obvious that a list item can have multiple attachments. And this will come in mass sooner.
I think we need to work out on it rather than showing the option of migration API as suggested by #495

**Comment by jansenbe** [comment]
Correct, I'll create a new issue to track the need for uploading list item attachments
