### ISSUE TITLE
Add-PnpListItem with Batch cannot add values

### ISSUE THREAD

**Issue by Micael-stack** [pnp/pnpcore#493]
## Category
- [x] Bug

## Describe the bug

1. If i use Add-PnpListitem normally without batch, my item is fully created with my given values. 
![image](https://user-images.githubusercontent.com/52808567/122944570-f154c200-d345-11eb-99f0-a3d9146996e2.png)

2. But if the command is run with batch param, Invoke-PnpBatch does nothing. there is no details and no error. The batch is cleared too.
![image](https://user-images.githubusercontent.com/52808567/122944799-1e08d980-d346-11eb-91a4-66fee8a44e0c.png)
![image](https://user-images.githubusercontent.com/52808567/122944965-3b3da800-d346-11eb-94c8-219d5c2543fe.png)

3. If I run the same thing, with only my title as value in Add-PnpListItem, the batch will complete and my items are created.
![image](https://user-images.githubusercontent.com/52808567/122945467-9a032180-d346-11eb-8289-b0be44f1600e.png)
![image](https://user-images.githubusercontent.com/52808567/122945532-a4252000-d346-11eb-803c-a05eaa82adea.png)

## Environment details (*development & target environment*)
VsCode Ps 7.1 
PnP.PowerShell 1.6.0

**Comment by jansenbe** [comment]
@Micael-stack : this is the same issue as in #496 and #498. Let's use #498 to track this.

**Comment by jansenbe** [comment]
Closing this as it's a duplicate as mentioned above
