### ISSUE TITLE
Batch upload of Files

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#495]
## Category

- [x] Feature request

## Describe the feature

Is there any way we can upload files on batch?

## Additional context

Sharing is Caring!

**Comment by jansenbe** [comment]
@gopaldahal : that's not an option using the regular REST or Graph API's. We however do have specific migration API's that typically are used by migration ISVs to perform bulk operations. See https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview for some more context. Doing a quick checks shows that these APIs can be used from REST (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Site/func/CreateMigrationJob). You can explore how these APIs work in your scenario and do some testing by making the needed REST calls via our custom API call option: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request

**Comment by jansenbe** [comment]
Hi @gopaldahal, given that these migration APIs are specific for migration tool vendors we're currently not planning to add support for them in PnP Core SDK, so I'll close this issue. You can however use the custom API call option to integrate them in your code base: https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request
