### ISSUE TITLE
Not able to Set value of "MetaInfo" property of item during batch commit.

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#496]
## Category

- [x] Bug

## Describe the bug

If I set the MetaInfo value during the batch commit, The value is not being preserved.
It is just being set after the item is created and is updated using item.update()

## Steps to reproduce

```
            var parentList = await context.Web.Lists.GetByTitleAsync("AddTest", l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
            var parentWeb = await context.Web.GetAsync(s => s.Language, s=>s.Url);
            var parentFields = parentList.Fields.ToList();

            List<Dictionary<string, object>> propertiesToUpdate = new List<Dictionary<string, object>>();
            var prop = new Dictionary<string, object>();
            prop.Add("Title", "My title 1");
            prop.Add("MetaInfo", "abc");
            propertiesToUpdate.Add(prop);
            var prop2 = new Dictionary<string, object>();
            prop2.Add("Title", "My title 2");
            propertiesToUpdate.Add(prop2);

            var uploadedListItems = new List<IListItem>();
            foreach (var propItem in propertiesToUpdate)
            {     
                try
                {
                    var item = await parentList.Items.AddBatchAsync(propItem);
                    uploadedListItems.Add(item);
                }
                catch(Exception ex)
                {
                }
            }
            var batchResponses = await context.ExecuteAsync(false);

            await uploadedListItems.First().LoadAsync(d => d.All);

            foreach (var batchResponse in batchResponses)
            {

            }

```
## Expected behavior

MetaInfo Property should have been preserved using Batch. IF Property needs to be manually updated after batch, the complete batch may not be achieved.
## Environment details (*development & target environment*)

- **SDK version**: [1.1.0 ]
- **OS**: [Windows 10]
- **SDK used in**: [Console App ]
- **Framework**: [NET Framework v4.7.2 ]
- **Tooling**: [Visual Studio 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Thanks for reporting this @gopaldahal , I'll have a look

**Comment by jansenbe** [comment]
@gopaldahal : things seem to go wrong as soon as you're adding extra fields (so MetaInfo in your case)...I'll investigate

**Comment by jansenbe** [comment]
@gopaldahal : this is the same issue as #498 and #493. Let's use #498 to track this.

**Comment by jansenbe** [comment]
Closing this one as duplicate
