### ISSUE TITLE
Adding multiple ListItem problem

### ISSUE THREAD

**Issue by dhz1234** [pnp/pnpcore#498]
## Category

- [x] Bug

## Describe the bug

I have a foreach cycle to define and upload multiple ListItem in a SharePoint List. 
The items are created inside some subfolders. (but I also tried in the root of the library)
The first Item is correctly created, all the next items are not created and no error or exception is rised.

## Steps to reproduce

```
IList list = await ctx.Web.Lists.GetByIdAsync(new Guid(config.Value.ListIdSessioniFormative));

foreach (var session in edition.sessions)
{
          Dictionary<string, object> data = new Dictionary<string, object>()
          {
              { "Title", edition.editionCode },
              // various metadata
          };
          IListItem item = list.Items.Add(data, $"{folderCompany}/{folderYear}");
}
```

## Expected behavior

A number of item equal to the foreach round should be created.

## Environment details (*development & target environment*)

- **SDK version**: [1.2.0 ]
- **OS**: [Windows 10]
- **SDK used in**: [ASP.Net Web app]
- **Framework**: [.NET Core v3.1 ]
- **Browser(s)**: [Chrome v90]
- **Tooling**: [Visual Studio 2019]
- **Additional details**: 

### Additional context

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide any other context about the problem.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Thanks for reporting this @dhz1234 , I'll have a look

**Comment by jansenbe** [comment]
@dhz1234 : I just wrote below test case and things do work from my side (see code below). 

```csharp
var listTitle = TestCommon.GetPnPSdkTestAssetName("BulkAddListItemsTest");
var list = await context.Web.Lists.AddAsync(listTitle, ListTemplateType.GenericList);

// Enable folder creation
await list.EnsurePropertiesAsync(l => l.RootFolder);
list.ContentTypesEnabled = true;
list.EnableFolderCreation = true;
list.Update();

// Create a folder named Test
var folderItem = await list.AddListFolderAsync("Test");

// Add 10 items to folder test
for (int i = 0; i < 10; i++)
{
    Dictionary<string, object> data = new Dictionary<string, object>()
      {
          { "Title", $"Item {i}" },
          // various metadata
      };
    IListItem item = list.Items.Add(data, "Test");
}

await list.DeleteAsync();
```

Do note that you can also batch these adds, this way you'll only have one server roundtrip versus 10:

```csharp
for (int i = 0; i < 10; i++)
{
    Dictionary<string, object> data = new Dictionary<string, object>()
      {
          { "Title", $"Item {i}" },
          // various metadata
      };
    IListItem item = list.Items.AddBatch(data, "Test");
}
// Send batch to the server
await context.ExecuteAsync();
```

**Comment by jansenbe** [comment]
@dhz1234 : looking into another issue revealed that list items are not added anymore whenever there's more than the title field in the payload...investigating now...

**Comment by jansenbe** [comment]
@dhz1234 , @gopaldahal, @Micael-stack: when setting custom field properties it's **required** to use the field's **InternalName**. When adding fields SharePoint sometimes appends a number to the name you've provided, so when adding for example a field with name "MetaInfo" the actual internal name will be "MetaInfo0". 

Can you confirm that when using the actual internal name of the field the batch add does work.


```csharp
var list = await context.Web.Lists.AddAsync(listTitle, ListTemplateType.GenericList);
                
IField myField = await list.Fields.AddTextAsync("MetaInfo", new FieldTextOptions()
{
    Group = "Custom Fields",
    AddToDefaultView = true,
});

List<Dictionary<string, object>> propertiesToUpdate = new List<Dictionary<string, object>>();

var prop = new Dictionary<string, object>
{
    { "Title", "My title 1" },
    { myField.InternalName, "abc" }
};
propertiesToUpdate.Add(prop);

var prop2 = new Dictionary<string, object>
{
    { "Title", "My title 2" },
    { myField.InternalName, "abc" }
};
propertiesToUpdate.Add(prop2);

var uploadedListItems = new List<IListItem>();
foreach (var propItem in propertiesToUpdate)
{
      var item = await list.Items.AddBatchAsync(propItem);
      uploadedListItems.Add(item);
}

var batchResponses = await context.ExecuteAsync(false);
```

**Comment by dhz1234** [comment]
@jansenbe I found my issue.
The problem was on a specific field that was causing problems. 
But I think that this could be an issue too:

I have to populate a people field with multiple users.
All the listItems that i'm adding have the same list of users, so I calculate the field right before the "for" loop, in this way:

```
IField _field = list.Fields.Where(f => f.InternalName == "<INTERNAL NAME OF THE FIELD>").FirstOrDefault();
var _userCollection = _field.NewFieldValueCollection();
foreach(var email in usersMail)
{
var usr = ctx.Web.UnsureUser(email);
_userCollection.Values.Add(_field.NewFieldUserValue(usr));
}
```

Then after populating this field "_userCollection" i proceed with my loop where I create all the listItems

```
foreach(var session in edition.session)
{
Dictionary<string,object> data = new Dictionary<string,object>()
{
{"Title","My Title"},
{"<INTERNAL NAME OF PEOPLE FIELD>", _userCollection}
};
ctx.Web.Lists.GetById(Guid.Parse(<GUID>)).Items.Add(data);
}
```

only the first loop will create correctly. The second time the item is not created.
I found that I have to initiate a new NewFieldValueCollection() for each loop.

Is that something correct?

Thanks

**Comment by gopaldahal** [comment]
@jansenbe,
"MetaInfo" property do not hold "0" at end as you mentioned
![image](https://user-images.githubusercontent.com/27617624/123416891-d51b8400-d5d6-11eb-822c-6f6b5c6ae25a.png)

**Comment by jansenbe** [comment]
@gopaldahal : is your column a regular text column or from a different type?

**Comment by jansenbe** [comment]
@dhz1234 : as the NewFieldValueCollection does track changes, it's indeed required to create a new one for each row you're creating.

**Comment by gopaldahal** [comment]
@jansenbe, Exploring the field metadata, it is a lookuptype,

Uing CSOM, I used to update the same with
item["MetaInfo"] = "some XML values"

**Comment by jansenbe** [comment]
@dhz1234 , @gopaldahal, @Micael-stack: just pushed a change that will throw an exception when the adding of the IListItem succeeded with HTTP 200 while the `HasException` property of the returned IListItem data is true. This will at least inform folks when the fields InternalName is different from the StaticName.

**Comment by jansenbe** [comment]
@dhz1234 : I've pushed a doc update to clarify the requirement on the IFieldValueCollection, this should help others prevent making the same error

**Comment by jansenbe** [comment]
@gopaldahal : check out this for handling lookup fields https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#lookup-fields.

**Comment by Micael-stack** [comment]
@jansenbe i will look into it but from my side all my internal names and static names are normally the same. All my fields in my test were simple text and datetime.

**Comment by jansenbe** [comment]
@Micael-stack : if you try with the next nightly from PnP PS you'll be able to verify things, if this is due to a field returning an exception on save you'll now see an exception being thrown. I was surprised by the differences between InternalName and StaticName...I need to dig deeper to understand why SharePoint sometimes appends a number to the InternalName.

**Comment by Micael-stack** [comment]
@jansenbe  If your static and internal dont match, it is because you got into two possibilities : the internal name was already used within the site, or, the length was too long. Static name is not unique and internal should always be prefered if we want perfect match...

**Comment by jansenbe** [comment]
@Micael-stack : can you confirm the updates helped...using internal names should work, if for some reason the internal name differs from the static name or something else goes wrong while saving you know should see an exception being thrown.

**Comment by jansenbe** [comment]
note that there's an issue with the current PowerShell nightly builds as they still use an older version of PnP Core SDK...so the done updates are not showing up in PowerShell...we're working on a fix for that.

**Comment by jansenbe** [comment]
and PowerShell issue has been fixed, so tomorrow's nightly will use the latest PnP Core SDK again

**Comment by Micael-stack** [comment]
@jansenbe  i just tested pnp.Powershell Nightly 1.6.25, i was having same result ( no items, no message) then i tried to isolate the specific field and i got the problem : The batch method doesn't format correctly date field string from supported language. I can call add-pnpListItem with a date format "YYYY-MM-DD time" but in batch it wont work and espect me to pass an english standard "DD/MM/YYYY time". After i formatted my date in english it passed and items created in batch. 

So, it does fail from an internal error but there is still no feedback with invoke-batch -details

**Comment by jansenbe** [comment]
@Micael-stack : with tomorrow's PnP PS build you should see an exception being thrown for this (as PnP PS was still using an old PnP Core library). Good that you've found the failing field...maybe create a PR for the PowerShell docs to clarify this?

**Comment by jansenbe** [comment]
I'm closing this issue. @gopaldahal already created a new issue for his specific ask, if others still have issues recommend to do the same.
