### ISSUE TITLE
Use code generation to generate initial model classes and collections

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#5]
Model classes and collection classes support a partial class model allowing us to generate part of the implementation class and public interface. This will help speed up development of the model.

Being able to regenerate is not a current requirement, more looking towards using this to speed up things.

**Comment by jansenbe** [comment]
@PaoloPia : we'll need to decide what to do with this one...go for the (onetime) generation route or not? If not we can merge the model.gen.cs and model.cs classes

**Comment by PaoloPia** [comment]
Let me try to update the code generator to the latest outline of the .gen.cs files and see how painful it is to run it once or on a build-basis.

**Comment by jansenbe** [comment]
Let's start with SPO Rest first, as that's the largest API surface we have to cover

**Comment by jansenbe** [comment]
90% done, see output in https://github.com/pnp/pnpcore/tree/dev/src/generated

**Comment by jansenbe** [comment]
Closing this issue, think we've enough in place to speed up the SP rest based development. The graph surface we need is much smaller and the Teams side is already quite far, so there's no immediate need to generate graph classes
