### ISSUE TITLE
Authenticate Onpremise SharePoint using PnP

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#501]
## Category

- [x] Feature request

## Describe the feature

Since PnP Core makes use of Graph and Rest, and On-premise itself makes use of Rest API.
It would be great if we can add the authentication process for OnPremise as well.
It would add great support.

## Describe the solution you'd like
 
We already have the option to use Graph or Not, Thus if I do not want to make use of Graph and just Rest, and would like to make authentication based on cookie-based or credential-based instead of App, it would add more flavor to our PnP.
I may have missed something or might have been implemented already.

## Additional context

Sharing is Caring!!

**Comment by jansenbe** [comment]
Hi @gopaldahal , PnP Core SDK only targets SharePoint Online and we don't have plans to support it for SharePoint on-premises scenarios. The REST API surface differs between on-premises SharePoint versions and SharePoint Online, so building support would require taking in account these differences, which will add a lot of extra complexity and maintenance cost. Hope that clarifies things.
