### ISSUE TITLE
Text field value is as DateTime

### ISSUE THREAD

**Issue by MarcoSR2021** [pnp/pnpcore#519]
## Category

- [x] Bug

## Describe the bug

A value "1.1" in a text field on a Sharepoint list item is returned as DateTime from the Values collection.
FieldValuesAsText doesn't contain the custom field.

## Steps to reproduce

1. Define a singleline text field on a Sharepoint list, e.g. "ChapterNumber"
2. Create a new list item
3. Enter "1.1" as value for the field
4. Retrieve list item via `GetByIdAsync` and query field value via `listItem.Values["ChapterNumber"]`
5. The value returned is DateTime 1/1/2021

## Expected behavior

Text field values must be kept as string or a "Raw" value needs to be available.

## Environment details (*development & target environment*)

- **SDK version**: v1.3.0 (also tried v1.3.9-nightly)
- **OS**: Windows 10
- **SDK used in**: Class library
- **Framework**: .NET 5.0
- **Tooling**: Visual Studio 2019
- **Additional details**: Culture de-DE

### Additional context

Culture de-DE may be needed for "1.1" being parsed as DateTime. However in German language a date needs to be like "1.1." with dot at the end or "31.12.2021".

Fields on list are loaded, so FieldTypeKind is available. However it seems the code (probably `sdk\PnP.Core\Services\Core\JsonMappingHelper.cs`?) ignores it.

LoadListDataAsStreamAsync doesn't have this issue - it takes care for FieldTypeKind.

**Comment by MarcoSR2021** [comment]
Added information that GetByIdAsync has this issue while LoadListDataAsStreamAsync doesn't have it.

**Comment by jansenbe** [comment]
@MarcoSR2021 : this indeed a bug, will work on a fix

**Comment by jansenbe** [comment]
@MarcoSR2021 : I've added a fix that will prevent DateTime parsing for short strings...this still does not prevent a text field with a normal formatted date time string (length 10 or more) to be parsed as DateTime, but at least there should be less occurrences

**Comment by jansenbe** [comment]
@MarcoSR2021 : closing this issue, but feel free to re-open or raise a new issue if you still face issues.
