### ISSUE TITLE
PnP Core in C# not able to change Created, Created By, Modified, Modified By columns in SharePoint list item

### ISSUE THREAD

**Issue by subhasishmukhopadhyay2018** [pnp/pnpcore#522]
## Category

- [x] Bug

## Describe the bug
PnP Core based code in C# not able to change Created, Created By, Modified, Modified By columns in SharePoint list item

## Steps to reproduce

1. See code below

 IField createdByField = listObj.Fields.Where(f => f.InternalName == "Author").FirstOrDefault();
 ISharePointUser createdByObj = await context.Web.EnsureUserAsync(item.CreatedBy);
 FieldValue createdBy = contentOwnerMgrField.NewFieldUserValue(createdByObj);

  IField modifiedByField = myLinks0001.Fields.Where(f => f.InternalName == "Editor").FirstOrDefault();
  ISharePointUser modifiedByObj = await context.Web.EnsureUserAsync(item.ModifiedBy);
  IFieldValue modifiedBy = contentOwnerMgrField.NewFieldUserValue(modifiedByObj); 
#...... code to create item and then in returned object AddedItem ...............
Dictionary<string, object> itemValues = new Dictionary<string, object>()
                    {
                        { "Title", link0001.Title }
                    };
IListItem AddedItem = await listObj.Items.AddAsync(itemValues);

AddedItem["Created"] = created; // date time
AddedItem["Modified"] = modified; // date time
AddedItem["Author"] = createdBy;
AddedItem["Editor"] = modifiedBy;
await AddedItem.UpdateOverwriteVersionAsync();

## Expected behavior
Code executes fine and should change these four system fields which not happening even there is no error.

## Environment details (any environment of SPO)
- **SDK version**: PnP.Core 1.3.1
- **OS**: [e.g. Windows 10]
- **SDK used in**: Console App
- **Framework**: .NET Core v5.x
- **Browser(s)**: NA
- **Tooling**: Visual Studio 2019

*Thanks for your contribution! Sharing is caring.*

**Comment by gopaldahal** [comment]
Author and Editor are of FieldUserValue model. Thus assigning such field can be explored through provided URL
https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields

**Comment by jansenbe** [comment]
@subhasishmukhopadhyay2018 : here's a piece of code that shows how to do this, just verified this in my test environment:

```csharp
// get items from the list
await myList.LoadAsync(p => p.Items, p => p.Fields);

// grab first item
var firstItem = myList.Items.AsRequested().FirstOrDefault();
if (firstItem != null)
{
    Assert.IsTrue(firstItem.Values["Title"].ToString() == "Yes");

    // Load the Author and Editor fields
    var author = myList.Fields.AsRequested().FirstOrDefault(p => p.InternalName == "Author");
    var editor = myList.Fields.AsRequested().FirstOrDefault(p => p.InternalName == "Editor");

    // load the current user
    var currentUser = await context.Web.GetCurrentUserAsync();
    var newDate = new DateTime(2020, 10, 20);

    firstItem.Values["Author"] = author.NewFieldUserValue(currentUser);
    firstItem.Values["Editor"] = editor.NewFieldUserValue(currentUser);                             
    firstItem.Values["Created"] = newDate;
    firstItem.Values["Modified"] = newDate;

    await firstItem.UpdateOverwriteVersionAsync();

    // get items again from the list
    await myList.LoadAsync(p => p.Items);
    firstItem = myList.Items.AsRequested().FirstOrDefault();

    Assert.IsTrue(firstItem.Values["Created"].ToString() == newDate.ToString());
    Assert.IsTrue(firstItem.Values["Modified"].ToString() == newDate.ToString());
}
```

**Comment by jansenbe** [comment]
@subhasishmukhopadhyay2018 : closing this issue, but feel free to re-open or raise a new issue if you still face issues.
