### ISSUE TITLE
Support for new Section Properties in Client Side Pages

### ISSUE THREAD

**Issue by czullu** [pnp/pnpcore#539]
## Category

- [x] Feature request

## Describe the feature
In order to support new sections settings in Client Side Pages we should add support for those new settings into PnP.Core\Model\SharePoint\Pages\Internal\CanvasControlData.cs

	"zoneGroupMetadata": {
		"type": 1,
		"displayName": "Docs",
		"isExpanded": true,
		"iconAlignment": "right",
		"showDividerLine": true
	},
	"reservedHeight": 693,
	"reservedWidth": 1180

**Comment by czullu** [comment]
@jansenbe just seen MC266077 - you might have more info if there will be some upcoming changes to this settings

**Comment by jansenbe** [comment]
@czullu : support for collapsible sections has been added, see https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/PagesTests.cs#L790-L873 for a test showing how to use them. Docs (https://pnp.github.io/pnpcore/using-the-sdk/pages-intro.html) are also updated.

Please give this a try with tomorrow's build and let me know if you face issues.

**Comment by czullu** [comment]
@jansenbe looks good to me. could read and change the settings - even the crazy title test was ok.
![image](https://user-images.githubusercontent.com/31336529/132741873-06c38c76-ecd6-4885-803f-2ba2734d44ed.png)
**Thank you**
