### ISSUE TITLE
Property given on ViewXml of RenderListDataOptions under LoadListDataAsStreamAsync is not working as expected

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#546]
## Category

- [x] Bug

## Describe the bug

ViewXml provided with fields Like "ID" is not returned from LoadListDataAsStreamAsync operation.
"ID" is just an example I have shared here with the example code below.
However in my scenario provided list has around 80 fields, when applied all these fields under ViewXml during query with LoadListDataAsStreamAsync, only 60 fields and their values are returned.

## Steps to reproduce
```

                int rowLimit = 200;
                bool paging = true;
                string nextPage = null;
                string viewXml = "<View><ViewFields><FieldRef Name='ID'/></ViewFields><RowLimit Paged='TRUE'>200</RowLimit></View>";
                var loadOption = new RenderListDataOptions()
                {
                    ViewXml = viewXml,
                    RenderOptions = RenderListDataOptionsFlags.ListData,
                    Paging = nextPage ?? null,
                    DatesInUtc = true,
                    FolderServerRelativeUrl = folderRelativeUrl
                };
                while (paging)
                {
                    var output = parentList.LoadListDataAsStreamAsync(loadOption).Result;

                    if (output.ContainsKey("NextHref"))
                    {
                        nextPage = output["NextHref"].ToString().Substring(1);
                    }
                    else
                    {
                        paging = false;
                    }
                }
               var result = parentList.Items.AsRequested();
                //here result[0].values misses the "ID" value.
```
## Expected behavior

Method should have returned field values with all the provided fields.

## Environment details (*development & target environment*)

- **SDK version**: [1.3.0 ]
- **OS**: [Windows 10]
- **SDK used in**: [Console App]
- **Framework**: [ .NET Framework v4.7.2 ]
- **Tooling**: [Visual Studio 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@gopaldahal : not sure about not returning all the fields, in the end the SDK is calling a SharePoint REST API providing the CAML query...might be a CAML limitation. If you don't specify the viewfields do you then get all fields?

**Comment by gopaldahal** [comment]
@jansenbe 
Without applying the view fields, I am able to achieve more view fields this time. However, miss some other view fields.

The missing fields were
ID
_EditMenuTableEnd
_EditMenuTableStart
_EditMenuTableStart2
_IsRecord
BaseName
DocIcon
Edit
EncodedAbsUrl
HTML_x0020_File_x0020_Type
LinkFilename
LinkFilename2
LinkFilenameNoMenu
LinkTitle:LinkTitle2
LinkTitleNoMenu
SelectTitle
ServerUrl

**Comment by jansenbe** [comment]
@gopaldahal : the ID field is a special case, it's not added to the collection of field values but it's available via the `Id` property of the loaded list item. When I do load items from a test list I'm getting 116 fields returned, including the fields you've mentioned that are not returned. Do you always see the same missing fields, also when you query a list with less than 80 custom fields?

```csharp
var result = await myList.LoadListDataAsStreamAsync( new RenderListDataOptions()
{ 
    ViewXml = "<View><RowLimit>5</RowLimit></View>",
    RenderOptions = RenderListDataOptionsFlags.ListData 
});
```

![image](https://user-images.githubusercontent.com/7451219/133572632-49169ed3-443a-4fb9-b256-1ef804958885.png)

**Comment by gopaldahal** [comment]
@jansenbe,
My apology, Seems I missed few things on my previous tests. 
This time, my test result just misses 2 fields "ID" and "Edit".
As you said ID is available on the item object itself. Fine.
However, "Edit" property is neither on ListItem nor on the Values.

I do have one more concern.
Without adding the view fields, it gave almost all the view fields set,
But adding the same view fields on the ViewField query is not returning the same.
Please guide!

Sharing is Caring!!

**Comment by jansenbe** [comment]
@gopaldahal : I also see the Edit (it's a computed field) in the returned data:

![image](https://user-images.githubusercontent.com/7451219/133747390-1db9afbe-34d6-4bcf-bbf5-60c9e495f44b.png)

I did some more testing on specifying fields to load in the CAML query and seems that fields of type `Computed` are never returned when explicitly asked for. So in your case I guess the best solution is to query the lists without specifying the view fields.  Also tested with `LoadItemsByCamlQueryAsync` but that did not return these fields either.

Given this is how SharePoint works, I don't see this as an issue for PnP Core SDK and therefore I suggest we close this.

**Comment by gopaldahal** [comment]
@jansenbe:
If you are sure that SharePoint on itself does not return computed fields (when explicitly asked), I have no problem closing this one.

Retired again regarding "Edit" property, but still not retrieved on my end( no view fields specified).
https://comparetext.codersup.com/shareUrl/b84fe267-a344-432f-a568-4ed0e4eeb44e

**Comment by jansenbe** [comment]
@gopaldahal : I'm closing this issue as what's returned by a caml query is beyond my scope to change here, in my testing I see all properties being returned, so weird you always miss the Edit field. 

Would also strongly recommend to give the current nightly a go as there have been massive perf improvements that will help with speeding up the reading of list data. Check the changelog and commit history to learn more.
