### ISSUE TITLE
`IFile.GetContentAsync` Doesn't Work in Prerelease

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#553]
## Category

- [x] Bug

## Describe the bug
In 1.3.0, getting the actual stream/binary works great. However, using 1.3.61-nightly, if we try to write the file, it's 0 bytes.

## Steps to reproduce
_Will add code snippet in a little bit..._

## Expected behavior
Gotta get that binary/stream! 😄 

## Environment details (*development & target environment*)
- **SDK version**: 1.3.61-nightly
- **OS**: Windows 10
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 5.0.10
- **Tooling**: Visual Studio 2019

**Comment by jansenbe** [comment]
@DaleyKD : probably a regression from the perf updates...will still need to do a full live test run, should be fixed in the coming days

**Comment by jansenbe** [comment]
@DaleyKD : GitHub auto closed this one as I tagged the issue in my commit...anyhow, issue is fixed and next nightly should work. Will still plan a full online run, if you encounter other strange things after all the perf updates then please let me know.

**Comment by DaleyKD** [comment]
Thanks @jansenbe ! I'll check on Monday.

(Thanks for not having me write a code snippet. 😄 )
