### ISSUE TITLE
Method EnsureSiteCollectionContext is causing 403 errors

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#557]
## Category

- [x] Bug

## Describe the bug

Continuation of #556, after working around that error, the next error generated is this method with the EnsureSiteCollectionClientContext

![image](https://user-images.githubusercontent.com/8781041/135347666-c5aaa86a-2dc4-41ab-af9f-5d776f0d5ff8.png)

[Log.txt](https://github.com/pnp/pnpcore/files/7255044/Log.txt)

## Steps to reproduce

Transform Classic to Modern Page
Note: this is a multi-lingual site - just because im difficult lol.

Run SharePointTransformAsync

## Expected behavior

Transforms file.

**Comment by pkbullock** [comment]
I have a fix for this, coming shortly.

**Comment by PaoloPia** [comment]
Thanks! Merged!
