### ISSUE TITLE
AnalysePublishingPageAsync method doesn't use collected analyzer data

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#562]
## Category

- [x] Bug

## Describe the bug

I am transforming online to online with a multi-lingual site, using the Publishing Page features. 
Method AnalyzePublishingPageAsync in the SharePointMappingProvider class feels incomplete. 

The analyzer code gathers the information (pending latest PR) from the page layout file, the return to the calling method isn't sufficient to include all the information gathered. 

Line 1603 returns all the data from the analysed mapping file just not used yet. I'll need some help to discuss either expanding the return to the calling method or a caching mechanism. Not use if there is an equivalent to the cache manager.

![image](https://user-images.githubusercontent.com/8781041/135769971-94b2166f-6ad9-4657-8671-d25aa753b2e0.png)

I have put temporary code here to return something to see what happens in future steps. I feel some more work in this area maybe required, of course happy to help.

## Steps to reproduce

Transform a publishing page using the SharePointTransformAsync (fix for casing ;-)) test

**Comment by pkbullock** [comment]
Please note line numbers refer to #563 after that is merged.

**Comment by jansenbe** [comment]
Closing for now, will re-open if this effort will be picked up again
