### ISSUE TITLE
PnPContext.Web does not provide GetFileByUrl

### ISSUE THREAD

**Issue by LegendaryB** [pnp/pnpcore#565]
## Category

- [x] Bug

## Describe the bug

It seems like the `PnPContext.Web` instance does not provide the method `GetFileByUrl`. I need that method because it works flawlessly with different sharepoint links (Share with people who have access link, direct link etc.). I can use this method manually using `PnPContext.Site.ExecuteRequestAsync` + matching `ApiRequest` instance like so:

```csharp
var request = new ApiRequest(ApiRequestType.SPORest, $"_api/web/GetFileByUrl('{my_url}')");
var response = await context.Site.ExecuteRequestAsync(request);

var model = JsonDocument.Parse(response.Response);
```

Any possibility to parse this model or response at least into a IFile instance? So that I can work normally with the `GetContentAsync` function?

## Expected behavior

`GetFileByUrl` is available through the Web instance property of the `PnPContext`

**Comment by jansenbe** [comment]
Hi @LegendaryB ,

We do have a series of `GetFileByServerRelativeUrl` methods available (see https://pnp.github.io/pnpcore/api/PnP.Core.Model.SharePoint.IWeb.html#PnP_Core_Model_SharePoint_IWeb_GetFileByServerRelativeUrl_System_String_Expression_Func_PnP_Core_Model_SharePoint_IFile_System_Object_____ for the docs) which use `$"_api/Web/getFileByServerRelativePath(decodedUrl='{encodedServerRelativeUrl}')` as API call. It's not exactly the same as GetFileByUrl though and we can definitely add native support for that one, but wanted to share the other approach just in case.

Thanks for using the PnP Core SDK and providing feedback.

**Comment by jansenbe** [comment]
Hi @LegendaryB ,

Can you try the following approach:

- Use the Microsoft Graph sharing API to obtain a DriveItem (see https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#encoding-sharing-urls)
- Use the part before "/_layouts..." in the returned  driveitem web url as web url for connecting the context to

For example this sharing url (https://bertonline.sharepoint.com/:w:/s/prov-1/EYja-X6NRfhPj3VfviUnUvIBN1J-1HzBbyqux7olhNXRZA?e=7yvXn0) is translated to this sharing id `u!aHR0cHM6Ly9iZXJ0b25saW5lLnNoYXJlcG9pbnQuY29tLzp3Oi9zL3Byb3YtMS9FWWphLVg2TlJmaFBqM1ZmdmlVblV2SUJOMUotMUh6QmJ5cXV4N29saE5YUlpBP2U9N3l2WG4w` via 

```csharp
string sharingUrl = "https://bertonline.sharepoint.com/:w:/s/prov-1/EYja-X6NRfhPj3VfviUnUvIBN1J-1HzBbyqux7olhNXRZA?e=7yvXn0";
string base64Value = System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(sharingUrl));
string encodedUrl = "u!" + base64Value.TrimEnd('=').Replace('/', '_').Replace('+', '-');
Console.WriteLine(encodedUrl);
```

Once you have the sharing id you can use the Graph shares endpoint: shares/u!aHR0cHM6Ly9iZXJ0b25saW5lLnNoYXJlcG9pbnQuY29tLzp3Oi9zL3Byb3YtMS9FWWphLVg2TlJmaFBqM1ZmdmlVblV2SUJOMUotMUh6QmJ5cXV4N29saE5YUlpBP2U9N3l2WG4w/driveitem/weburl

![image](https://user-images.githubusercontent.com/7451219/136357063-1e25f188-fe51-415e-b638-8e4c3a85f921.png)

You did already use the custom API approach to call `GetFileByUrl` and the same model can be used to make Graph calls as well.

Let me know how that goes.

**Comment by jansenbe** [comment]
@LegendaryB : can you try if this works:

![image](https://user-images.githubusercontent.com/7451219/136365841-19324e19-64c8-4ed6-be94-172cf0822346.png)

**Comment by LegendaryB** [comment]
@jansenbe Thanks for all your help. I finished the task by implementing GetFileByUrl. But only really basic and I just parse some informations from there to be able to download the file.

My issue can be closed :)
