### ISSUE TITLE
When transforming Images do not get stored in SitePages folder

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#571]
## Category

- [x] Bug

## Describe the bug

When images are transformed along with the page, the page folder isnt created and image is not located in 
/SitesAssets/SitePages/{PageName}/Image.jpg 

Currently, its just /SiteAssets/

## Steps to reproduce

Created a simple page with text and image. 
Transformed using unit test "SharePointTransformAsync"

## Expected behavior

Images are stored in target in the same locations are the standard pages image feature locations.

**Comment by jansenbe** [comment]
Closing for now, will re-open if this effort will be picked up again
