### ISSUE TITLE
When transforming the target image size is HUGE, bug?

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#572]
## Category

- [x] Bug

## Describe the bug

When transforming a simple publishing page with image and text, the image thats transformed is super large. Go to the editing experience and the image shrinks, revert = huge, save/publish = proper size.

Think this is a bug.

## Steps to reproduce

Transform a publishing page with text and image.

Have added a video to record the observed behaviour. Not sure if this is a SP or tranformation bug.

https://user-images.githubusercontent.com/8781041/136845268-754d9624-5339-4917-a5a4-9554686903f9.mp4

## Expected behavior

Images are transformed into the correct sizes.

**Comment by jansenbe** [comment]
Closing for now, will re-open if this effort will be picked up again
