### ISSUE TITLE
Getting Lists causes 'Instance Was deleted Error'

### ISSUE THREAD

**Issue by bajce** [pnp/pnpcore#576]
In my solution I'm trying to read all SharePoint Online data of a tenant, and in order to improve performance and reduce the amount of objects in memory, I use separate threads for each SharePoint object. The PnPContext is created only once per URL, stored in a Map and re-used as needed.

When I try to read Lists from Web I sometimes get the following exception:

`This model instance was deleted, you can't use it anymore`

```
at PnP.Core.Model.TransientObject.CheckDeleted()
at PnP.Core.Model.TransientObject.GetValue[T](String propertyName)
at PnP.Core.Model.BaseDataModel`1.GetModelCollectionValue[T](String propertyName)
at PnP.Core.Model.SharePoint.Web.get_Lists()
```

Code I use for loading Lists:

`var list = context.Web.Lists.GetById(new Guid("xxxxx")`

**Important: I have multiple threads running parallel that are probably using the same Context to load different Lists of the current Web.**

**Comment by jansenbe** [comment]
@bajce : The PnP Core SDK `PnPContext` object is not thread-safe, so would not recommend re-using it across threads. From experience we know that massive parallel operations will get you throttled by SharePoint...and then there are no performance benefits anymore. 

If you need to regularly process the same data you should consider using a model were you read data once and keep track of the information you need in your backend. This tracked data can be updated by either using subscriptions/webhooks to let SharePoint notify you of changes or alternatively use use the PnP Core GetChanges operations on a regular basis to check for changes and then process the incoming changes. https://aka.ms/scanguidance provides more context on this model.

If you want to stick with the current approach of just reading the data then create a thread per web/site, each using it's own PnPContext and run the work in parallel per site.

To optimize on performance do know that you can ask additional data to be loaded when the PnPContext is initialized (see https://pnp.github.io/pnpcore/using-the-sdk/basics-context.html#loading-additional-iweb-and-isite-properties-when-creating-a-pnpcontext). The advantage is that in this way you'll additional data loaded in your PnPContext without doing additional server round trips.

**Comment by bajce** [comment]
Yes this answers my question. Thank You.

**Comment by KoenZomers** [comment]
Ran into the same here with only two concurrent threads. Cloning the PnPContext for every call as Bert mentions above fixed it for me.
