### ISSUE TITLE
Discussion  List Fields, while loading misses some of  the available fields.

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#590]
## Category

- [x] Bug

## Describe the bug

Some of the fields are missing while reading from List.Fields method under Discussion list.
In my case, it's missing around 30 fields in 130

## Steps to reproduce

```
                //listId is guid for discussion type of list
                 var parentList = context.Web.Lists.GetById(listId, l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
               //misses "IsRootPost" field
                var parentFields = parentList.Fields.ToList();
                string nextPage = null;
                string viewXml = "<View><RowLimit Paged='TRUE'>1000</RowLimit><Query><Where><Eq><FieldRef Name='FSObjType'/><Value Type='int'>1</Value></Eq></Where></Query></View>"
                do
                {
                    var loadOption = new RenderListDataOptions()
                    {
                        ViewXml = viewXml,
                        RenderOptions = RenderListDataOptionsFlags.ListData,
                        Paging = nextPage ?? null,
                        DatesInUtc = true,
                        FolderServerRelativeUrl = folderRelativeUrl
                    };
                    var output = parentList.LoadListDataAsStreamAsync(loadOption).Result;
                    if (output.ContainsKey("NextHref"))
                    {
                        nextPage = output["NextHref"].ToString().Substring(1);
                    }
                    else
                    {
                        nextPage = null;
                    }
                }
                while (!string.IsNullOrEmpty(nextPage));
               //every item have "IsRootPost" field
               var items = parentList.Items.AsRequested();
```

Here Items have a property with the internal name "IsRootPost"
However, the same is missing on list fields.
There are some other properties that are missing too.

## Expected behavior

Must have retrieved all fields

## Environment details (*development & target environment*)

- **SDK version**: [1.2.31.0 ]
- **OS**: [Windows]
- **SDK used in**: [Console App ]
- **Framework**: [.NET Framework v4.7.2]
- **Tooling**: [Visual Studio 2019]
### Additional context
*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@gopaldahal , just to make sure I understand the ask: when you retrieve the fields from a list not all the fields you'd expected show up? And this only applies to lists of type "discussion list" or to other list types as well?

**Comment by jansenbe** [comment]
Hi @gopaldahal ,

I spotted something strange in your code, you do the following:

```csharp
var parentList = context.Web.Lists.GetById(listId, l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
var parentFields = parentList.Fields.ToList();
```

Which results in loading the fields twice. If you want to query the fields already loaded via the first GetById call then do this (notice the **AsRequested**):
```csharp
var parentList = context.Web.Lists.GetById(listId, l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
var parentFields = parentList.Fields.AsRequested();
foreach (var fld in parentFields)
{
  // do something with the field
}
```

Second complication is that doing `var parentFields = parentList.Fields.ToList();` under the covers uses paging and I've today discovered and fixed a bug: only the first page of fields (default page size is 100) was retrieved => this might explain the missing fields you saw.

Would recommend using the `AsRequested()` method. If you do rely on our implicit paging then best to test with tomorrow's nightly build or alternatively increase page size to rule out that paging was causing the missing fields.

Thanks for reporting this.
