### ISSUE TITLE
Improve support for working with fields via a "typed" field collection

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#596]
**Proposal for future improvement:**

Today web/list fields can be read and returned as a collection of `IField`. This works fine for basic fields but for more complex fields (eg taxonomy fields) part of the field definition (e.g. term set id) lives inside the field's `SchemaXml` property. What if there was a method `AsTypedFields()` on the current `IFieldsCollection` that would return the fields a collection of `ITextField`, `IBoolField`, `ITaxonomyField` ...all inheriting from a common `ITypedField`. This way developers don't have to parse the field xml themselves, they can just use a typed experience to work with the field properties.

These typed fields should also have the respective `Update` and `Delete` methods to allow for easy updating of the field.

**Comment by jansenbe** [comment]
Awesome! Having a more intuitive way to handle fields in SharePoint will be really helpful for new developers coming to SharePoint, looking forward to see how you'll implement this one.

**Comment by s-KaiNet** [comment]
@jansenbe could you help me clarify a few things here? 
When looking deeper at the issue and in the code now it's not that clear for me. What would be the relation between `IField` and say `ITextField's` properties? `IField` itself contains a lot of different properties, should we include all of them in `ITextField` as well? In that case, it looks like most of the typed versions of field types (`ITextField`, `IBoolField`, etc.) will be the same as `IField`, except only a few like taxonomy, lookup, and some others, which will have advanced properties available. In that case, it looks like it doesn't make a lot of sense. Or maybe I just lost the idea on the way :)

**Comment by jansenbe** [comment]
@s-KaiNet : thanks for details, when I wrote this issue I was indeed thinking about the special fields like taxonomy. For example if you read a taxonomy field there's no property telling you the id of the termset that's used for this field. Now the question whether this justifies coming up with all new types like you said...that indeed is a bit of overkill. What about with just starting with a single method on IField to get additional taxonomy information from a taxonomy field and show how to use that in our docs (https://pnp.github.io/pnpcore/using-the-sdk/fields-intro.html)? If overtime there's additional asks we can add more methods.

**Comment by s-KaiNet** [comment]
Yeah, as you suggested, let's start with the taxonomy field adjustment and will see if additional options or needs will popup.

**Comment by jansenbe** [comment]
Thanks @s-KaiNet , nice and simple solution for the problem. I like it!
