### ISSUE TITLE
Updating list items with added fields seems not to work

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#605]
## Category

- [x] Bug

## Describe the bug

I was following the sample code for updating a list item from [here](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-list-items) and performed a slight modification.

I am using the SDK version 1.4. The operation for adding the item is executed successfully but the update immediately after is not reflected in SharePoint Online. I am performing this operation on a list with more than 100 items.

```
Dictionary<string, object> item = new Dictionary<string, object>()
{
    { "Title", "Item1" },
    { "Field A", 25 }
};

// Persist the item
var addedItem = await myList.Items.AddAsync(item);

// Update the item values
addedItem["Field A"] = 100;
addedItem["NewFieldToUpdate"] = 5555;

// Update the item in SharePoint
await addedItem.UpdateAsync();
```

The update of the code above does not update the NewFieldToUpdate field.

## Expected behavior

The "NewFieldToUpdate" field is considered in the update process.

## Environment details (*development & target environment*)

SharePoint Online with a custom list with more than 100 items.

- **SDK version**: 1.4
- **OS**: Windows 10
- **SDK used in**: .NET Core 3.1

**Comment by jansenbe** [comment]
@plamber , thanks for using PnP Core SDK and reporting this. I'm currently not able to reproduce the issue. I've build below code that is quite similar to yours and this works for me. Can you test below code and verify that your "NewFieldToUpdate" does exist with "NewFieldToUpdate" as static name.

```csharp
string listTitle = "MyTestList";
string fldNumber1 = "SpecialField1";
string fldNumber2 = "SpecialField2";

// Create the list
var myList = await context.Web.Lists.AddAsync(listTitle, ListTemplateType.GenericList);

// Add 2 number fields in batch
IField addedNumberField1 = await myList.Fields.AddNumberBatchAsync(fldNumber1, new FieldNumberOptions()
{
    Group = "TEST GROUP",
    AddToDefaultView = true,
});
IField addedNumberField2 = await myList.Fields.AddNumberBatchAsync(fldNumber2, new FieldNumberOptions()
{
    Group = "TEST GROUP",
    AddToDefaultView = true,
});

// Send field adds to server
await context.ExecuteAsync();

// Add a list item to this list
Dictionary<string, object> values = new Dictionary<string, object>
    {
        { "Title", "Yes" },
        { fldNumber1, 25 },
    };

var addedItem = await myList.Items.AddAsync(values);

addedItem[fldNumber1] = 100;
addedItem[fldNumber2] = 5555;
await addedItem.UpdateAsync();

// Clean up
await myList.DeleteAsync();
```

**Comment by plamber** [comment]
Hi @jansenbe,
indeed. I am no more able to reproduce it. Most likely there was an issue with my fields and I haven't noticed it.

Thank you for your prompt response

Cheers
