### ISSUE TITLE
Unable to fetch LookupValue in ListItems

### ISSUE THREAD

**Issue by somdeepgniyogi** [pnp/pnpcore#608]
## Category

- [X] Bug

## Describe the bug

>I am not getting LookupValue for People field. The LookupId field is populated however the LookupValue is empty.

![image](https://user-images.githubusercontent.com/6120892/139651630-4aaceffd-ed99-406b-8d2d-29397cefb6ce.png)

Moreover the OOB Author and Editor fields are not returned as lookup.

![image](https://user-images.githubusercontent.com/6120892/139651837-f27470c5-6bf0-4d7a-9618-3ee3401d57c4.png)

The error returned "Property Author does not exist in this entity"

Can you kindly help?

**Comment by hohenp** [comment]
Hi @somdeepgniyogi , I am having the same issue. Have you found a solution?

**Comment by somdeepgniyogi** [comment]
Hi @hohenp ,

Can you try to ugrade the pnp version.

BR

**Comment by hohenp** [comment]
Hi @somdeepgniyogi, I am on 1.5.0, the latest version in the moment.
when I load sharepoint listitems with lookups, only the LookupId ist set. The LookupValue is empty.
Have you had the same issue?
