### ISSUE TITLE
.NET 6 is available: prepare your development environment to support .NET 6

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#618]
### .NET 6 is available!

With .NET 6 shipping (https://devblogs.microsoft.com/dotnet/announcing-net-6/) we plan to add support for .NET 6 to PnP Core SDK and PnP Framework. As .NET 6 is an LTS (Long Term Supported) version it will mean that .NET 5 support will end soon, more specifically on May 8th 2022 (see https://github.com/dotnet/core/blob/main/releases.md). We'll start with adding .NET 6 binaries next to our .NET 5 and .NET Standard 2.0 versions. There's no final timeline on when we'll drop .NET 5 from our SDKs, most likely this will happen with a next major release and after .NET 5 support ended.

Developing with .NET 6 requires an update to your local development setup:

- Install the .NET 6 SDK: https://dotnet.microsoft.com/download/dotnet/6.0
- If you're using Visual Studio upgrade to Visual Studio 2022 as that's the only version that officially supports .NET 6

### Call to action
We're planning to commit .NET 6 support by end of the November 2021, so wanted to give you a heads up on already updating your development environment.

**Comment by Ofer-Gal** [comment]
Not sure if here is the place for issues. the [Sample]( /samples/Demo.AzureFunction.OutOfProcess.AppOnly) works fine in VS 2022
The Register-PnPAzureADApp  did not work for me. Error: `Checking if application 'PnPDemo' does not exist yet...Register-PnPAzureADApp: Exception of type 'PnP.PowerShell.Commands.Model.Graph.GraphException' was thrown.` 
I had my own register App and it worked OK
Also, After deploying, the Azure URL worked for a while but returned 501. Attach a debugger did not work and there is no way to test it in Azure.
Any Suggestions?
Is there a way to to make it "In Process" ? 
Thanks for great Software

**Comment by jansenbe** [comment]
https://pnp.github.io/pnpcore/demos/Demo.AzureFunction/README.html is an in-process sample using v3 functions. About the PnP Cmdlet, you need to be global admin to configure Azure AD with application permissions, so that might be the issue. Thanks for providing the feedback!

**Comment by Ofer-Gal** [comment]
I was targeting .NET 6.  
Don't believe just changing to 6 will work 👎 
I am  global admin on this developer tenant.

**Comment by jansenbe** [comment]
@Ofer-Gal : here's the Azure functions tutorial for .NET 6 with in-process: https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-csharp?tabs=azure-cli%2Cin-process. This is not showing any PnP Core SDK usage, but it should  help get you started using the in-process model.

**Comment by Ofer-Gal** [comment]
Demo.AzureFunction.OutOfProcess.AppOnly works fine for me. I wonder if you can help me with adding configuration Items that will be visible to the functions.
I added "DomainName": "myname" to the json and  public string DomainName { get; set; }  to the class "AzureFunctionSettings" but when I try something like:
```
private readonly AzureFunctionSettings _settings;
private readonly ILogger logger;
private readonly IPnPContextFactory contextFactory;

public CreateSite(AzureFunctionSettings settings, IPnPContextFactory pnpContextFactory, ILoggerFactory loggerFactory)
        {
            _settings = settings;
            logger = loggerFactory.CreateLogger<CreateSite>();
            contextFactory = pnpContextFactory;
        }
```

The run time errors with:
```
 Executed 'Functions.CreateSite' (Failed, Id=f590b9f8-84f9-43f8-a5fc-cbbcb8af25f0, Duration=334ms)
[2021-11-19T18:13:56.993Z] System.Private.CoreLib: Exception while executing function: Functions.CreateSite. System.Private.CoreLib: Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'ProvisioningDemo.AzureFunctionSettings' while attempting to activate 'ProvisioningDemo.CreateSite'.
[2021-11-19T18:13:56.995Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2021-11-19T18:13:56.999Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2021-11-19T18:13:57.003Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2021-11-19T18:13:57.007Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
[2021-11-19T18:13:57.013Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
```
So for sure I am doing it wrong.
How can I safely read the values of "AzureFunctionSettings"?

Thank you much

**Comment by jansenbe** [comment]
@Ofer-Gal : that should work, ensure there's no case mismatch.

**Comment by Ofer-Gal** [comment]
But it does not. :-( 
Did you try doing the same?

**Comment by jansenbe** [comment]
Ah, might be an issue with the dependency injection. Will have look later... Friday evening here 🙂

**Comment by Ofer-Gal** [comment]
Silly me 🥇 I can use `string tenant = Environment.GetEnvironmentVariable("TenantName");` and forget about the `AzureFunctionSettings _settings; `

Sorry I bothered you. have a good week end

**Comment by jansenbe** [comment]
.NET 6 support has been pushed
