### ISSUE TITLE
Extend the domain model for Web/Site Feature support

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#62]
## Category

- [x] Feature request

## Describe the feature

Feature support should list the enabled features on a site/web and allow to enable/disable additional features. See https://aka.ms/pnp/coresdk/contributors on how to get started.

This is a nice work item for new contributors, if you're interested in it please reply on this list item and we'll help you get started.

**Comment by pkbullock** [comment]
Hi @jansenbe, can you put my name down? Might be a good learning task and another area i could start to contribute to

**Comment by jansenbe** [comment]
Thanks @pkbullock , assigned this to you. Feel free to reach out for a sync, happy to help you get started.

**Comment by jansenbe** [comment]
Thanks @pkbullock !
