### ISSUE TITLE
This model instance was deleted, you can't use it anymore

### ISSUE THREAD

**Issue by indieza** [pnp/pnpcore#626]
## Category

- [x] Bug

Hello,
I receive the following error message(This model instance was deleted, you can't use it anymore
) when I try to execute some GET Request to my SharePoint website via Pnp.Core SDK. The situation is that, the application is written on WinForms technology via C# dev language. I have base form where I show all possible operation to the user for manipulating the SharePoint structure. Each option show a new window.
This is the code which I use. [https://pastebin.com/Qd6WpaFp](url)
And the error is thrown in "AllListsComboBox_SelectedIndexChanged" method.
I make proposal there is some problem with the async-await part. Is that right? Also, is there some way to execute the code without freezing the UI Part of the application.

Regards,
Simeon Valev

**Comment by jansenbe** [comment]
Hi @indieza , thanks for using PnP Core SDK and reporting feedback.

The link for the code share is not valid, can you check that or provide a repro in another way?

When using the async methods the UI thread should not be blocked, will give this a try once I have your repro.

**Comment by indieza** [comment]
https://pastebin.com/Qd6WpaFp
If you paste the link in the browser it should open the code for sure 🙂

**Comment by indieza** [comment]
Now I saw, the code is without async-await but when I use all async PnP methods(GetByIdAsync, ToListAsync etc.) receive the error message.

**Comment by indieza** [comment]
Here what a mean:
var lists = await this.listGetOperationsService
                    .GetAllNotSystemLists(this.web);
var listContentTypes = await this.listGetOperationsService
                        .GetListContentTypes(this.web, list.ID);
                    var allContentTypes = await this.webGetOperationsService                 .GetAllNotSystemContentTypes(this.web);

**Comment by jansenbe** [comment]
@indieza : can you also share the relevant ...Service code parts. If you want to keep things private feel free to send your code to Bjansen@microsoft.com

**Comment by indieza** [comment]
I will add you in the repo, second please. Feel free to give me advice for the solution here. 🙂

**Comment by jansenbe** [comment]
Hi @indieza ,

I did test the sample you've shared and managed to repro the issue...but not yet solve it. For some reason calls in your services will trigger the IndexChanged event to fire again resulting in the errors you see. Loading data upfront in `GetSharePointWebsiteWeb` 

```csharp
using (var context = await pnpContextFactory.CreateAsync(new Uri(url)))
{
    this.web = await context.Web.GetAsync(p => p.All, p => p.ContentTypes, p => p.Lists.QueryProperties(l => l.ContentTypes));
}
```

and then reuse the loaded data in the service will offer a work around (and most likely be more performant as there's only one single call)

```csharp
public async Task<ICollection<ContentTypeBaseModel>> GetListContentTypes(IWeb web, Guid listId)
{
    var list = web.Lists.AsRequested().First(l => l.Id == listId);
    var contentTypes = list.ContentTypes.AsRequested();
    var model = contentTypes
        .Select(x => new ContentTypeBaseModel(x.Id, x.Name))
        .OrderBy(x => x.Name)
        .ToList();
    return model;
}
```

I'll do some more investigating, but seems to be a issue when combing async event handlers with async operations in async service calls...

**Comment by jansenbe** [comment]
@indieza , this now works for me. Notice the following:

- Using `await Task.Run(async () =>{ })` to ensure the async method calls run on another thread and not on the UI thread
- Use `.ConfigureAwait(false)` on the async call invocations

```csharp
private async void AllListsComboBox_SelectedIndexChanged(object sender, EventArgs e)
{
    var list = this.AllListsComboBox.SelectedItem as ListBaseViewModel;

    if (this.web != null && list != null)
    {
        try
        {
            List<ContentTypeBaseModel> possibleContentTypes = null;

            await Task.Run(async () =>
            {
                var listContentTypes = await this.listGetOperationsService
                .GetListContentTypes(this.web, list.ID).ConfigureAwait(false);
                var allContentTypes = await this.webGetOperationsService
                    .GetAllNotSystemContentTypes(this.web).ConfigureAwait(false);

                possibleContentTypes = allContentTypes
                    .Where(x => !listContentTypes.Any(y => y.ID == x.ID || y.Name == x.Name))
                    .OrderBy(x => x.Name)
                    .ToList();
            });

            this.AllContentTypesComboBox.DataSource = new BindingSource(possibleContentTypes, null);
            this.AllContentTypesComboBox.DisplayMember = nameof(ContentTypeBaseModel.Name);
            this.AllContentTypesComboBox.ValueMember = nameof(ContentTypeBaseModel.ID);
            this.AllContentTypesComboBox.Enabled = true;
            this.selectedList = list;
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }
}
```

with 

```csharp
public async Task<ICollection<ListBaseViewModel>> GetAllNotSystemLists(IWeb web)
{
    var lists = await web.Lists.Where(x => x.Hidden == false).ToListAsync().ConfigureAwait(false);
    var model = lists
        .Select(x => new ListBaseViewModel(x.Id, x.Title, x.Description, x.TemplateType))
        .OrderBy(x => x.Title)
        .ToList();
    return model;
}

public async Task<ICollection<ContentTypeBaseModel>> GetListContentTypes(IWeb web, Guid listId)
{
    // await Task.Delay(1).ConfigureAwait(false);
    var list = await web.Lists.GetByIdAsync(listId).ConfigureAwait(false);
    var contentTypes = await list.ContentTypes.ToListAsync().ConfigureAwait(false);
    var model = contentTypes
        .Select(x => new ContentTypeBaseModel(x.Id, x.Name))
        .OrderBy(x => x.Name)
        .ToList();
    return model;
}
```

**Comment by indieza** [comment]
Hello,
Thank you for the time, I will take a look over the implementation and will come back ASAP🙂

**Comment by jansenbe** [comment]
Here's some research on Task.Run:

- https://stackoverflow.com/questions/18013523/when-correctly-use-task-run-and-when-just-async-await
- https://www.pluralsight.com/guides/using-task-run-async-await

**Comment by indieza** [comment]
Hello,
I update the code and run in on Debug mode, but still receive the same error. I commit the new version, may you take a look over it.

**Comment by jansenbe** [comment]
@indieza : ok,  I missed the inner exception that happens on the first run after opening the form. As you need to run the async calls outside of the UI thread (to avoid blocking it) you end up with multiple threads using the same `PnPContext` instance...especially in this case as loading the lists combo triggers a change event that calls to load list again and it's content types.

You could try with writing code to ensure thread safe access to the PnPContext you're using, but a more performing approach would be to simply load all the data you need at form load and stuff it into the PnPContext. You can then in the event handlers just use that data.

So in `GetSharePointWebsiteWeb` use this:

```csharp
                using (var context = await pnpContextFactory.CreateAsync(new Uri(url)).ConfigureAwait(false))
                {
                    this.web = await context.Web.GetAsync(p => p.ContentTypes,
                                                          p => p.Lists.QueryProperties(p => p.Hidden, p => p.Title, p => p.Description, p => p.TemplateType, p => p.ContentTypes)).ConfigureAwait(false);
                }

```

The event handlers would then be implemented like this:

```csharp
        private async void AuthenticateButton_Click(object sender, EventArgs e)
        {
            try
            {
                ICollection<ListBaseViewModel> lists = new List<ListBaseViewModel>();

                await Task.Run(async () =>
                {
                    this.web = await this.sharePointAuthenticationService
                        .GetSharePointWebsiteWeb(this.WebsiteUrlTextBox.Text)
                        .ConfigureAwait(false);
                });

                lists = this.web.Lists.AsRequested().Where(x => x.Hidden == false)
                    .Select(x => new ListBaseViewModel(x.Id, x.Title, x.Description, x.TemplateType))
                    .OrderBy(x => x.Title)
                    .ToList();

                this.AllListsComboBox.DataSource = new BindingSource(lists, null);
                this.AllListsComboBox.DisplayMember = nameof(ListBaseViewModel.Title);
                this.AllListsComboBox.ValueMember = nameof(ListBaseViewModel.ID);
                this.AllListsComboBox.Enabled = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private async void AllListsComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            var list = this.AllListsComboBox.SelectedItem as ListBaseViewModel;

            if (this.web != null && list != null)
            {
                try
                {
                    var possibleContentTypes = new List<ContentTypeBaseViewModel>();

                    var allContentTypes = this.web.ContentTypes.AsRequested()
                        .Where(x => x.Group != "_Hidden")
                        .Select(x => new ContentTypeBaseViewModel(x.Id, x.Name))
                        .OrderBy(x => x.Name)
                        .ToList();

                    var listToUse = this.web.Lists.AsRequested().First(p => p.Id == list.ID);
                    var listContentTypes = listToUse.ContentTypes.AsRequested()
                        .Select(x => new ContentTypeBaseViewModel(x.Id, x.Name))
                        .OrderBy(x => x.Name)
                        .ToList();

                    possibleContentTypes = allContentTypes
                        .Where(x => !listContentTypes.Any(y => y.ID == x.ID || y.Name == x.Name))
                        .OrderBy(x => x.Name)
                        .ToList();

                    this.AllContentTypesComboBox.DataSource = new BindingSource(possibleContentTypes, null);
                    this.AllContentTypesComboBox.DisplayMember = nameof(ContentTypeBaseViewModel.Name);
                    this.AllContentTypesComboBox.ValueMember = nameof(ContentTypeBaseViewModel.ID);
                    this.AllContentTypesComboBox.Enabled = true;
                    this.selectedList = list;
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

```

**Comment by indieza** [comment]
It sounds great, I will test it and will come back if there is something which stop me. Thanks 🙂

**Comment by jansenbe** [comment]
Yes, I'm gonna close this thread as I feel this is not due to a bug in PnP Core SDK but rather related to how to correctly use and handle async calls in WinForm UI events. Don't triggering the refresh of the content type combo when loading the initial list combo will also improve things as then you avoid the parallel threads
