### ISSUE TITLE
Get list view by title throws an exception

### ISSUE THREAD

**Issue by s-KaiNet** [pnp/pnpcore#627]
## Category

- [x] Bug

## Describe the bug

When I try to get a listview by its title, I got an exception. 

## Steps to reproduce
The code is fairly simple:

```csharp
using (var context = await TestCommon.Instance.GetContextAsync(TestCommon.TestSite))
{
	var list = context.Web.Lists.GetByServerRelativeUrl($"{context.Uri.LocalPath}/Shared Documents");
	var wh = await list.Views.Where(s => s.Title == "All Documents").FirstOrDefaultAsync();
}
```

From developer perspective it's a perfectly valid code, it compiles, however it throws
> System.InvalidCastException: Unable to cast object of type 'System.Linq.EmptyPartition`1[PnP.Core.Model.SharePoint.IView]' to type 'PnP.Core.Model.SharePoint.IView'. 

at [this line](https://github.com/pnp/pnpcore/blob/8d6a0c51317c2409044b33607c938d545d5d8fbb/src/sdk/PnP.Core/QueryModel/Linq/BaseQueryProvider.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L164) as a result of  [this](https://github.com/pnp/pnpcore/blob/8d6a0c51317c2409044b33607c938d545d5d8fbb/src/sdk/PnP.Core/QueryModel/Query/DataModelQueryService.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L148). `View` does not implement `IQueryableDataModel`, as a result a new `Enumerable.Empty<TModel>();` is returned, but the cast fails later on.

I used the `View` object as an example, we might see the similar issues for other objects as well. The problem is, that we actually don't know what should be the return type. If I use `FirstOrDefault`, then the return type should be `default(TModel)`, if `ToList`, then `IEnumerable<TModel>` etc. Even if we return a valid type, it still might be confusing for a library consumer why it doesn't return value? (I know, that there is a view called `All Documents), but the library return null.   

Would it be more natural to just throw an exception in this case? I.e. if a class does not implement `IQueryableDataModel`, then [here](https://github.com/pnp/pnpcore/blob/8d6a0c51317c2409044b33607c938d545d5d8fbb/src/sdk/PnP.Core/QueryModel/Query/DataModelQueryService.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L148): 

```diff
- return Enumerable.Empty<TModel>();
+ throw new Exception($"LINQ queries are not supported for {typeof(TModel).Name} type.");
```

**Comment by jansenbe** [comment]
Thanks for reporting this @s-KaiNet. The fact that some models that are populated via REST and having their `LinqGet` property set do have the `IQueryableDataModel` interface set is wrong. I'll fix those.

I also do like the idea of throwing an exception instead of returning an empty collection, think this way things will be better for the developer as there's clarity on why things do not work.

**Comment by jansenbe** [comment]
@s-KaiNet : implemented.
