### ISSUE TITLE
Only the first LookupValue is written when using NewFieldValueCollection

### ISSUE THREAD

**Issue by RoRo300** [pnp/pnpcore#628]
## Category

- [x] Bug

## Describe the bug

When creating or updating a list item in Sharepoint only the first field lookup value is written to the list if a field is a multiple lookup value. further items are ignored. 

## Steps to reproduce

A new FieldValueCollection is declared and 1-n lookup items are assigned with NewFieldLookupValue from IField.
The return value is the declared lookupCollection that is later assigned to the values dictionary of the list item. AddAsync or UpdateAsync are respectively successful.

if (propTypeFromSource == typeof(IEnumerable<LookupItem>))
{
       var lookupCollection = field.NewFieldValueCollection();
       if (valuesFromSource != null)
       {
             List<LookupItem> lookupItemsEnum = ((IEnumerable<LookupItem>)valuesFromSource).ToList();
             lookupItemsEnum.ForEach(p => lookupCollection.Values.Add(field.NewFieldLookupValue(p.LookupId)));
       }
       return lookupCollection;
}

## Expected behavior

All assigned FieldLookupValues are properly written to a list item when using a FieldValueCollection on a multiple lookup field

## Environment details (*development & target environment*)

Development: VS 2019
Version SDK: PnP.Core 1.4.14-nightly
Target: Sharepoint Online
Authentification: interactive

**Comment by jansenbe** [comment]
Thanks for using PnP Core SDK @RoRo300 , I'll have a look and report back

**Comment by jansenbe** [comment]
@RoRo300 : I could reproduce and fix the issue. See https://github.com/pnp/pnpcore/issues/628 for the fix itself. This change will appear in tomorrow's nightly build, so please give that a try and let us know. Thanks!

**Comment by RoRo300** [comment]
Cool! Thanks for your fast reaction. Will try it tomorrow and let you know if it works!

**Comment by RoRo300** [comment]
Hi Bert! Works perfectly! GREAT!
