### ISSUE TITLE
PnP.Core.ClientException: Specify the GraphGet/GraphGetLinq field of the ClassMapping property

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/pnpcore#631]
## Category

- [x] Bug / Question?

## Describe the bug
Unhelpful exception when querying sub-webs:
PnP.Core.ClientException: Specify the GraphGet/GraphGetLinq field of the ClassMapping property

Attempting to follow documentation to enumerate sub-webs:
https://pnp.github.io/pnpcore/using-the-sdk/webs-intro.html#getting-sub-webs

Error thrown:
![image](https://user-images.githubusercontent.com/3208188/142072652-5af6564f-d0fa-4544-a1e8-19d35f8ff4b1.png)

Source code:
![image](https://user-images.githubusercontent.com/3208188/142072735-35142dc7-f7db-4e90-b67e-28b5eb7b4ce3.png)

Essential bits:
`
var url = "https://contoso.sharepoint.com";

var context = await Pnp.CreateAsync(new Uri(url));

log.Log($"Loaded context for {ctx.Site.Id}");

var site = ctx.Site;

await site.GetAsync(p => p.RootWeb);

var rw = site.RootWeb;

await rw.GetAsync(p => p.Webs);

foreach (var w in rw.Webs) << Exception accessing rw.Webs property.
`

## Steps to reproduce

Code above.
Can I not use PnPContext.Site.RootWeb.Webs with the foreach?

## Expected behavior

When accessing Context.Site.RootWeb.Webs I expect to be able to enumerate the webs within that site after doing the GetAsync calls as per the documentation.

Throw informative exception or improve documentation?

## Environment details (*development & target environment*)

- **SDK version**: 1.4.0
- **OS**: Win10
- **SDK used in**: Console app, .NET Framework 4.7.2
- **Framework**: .NET Framework 4.7.2
- **Browser(s)**: Chorme?
- **Tooling**: VS2019
- **Additional details**: None.

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@SPDEVGUY : Once you've loaded data you need to use `.AsRequested()` to query the loaded data...in your case you're trying to query twice. The documentation was still missing `AsRequested()` thanks for spotting that.

So your code would be like this:

```csharp
var url = "https://contoso.sharepoint.com";
var context = await Pnp.CreateAsync(new Uri(url));
log.Log($"Loaded context for {ctx.Site.Id}");
var site = ctx.Site;
await site.GetAsync(p => p.RootWeb);
var rw = site.RootWeb;
await rw.GetAsync(p => p.Webs);

foreach (var w in rw.Webs.AsRequested())
{
}
```

You could also optimize above code a little bit as rootweb is always loaded by default + possibly you can save a roundtrip by loading additional RootWeb properties during PnPContext initialization (see https://pnp.github.io/pnpcore/using-the-sdk/basics-context.html). Taking that in account below code will do 2 server roundtrips to achieve the same result:

```csharp
var options = new PnPContextOptions()
{
    AdditionalWebPropertiesOnCreate =
        new Expression<Func<IWeb, object>>[]
        {
            w => w.Webs
        }
};

var url = "https://contoso.sharepoint.com";
var context = await Pnp.CreateAsync(new Uri(url), options);


```

**Comment by s-KaiNet** [comment]
I think still we have an issue here, because below code throws an exception:

```csharp
var webs = context.Web.Webs.ToList();
```
To my understanding, it shouldn't throw and should query subwebs instead.

**Comment by jansenbe** [comment]
@s-KaiNet : Yes, I know...something to still be fixed. For @SPDEVGUY 's case however the provided code is a good alternative, but I do agree that this should be fixed to ensure a consist experience across the various models

**Comment by jansenbe** [comment]
@s-KaiNet , @SPDEVGUY : I've also pushed a fix that enables using LINQ (`context.Web.Webs.ToList()` or `foreach (var w in rw.Webs) `. Think this issue can be closed now.
