### ISSUE TITLE
Unable to Make Custom API calls with Custom Header

### ISSUE THREAD

**Issue by somdeepgniyogi** [pnp/pnpcore#637]
Hi,

The WithHeader extension is not available with IWeb. 
![image](https://user-images.githubusercontent.com/6120892/142242132-cbd71588-dc9d-4dd6-a565-8b4b400a0924.png)

I have added reference to PnP.Core.Models.

Can somebody please help.

BR

**Comment by jansenbe** [comment]
@somdeepgniyogi : this only is available in our preview versions of 1.4...are you using those? `WithHeaders` is in the `PnP.Core.Model` namespace.

**Comment by somdeepgniyogi** [comment]
Hi @jansenbe ,

Thanks a lot, it works.

BR,
Somdeep
