### ISSUE TITLE
Review and complete the Web/Site domain model 

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#64]
## Category

- [x] Feature request

## Describe the feature

Review and complete the Web/Site domain model : current web/site model was copied from pnp provisioning engine model and still lacks some of the web/site properties. This is a nice and simple change to start with for new contributors. See https://aka.ms/pnp/coresdk/contributors on how to get started.

**Comment by ypcode** [comment]
Temporarily self assigned to implement some of the properties of the Web model

**Comment by jansenbe** [comment]
Closing this one for now, think we cover more than enough for preview 3. Let's create new issues for the individual missing things once they popup. Thanks for all the great work here @ypcode !
