### ISSUE TITLE
Saving a page via PnP leads to duplicates of inline image webparts

### ISSUE THREAD

**Issue by frupprecht-nC** [pnp/pnpcore#644]
## Category

- [x] Bug

## Describe the bug

Microsoft recently added the ability, to add images inside a text webpart. Unfortunately PnP does not handle this new funcionality correctly.

I've created a new page with an image inside a text webpart. If I now load and save this page via PnP (without any modifications in between), the image appears twice on the page. The inline image is still in place inside the text webpart, but above the text webpart there is now an additional image webpart containing the same image. If I delete the added image webpart, also the inline image inside the text webpart disappears.

## Steps to reproduce

1. Create a new SitePage
1. Add some text and an inline image to the existing text webpart
1. Save the page via SharePoint UI
1. Load and save the page without any modifications in between via PnP. Example code below (C#):
```
var context = await authProvider.GetContextAsync("https://mytenant.sharepoint.com/sites/testsite");
var page = context.Web.LoadClientSidePage("MyPage.aspx");
await page.SaveAsync();
```

## Expected behavior

The page should not be modified at all, since we do not make any changes to it between loading and saving it via PnP. The image should not be duplicated.

## Environment details (*development & target environment*)

- **SDK version**: PnP.Core 1.4.0, PnP.Core.Auth 1.4.0, PnP.Framework 1.7.0
- **SDK used in**: Azure Function, Console App
- **Framework**: .NET Core 3.1, .NET 5
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
@frupprecht-nC , thanks for reporting this. We've not yet tested the inline image scenario, so guess we've some work to do :-)

**Comment by jansenbe** [comment]
@frupprecht-nC : I've just pushed a fix that enables support for inline images. Now you can read and save a page having text with inline images but you can also programmatically add inline images to your text parts. Doc updates will follow.

**Comment by frupprecht-nC** [comment]
@jansenbe That's great, thanks for the quick response and fix ☺

**Comment by jansenbe** [comment]
@frupprecht-nC : docs are here https://pnp.github.io/pnpcore/using-the-sdk/pages-webparts.html#using-inline-images-in-text-parts, I've kicked off the generation of a new nightly build, so within 30 minutes or so you can pull the latest version and give it a try.

**Comment by jansenbe** [comment]
@frupprecht-nC : fee free to try with current nightly release and see if things work for you. If so, then we can close this issue.

**Comment by jansenbe** [comment]
@frupprecht-nC : I'm closing this issue, if you still have issues feel free to either re-open this one or create a new issue.

**Comment by frupprecht-nC** [comment]
Works great on my end, thank you very much!
