### ISSUE TITLE
Unresolved tokens found in API Call (ISite.HubSiteSynchronizableVisitorsGroup)

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/pnpcore#645]
## Category

- [x] Bug

## Describe the bug
![image](https://user-images.githubusercontent.com/3208188/142520169-f37dd013-ccf7-40a3-8d77-c0add4dad392.png)
![image](https://user-images.githubusercontent.com/3208188/142520217-8c986cf6-48ff-43df-b426-d1554ec6bf82.png)

Did a load on ISite.HubSiteSynchronizableVisitorGroup then attempting to query property Id.  PnP says Id isn't loaded, so I check if the group property is null and then do an ensure on the property.  Exception received, likely because the visitor group is actually null.  The site isn't a hub-site member.  Technically the call is invalid however a better error could be thrown.  I'll add some logic to my code to not perform that op if hub site id is an empty guid.

As a bit of a context background, I am actually trying to query all properties of the group when i get the group.  Is there any more efficient way to tell the framework I want all the properties on an object instead of me manually coding each property I want into an EnsureProperties call?

## Steps to reproduce

1. have a site collection that isn't a hub site member.
2. load site collection context
3. ISite.LoadAsync(p=>HubSiteSynchronizableVisitorGroup)
4. Expecting NULL or something from ISite.HubSiteSynchronizableVisitorsGroup if it doesn't exist.
5. EnsurePropertiesAsync on ISite.HubSiteSynchronizableVisitorGroup.Id
6. Explode

## Expected behavior

give me null on HubSiteSynchronizableVisitorsGroup once loaded ?

## Environment details (*development & target environment*)

- **SDK version**: 1.4.5
- **OS**: win10
- **SDK used in**: Console app
- **Framework**: .net FW 4.7.2 (.net core 2)
- **Browser(s)**: chrome
- **Tooling**:  VS 2019
- **Additional details**: none

### Additional context
none
*Thanks for your contribution! Sharing is caring.*

**Comment by SPDEVGUY** [comment]
`
if (site.HasValue(nameof(site.HubSiteSynchronizableVisitorGroup)))
`
does not work for checking this as well.

**Comment by jansenbe** [comment]
@SPDEVGUY: checking if a simple property is loaded is best done using `IsPropertyAvailable` or `ArePropertiesAvailable` so for example `site.IsPropertyAvailable(p => p.HubSiteSynchronizableVisitorGroup)`. This approach takes in account the scenario you see, meaning that there's no group.

To load all the default properties you can do something like `await site.LoadAsync(p => p.All)`. Note that this returns the properties set as default for a Site by the SharePoint team, so not each and every property will be returned. If the property you need is missing you can combine the All with the missing properties e.g. `await site.LoadAsync(p => p.All, p=>p.ThicketSupportDisabled)`
