### ISSUE TITLE
How do I use PNP Core SDK to connect with Application Permission

### ISSUE THREAD

**Issue by somdeepgniyogi** [pnp/pnpcore#647]
Hi,

I have an Azure App that needs to connect to SharePoint Online using Graph APIs. I am using PNP core SDK and trying to connect to SharePoint Online using the below code

 **var siteUrl = new Uri(_pnpCoreOptions.Sites["Site"].SiteUrl);
            return await _pnpContextFactory.CreateAsync(siteUrl,
                           new ExternalAuthenticationProvider((resourceUri, scopes) =>
                           {
                               return _tokenAcquisition.GetAccessTokenForAppAsync(scopes.FirstOrDefault()).GetAwaiter().GetResult();
                           }
                   )).ConfigureAwait(false);**

I have the below permissions

![image](https://user-images.githubusercontent.com/6120892/142624473-47592c25-2af8-4b8b-b3b4-a01534ec160c.png)

However I am getting PnP.Core.SharePointRestServiceException 401.

It works if I   return _tokenAcquisition.GetAccessTokenForUserAsync.(scopes).GetAwaiter().GetResult();

Can you kindly help what am I doing wrong.

BR,

**Comment by jansenbe** [comment]
Using sites.selected only works for Graph based APIs at the moment and PnP Core SDK also requires SharePoint REST APIs. What you can do is not use sites.selected, add SharePoint Sites.FullControl.All permissions and use that. See https://pnp.github.io/pnpcore/tutorials/azurefunctions/v4processisolatedapponly.html for a tutorial on using app-only in an Azure Function.

**Comment by jansenbe** [comment]
@somdeepgniyogi : note that support for using sites.selected is coming for REST/CSOM APIs...

**Comment by somdeepgniyogi** [comment]
Hi @jansenbe ,

Thanks a lot for your reply. Will be waiting for Site.Selected scope to be available for PNP core.


BR

**Comment by jansenbe** [comment]
@somdeepgniyogi : well that's not a PnP thing but a SharePoint feature...once sites.selected can be used with REST/CSOM APIs it should automatically work in PnP Core SDK as well, no changes needed.

**Comment by jansenbe** [comment]
Will close this issue then.
