### ISSUE TITLE
Docs - Setup for tests

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#65]
## Category

- [x] Bug

You may need a new category for doc updates maybe?

When setting up the unit tests the solution relies on an Azure AD app "PnP Office 365 Management Shell" which needs to either be added or consented. I used PnP PowerShell docs example 11 in https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps to set this up.

```powershell
Connect-PnPOnline -Url https://contoso.sharepoint.com -PnPO365ManagementShell
```
All tests build after this.

You ok for me to update the docs?

**Comment by jansenbe** [comment]
Thanks for this one @pkbullock , just merged your PR
