### ISSUE TITLE
GetSiteCollectionsAsync returns exception "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by pxmonti** [pnp/pnpcore#651]
## Category

- [x] Bug

## Describe the bug

Recently, calling _await context.GetSiteCollectionManager().GetSiteCollectionsAsync()_ throws a Json exception.
This was not happening last week.
The GraphAPI response must have changed.

## Steps to reproduce

Obtain a context and then call
await context.GetSiteCollectionManager().GetSiteCollectionsAsync()

## Environment details (*development & target environment*)

- **SDK version**: 1.4.53-nightly
- **OS**: Windows 11
- **SDK used in**: Azure function
- **Framework**:.NET Core v3.1
- **Browser(s)**:  Chrome | Edge 
- **Tooling**: Visual Studio 2019

### Additional context

The GraphAPI JSON response does not contain the property _sharepointIds_  but the SDK expects it.

Response captured by Fiddler

![image](https://user-images.githubusercontent.com/4302704/142838549-fe32732c-d5c5-48ae-85f9-0532b36f13a3.png)

The property is referenced in 
src/sdk/PnP.Core.Admin/Model/SharePoint/Core/Internal/SiteCollectionEnumerator.cs

method:
internal async static Task<List<ISiteCollection>> GetViaGraphSitesApiAsync(PnPContext context)

Line 415:

``` CSharp
// Root sites have the root property set, ensuring we're not loading up sub sites as site collections
                        if (siteInformation.TryGetProperty("root", out JsonElement _))
                        {
                            var sharePointIds = siteInformation.GetProperty("sharepointIds");

                            AddLoadedSite(loadedSites,
                                          siteInformation.GetProperty("id").GetString(),
                                          siteInformation.GetProperty("webUrl").GetString(),
                                          sharePointIds.GetProperty("siteId").GetGuid(),
                                          sharePointIds.GetProperty("webId").GetGuid(),
                                          siteInformation.TryGetProperty("displayName", out JsonElement rootWebDescription) ? rootWebDescription.GetString() : null);
                        }

```

Exception stack trace:

The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetViaGraphSitesApiAsync(PnPContext context)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetAsync(PnPContext context, Boolean ignoreUserIsTenantAdmin)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetSiteCollectionsAsync(Boolean ignoreUserIsSharePointAdmin)
   at TestSPOScan.TenantScanScheduler.Run(TimerInfo myTimer, ILogger log) in 
...

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@pxmonti : interesting, will have a look later today

**Comment by jansenbe** [comment]
@pxmonti : seems like the default properties returned by Graph have changed :-(

I've now defined the properties in the $select and we're back in business. Fix will appear in the next nightly.

**Comment by pxmonti** [comment]
Perfect, thank you @jansenbe . I will try tomorrow with the new nightly build.

**Comment by pxmonti** [comment]
Hello @jansenbe, it seems that with the 1.4.57-nightly the issue is fixed. Thank you!
