### ISSUE TITLE
[BUG] Remove sections of the page not working

### ISSUE THREAD

**Issue by Employee87** [pnp/pnpcore#666]
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
It removes the sections of the page.

### Actual behavior 
Sections of the page still persists. No error thrown. I tried a test where the Home page has 2 sections. And it prints out `1` and then `0`.

### Steps to reproduce behavior
```
Connect-PnPOnline -Url "https://mysite.sharepoint.com/sites/TestSite" -Interactive
 $pg = Get-PnPPage -Identity "Home"
 $sectionsCount = $pg.Sections.Count
 for($i=$sectionsCount-1; $i -ge 0; $i--) {
     write-host $i
     $pg.Sections.RemoveAt($i)
 }
 $pg.Save()
 $page = Set-PnPPage -Identity $pg -Publish
 Disconnect-PnPOnline
```

### What is the version of the Cmdlet module you are running?
Manifest 1.7.0 PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jansenbe** [comment]
@Arturiby: thanks for notifying me of this issue. I've fixed this and the next nightly PowerShell version will have it included.

FYI @Employee87 / @gautamdsheth
