### ISSUE TITLE
Linq query improvement: detect unsupported expressions and throw proper exception

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#67]
## Category

- [x] Feature request

## Describe the feature

Below works:

```csharp
var listGuid = Guid.Parse("56615e6f-6767-465c-aae9-1aa3cba2d846");
var list = context.Web.Lists.Where(p => p.Id == listGuid).FirstOrDefault();
```
but this doesn't. Is this something that we can add or too complex to implement?

```csharp
var list = context.Web.Lists.Where(p => p.Id == Guid.Parse("56615e6f-6767-465c-aae9-1aa3cba2d846")).FirstOrDefault();
```

**Comment by jansenbe** [comment]
Let's align with EF LINQ support - this is not needed - check if we throw the proper exception

**Comment by ypcode** [comment]
Have you tried new Guid(« ... ») instead ?

**Comment by jansenbe** [comment]
Not really a problem - dropping this one
