### ISSUE TITLE
"Access token validation failure. Invalid audience." Accessing USGovernmentHigh Tenant

### ISSUE THREAD

**Issue by Sean-LM** [pnp/pnpcore#671]
## Category

- [x] Bug

## Describe the bug

I am attempting to follow the steps from there:
https://pnp.github.io/pnpcore/using-the-sdk/configuring%20authentication.html#application-permissions-acting-as-an-app-account-with-app-only-permissions

The main difference is that my tenant is in Azure US Government High (i.e. portal.azure.us, xyz.sharepoint.us) - I figured out to set the 
`Environment = Microsoft365Environment.USGovernmentHigh,` on my `PnPCoreAuthenticationCredentialConfigurationOptions` object, and looking at the log output, most of the authentication chatter is going to `.us` domains.

Eventually, I fail with `'Microsoft Graph service exception'` which has an inner Error with a 401 `"Access token validation failure. Invalid audience."`

Here are the last few lines of logging output before the 401 (there is quite a bit of back and forth 200 requests before this point):

```
info: System.Net.Http.HttpClient.MsalHttpClient.LogicalHandler[100]
      Start processing HTTP request POST https://login.microsoftonline.us/redacted/oauth2/v2.0/token
System.Net.Http.HttpClient.MsalHttpClient.LogicalHandler: Information: Start processing HTTP request POST https://login.microsoftonline.us/redacted/oauth2/v2.0/token
info: System.Net.Http.HttpClient.MsalHttpClient.ClientHandler[100]
      Sending HTTP request POST https://login.microsoftonline.us/redacted/oauth2/v2.0/token
System.Net.Http.HttpClient.MsalHttpClient.ClientHandler: Information: Sending HTTP request POST https://login.microsoftonline.us/redacted/oauth2/v2.0/token
info: System.Net.Http.HttpClient.MsalHttpClient.ClientHandler[101]
      Received HTTP response headers after 256.5868ms - 200
System.Net.Http.HttpClient.MsalHttpClient.ClientHandler: Information: Received HTTP response headers after 256.5868ms - 200
info: System.Net.Http.HttpClient.MsalHttpClient.LogicalHandler[101]
      End processing HTTP request after 264.6012ms - 200
System.Net.Http.HttpClient.MsalHttpClient.LogicalHandler: Information: End processing HTTP request after 264.6012ms - 200
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://graph.microsoft.com/' from , https://graph.microsoft.com/.default
PnP.Core.Auth.OAuthAuthenticationProvider: Information: Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://graph.microsoft.com/' from , https://graph.microsoft.com/.default
info: System.Net.Http.HttpClient.MicrosoftGraphClient.LogicalHandler[100]
      Start processing HTTP request POST https://graph.microsoft.us/v1.0/$batch
System.Net.Http.HttpClient.MicrosoftGraphClient.LogicalHandler: Information: Start processing HTTP request POST https://graph.microsoft.us/v1.0/$batch
info: System.Net.Http.HttpClient.MicrosoftGraphClient.ClientHandler[100]
```

The suspicious part to me is here:

> Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://graph.microsoft.com/' from , https://graph.microsoft.com/.default

Should those scopes be `...microsoft.us...`?

## Steps to reproduce

1. Using a Tenant is US Government Azure env, follow guidance from https://pnp.github.io/pnpcore/using-the-sdk/configuring%20authentication.html#application-permissions-acting-as-an-app-account-with-app-only-permissions to access basic details about a SharePoint Online Site.

## Expected behavior

Able to authenticate and interact with SharePoint API in SPOnline environment in US Government Azure Environment.

## Environment details (*development & target environment*)

- **SDK version**: 1.4.68-nightly
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .NET 6
- **Browser(s)**: n/a
- **Tooling**: VS Code 
- **Additional details**: 

### Additional context

Thanks in advance, let me know if I can provide any further detail. I am fairly new to Azure & SPOnline development but I have a lot of experience with the PnP libraries and on-prem SharePoint development utilizing the older versions.

**Comment by jansenbe** [comment]
Thanks using PnP Core SDK and raising this issue @Sean-LM . Looking at the code we indeed were still hard coding graph.microsoft.com for acquiring an access token, which was not working. I've made a fix and created a new build (1.4.70), can you test if that one works. I unfortunately do not have access to an USGovernmentHigh tenant, but hoping you could verify things. If there's other issues then please let me know.

**Comment by Sean-LM** [comment]
🎉 Thanks so much - first try after upgrading to 1.4.70-nightly worked! I am able to retrieve my `sharepoint.us` site detail!

**Comment by Ambergahill** [comment]
Is this related to the issue I am having? Same "Access token validation failure. Invalid audience." error. I am trying to create a group connected team site using New-PnpSite -Type TeamSite -Title 'test site' -alias TestAlias

This is also for an Azure US gov high tenant. I have no issues using New-PnPSite to create a communication site or non-group connected team site. I am on build 1.10.0
