### ISSUE TITLE
Styles for PageImageOptions

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpcore#677]
## Category

- [ ] Feature request

## Describe the feature

> Hello, I was thinking about adding some possibilities of styling for inline images in text webparts

## Describe the solution you'd like

> Possibility to have feature in code like:
var options = new PageImageOptions();
options.Alignment = PageImageAlignment.Left;
options.Width = 800; // px
options.Height = 600; // px
var inlineImage = page.GetInlineImage(control, url, options);

**Comment by jansenbe** [comment]
Implemented (https://github.com/pnp/pnpcore/commit/c47b4b757320042f276d9cb1ba48d0224a04c5da). Will be part of the next nightly version (1.4.74)

**Comment by jansenbe** [comment]
Closing the issue, please re-open when things are not working as expected.
