### ISSUE TITLE
Update documentation for ISharePointGroup.GetRoleDefinitionsAsync to note that it is based on current pnp web context

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/pnpcore#682]
## Category

- [x] Bug

## Describe the bug

https://pnp.github.io/pnpcore/api/PnP.Core.Model.Security.ISharePointGroup.html?q=ISharePointGroup

Documentation should be adjusted to inform the developer that GetRoleDefinitions/async() is querying against the current Web Context to retrieve a flattened view of the RoleAssignments listed from the pnp context web.

## Steps to reproduce

documentation adjustment

## Expected behavior

Initially I was confused thinking SPOnline had options for site collection wide role definitions associated with a group.

## Environment details (*development & target environment*)

N/a

### Additional context

The cool thing about open source is that you can see what it's actually doing =P  I feel like this would just be an improvement on the context incase someone like me is enumerating groups at the site collection root web level.

**Comment by jansenbe** [comment]
@SPDEVGUY : thanks for feedback. PnP Core SDK uses a `PnPContext` object as entry point for a given web, whether that's the root web of a site collection or a sub web of that root web. So you're creating a context for a web (SPWeb) and not a site (SPSite). In non technical terms folks then often speak about a site collection (= SPSite) and a site (=SPWeb) and I do agree that this might be confusing.

I'll see if we can further clarify in docs that you need to create a new `PnPContext` per site (=SPWeb) you're working with. We'll not automatically start doing operations across all SPWebs as that would be a breaking change with the current behaviour + it could lead to performance issues when a site collection has a ton of sub sites. https://pnp.github.io/pnpcore/using-the-sdk/webs-intro.html#getting-sub-webs describes how you can iterate the webs of the current web.

**Comment by jansenbe** [comment]
Here's the [updated doc part](https://pnp.github.io/pnpcore/using-the-sdk/readme.html#obtaining-a-pnpcontext):

![image](https://user-images.githubusercontent.com/7451219/145361220-5aedc7fd-35b0-4209-ba2d-839d760989c5.png)

Closing this issue now.
