### ISSUE TITLE
_layouts images in InlineImage

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpcore#697]
### Discussed in https://github.com/pnp/pnpcore/discussions/695

<div type='discussions-op-text'>

<sup>Originally posted by **Nevinia210** December 17, 2021</sup>
Hello everyone,

Is it possible to have inline image from system images("/_layouts/images/icpdf.png")?
I'm getting following error while trying to do that:
The file /sites/mytestsite/_layouts/images/icpdf.png does not exist.

when i try to access that file with url, its there</div>

**Comment by jansenbe** [comment]
Hey @Nevinia210 ,

As there's no UI option to add (inline) image web parts pointing to images in _layouts I don't think it's a good idea to allow this via the API. Doing so might end up in a page, that after editing by a user, will loose the image. Therefore I'm closing this issue, hope you can understand. 

![image](https://user-images.githubusercontent.com/7451219/146894535-9d4052e7-c14e-4930-a27e-37ff7b2bc88c.png)
