### ISSUE TITLE
Iterating Items on list executes REST with $top & $skip

### ISSUE THREAD

**Issue by trueleader** [pnp/pnpcore#701]
## Category

- [x] Bug

## Describe the bug

I have configured to use GraphFirst but console outputs REST usage with $top & $skip. The iteration never ends on a list with 163 items (max ID 171):

> dbug: PnP.Core.Services.PnPContext[0]
      GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists?$select=Id%2cFields%2fInternalName%2cFields%2fFieldTypeKind%2cFields%2fTypeAsString%2cFields%2fTitle%2cFields%2fId&$expand=Fields&$filter=Title+eq+%27Divisions%27&$top=1
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://mxdev.sharepoint.com/sites/GremlinAppDev' from , https://mxdev.sharepoint.com/.default
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[100]
      Start processing HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists?$select=Id%2cFields%2fInternalName%2cFields%2fFieldTypeKind%2cFields%2fTypeAsString%2cFields%2fTitle%2cFields%2fId&$expand=Fields&$filter=Title+eq+%27Divisions%27&$top=1
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[100]
      Sending HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists?$select=Id%2cFields%2fInternalName%2cFields%2fFieldTypeKind%2cFields%2fTypeAsString%2cFields%2fTitle%2cFields%2fId&$expand=Fields&$filter=Title+eq+%27Divisions%27&$top=1
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[101]
      Received HTTP response after 97.9856ms - OK
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[101]
      End processing HTTP request after 98.1717ms - OK
dbug: PnP.Core.Services.PnPContext[0]
      GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://mxdev.sharepoint.com/sites/GremlinAppDev' from , https://mxdev.sharepoint.com/.default
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[100]
      Start processing HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[100]
      Sending HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[101]
      Received HTTP response after 233.5762ms - OK
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[101]
      End processing HTTP request after 233.7953ms - OK
dbug: PnP.Core.Services.PnPContext[0]
      GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=100
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://mxdev.sharepoint.com/sites/GremlinAppDev' from , https://mxdev.sharepoint.com/.default
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[100]
      Start processing HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=100
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[100]
      Sending HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=100
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[101]
      Received HTTP response after 90.5449ms - OK
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[101]
      End processing HTTP request after 90.656ms - OK
dbug: PnP.Core.Services.PnPContext[0]
      GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=200
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://mxdev.sharepoint.com/sites/GremlinAppDev' from , https://mxdev.sharepoint.com/.default
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[100]
      Start processing HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=200
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[100]
      Sending HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=200
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[101]
      Received HTTP response after 94.2781ms - OK
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[101]
      End processing HTTP request after 94.4402ms - OK
dbug: PnP.Core.Services.PnPContext[0]
      GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=300
info: PnP.Core.Auth.OAuthAuthenticationProvider[0]
      Retrieved access token for resource X509CertificateAuthenticationProvider with scopes 'https://mxdev.sharepoint.com/sites/GremlinAppDev' from , https://mxdev.sharepoint.com/.default
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[100]
      Start processing HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=300
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[100]
      Sending HTTP request GET https://mxdev.sharepoint.com/sites/GremlinAppDev/_api/web/lists(guid'fecd0f3f-b0e2-4cfd-985c-c36b35d066be')/items?$select=Id%2cTitle&$top=100&$skip=300
info: System.Net.Http.HttpClient.SharePointRestClient.ClientHandler[101]
      Received HTTP response after 122.2679ms - OK
info: System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler[101]
      End processing HTTP request after 122.4864ms - OK
      ...

## Steps to reproduce

Configured service
```cs
services.AddPnPCore(options =>
{
	options.PnPContext.GraphFirst = true;
	options.HttpRequests.UserAgent = "GremlinMigrations";

	options.Sites.Add("Gremlin", new PnP.Core.Services.Builder.Configuration.PnPCoreSiteOptions
	{
		SiteUrl = config.Url
	});
});

services.AddPnPCoreAuthentication(options =>
{
	options.Credentials.Configurations.Add("certificate", new PnPCoreAuthenticationCredentialConfigurationOptions
	{
		ClientId = config.ClientId,
		TenantId = config.TenantId,
		X509Certificate = new PnPCoreAuthenticationX509CertificateOptions
		{
			Certificate = new X509Certificate2(config.ClientCertPath)
		}
	});

	options.Credentials.DefaultConfiguration = "certificate";

	options.Sites.Add("Gremlin", new PnPCoreAuthenticationSiteOptions
	{
		AuthenticationProviderName = "certificate"
	});
});
```

Instanciate PnP, put it into a DataCreator instance and execute
```cs
public async Task<DataCreator> Instance()
{
	var pnp = await _pnpFactory.CreateAsync("Gremlin").ConfigureAwait(false);
	return new DataCreator(pnp);
}

private async Task Execute(DataCreator creator)
{
	await creator.Create().ConfigureAwait(false);
}
```

DataCreator:RetrieveListMap never ends when iterating the Divisions list items
```cs
public class DataCreator : IDisposable
{
	private readonly PnPContext _pnp;

	private bool _initialized;

	public DataCreator(PnPContext pnp)
		=> _pnp = pnp;

	public async Task Create()
	{
		if (!_initialized) await Initialize().ConfigureAwait(false);

		// ...
	}

	public void Dispose()
	{
		Dispose(true);
		GC.SuppressFinalize(this);
	}

	private async Task Initialize()
	{
		if (_initialized) return;

		await _pnp.Web.GetAsync(w => w.ServerRelativeUrl).ConfigureAwait(false);
		await EnsureDivisions().ConfigureAwait(false);

		// ...

		_initialized = true;
	}

	private async Task EnsureDivisions()
	{
		var existingMap = await RetrieveListMap("Divisions").ConfigureAwait(false);
		// ...
	}

	private async Task<Dictionary<string, int>> RetrieveListMap(string listTitle)
	{
		var list = _pnp.Web.Lists.GetByTitle(listTitle, p => p.Fields.QueryProperties(
			p => p.InternalName,
			p => p.FieldTypeKind,
			p => p.TypeAsString,
			p => p.Title
		));

		var result = new Dictionary<string, int>();
		await foreach (var item in list.Items.QueryProperties(i => i.Id, i => i.Title).AsAsyncEnumerable())
		{
			result[item.Title] = item.Id;
		}

		return result;
	}

	private void Dispose(bool disposing)
	{
		if (!disposing) return;

		_pnp.Dispose();
	}
}
```

## Expected behavior

Iterating the existing items only once via Graph or REST next link (?%24skiptoken=Paged...)

## Environment details

- **SDK version**: 1.5 via PnP.Core.Auth 1.5.0
- **OS**: Windows 10
- **SDK used in**: Class library inside Console App
- **Framework**: Class library: Standard 2.0; Console App: .Net Framework 4.8 because it reads OnPremise Data via SharePointPnPCoreOnline 3.28.2012 ... which will be added to SPO by the class library
- **Browser(s)**: -
- **Tooling**: Visual Studio 2022

**Comment by trueleader** [comment]
Maybe it is only somewhat "counterintuitive":

There is the posibility to use QueryProperties on Items. Documentation-Details explains the usage: https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#b-getting-list-items-via-paging-no-item-limit

But on the start of the page is a summary for CAML usage: https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#you-need-to-read-system-properties-like-fileleafref-filedirref-or-you-need-to-filter-list-items-or-you-want-to-define-the-returned-fields

> You need to read 'system properties' like FileLeafRef, FileDirRef or you need to filter list items **or you want to define the returned fields**

No problem occures if I use the CAML variant. Maybe the field-selector is the problem?

**Comment by jansenbe** [comment]
@trueleader : I've built a test case for this and I can reproduce the issue you're seeing. Will work on a fix. Thanks for reporting this.

**Comment by jansenbe** [comment]
@trueleader : this failure is a regression from the work done to move to odata=nometadata which resulted in the returned next page link not being picked up. A fix will be committed shortly

**Comment by jansenbe** [comment]
@trueleader : please test again with the next nightly version (1.5.17)

**Comment by trueleader** [comment]
Thank you. I´m actually in vacation. Testing next week

**Comment by trueleader** [comment]
@jansenbe I could successfull test your fix :)
