### ISSUE TITLE
// Or clear the taxonomy field addedItem["MyField"] = null; and  as IFieldUserValue).Principal = principal do not work

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpcore#704]
## Category

- [x] Bug
## Describe the bug
Following the documentation in https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#taxonomy-fields

I used `listItem["DocumentType"] = null` to clear the taxonomy field DocumentType  
It does not error but it leaves the existing value un changed after ` await listItem.UpdateAsync();.` 

Then I tried the following: 
```
(listItem["DocumentType"] as IFieldTaxonomyValue).TermId = new Guid("729779b3-b4f1-40d1-8139-8f5e8f6cc61e");
(listItem["DocumentType"] as IFieldTaxonomyValue).Label = null;
```
and it did not work.

I also try to update a person field like so:
```
var principal = await web.EnsureUserAsync(DocNumItems[0].RequestForEmail);
```
then in the loop
```
IListItem listItem = DPCDocumentsList.Items.GetById((int)item.IdInProject);
 (listItem["Requester"] as IFieldUserValue).Principal = principal;

await listItem.UpdateAsync();
```
Again, no error but no update.

>
## Expected behavior
"DocumentType" field should have no value and "Requester" should have an "ensured" person
## Environment details development 
your issue... save the time and provide it in your initial submission*).

- **SDK version**: 1.5.0
- **OS**:  Windows 10  
- **SDK used in**: Azure Function
- **Framework**:  .NET 6
- **Browser(s)**: Chromium Edge 
- **Tooling**: Visual Studio 2022

### Additional context
before using PnP Core I was able to clear taxonomy fields with HttpClient like so:
```
string valuesJson = "{'DocumentType':{null} }";
var valuesContent = new StringContent(valuesJson, Encoding.UTF8, "application/json");
string valuesUri = $"https://{Util.GetEnvironmentVariable("AADDomain")}/Teams/{projectNumber}/_api/web/lists/getbytitle('DPC Documents')/items({IdInProject})";
                using (HttpResponseMessage patchResponse = await httpClient.PatchAsync(valuesUri, valuesContent))
                {
                    patchResponse.EnsureSuccessStatusCode();
                    _log.LogInformation($"Patch  results: {patchResponse.StatusCode}");
                }
```
I would rather use PnP Core

Thanks for Great libaray

**Comment by jansenbe** [comment]
Hi @Ofer-Gal ,

I just tried to reproduce the issue you're seeing but I could not. In my test I've a list with a managed metadata field, populated with a list item that has the managed metadata field set. I then load the list item, clear the managed metadata field and update the item:

```csharp
var list = await context.Web.Lists.GetByTitleAsync("FieldTypes", p => p.Items);

var firstItem = list.Items.AsRequested().First();

firstItem["MMSingle"] = null;

await firstItem.UpdateAsync();
```

Can try above simple code from your end and see if that works?

**Comment by Ofer-Gal** [comment]
My target is a file library in various sites. I found out that when the library does not contain too many files, the code works as expected.
When the code needs to update a library containing more then 3800 files and the taxonomy field is required, the code fails with no error and the other normal fields do not update.

I think I can make this field not required to eliminate the issue.
Thank you for the help
