### ISSUE TITLE
Batching APIRequest seems broken

### ISSUE THREAD

**Issue by czullu** [pnp/pnpcore#722]
## Category

- [x] Bug

## Describe the bug
While the Request for test1 still returns a result, the request for test2 returns null and shows a type initialization error.
However - when check loadPlansBatch.Requests[0].ResponseJson i can see the loaded Json-Data, so the call was fine and we got Data successfully.

```
using (var context = await pnpContextFactory.CreateAsync(new Uri("https://xyz.sharepoint.com/sites/TestGroupSiteWithPlanner")))
{
                 await context.Site.LoadAsync(s => s.GroupId);
                    Guid groupId = context.Site.GroupId;

                    var test1=context.Group.ExecuteRequest(new ApiRequest(ApiRequestType.Graph, $"groups/{groupId}/planner/plans"));

                    var loadPlansBatch = context.NewBatch();
                    var plannerResponse = context.Group.ExecuteRequestBatch(loadPlansBatch, new ApiRequest(ApiRequestType.Graph, $"groups/{groupId}/planner/plans"));
                    var Errors = await context.ExecuteAsync(loadPlansBatch, false);
                    if(!Errors.Any()&& plannerResponse.IsAvailable && plannerResponse.Result.Value!=null)
                    {
                        string test2 = plannerResponse.Result.Value;
                    }
}
```

## Steps to reproduce
Use a User Context against GroupSite with Planner and the call should return the assoicated Plans. While it does for single call, it does not for batch even when Data is actually visible in Batch-Object.

## Expected behavior
in earlier Version loading this data by Batch did work without an issue - would be nice it would do it again.

## Environment details (*development & target environment*)
DEV Version from today
Commit: a9320ab0ea5fab1b9103a84b9c86765ddfee6e9a [a9320ab]
Parents: cfb46c7de6, 41b2475123
Author: Bert Jansen <jansenbe@users.noreply.github.com>
Date: Friday, 14 January 2022 09:27:38

**Comment by czullu** [comment]
@jansenbe That's how the object looks in Debugger 
![image](https://user-images.githubusercontent.com/31336529/149599895-b1bb17d4-f893-46bb-82bc-06a6f18fdc6a.png)
while i can see that ExecuteRequestBatchAsync ->RawResultsHandler get called and get's the json response i somewhat fail to see when BatchSingleResult -> result should be set. in Breakpoint BatchSingleResult.Result in object BatchRequest i still see the return value but in code we would return result..

**Comment by jansenbe** [comment]
@czullu : I'll have a look, with 1.5 we did several changes to lower network traffic and one of the changes is that for a single request batch we now do an interactive request with compression enabled, this might be a regression of that.

**Comment by czullu** [comment]
@jansenbe Thank you - that's a good lead and indeed, when i add multiple requests like this:
```
                    var loadPlansBatch = context.NewBatch();
                    var GroupResponse = context.Group.ExecuteRequestBatch(loadPlansBatch, new ApiRequest(ApiRequestType.Graph, $"groups/{groupId}"));
                    var GroupDriveResponse = context.Group.ExecuteRequestBatch(loadPlansBatch, new ApiRequest(ApiRequestType.Graph, $"groups/{groupId}/drive"));
                    var plannerResponse = context.Group.ExecuteRequestBatch(loadPlansBatch, new ApiRequest(ApiRequestType.Graph, $"groups/{groupId}/planner/plans"));
                    var Errors = await context.ExecuteAsync(loadPlansBatch, false);
                    if(!Errors.Any()&& plannerResponse.IsAvailable && plannerResponse.Result.Value!=null)
                    {
                        string groupInfo = GroupResponse.Result.Value;
                        string groupDrive = GroupDriveResponse.Result.Value;
                        string planner = plannerResponse.Result.Value;
                    }
```
then i get a response on each

**Comment by czullu** [comment]
When i replace ExecuteMicrosoftGraphInteractiveAsync with ExecuteMicrosoftGraphBatchRequestAsync in line 481 on BatchClient then i get results again.

**Comment by czullu** [comment]
@jansenbe  there are 2 an other issue with ExecuteMicrosoftGraphInteractiveAsync as well - post seems not to work - for example when try to create a group. Secound issue: var Errors = await context.ExecuteAsync(loadPlansBatch, false); - the false is not respected - if i get a 403 - then it will throw the error and not add to the collection.
The Post issue i did adress in the Pull-request with a fallback, the throwing of the error i still not found where i need to fix this.

**Comment by czullu** [comment]
post error with ExecuteMicrosoftGraphInteractiveAsync has been some kind of Hiccup - i removed the fallback to ExecuteMicrosoftGraphBatchRequestAsync  and could completed all test on my end.

**Comment by jansenbe** [comment]
@czullu : I've reproduced the issue and will fix this using a different approach then your PR. I actually did fix a similar issue for a single REST request batch, but as I added interactive Graph later on I forgot to add that fix. Update will be in soon.

**Comment by jansenbe** [comment]
@czullu : fix has been committed.
