### ISSUE TITLE
Load SiteUsers fails with Error on AadObjectId

### ISSUE THREAD

**Issue by czullu** [pnp/pnpcore#729]
## Category

- [x] Bug

## Describe the bug
the line: await foreach (var user in pnpCoreSiteContext.Web.SiteUsers.AsAsyncEnumerable())
will fail with error "Property AadObjectId was not yet loaded" on MoveNext as soon as we hit a user not from AAD i.e. a system user.

   at PnP.Core.Model.TransientObject.GetValue[T](String propertyName)
   at PnP.Core.Model.Security.SharePointUser.get_AadObjectId()

The Error remains the same if i do a more explicit request
await foreach (var user in pnpCoreSiteContext.Web.SiteUsers.QueryProperties(u => u.Id, u => u.LoginName, u => u.PrincipalType, u => u.AadObjectId).AsAsyncEnumerable())

## Expected behavior
in absence of the attribute in the request response it should return null for AadObjectId.  

## Environment details (*development & target environment*)
dev branch

i will provide a fix for PnP.Core.Model.TransientObject.GetValue[T](String propertyName) by adding param bool allowedToBeAbsent=false and change that on true for get_AadObjectId

**Comment by jansenbe** [comment]
@czullu : I'll have a look later today / tomorrow. Thanks for bringing this up.

**Comment by czullu** [comment]
Hi Bert, do you Run apponly and get system\User in the results?
I can provide full example later today.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jansenbe** [comment]
@czullu : I did not try via app-only yet, something I'll give a try later today as well

**Comment by czullu** [comment]
failing users are "c:0(.s|true", "c:0-.f|rolemanager|spo-grid-all-users/....", "i:0#.w|nt service\spsearch", "i:0i.t|00000003-0000-0ff1-ce00-000000000000|app@sharepoint",  "SHAREPOINT\system". 

i'm getting them app-only from a GROUP#0 site on my MsDev-Tenant with options.PnPContext.GraphFirst = true;
rest of options are default, changing options.PnPContext.GraphFirst = false does not change behavior as expected.

with code 
```
await foreach (var user in context.Web.SiteUsers.QueryProperties(u => u.Id, u => u.LoginName, u => u.PrincipalType, u => u.AadObjectId).AsAsyncEnumerable())
{
    string aadObj = user.AadObjectId != null ? user.AadObjectId : "";
    Console.WriteLine($"{aadObj}/{user.LoginName}");
}
```

**Comment by jansenbe** [comment]
Hi @czullu ,

Think there are two things at play here: 
1. `user.AadObjectId != null` is not a valid check, you should write this as `user.IsPropertyAvailable(p=>p.AadObjectId)`
2. Think there is an issue resulting in AadObjectId never being populated as the field is named `UserId` in the response json and not `AadObjectId`

I'll fix the latter, the first one you should update in your code :-)

**Comment by jansenbe** [comment]
Also closing this issue, but please re-open or contact me in case you still have issues. Thanks for using PnP Core SDK and being vigilant about it's possible quirks 👍

**Comment by czullu** [comment]
Hi @jansenbe, better late the never ;-) - thank you for the 2 hint's - odata=nometadata and IsPropertyAvailable.
