### ISSUE TITLE
Error in Demo.Blazor\README.md line 19: instruction to configure Web platform

### ISSUE THREAD

**Issue by TimDol64** [pnp/pnpcore#735]
Following the README instructions, I added a redirect URL for 'Web' platform.
This resulted in an empty error description when I ran the app:
‘There was an error logging you in: ‘’’

With the help of this video [(https://www.youtube.com/watch?v=FxBJtemCbV0&ab_channel=CodingFlamingo)]
I updated Authentication.razor (see attachment) and was able to get more info on the error.

After configuring the URL for the Single Page Application platform I was able to run the program.
[Authentication.razor.txt](https://github.com/pnp/pnpcore/files/7959859/Authentication.razor.txt)
.

**Comment by jansenbe** [comment]
Thanks for sharing this @TimDol64 , I've updated the sample to use this.
