### ISSUE TITLE
CORS error when enumerating IWeb.Folders

### ISSUE THREAD

**Issue by TimDol64** [pnp/pnpcore#749]
## Category

- [x] Bug

## Describe the bug

When trying to iterate over the IWeb.Folders, a CORS exception is raised:

Access to fetch at 'https://&lt;tenant&gt;/sites/DevSite/_vti_bin/client.svc' from origin 'https://localhost: &lt;port&gt;' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

## Steps to reproduce

In Demo.Blazor, in the SiteInfo.razor component, try to iterate the folders for the web object.

1. Open Demo.Blazor/Pages/SiteInfo.razor
1. Append the following code after `<h1>@web.Title</h1>`
`@foreach (IFolder fld in web.Folders)`
`    {`
`        <p>Folder : @fld.UniqueId.ToString()</p>`
`    }`
1. Run the project and navigate to SiteInfo
1. See error

## Expected behavior

List the GUIDs of Folders in the web.

## Environment details (*development & target environment*)

- **SDK version**: 1.5.48-nightly
- **OS**: Windows 10
- **SDK used in**: Blazor WebAssembly
- **Framework**: .NET 6.0
- **Browser(s)**: Chromium Edge v97.0.1072.76
- **Tooling**: Visual Studio 2022
- **Additional details**: Earlier this week, @jansenbe solved https://github.com/pnp/pnpcore/issues/736 , which was also a CORS issue. This makes we wonder, how wide spread CORS issues will be in Blazor.

### Additional context

The minimum I would like to be able to do from Blazor is:
1. Download a file (now possible thanks to the recent fix)
2. Get a reference to a document library, based on either the url or ListId that I have available. Currently an issue because I get a CORS error when I try to `siteAssetsFolder = await ctx.Web.Folders.Where(f => f.UniqueId == new Guid(folderGuid)).FirstOrDefaultAsync();`
3. Save a file in that document library

**Comment by jansenbe** [comment]
@TimDol64 : I think the cors error you see is not related here, when we load we try to find the tenant id for telemetry purposes and that part fails in Blazor. I created an issue to track that (#746), but this error is not blocking any functionality.

To get the site folder you can also use `await ctx.Web.GetFolderByIdAsync(folderGuid)` as easier approach, might be that in your approach the `new Guid()` part is causing issues for our LINQ parser...try creating the GUID outside and use the variable inside the LINQ expression

**Comment by jansenbe** [comment]
@TimDol64 : the CORS error that you saw (due to #746) is fixed in the current nightly build, that however is not the reason for you r issue as mentioned in my previous reply.

**Comment by TimDol64** [comment]
Thanks. I can confirm that I can read the template, generate the document, and save it to the document library.
There is still some work to do, but at least I am convinced that it is technically possible to do what I aimed for.
Thanks again for the great and fast support. 

I hope to extend my work from Winforms Word/PowerPoint/Pdf to Blazor/SharePoint this year.
