### ISSUE TITLE
Upating FileLeafRef with SystemUpdateAsync overwrites Editor and Modified properties

### ISSUE THREAD

**Issue by TanguyPa** [pnp/pnpcore#750]
## Category

- [x] Bug

## Describe the bug
When I try to rename a document set (content type) with the property FileLeafRef, the Editor and Modified properties are overwritten.
I don't know if this is a normal behavior, I thought that by using the SystemUpdateAsync method the properties would not be overwritten.

I think the behavior is similar for a folder since a document set acts similarly to a folder, but I haven't tested it

## Steps to reproduce
I get the items this way (filter to differentiate between doc sets and files)
```csharp
string viewXml = @"<View Scope='RecursiveAll'>
										<ViewFields>
										  <FieldRef Name='FileLeafRef' />                                           
										  <FieldRef Name='FileDirRef' />                                           
										  <FieldRef Name='FileRef' />            
										  <FieldRef Name='Title' />
										</ViewFields>                                              
									   </View>";
// Execute the query
var output = await list.LoadListDataAsStreamAsync(new PnP.Core.Model.SharePoint.RenderListDataOptions()
{
	ViewXml = viewXml,
	RenderOptions = RenderListDataOptionsFlags.ListData
});
foreach (var item in list.Items.AsRequested())
{
	if ((string)item["ContentTypeId"] == "xxxx")
	{
		ensemblesDocsItems.Add(item);
	}
	else if ((string)item["ContentTypeId"] == "xxxx")
	{
		docsItems.Add(item);
	}

}
```

```csharp 
foreach (var ensItem in ensemblesDocsItems)
{                       
        var newDocSetName = "...";
	if ((string)ensItem["FileLeafRef"] != newDocSetName || (string)ensItem["Title"] != newDocSetName)
	{
		if ((string)ensItem["FileLeafRef"] != newDocSetName)
		{
			ensItem["FileLeafRef"] = newDocSetName;
		}
		if ((string)ensItem["Title"] != newDocSetName)
		{
			ensItem["Title"] = newDocSetName;
		}
		await ensItem.SystemUpdateAsync();                               

	}}
```

## Expected behavior

Change the property (so rename the document set) without overwriting the Editor and Modified properties

## Environment details (*development & target environment*)

- **SDK version**: 1.5.0 (try 1.4.0 too)
- **OS**:  Windows 10
- **SDK used in**:  Console App
- **Framework**:  .NET 5.0
- **Tooling**:  Visual Studio 2019

**Comment by jansenbe** [comment]
@TanguyPa : you can't overwrite `FileLeafRef`, that's an internal field in SharePoint. Try only setting the `Title` field. When it comes to preventing the Editor/Modified/Author/Created properties from changing you need to explicitly set the values you need and use `UpdateOverwriteVersionAsync`, see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-the-list-item-author-editor-created-and-modified-system-properties for more context and an example.

**Comment by TanguyPa** [comment]
@jansenbe Thanks for your answer, I didn't know there was a difference between internal fields and custom fields added.
Is there a way to rename a folder (or move it) without changing the Editor/Modified/Author/Created properties.
I am looking for a way to rename them with a name that respects a rule so that they can be more easily found in sharepoint as well as via synchronization in the explorer mode of windows..

**Comment by jansenbe** [comment]
@TanguyPa : if you first read the current Editor/Modified/Author/Created and use them in the approach I've outlined to update the Title field then that should work.

There's also an `MoveToAsync` method on an `IFolder`, you can give that try. Not sure if will leave Editor/Modified/Author/Created unchanged, doing a quick test should verify that

**Comment by jansenbe** [comment]
@TanguyPa : did you manage to get above problem fixed?

**Comment by jansenbe** [comment]
@TanguyPa : are you good with closing this issue?

**Comment by TanguyPa** [comment]
Yes, I tried to change the "Title" property, but it does not rename the document set. You also have to change the "FileLeafRef" property for it to take effect (which overwrites the Editor/Modified/Author/Created properties).

The MoveToAsync method does move the document set but also overwrites the Editor/Modified/Author/Created properties).

**Comment by TanguyPa** [comment]
I followed your answer above and it works. I update the FileLeafRef and Title attribute with a systemupdate. Then I retrieve the updated item to update its Created/Modified/Author/Editor attributes retrieved before the first change.
```csharp
ensItem["FileLeafRef"] = customName;
ensItem["Title"] = customName;
await ensItem.SystemUpdateAsync();
var ensToUpdate = list.Items.GetById(ensItem.Id);
ensToUpdate["Created"] = created;
ensToUpdate["Modified"] = modified;
ensToUpdate["Author"] = author;
ensToUpdate["Editor"] = editor;
await ensToUpdate.UpdateOverwriteVersionAsync();
```
