### ISSUE TITLE
raise events/notification when 429 throttling responses are returned

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpcore#756]
## Category

- [x] Feature request

## Describe the feature

Currently when you get 429 throttling responses, you don't know this in the code. Users of you app are wondering why things go slow. 

## Describe the solution you'd like
We should raise some events and/or some notification that you can catch to notify or log 429 throttling responses. When you detect a a threshold problem you can slow down the number of calls (for example by lowering the number of threads that access the tenant)

**Comment by jansenbe** [comment]
@mdissel : I've just committed a first lightweight event system, will be part of the nightly build that you can use as of tomorrow. To use it do the following:

1. Get an EventHub instance via dependency injection (so similarly as you're getting an IPnPContextFactory instance). Below is a sample:
```csharp
public ScanManager(IHostApplicationLifetime hostApplicationLifetime, StorageManager storageManager, SiteEnumerationManager siteEnumerationManager, 
                           IDataProtectionProvider provider, IPnPContextFactory pnpContextFactory, EventHub eventHubInstance)
{

}
```

2. On the EventHub instance implement the `RequestRetry` event handler. This one will fire whenever there's a request throttled.

```csharp
eventHub.RequestRetry = (retryEvent) => 
{  
  // request got retried due to throttling or socket exception...    
};
```

I'll add docs next week, please give this a try and let me know if things work as expected for you.

**Comment by jansenbe** [comment]
@mdissel : did you manage to try this?

**Comment by mdissel** [comment]
Sorry, not yet! Don't expect an answer from me on short terms due to other priorities. Did you see my comments on your changes ? https://github.com/pnp/pnpcore/commit/c847bb1b0ac95795b84011a909899b6819740dea#comments

**Comment by jansenbe** [comment]
@mdissel : didn't see that, thanks for pointing out. The exception will always be a socket exception, but yes makes sense to add that. I'm also adding a concept where you can "tag" a `PnPContext` with an object (e.g. scanner run id) and I'll add those to the event message. This way you can better understand what part of your application is throttled. Adding the planned wait is also needed, will add that. Thanks for the feedback.

**Comment by mdissel** [comment]
Maybe also do something with the returned header _X-ClientErrorCode_ ? In my case I get the value _Quota_. I don't know what other values are possible. It seems that _X-SharePointHealthScore_ is not returned when 429 request is returned.

**Comment by jansenbe** [comment]
@mdissel : would it be possible to add some of the throttling responses you're getting here? Definitely in for adding more "context" but need to verify scenarios as the event will fire for REST/Graph/CSOM requests and they do not all return identical throttling related data

**Comment by jansenbe** [comment]
@mdissel : here are some docs for the new feature:

- Using custom properties on PnPContext: https://pnp.github.io/pnpcore/using-the-sdk/basics-context.html
- Using the EventHub: https://pnp.github.io/pnpcore/using-the-sdk/basics-eventhub.html

**Comment by mdissel** [comment]
Here's a sample header collection from a 429 response.. Not much difference between the requests. This really kills our performance by the way. Retry-After is 55 seconds!!! this request takes 3 seconds when there's no 429 response :(
 
![image](https://user-images.githubusercontent.com/126084/154072641-1f76eb7a-4029-4051-9e8b-a7dbbe5a7ed8.png)

```
POST https://XXX.sharepoint.com/sites/123_003/_api/web/getFolderById('1e6ce5df-bf55-44ea-b075-1b4fe48818eb')/files/addusingpath(decodedUrl='XXX.csv',overwrite=false) HTTP/1.1
Host: XXX.sharepoint.com
If-Match: *
Authorization: XXXXX
Accept: application/json; odata=nometadata
Accept-Encoding: gzip, deflate, br
User-Agent: NONISV|SharePointPnP|PnPCoreSDK/1.5.54.0
X-ClientService-ClientTag: PnPSDK:1.5
Content-Length: 8218477

HTTP/1.1 429
Cache-Control: private
Content-Type: text/plain; charset=utf-8
Retry-After: 55
Server: Microsoft-IIS/10.0
SPRequestGuid: a8ad1fa0-c021-3000-a0c2-8bc3c9b96e78
request-id: a8ad1fa0-c021-3000-a0c2-8bc3c9b96e78
MS-CV: oB+tqCHAADCgwovDyblueA.0
Strict-Transport-Security: max-age=31536000
X-ClientErrorCode: Quota
SPRequestDuration: 57
SPIisLatency: 0
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.22126
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date: Fri, 11 Feb 2022 12:06:41 GMT
Content-Length: 21
```

**Comment by jansenbe** [comment]
Are you doing a bulk document creation? Maybe the migration APIs make sense to use then (see https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview). You might also want to limit the amount of parallel file creations, it will slow things down a bit, but if you can prevent throttling and as such also the long waits, then the net result might be faster.

**Comment by mdissel** [comment]
> Are you doing a bulk document creation?

Yes, we already use the migration API for the initial migration, but for the delta (migrated files are updated/newer versions added during the migration period (sometimes takes weeks)) you can't use the migration API, so we have to use the API...

**Comment by mdissel** [comment]
> You might also want to limit the amount of parallel file creations, it will slow things down a bit, but if you can prevent throttling and as such also the long waits, then the net result might be faster.

Maybe, in the screenshot we had the UseRetryAfterHeader = false but as you can see this makes things much worse, but respecting the wait time dramatically increased the overall time.. (this was a 10-thread single AppID upload mechanism used as a sample for Microsoft Support team to give us some feedback from internal sharepoint logs) (currently testing if multiple AppIDs makes a difference).

**Comment by jansenbe** [comment]
@mdissel : I'm gonna close this issue as the original ask has been implemented. I'm internally following up with folks to see if we expose more throttling information and if so will implement it in PnP Core SDK.
