### ISSUE TITLE
Text editor webpart Images are disappearing after site page edit

### ISSUE THREAD

**Issue by sanjaigandhig** [pnp/pnpcore#759]
Hi Team,
We are working on one of the migration project, where we are migrating contents from classic ASP (Static Content) into SharePoint Online. We are parsing the ASP static content and sanitizing it to have only HTML tags and injecting that using the PnP framework into SharePoint online. This approach was working until few weeks back but started breaking now due to the new patch on the SharePoint online tenant has introduced new image webpart with in Text editor webpart. Now, our migrated pages are looks fine during view, but the movement user edit the page (even without saving just edit) and when saving the site page, the image tag are ripped of by SharePoint online and we have to manually insert it using the image component which was newly introduced.

Could you guys help us in this to see what is causing the images are getting disappearing and what we need to do when migrating so that images are not removed by SharePoint Online.

This is causing major issue in our migration which includes thousands of pages getting affected.

Thanks,
Sanjai.

**Comment by jansenbe** [comment]
@sanjaigandhig / @virendramunot : The latest version of our open source pages API does support inline images like one would create manually on a modern page. An inline image is represented by a specific HTML blob inside the text you put in a text part and we've a method to generate that HTML blob. This is documented over here: https://pnp.github.io/pnpcore/using-the-sdk/pages-webparts.html#using-inline-images-in-text-parts.

Using this approach should get you unblocked for the future pages, for the existing pages the only solution I see is writing code that iterates over them and where needed replaces basic image tags with "compliant" ones as created via the PnP Page API. 

I fully understand your frustration around the support situation, in the ideal world there would be an official pages API and official documentation explaining the HTML model that one can use inside a text editor part. We (MSFT) are working on improving the situation, but in the short term I can only offer to help get you unblocked and help with implementing a fix that will update the already created pages.

Hope this already helps, happy to further work with you all to fix this.

**Comment by sanjaigandhig** [comment]
Thanks @jansenbe for your immediate response in this case. We will take back your input and try the option provided in the document url you have provided to see if it helps in our current migration issue. We need the urgent solution for the current migration issue only which is newly creating pages through pnp module.
I will keep you posed on this further on the tryout.

**Comment by jansenbe** [comment]
@sanjaigandhig : wanted to check-in and see how things are going...so far things work?

**Comment by sanjaigandhig** [comment]
@jansenbe , thanks for the support and suggestions. This approach is little different than what we use, we are using OfficeDevPnP core where as we need to use PnPCore SDK, hence it took for us some time to check the solution works for our situation or not. We able to make it working fine based on the suggested approach. Thanks a lot for your help. We will continue to update the code to make it working for entire requirement and scenario's and confirm the output. For now we seems to be good to go with current issue. I will close this issue by next week after our further testing.

**Comment by jansenbe** [comment]
@sanjaigandhig  / @virendramunot : I think we can close this one, if not then please let me know and re-open again.
