### ISSUE TITLE
Pages with text web part not update the previw text in the News web part

### ISSUE THREAD

**Issue by greenfox75** [pnp/pnpcore#765]
## Category

- [x] Bug

## Describe the bug
I added the news web part in my site home page for show my custom page created by code.
After created my custom page where I have added text web part with text.
I updated the text in the text web part.
The preview of the text in the News web part not updated the text.

## Steps to reproduce
Add in home page a News web part. Setting the news web part with layout 'side by side'.
Create by code custom news with web part text and custom text and publish.
After check the news web part and remember the text of the web part in the preview text.
Update the text in the news web part and republish the news.
Return on the home page and check the preview. The text preview in the news web part not updated.

## Expected behavior
That when The user update the text in web part created by code the preview in the web part News update the text.

## Environment details (*development & target environment*)

SDK version: [1.5.0]
OS: [e.g. Windows 10]
SDK used in: [Console application]
Framework: [NET Framework 4.8 ]
Browser(s): [Goggle Crome]
Tooling: [ Visual Studio 2019]
Additional details: Check next section details.

### Additional context
SharePoint online

**Comment by jansenbe** [comment]
See also #790

**Comment by jansenbe** [comment]
@greenfox75 : I've just committed a fix for this. Now the behavior aligns with what you would get for a manually created page. When a page is created the library sets a default description, but leaves it marked as "default"...when a user then edits the page the description is overwritten depending on the user's edits and this should also reflect in roll up web parts (search/caching might delay this a bit). 

Note, when programmatically updating a page we're not overwriting the existing description if any was set. We do respect the default description flag if it was set before, so a page that was given a custom description via the UI will stay in that mode on page edit.

For now we do not offer an option to change a custom description, if you feel that's needed then let me know.

Note that I'm also closing this case for now, please try with the next nightly (or 1.6 which we hope to release soon) and if you still see issues then please re-open or create a new issue.
