### ISSUE TITLE
Items requested with LoadListDataAsStreamAsync or LoadItemsByCamlQueryAsync misses field values though sent on viewxml for Discussion list type

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#774]
## Category

- There are around 75 fields under list (Discussion type) properties. However when I send the list of internal name of all the fields under viewxml for making query. It returns the items, but just with 8 fields values.
- I had posted the same type of issue previously #590, It was working like a charm, but seems some thing is missing again.

## Steps to reproduce
``
//listId is guid for discussion type of list
                 var parentList = context.Web.Lists.GetById(listId, l => l.EnableModeration, l => l.TemplateType, l => l.EnableVersioning, l => l.Title, l => l.Fields, l => l.ContentTypes);
               //eg. misses "_UIVersionString" field
                var parentFields = parentList.Fields.AsRequested();
                string nextPage = null;
                string viewXml = "<View><RowLimit Paged='TRUE'>1000</RowLimit><Query><Where><Eq><FieldRef Name='FSObjType'/><Value Type='int'>1</Value></Eq></Where></Query></View>"
                do
                {
                    var loadOption = new RenderListDataOptions()
                    {
                        ViewXml = viewXml,
                        RenderOptions = RenderListDataOptionsFlags.ListData,
                        Paging = nextPage ?? null,
                        DatesInUtc = true,
                        FolderServerRelativeUrl = folderRelativeUrl
                    };
                    var output = parentList.LoadListDataAsStreamAsync(loadOption).Result;
                    if (output.ContainsKey("NextHref"))
                    {
                        nextPage = output["NextHref"].ToString().Substring(1);
                    }
                    else
                    {
                        nextPage = null;
                    }
                }
                while (!string.IsNullOrEmpty(nextPage));
               //every item have "IsRootPost" field
               var items = parentList.Items.AsRequested();
``
## Expected behavior

Fields mentioned on ViewXml must have been retrieved
## Environment details (*development & target environment*)

- **SDK version**: [1.5 ] [1.3]
- **OS**: [Windows 10]
- **SDK used in**: [Console App]
- **Framework**: [.NET Framework v4.7.2]
- **Tooling**: [Visual Studio 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by gopaldahal** [comment]
Seems I forget to define the Scope of Query on viewxml.
As I was applying filter based on ID of list items and my item is inside deep hierarchy.
It was must to define the scope of query to "RecursiveAll" while making query inside the library( if FolderServerRelativeUrl not defined).

**Comment by jansenbe** [comment]
Thanks for reporting back @gopaldahal !
