### ISSUE TITLE
Making content type the default for a list

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpcore#775]
I am converting a project on .Net 4.7 that used the old SharePointPnPCoreOnline nuget package to a new .Net Core 6 project using the Pnp.Core and PnP.Framework packages and have come up with an issue converting a piece of functionality

When adding an exisiting content type to a list we were able to make the content type the default one for the list with the 2nd property on the following
`	spList.AddContentTypeToListByName("contentTypeName", true);`
In the new world I can add the content type, with the below but there seems to be no option to make it the default
`	await spList.ContentTypes.AddAvailableContentTypeAsync(siteCT.Id);`
	
Can anyone advise on how to perform this with the new packages?

**Comment by jansenbe** [comment]
@dgtheninja : we did not yet implement this, but it's a good one to implement. The PnP Framework method you're referring to shows how this is done: the first content type in the `uniqueContentTypeOrder` list (=property on IFolder) is the default one. I'm currently OOF and have limited time, but will be able to have a look at this next week.

**Comment by jansenbe** [comment]
@dgtheninja : started working on this.

**Comment by jansenbe** [comment]
@dgtheninja : support for changing the content type order has been added, the content type you set as first is also known as the "default" content type. Docs are updated as well, see https://pnp.github.io/pnpcore/using-the-sdk/contenttypes-intro.html#getting-and-setting-the-content-type-order-in-the-list-new-menu. 

Can you please give things a go and provide feedback. These updates will appear in the next nightly build (= version 1.5.85 or higher)

**Comment by dgtheninja** [comment]
@jansenbe, again thanks for the swift implemention it does exactly what I need.

One small point, shouldn't the return value from the GetContentTypeOrder methods and the parameter to the ReorderContentTypes methods be IEnumerable<string> rather than List<string>?

**Comment by jansenbe** [comment]
Think in this case returning a `List<>` is better here, see https://daedtech.com/what-to-return-ienumerable-or-ilist/. Thanks for the feedback @dgtheninja .
