### ISSUE TITLE
How do you set a default value for a Taxonomy Field

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpcore#776]
## Category

- [x] Bug

## Describe the bug

I'm trying to set the default value for a Taxonomy field but I am getting a Json exception about a cyclical reference

```
A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. 
Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.
Path: $.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Field.DefaultValue.Label.
```
## Steps to reproduce

```
var taxonomyFieldValue = field.NewFieldTaxonomyValue(myTermId, myTermLabel);
field.DefaultValue = taxonomyFieldValue;
await field.UpdateAsync();
```

## Expected behavior

Default value should be set on the field

## Environment details (*development & target environment*)

- **SDK version**: 1.5.0
- **OS**: Windows Server
- **SDK used in**: Azure Function App
- **Framework**: .Net Standard 2.0
- **Browser(s)**: n/a
- **Tooling**: Visual Studio 2022
- **Additional details**: 

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@dgtheninja : I'll have a look somewhere next week most likely, oof at the moment

**Comment by jansenbe** [comment]
@dgtheninja : I've added support for providing the default value when creating a taxonomy field. You just need to specify the ITerm that will be the default value (or ITerms in case of a multi value field). Docs will be updated, but in the meantime you can already check out the test case: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/WebFieldTests.cs#L644-L704

**Comment by jansenbe** [comment]
@dgtheninja : for updating the default value of an existing taxonomy field you can use below approach. With above option and this info I hope you're unblocked. These changes will be part of the next nightly release, so please give things a try tomorrow and report back.

```csharp
taxField.DefaultValue = $"-1;#{term2.Labels.First(p => p.IsDefault == true).Name}|{term2.Id}";
await taxField.UpdateAsync();
```

**Comment by jansenbe** [comment]
Here's the docs: https://pnp.github.io/pnpcore/using-the-sdk/fields-add.html#taxonomy

**Comment by dgtheninja** [comment]
@jansenbe, I have tried this is and it all looks good. Thanks very much for the quick turn around
