### ISSUE TITLE
Batching add/update fails when request is too large

### ISSUE THREAD

**Issue by Tinathnath** [pnp/pnpcore#777]
Issue type: Bug/question
Scope: SharePoint list
PnP Version: latest stable (1.5.0)

Hi PnP Team,
I might have an issue on list item adding / updating.

I try to add/update around 250 items using batch. I tried the default batch and a custom one using `var batch = context.NewBatch()`.

My items are quite large as they contain some note fields with html content (yeah, I know...). I'm getting this error from SharePoint: _The maximum number of bytes allowed to be read from the stream has been exceeded. After the last read operation, a total of 1063984 bytes has been read from the stream; however a maximum of 1048576 bytes is allowed._

Is this a bug as batching calculation (nbItems / 100) should also count request size, or I am doing something wrong ? I could not find in the docs how to limit the number of items in a batch, it could be a workaround to decrease request size. For the moment I create/update items one by one, it works but it is much much slower obviously.

Thanks !

**Comment by jansenbe** [comment]
@Tinathnath : ideally batching should take in account the request size, but for the moment we don't have that feature built in. I think it's best that you group your requests yourselves, for example make batches of 10 or 20 requests ensuring you don't hit the limit.

**Comment by Tinathnath** [comment]
@jansenbe Thanks, that's what I intented to do if there were no other solutions :)

**Comment by jansenbe** [comment]
Closing this issue for now as you're unblocked
