### ISSUE TITLE
Setting Taxonomy field to Allow Fill-in choices fails

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpcore#778]
## Category

- [x] Bug

## Describe the bug

I'm trying to set a taxonomy field to allow fill-in choices for an open term set, but it throws a **SharePointRestServiceException** with the following detail
```
HttpResponseCode: 400
Code: Microsoft.SharePoint.Client.InvalidClientQueryException
Message: The property 'Open' does not exist on type 'SP.Field'. Make sure to only use property names that are defined by the type.
```

Reading the Open property of the field correctly describes the state of the field, but setting the property fails.

## Steps to reproduce
```
    await ctx.Web.LoadAsync(w => w.Fields);

    var taxField = ctx.Web.Fields.AsRequested().Where(f => f.InternalName == "TestTaxField2").FirstOrDefault();

    taxField.Open = true;
    await taxField.UpdateAsync();
```

## Expected behavior

Call should succeed and the taxonomy field is updated to allow fill-in choices

## Environment details (*development & target environment*)

- **SDK version**: 1.5.0
- **OS**: Windows Server
- **SDK used in**: Functions App/Console App
- **Framework**: .NET 6/.NET Standard 2.0
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2022

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Hi @dgtheninja ,

I've added support for creating taxonomy fields as open. See this test case for details, docs will follow. https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/WebFieldTests.cs#L708-L751

**Comment by jansenbe** [comment]
@dgtheninja : updating the open status for an existing taxonomy field is not yet implemented, feels like that is a less common case and hoping that support for setting "open" on field creation is sufficient? Anyhow, these changes will be part of the next nightly so you can give things a try tomorrow and report back.

**Comment by jansenbe** [comment]
Here's the docs: https://pnp.github.io/pnpcore/using-the-sdk/fields-add.html#taxonomy

**Comment by dgtheninja** [comment]
@jansenbe, it covers our use case for the moment to only do this on field creation rather than update so very happy with this thanks. 

One small comment on the docs, you have the following line
`Setting a termset as open only is possible is the respective termset is created as open termset.`

should that be
`Setting a termset as open only is possible if the respective termset has an open submission policy.`
