### ISSUE TITLE
Extend the model to support SharePoint Files and Folders

### ISSUE THREAD

**Issue by ypcode** [pnp/pnpcore#78]
## Category

- [x] Domain model extension

## Describe the domain model extension

Create, Read, Update and Delete files and folders in SharePoint

### Model

Model: __File__, __Folder__
Properties: __List.RootFolder__, __List.Folders__, __Folder.Files__,  __Folder.Folders__

### APIs

API :
https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}/children
https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}
https://graph.microsoft.com/v1.0/sites/{site-id}/drive/root:/{item-path}
https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}/driveItem

### Additional Information

[Files Microsoft Graph Documentation](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)

**Comment by ypcode** [comment]
Hi guys, please assign this one to me :)

**Comment by ypcode** [comment]
Files IRM properties have to be properly tested with a tenant properly configured with IRM in place.

**Comment by jansenbe** [comment]
@ypcode : guess we're getting feature complete here and close this issue?

**Comment by ypcode** [comment]
Testing is still needed on IRM and user type fields are note implemented. 

But I guess we can close this one and create more specific ones for what's remaining ?
