### ISSUE TITLE
Page description not changing automatically after page creation (but normally it should).

### ISSUE THREAD

**Issue by grillaertr** [pnp/pnpcore#790]
Normally, when creating a new site page in SharePoint and adding a text webpart, the page description property changes depending on the displayed text (unless the page description property is changed manually, then the link between text in webparts and the page description is gone). But when I create a new site page using PnP Powershell or custom code (with or without adding a text webpart), the link between the text in webparts and the description property of the site page is gone. I guess this issue is because even tho there is no text on the site page, the site page description is still changed in the code ([Starting on line 1288](https://github.com/pnp/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs)).

**Comment by PieterHeemeryck** [comment]
We've been able to fix this by modifying the CanvasContent1 property of the page. It has to do with its contents. You can change it back such that the default description is being used again. Just be careful when updating its contents, as it is a lengthy string with lots of values.

**Comment by jansenbe** [comment]
@PieterHeemeryck : can you clarify what you've changed...will help speed up a fix for this :-)

**Comment by jansenbe** [comment]
@grillaertr , @PieterHeemeryck : I've just committed a fix for this. Now the behavior aligns with what you would get for a manually created page. When a page is created the library sets a default description, but leaves it marked as "default"...when a user then edits the page the description is overwritten depending on the user's edits and this should also reflect in roll up web parts (search/caching might delay this a bit). 

Note, when programmatically updating a page we're not overwriting the existing description if any was set. We do respect the default description flag if it was set before, so a page that was given a custom description via the UI will stay in that mode on page edit.

For now we do not offer an option to change a custom description, if you feel that's needed then let me know.

Note that I'm also closing this case for now, please try with the next nightly (or 1.6 which we hope to release soon) and if you still see issues then please re-open or create a new issue.
