### ISSUE TITLE
On-Premises Connection/Auth for Transformation Testing

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#796]
## Category

- [x] Feature request

## Describe the feature

Add capability to connect to on-premise servers for transformation. We currently lack (AFAIK) authentication mechanism for connect to on-premises sources for testing.  At the moment, all the authentication is currently designed for SharePoint Online or the Graph. 

## Describe the solution you'd like

So PnP Core SDK isn't intended to be used for on-premises connections only online. Except the transformation tech requires on-premises connections for the SP2013,16,19,SE versions for converting to online.

I am implementing the connection logic in the test class as a supporting mechanism - reusing much of the existing code in PnP.Framework, since this has the code to connect to the data sources.

### Why Am I doing this?

During initial testing of the new modernisation tech, all on-premises transformations fail when using via PnP PowerShell (latest nightly build) that uses the Invoke-PnPTransformation cmdlets. I want to be able to debug the tooling independently of using PnP.Framework and PnP Powershell.

**Comment by pkbullock** [comment]
Related to #799

**Comment by pkbullock** [comment]
Keeping this open as, discussion needed for the auth aspect.

**Comment by jansenbe** [comment]
Closing for now, will re-open if this effort will be picked up again
