### ISSUE TITLE
Global Tokens Issue

### ISSUE THREAD

**Issue by pkbullock** [pnp/pnpcore#806]
## Category

- [x] Bug

## Describe the bug

Error when running transformation with PnP PowerShell using Invoke-PnPTransformation

Message          : Object reference not set to an instance of an object.
Stacktrace       :    at PnP.Core.Transformation.SharePoint.MappingProviders.SharePointWebPartMappingProvider.PrepareGl
                   obalTokens(Dictionary`2 mappingProperties)
                      at PnP.Core.Transformation.SharePoint.MappingProviders.SharePointWebPartMappingProvider.MapWebPar
                   tAsync(WebPartMappingProviderInput input, CancellationToken token)
                      at PnP.Core.Transformation.SharePoint.MappingProviders.SharePointMappingProvider.MapAsync(Mapping
                   ProviderInput input, CancellationToken token)
                      at PnP.Core.Transformation.Services.Core.DefaultPageTransformator.TransformAsync(PageTransformati
                   onTask task, CancellationToken token)
                      at PnP.PowerShell.Commands.Transformation.InvokeTransformation.ExecuteCmdlet() in
                   D:\a\powershell\powershell\src\Commands\Transformation\InvokeTransformation.cs:line 320
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in
                   D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 26

## Steps to reproduce

Transform an on-premises page.

## Probably cause

In the old transformation we instantiate the Mapping Properties parameter, in the new one we don't so it is null, and lacks the appropriate check and instantiation.

**Comment by jansenbe** [comment]
Thanks for testing this @pkbullock ! I hope to get a bit more room in the coming weeks to also contribute to page transformation again, let's align when you feel fundamental changes are required.

**Comment by pkbullock** [comment]
One for Discussion when your available - is this is the best place, using the new cleaner model. The MappingProperties is required to be instantiated and "UseCommunityScriptEditor" to be present in the dictionary, otherwise a method ContentEmbedSelectorContentLink isnt recognised by the function processor, and treats the transformation for text web part as an Add-In.

**Comment by pkbullock** [comment]
@jansenbe - I'll mark those requiring input with Question, so when you are available we can discuss with team. For the fix, ill patch the problem pending a better approach.

**Comment by jansenbe** [comment]
Fix was merged, thx a ton @pkbullock . Closing this one, feel free to re-open or create a new one if needed.
