### ISSUE TITLE
Exception when creating context with UsernamePasswordAuthenticationProvider (MS-Trust)

### ISSUE THREAD

**Issue by vroesgen** [pnp/pnpcore#822]
## Category

- [x] Bug

Since last week I suddenly get an exception when creating context with UsernamePasswordAuthenticationProvider .
Everything was working since 6 months.

Exception message: 
**`There was an error parsing WS-Trust response from the endpoint. This may occur if there is an issue with your ADFS configuration`**

InnerException.Message:
**`Federated service at https://autologon.microsoftazuread-sso.com/biofrontera.com/winauth/trust/2005/usernamemixed?client-request-id=5ee9acfa-c7ff-4221-abf7-dc524c819bf2 returned error: Authentication Failure`** 

I found in this document [https://support.dotdigital.com/hc/en-gb/articles/4903754728594--April-2022-Microsoft-authentication-update](url) that WS-Trust protocol has been removed by Microsoft sind April 1, 2022

I strongly suspect that there are connections here.

- **SDK version**:  1.6.0
- **OS**: Windows 11
- **SDK**: Console App, Blazor Server
- **Framework**: .NET 6.0
- **Browser(s)**:  Chrome v100.0.4896.75 
- **Tooling**: Visual Studio 2022

**Comment by jansenbe** [comment]
Thanks for reporting this @vroesgen , we'll have a look.

**Comment by jansenbe** [comment]
Hi @vroesgen , our UsernamePasswordAuthenticationProvider still works fine when passing in a Azure AD user and password. The article you mention is related to WS-Trust which is something we're not using (we use OAuth). Could it be the case that you've setup ADFS for on-premises auth that somehow uses WS-Trust to federate with Azure AD? Can you reproduce this issue with an account that lives in Azure AD?

**Comment by jansenbe** [comment]
Closing per no additional feedback, if you feel this is still an SDK issue then please re-open this issue @vroesgen . Also would be good to then provide a Fiddler trace so we can understand more about the traffic flow.
