### ISSUE TITLE
Available web templates missing

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#833]
## Category

Didn't find the method for Listing of Web Available templates. Please guide. Equivalent operation on SOAP/CSOM is provided below

## Describe the feature
Equivalent method on SOAP

```
        public uint GetSiteTemplates(uint LCID, out Template[] TemplateList) {
            object[] results = this.Invoke("GetSiteTemplates", new object[] {
                        LCID});
            TemplateList = ((Template[])(results[1]));
            return ((uint)(results[0]));
        }
```

Equivalent code on CSOM
```

     WebTemplateCollection oWebtTemplateCollection = clientContext.Web.GetAvailableWebTemplates(1033, false);
            clientContext.Load(oWebtTemplateCollection);
            clientContext.ExecuteQuery();
            foreach (WebTemplate t in oWebtTemplateCollection)
            {
            }
```

**Comment by jansenbe** [comment]
@gopaldahal : we currently don't have that method implemented, but since this is possible via REST (see https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Web/func/GetAvailableWebTemplates) it's not that much work to add support for this. Adding to our backlog.

**Comment by jansenbe** [comment]
@gopaldahal : Thanks the work of @MathijsVerbeeck this missing functionality has already been built, thanks a ton @MathijsVerbeeck !!

See https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/WebTests.cs#L1651-L1727 for the test cases explaining how to use the added methods. This change will be part of the next nightly release, version 1.6.36 or higher.

Will close this issue now, but don't hesitate to re-open in case you still have issues
