### ISSUE TITLE
Document the Teams Calendar Support (PR #848)

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#851]
Document the new event support for a team/group. See https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/Teams/TeamEventTests.cs for the related test case

**Comment by MathijsVerbeeck** [comment]
@jansenbe I'll work on this, I'll combine this with replying to a teams channel message and mentioning a user, team, tag, ... in a teams channel message.

**Comment by jansenbe** [comment]
Thanks @MathijsVerbeeck !!
