### ISSUE TITLE
Getting the administrators of a site collection not working

### ISSUE THREAD

**Issue by andreanpo** [pnp/pnpcore#857]
## Category

- [x] Bug

## Describe the bug

Hi, I’m trying to retrieve all the admins of a list of sites. In this list there are sites where my user is not added, however, despite being a Global Administrator and a sharepoint Administrator, I can not recover the list of admin.
The first example does not work, is executed but remains waiting for an indefinite time without returning nothing (neither error and neither answer).
The second example is impossible to try because it gives me the following error: "ISharePointAdmin' does not contain a definition for 'GetSiteCollectionAdmins' and no accessible extension method 'GetSiteCollectionAdmins' accepting a first argument of type 'ISharePointAdmin' could be found (are you missing a directive or an assembly reference?)"
The NuGet packages installed in the solution are:
- PnP.Core.Admin
- Pnp.Core.Auth
- Pnp.Core

These are the permissions authorized on Azure AD:
![image](https://user-images.githubusercontent.com/106310670/170500544-fa583e32-6aba-43bc-8e2f-b736228e1603.png)

`// Not Working: 
using (var context = await pnpContextFactory.CreateAsync("SiteToWorkWith"))
{
var admins = context.GetSiteCollectionManager().GetSiteCollectionAdmins(new Uri("https://....sharepoint.com/sites/..."));
}`

`// Not found: 
using (var context = await pnpContextFactory.CreateAsync("SiteToWorkWith"))
{
var siteCollections = await context.GetSharePointAdmin().GetSiteCollectionAdmins(new Uri("https://....sharepoint.com/sites/..."));
}`

## Expected behavior

I expect it to return site admins

## Environment details (*development & target environment*)

- **SDK version**: 1.6.0
- **OS**: Windows 10
- **SDK used in**: Windows Form
- **Framework**: .NET 6.0
- **Browser(s)**: none
- **Tooling**: Visual Studio 2022
- **Additional details**: none

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Any update here @andreanpo ?

**Comment by jansenbe** [comment]
Hey @andreanpo , we'll be closing this issue per no response. If you still see problems please re-open and provide the needed debug information so we can investigate. Thx.
