### ISSUE TITLE
StorageMetrics for newly copied folders is unavailable

### ISSUE THREAD

**Issue by kentlhastings** [pnp/pnpcore#861]
## Category

- [x] Bug

## Describe the bug

Our goal is to copy a folder, including its subfolders and all files to another location and then verify that everything was copied correctly by getting a folder and file count and by verifying the TotalFileStreamSize.

Our method for retrieving and evaluating the storage metrics is as follows:

```
public static async Task<(bool, bool)> ValidateStorageMetrics(string projectSourceURL, string projectDestinationURL, PnPContext context = null)
        {
            if (context is null)
            {
                context = _helper.GetBatchContext();
            }

            var sourceFolder = await context .Web.GetFolderByServerRelativeUrlAsync(projectSourceURL, f => f.StorageMetrics);
            await sourceFolder.StorageMetrics.EnsurePropertiesAsync();
            var sourceFileStreamSize = sourceFolder.StorageMetrics.TotalFileStreamSize;
            var sourceFileNumber = sourceFolder.StorageMetrics.TotalFileCount;

            var destinationFolder = await context .Web.GetFolderByServerRelativeUrlAsync(projectDestinationURL, f => f.StorageMetrics);
            await destinationFolder.StorageMetrics.EnsurePropertiesAsync();
            var destinationFileStreamSize = destinationFolder.StorageMetrics.TotalFileStreamSize;
            var destinationFileNumber = destinationFolder.StorageMetrics.TotalFileCount;

            return (sourceFileStreamSize == destinationFileStreamSize && sourceFileNumber == destinationFileNumber, sourceFileStreamSize > 0 && destinationFileStreamSize > 0);
        }
```

Ideally, destinationFileStreamSize and destinationFileNumber would be accurate, however they are always 0, unless the same copy operation is performed twice in a row. We would simply repeat the copy, however some copy jobs take more than 2 hours.

Also, please note that the file and folder count at the destination is correct. This is verified immediately prior to our storageMetrics validation by running the following method on both our source and destination URLs:

```
public async Task<URLCollection> QueryProjectResourceURLS(PnPContext context, string sourceFolderPath)
        {
            ConsoleBuffer.Write();

            //Begin with root folder
            var folders = new List<string>() { sourceFolderPath };
            var files = new List<string>();

            //Iterate through all folders, adding more files and folders as we go
            for (var i = 0; i < folders.Count; i++)
            {
                ConsoleBuffer.Write();

                var rootFolder = await context.Web.GetFolderByServerRelativeUrlAsync(folders[i], x => x.ServerRelativeUrl, x => x.Folders.QueryProperties(x => x.ServerRelativeUrl), x => x.Files.QueryProperties(x => x.ServerRelativeUrl));
                foreach (var folder in rootFolder.Folders.AsRequested())
                    folders.Add(folder.ServerRelativeUrl);
                foreach (var file in rootFolder.Files.AsRequested())
                    files.Add(file.ServerRelativeUrl);
            }

            return new URLCollection(folders, files);
        }
```

## Steps to reproduce

1. Initiate a copy job using API call: 

```
var migrationOptions = new CopyMigrationOptions()
            {
                AllowSchemaMismatch = true,
                AllowSmallerVersionLimitOnDestination = true,
                IgnoreVersionHistory = false,
                IsMoveMode = false,
                BypassSharedLock = true,
                ExcludeChildren = false,
                NameConflictBehavior = SPMigrationNameConflictBehavior.Replace,
            };
            try
            {
                var moveJobs = await context.Site.CreateCopyJobsAsync(jobUris.ToArray(), destinationPathURL, migrationOptions);
                await context.Site.EnsureCopyJobHasFinishedAsync(moveJobs);
            }
            catch (Exception ex)
            {
                throw ex;
            }
```

2. Query the storagemetrics from the server relative path of the destination URL

```
var destinationFolder = await batchContext.Web.GetFolderByServerRelativeUrlAsync(projectDestinationURL, f => f.StorageMetrics);
            await destinationFolder.StorageMetrics.EnsurePropertiesAsync();
            var destinationFileStreamSize = destinationFolder.StorageMetrics.TotalFileStreamSize;

```
3. The destinationFileStreamSize will be 0, unless the copy operation is performed more than once
## Expected behavior
destinationFileStreamSize should be accurate

## Environment details (*development & target environment*)

- **SDK version**: PnP.Core.Auth(1.6.58-nightly)
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: .Net Core 3.1
- **Browser(s)**: Chrome Version 101.0.4951.67 (Official Build) (64-bit)
- **Tooling**: Visual Studio 2019 Professional
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@kentlhastings : If you leave some time between the copy operation and the actual retrieval of the filestream metrics do you then still see 0 being returned? 

Also try with `await destinationFolder.LoadAsync(p=>p.StorageMetrics);`

**Comment by kentlhastings** [comment]
Hello Bert,

Thank you very much for your reply. If we leave time between the copy op
and metrics retrieval, we do typically get valid storage metrics. We will
try your suggestion of using destinationFolder.LoadAsync() to see if this
improves our ability to get real-time results.

Thank you and take care,
Kent

**Comment by kentlhastings** [comment]
Hi Bert,

Thank you for that clarification. Our intended use was to archive data by
moving it to an archive folder. Once moved, we wanted to verify that it was
moved correctly, and then delete it at the source, all in one go.
Nevertheless, we appreciate your efforts looking into this and improving
the PNP SDK.

Take care,
Kent
