### ISSUE TITLE
Inline image resize functionality

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpcore#868]
## Category
Inline image resizing

- [ ] Bug
Height and width of resizing image is 0 in edit mode

## Describe the bug
After inline image is included in page, it has 0height and 0width for resize box (if nullable values in options are not provided)

## Steps to reproduce
1. See code
```C#
var newPage = await context.Web.NewPageAsync();
var exampleHTML = "<H1>Hello github</H1>Lorem ipsum<br><img src=\"example.jpg\"><br>Lorem ipsum";
IPageText control = newPage.NewTextPart();

var doc = new HtmlDocument();
doc.LoadHtml(exampleHTML);

var imageNode = doc.DocumentNode.SelectNodes("//img").FirstOrDefault();
var options = new PageImageOptions() {Alignment = PageImageAlignment.Center };
string inlineImageHtml = newPage.GetInlineImage(control, "ExampleImageOnPage.jpg", options);
var changedHtml = imageNode.OuterHtml.Replace(imageNode.OuterHtml, $"{inlineImageHtml}");

var imageDocNew = new HtmlDocument();
imageDocNew.LoadHtml(changedHtml);

imageNode.ParentNode.ReplaceChild(imageDocNew.DocumentNode.ChildNodes.FirstOrDefault(), imageNode);
control.Text = doc.DocumentNode.WriteTo();
newPage.AddControl(control);

await newPage.SaveAsync("MyPage.aspx");
```
2. After that code runs, MyPage.aspx is created with IPageText webpart
3. Edit Page
4. Click on inline image
5. See that resizing box has incorrect height and width
![image](https://user-images.githubusercontent.com/42325625/171599901-da5e0f4f-54c8-44e5-9c5a-42eacd2d03a8.png)

## Expected behavior
Inline image will have correctly set resizing points in corners of an image
![image](https://user-images.githubusercontent.com/42325625/171600141-2948ed59-0cea-46bf-9908-2fa0948734da.png)

## Environment details (*development & target environment*)

- **PnP.Core version**: 1.6.0
- **OS**:  Windows 10
- **Framework**: .NET Framework 5.0
- **Browser(s)**: Edge
- **Tooling**: Visual Studio 2019

**Comment by jansenbe** [comment]
@Nevinia210 : it's up to the caller to specify the correct image size via the `PageImageOptions` `Height` and `Width` properties. When not specified these values default to -1. I've considered improving this, but that would mean that the SDK would need to get the images bytes and then try to figure out it's dimensions in a cross platform manner...which feels a bit overkill and going beyond the purpose of the library.

The documentation is not mentioning this, so I'll update the docs to clarify this need.
