### ISSUE TITLE
Extend the Remote Event Receiver functionallity to also be created on Site level

### ISSUE THREAD

**Issue by MathijsVerbeeck** [pnp/pnpcore#869]
## Category

- [x] Feature request

## Describe the feature

Apparently, it is possible to also create remote event receiver on Site level. I was unaware of this when creating the original functionallity, hence why I've only created it on Web / List level. I do however think that this should be expanded so that it's also possible to create them on Site level

## Describe the solution you'd like

Being able to create Remote Event Receivers for a Site

## Additional context

N/A

@jansenbe I could work on this one, as the Collection for the Event Receivers has already been created, I think this should be an easy implementation. (Adding Rest-call for Parent typeof(Site)) and some checks in the AddApiCallHandler when building the REST-Api call

**Comment by jansenbe** [comment]
Thanks @MathijsVerbeeck !
