### ISSUE TITLE
Add support to set document list view scope

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#874]
The Scope property is readonly for a document list view. I need to create a view with scope = Recursive.

// Get Documents list with views via title
var myList = await context.Web.Lists.GetByTitleAsync("Documents", p => p.Views);

// Get the view to update
var viewToUpdate = myList.Views.AsRequested().FirstOrDefault(p => p.Title == "All Documents");

// Update the view
viewToUpdate.Title = "All";
**viewToUpdate.Scope = ViewScope:Recursive  => Not supported (read only)**
await viewToUpdate.UpdateAsync();

**Comment by jansenbe** [comment]
Hi @matsla , there indeed were some `IView` properties read-only while they could be set. This is fixed, will appear in next nightly build. 

As such, I'm closing this issue now, but feel free to re-open or create a new one in case it still does not work. 

Note that we plan to release 1.7 before end of the month
