### ISSUE TITLE
Support to set local navigation orientation for a team site

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#875]
The branding manager does not support to set the local navigation orientation options for a team site, like attached picture. I need to set the local navigation orientation to horizontal and the menu style to cascading.

var chrome = await context.Web.GetBrandingManager().GetChromeOptionsAsync()

![nav](https://user-images.githubusercontent.com/24357356/172786721-d2bed3e5-d84a-4927-b875-ce6c70ffa81e.PNG)

**Comment by jansenbe** [comment]
@matsla : I've added support for this, with tomorrow's nightly build you'll have an `INavigationOptions` object when you load the `IChromeOptions` of a site allowing you to set `HorizontalQuickLaunch` and `MegaMenuEnabled` as options.

Will close this issue, re-open when it still does not work for you.
