### ISSUE TITLE
CreateCopyJobsAsync is missing from ISite interface

### ISSUE THREAD

**Issue by web265p3** [pnp/pnpcore#876]
## Category

- [x] Bug

## Describe the bug

I was about to move around some files/folders, but encountered that in the current version (NuGet package version 1.6.0) the function CreateCopyJobsAsync does not exist.  
The snipped posted [in your examples does](https://pnp.github.io/pnpcore/using-the-sdk/sites-copymovecontent.html) not work for me:

`'ISite' does not contain a definition for 'CreateCopyJobsAsync' and no accessible extension method 'CreateCopyJobsAsync' accepting a first argument of type 'ISite' could be found`

Was this feature moved to another class? Or what am I doing wrong?

Can you update the documentation?

**Comment by jansenbe** [comment]
@web265p3 : this is currently only available in our nightly build, we'll release 1.7 before end of the month in case you can't use a nightly build.

**Comment by web265p3** [comment]
Thanks! That seems to be the case. 
How can I see that in the docs? There is no notice that I need to install the nightly build?

**Comment by jansenbe** [comment]
You've a point there @web265p3 , something we should find an (easy) solution for...Given that's something else I'm closing this issue now. Thanks for using PnP Core SDK and providing the feedback.
