### ISSUE TITLE
Support to use join a hub site with application API permissions

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#878]
It seems that its only support to use the join hub site with delegated permissions according to SDK. Can it be supported to with application API permissions as well?

https://pnp.github.io/pnpcore/using-the-sdk/sites-hubsites.html

**Comment by jansenbe** [comment]
We've had some issues when doing this for multi-geo (see https://github.com/pnp/pnpcore/issues/734) and I'm quite sure it applies to app-only in general. @matsla : can you give it a try and see if it works on a regular tenant?

**Comment by jansenbe** [comment]
@matsla : tested myself as well and this indeed works. I've updated the docs to spell out the nuance with the non default geo locations. I'll close this issue now.
