### ISSUE TITLE
PageListItem.Update() does not work on CanvasContent1 field

### ISSUE THREAD

**Issue by jensotto** [pnp/pnpcore#880]
## Category

- [x] Bug

## Describe the bug

The Page object PageListItem.Update() method does not work on CanvasContent1 field.

## Steps to reproduce

Connect to any site and execute the following using PnP.PowerShell
(add a web part to the home page that can be deleted later either using PnP.PwoerShell or manually using the UI)

`Add-PnPPageTextPart -Page home.aspx -Text Test`

```PowerShell
$page = Get-PnPPage home.aspx
$page.Controls
$page.Controls[<Index to a control that can be removed>].Delete()
$page.PageListItem["CanvasContent1"] = $page.ToHtml()
$page.PageListItem.Update()
```
Check the page in a browser, and notice that the web part has not been removed.

Perform the exact same procedure using SystemUpdate() and it works.

Also you can do the same using CSOM and Update(), and it works:

```PowerShell
$file = Get-PnPFile -Url "sitepages/home.aspx"
$file.ListItemAllFields["CanvasContent1"] = $page.ToHtml()
$file.ListitemAllFields.Update()
$file.Context.ExecuteQuery()
```

## Expected behavior

Page should be updated with the changes to CanvasContent1

## Environment details (*development & target environment*)

- **SDK version**: Same as PnP.PowerShell 1.10.0 (1.6.1.0)
- **OS**: Windows 10
- **SDK used in**: PowerShell
- **Framework**: PowerShell 7/5.1
- **Browser(s)**: N/A
- **Tooling**: N/A
- **Additional details**:

**Comment by jansenbe** [comment]
@jensotto : our default ListItem update is currently based upon the `ValidateListItemUpdate` REST methods and that one cannot handle large string fields (you'll get "This field can have no more than 255 characters"). Next to that the PnP Core SDK implementation kept the update model from the previous pages implementation in PnP Framework to not break backwards compatibility. 

You can always use CSOM to directly update the page list item if you prefer that, which is a valid workaround.

As we're not going to change this in the near future I'm closing this issue now. Thanks for providing the feedback.
