### ISSUE TITLE
Support to create crawled and managed search properties

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#887]
Is there any plan to support to create crawled and managed search properties in scope site collection and tenant?

**Comment by matsla** [comment]
@jansenbe yes this can help out in my scenario. I need to move search configuration on site collection level to a target site collection on a different tenant.

**Comment by jansenbe** [comment]
@matsla : this is in progress, search configuration export methods are already done at site/web level, the other parts will come soon.

**Comment by jansenbe** [comment]
@matsla : the search configuration can now be exported and imported at web, site and tenant level. Under the covers this is realized by wrapping the needed CSOM APIs, to feature wise this works the same as in PnP Framework or PnP PowerShell. Will be part of the next nightly release and just in time for version 1.7 which we'll release this week.
