### ISSUE TITLE
Tell us what is missing in PnP Core SDK / what feature would you like to see added

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#897]
To further grow PnP Core SDK we'd like to understand what features you'd like to see added to PnP Core SDK. If you've need a feature in your project or you've suggestions for features to add then please create a new issue in our issue list so that we can track your ask.

**Comment by valpvt** [comment]
The Author property is missing from the IWeb class.
This is not a lot but it would be quite useful to me for a reporting app I'm building.
Hope to see this property included in next release.

Thanks a lot for your great work !

**Comment by gautamdsheth** [comment]
Feature request: 

Add capability to easily add Quick Links webpart on a page, similar to Image or Text webpart. 
Here, we will be able to define Link URL, Thumbnail Image or Icon , Alt text and maybe if possible order of showing links in the webpart.

I would be happy to add a new cmdlet like - Add-PnPPageQuickLinksWebpart or something like that in PnP PowerShell.

**Comment by valpvt** [comment]
Feature request : 
Add capability to retrieve Private Channel Sites (like in Pnp PowerShell). 
Best regards

**Comment by joshmiller1FEI** [comment]
with SharePointPnPCoreOnline I could connect Without a clientID 
    ```
 var authManager = new OfficeDevPnP.Core.AuthenticationManager();
            ClientContext ctx = authManager.GetWebLoginClientContext("https://example.sharepoint.com/sites/example");
            Web web = ctx.Web;
            ctx.Load(web);
            ctx.ExecuteQuery();
```

How can I achieve the above with the new pnp.core ?

The new Minimal Console Example here requires registration of an AAD App and subsequent Client ID.

thank you
Josh

**Comment by jansenbe** [comment]
@joshmiller1FEI : the web login approach indeed is not in PnP Core SDK and that's by design, we're also not supporting Azure ACS anymore in PnP Core SDK. Both approaches are legacy authentication models, the only future proof authentication model for SharePoint is via OAuth and an Azure AD application.

**Comment by fowl2** [comment]
@jansenbe Azure AD authentication still doesn't have feature parity with ACS. For example: 
* Site collection admins can't grant permissions, only tenant admins. 
* There's no UI for granting granular (site or list level) permissions. 
* Only certificates are supported, not secrets.

**Comment by jansenbe** [comment]
Thanks for the feedback @fowl2. You're absolutely right in those, `Sites.Selected` has no UI in Azure AD and you need a tenant admin or a highly privileged application to configure it. We're aware of these shortcomings and evaluating improvements, however there's no confirmed plans yet and no timeline to share.

Regarding the need for certificates: yes, this is by design for calling SharePoint REST or CSOM APIs when using application permissions. If your application only uses Microsoft Graph calls, then a secret is sufficient. I'm not aware of any current plans to also allow a secret for calling SharePoint REST/CSOM using application permissions.

**Comment by mloitzl** [comment]
Hi @jansenbe,

In one of my past projects we somehow missed the ability to get terms by custom property, like in the good old [TermSet.GetTermsWithCustomProperty(CustomPropertyMatchInformation) Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.taxonomy.termset.gettermswithcustomproperty?view=sharepoint-csom)

I played around with this implementation in this fork of PnP Core and it somehow works:

https://github.com/mloitzl/pnpcore/tree/feature/termsbycustomproperty

Do you think this has potential to get into the PnP Core Library?

**Comment by jansenbe** [comment]
@mloitzl : I've taken a quick peek on the code and looks good. Can you please submit a PR?

**Comment by jansenbe** [comment]
> 

@gautamdsheth : with the new page API coming I don't see a need for that.

**Comment by jansenbe** [comment]
@valpvt : can you elaborate a bit more on how you see this?

**Comment by eduardpaul** [comment]
Hi @jansenbe, it would be very interesting to include in pnp core the possibility to expand some fields during a list query (or if it exists, the documentation on how to use it 😄). Ex.: expand user field to get email/principal/sip... using rest API it's only one request but using pnp core we need to get the items and then create a batch to get the properties that we need. 
Also, there is an older issue that describe exactly the same: https://github.com/pnp/pnpcore/discussions/382

**Comment by valpvt** [comment]
> @valpvt : can you elaborate a bit more on how you see this?

PnP Powershell relies on the hidden list at the admin site collection level and allows to get private channel sites. It seems like PnP Core SDK does not query this list because it does not retrieve private channel sites

**Comment by larry-lau** [comment]
Feature request :
Add the capability to approve permission requests like m365 cli
`m365 spo serviceprincipal permissionrequest approve`

We are able to use pnpcore to deploy SPFx app to app catalog. However, the app request permission to call Graph API. 
The only step we couldn't automate is the permission requests approval step.

**Comment by jansenbe** [comment]
> Feature request : Add the capability to approve permission requests like m365 cli `m365 spo serviceprincipal permissionrequest approve`
> 
> We are able to use pnpcore to deploy SPFx app to app catalog. However, the app request permission to call Graph API. The only step we couldn't automate is the permission requests approval step.

Thanks @larry-lau , that's a useful add. I've created a new issue to track this.

**Comment by jansenbe** [comment]
Closing this issue as it's not an ideal way to deal with feature asks. Please just create a new issue if you feel something is missing
