### ISSUE TITLE
Add property "filesFolderWebUrl" to Model ITeamChannel when calling the Beta graph

### ISSUE THREAD

**Issue by pmatthews05** [pnp/pnpcore#902]
## Category

- [x] Domain model extension

## Describe the domain model extension

This can only be obtained at the moment using Beta Graph. There is an additional property called 'filesFolderWebUrl' which gives you the SharePoint URL of the channel (Private and Public)
`https://graph.microsoft.com/beta/teams/<GroupID>/channels`

### Model

Model: PnP.Core.Model.Teams.ITeamChannel
Property: FilesFolderWebUrl

### APIs

`https://graph.microsoft.com/beta/teams/<GroupID>/channels`

### Additional Information

This is a link to the docs, but this property isn't showing in here.
https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&tabs=http

But you can see it using the Graph Explorer.
![image](https://user-images.githubusercontent.com/6736509/176220458-61ae034c-4a0d-488b-82e8-664a1f0c118f.png)

**Comment by jansenbe** [comment]
@pmatthews05 : doesn't this work for you? https://pnp.github.io/pnpcore/using-the-sdk/teams-channels.html#getting-access-to-the-channels-files

**Comment by pmatthews05** [comment]
@jansenbe The suggestion you have offered, is what I'm kind of doing now, (which only worked once I had the nightly build). However, that requires me to loop through each channel, then make the additional call for the getting the URL.

With this new property that is provided in the Beta graph, it would save multiple round trip calls.

**Comment by jansenbe** [comment]
@pmatthews05 : property has been added, but do note that you need to load each channel as our "let's switch to beta" detection logic only checks for the properties of the loaded model. Luckily you can batch these as shown in below snippet (coming from the test case):

```csharp
var team = await context.Team.GetAsync(o => o.Channels);

var batch = context.NewBatch();
foreach(var channel in team.Channels.AsRequested())
{
    await channel.LoadBatchAsync(batch, p => p.FilesFolderWebUrl);
}
var errors = await context.ExecuteAsync(batch, false);

foreach(var channel in team.Channels.AsRequested())
{
    if (channel.IsPropertyAvailable(p=>p.FilesFolderWebUrl))
    {
        Assert.IsTrue(!string.IsNullOrEmpty(channel.FilesFolderWebUrl.ToString()));
    }
}
```

Once the property goes to GA it will be loaded automatically. Alternatively you can force PnP Core SDK to always use the beta endpoint for everything, not recommended for production apps but might work for you. See https://pnp.github.io/pnpcore/using-the-sdk/basics-apis.html#graph-v1-versus-graph-beta for more details.

Closing the issue now, feel free to re-open whenever this still does not work for you.
