### ISSUE TITLE
Wrong if condition combination & instead of &&

### ISSUE THREAD

**Issue by mr-sven** [pnp/pnpcore#911]
## Category

- [x] Bug

## Describe the bug

For security checks I need to run code anaylses with sonarCube and the following blocker issue found:

https://github.com/pnp/pnpcore/blob/bf1985c3390e65fd65a45eeb592dd3f67c8fb02a/src/sdk/PnP.Core/QueryModel/Model/BaseQueryableDataModelCollection.cs#L86

Fix:
```csharp
if (provider != null && Expression != null)
```

## Steps to reproduce

Syntax error

**Comment by jansenbe** [comment]
@mr-sven : nice catch!

**Comment by jansenbe** [comment]
Fixed
