### ISSUE TITLE
Issue on loading RoleAssignments of list items

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#932]
## Category

- [x] Bug

## Describe the bug

Item loaded using LoadListDataAsStreamAsAsync is not able to load with Roledefinitions on next query execution.
It was on working state on version 1.3.
However throws unhandled exception on every consequent versions.

## Steps to reproduce
```
  item.RoleAssignments.LoadBatchAsync(context.CurrentBatch, x => x.RoleDefinitions).Wait();
     context.Execute();
```

## Expected behavior

Redefinitions must be loaded with out failure

## Environment details (*development & target environment*)

- **SDK version**: [1.7 ]
- **OS**: [Windows 10 ]
- **SDK used in**: [Console App ]
- **Framework**: [.NET Framework v4.7.1 ]
- **Tooling**: [Visual Studio 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@gopaldahal : can you provide a more detailed repro? Also an error message and stack trace will help identify what goes wrong.

**Comment by jansenbe** [comment]
@gopaldahal : closing this one, if the issue still is there, please re-open and provide the needed details to help troubleshoot the issue. Thx for using PnP Core SDK!

**Comment by rojin55** [comment]
@jansenbe 

I am also facing the same issue, while loading roleassignments.

`item.RoleAssignments.LoadBatchAsync(context.CurrentBatch, x => x.RoleDefinitions).Wait();`

this issue occur while upgrading Pnp.core to 1.7.17.0.

```
ArgumentNullException: Value cannot be null.
Parameter name: member
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at PnP.Core.Model.BaseDataModelCollection`1.ConvertExpressionToParent(Expression`1[] expressions)
   at PnP.Core.Model.BaseDataModelCollection`1.LoadBatchAsync(Batch batch, Expression`1[] expressions)
   at PnPCoreHandler.PnPCoreCommonUtils.GetItemProperties(String siteUrl, String listName, List`1 filters)
```

**Comment by jansenbe** [comment]
@gopaldahal , @rojin55 : sorry for the late reply, but below is how this should be used (works in my testing):

```csharp
await item.LoadBatchAsync(context.CurrentBatch, x => x.RoleAssignments.QueryProperties(x => x.RoleDefinitions));
```

This is because the `RoleAssignments` was not yet loaded after the `LoadListDataAsStreamAsync` call.

Closing issue now. Please create a new one if you still have issues using the current release.
