### ISSUE TITLE
Support to reindex list/site, column default values and follow/unfollow site/document

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#940]
Add support to reindex list and site?
Add support to follow/unfollow sites and documents?
Add support to set column default values?

**Comment by jansenbe** [comment]
@matsla : I've created new issues for reindexing and default values. Following sites/documents is possible today: https://pnp.github.io/pnpcore/using-the-sdk/social-following.html#follow-the-content

**Comment by jansenbe** [comment]
Closing this one since there are new issues to track the individual requests
