### ISSUE TITLE
The Author property is missing from the IWeb class.

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#947]
The Author property is missing from the IWeb class.
This is not a lot but it would be quite useful to me for a reporting app I'm building.
Hope to see this property included in next release.

Thanks a lot for your great work !

_Originally posted by @valpvt in https://github.com/pnp/pnpcore/issues/897#issuecomment-1220846299_

**Comment by jansenbe** [comment]
@valpvt: the `Author` property has been added. Will appear in the next nightly build (version 1.7.47 or higher)

**Comment by valpvt** [comment]
Awesome ! Many thanks @jansenbe
