### ISSUE TITLE
Mocking PnPContext using Moq

### ISSUE THREAD

**Issue by jansenbe** [pnp/pnpcore#948]
### Discussed in https://github.com/pnp/pnpcore/discussions/789

<div type='discussions-op-text'>

<sup>Originally posted by **sachinsatav** March 14, 2022</sup>
Hi,
I am using PnP.Core in one of my project to create new sharepoint sites and I need to write unit tests around it.
I am able to mock context factory since there is an interface for it.
`var _mockContextFactory = new Mock<IPnPContextFactory>();`

However I am not able to mock **PnPContext** since there is no public constructor. Also there is not interface which I can use for mocking. 

I looked at SDK test projects - https://github.com/pnp/pnpcore/tree/dev/src/sdk/PnP.Core.Test.Common & https://github.com/pnp/pnpcore/tree/dev/src/sdk/PnP.Core.Test but the setup is quite complicated and most of method calls used in there are only exposed to SDK solution projects. 

Can someone please help with how I can mock PnPContext? Thank you.</div>

**Comment by jansenbe** [comment]
@sachinsatav, @wonderplayer : can you explain more about your requirements/needs. The mentioned discussion speaks about being able to set Web and Uri as properties...

**Comment by wonderplayer** [comment]
@jansenbe I'd like to set up unit testing. But if code contains PnP.Core framework in it, then I can't mock it - workaround to create class that will be calling PnP.Core and mock that class.
So, in general, it would be perfect if I could mock any part of PnPContext - web functions, administration, list, files, etc.

**Comment by wonderplayer** [comment]
@jansenbe Will this do?
https://github.com/wonderplayer/PnPCore-ConsoleApp

**Comment by wonderplayer** [comment]
@jansenbe Sure, let's do it 😊
Created mocked context, but tests failing. It requires ILogger - guess if I add resolution dependency injection for it, then it might work, but not necessarily all solutions will be using ILogger. At least IPnPContextFactory does not require ILogger dependency.

**Comment by jansenbe** [comment]
@wonderplayer : can you share the stack trace of the failure?

**Comment by wonderplayer** [comment]
@jansenbe I've pushed my changes to that repo.
New test file with mock PNP context.

**Comment by jansenbe** [comment]
@wonderplayer : I did play a bit with your code and experimented with adding an interface for PnPContext. Using that below code  works...would such an approach work for you?

```csharp
var ctx = new Mock<IPnPContext> { DefaultValue = DefaultValue.Mock };

IWeb web = ctx.Object.Web;

ctx.Setup(c => c.Web.GetAsync()).ReturnsAsync(web);
var webMock = Mock.Get(web);
webMock.Setup(p => p.Title).Returns(title);

var result = await web.GetAsync();

Assert.AreEqual(title, result.Title);
```

Interface added on `PnPContext`:

```csharp
/// <summary>
/// PnPContext interface to support mocking
/// </summary>
public interface IPnPContext
{
    /// <summary>
    /// Entry point for the Web Object
    /// </summary>
    IWeb Web { get; }
}
```

**Comment by jansenbe** [comment]
Code is not yet committed, will extend the interface to support additional objects before commit

**Comment by jansenbe** [comment]
@wonderplayer : I pushed the interface change and dropped the static method. Let me know if this unblocks your scenario.

**Comment by wonderplayer** [comment]
Thanks! I'll check tomorrow

**Comment by wonderplayer** [comment]
@jansenbe with the scenario that I have, it works perfectly! Now I can mock various parts, as they are interfaces. Thank you!

**Comment by jansenbe** [comment]
closing, thx!
