### ISSUE TITLE
Write tests for current Teams implementation

### ISSUE THREAD

**Issue by JarbasHorst** [pnp/pnpcore#95]
## Category

- [x] Domain model extension

## Describe the domain model extension

Write tests for the current Teams implementation which includes:
- Read, Add and Update Teams settings
- List, Add, Update and Delete Channels
- List, Add, Update and Delete Tabs
- List, Add, Update and Delete Chat Messages
- List, Add, Update and Delete Apps
- List, Add, Update and Delete Owners
- List, Add, Update and Delete Members

### Additional Information

Please, assign this task to me!

**Comment by jansenbe** [comment]
Thanks for taking up this work @JarbasHorst !

**Comment by JarbasHorst** [comment]
I've authored a PR #99, that covers the following topics:
- Separated enums in different files
- Created new enum for ChatMessageReactionType
- Removed unused using directives

**Comment by jansenbe** [comment]
#101 is also part of this implementation. Thanks @JarbasHorst .

**Comment by jansenbe** [comment]
Moving this one to beta 1

**Comment by jansenbe** [comment]
@JarbasHorst : let me know if you still plan to work on this, if not I'll open the task for others again

**Comment by pkbullock** [comment]
I've added as far as I can go with this task - any todo's or additional tests, model changes will be added in a future issue. Closing.

**Comment by jansenbe** [comment]
Thx @pkbullock !
