### ISSUE TITLE
Unable to get folder items if folder name contains "#" character.

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#958]
## Category

LoadListDataAsStreamAsync returns empty result if folder name contains "#" character.

## Describe the bug

let say my library is "HeyramLibrary" inside which there is a folder name "Folder#Name"
```
var folderRelativeUrl ="HeyramLibrary/Folder#Name"
var targetList = clientContext.Web.Lists.GetById(new Guid(targetListUid));
var result = GetListItems(targetList , folderRelativeUrl)
```

```
        public static IEnumerable<IListItem> GetListItems(IList parentList, string folderRelativeUrl) {
            try {
                int rowLimit = 1000;
                string nextPage = null;
                string viewXml = "<View Scope='Default'>" +
                    "<RowLimit Paged='TRUE'>" + rowLimit + "</RowLimit>" +
                   "</View>";
                do {
                    #region LoadListDataAsStreamAsync
                    var loadOption = new RenderListDataOptions() {
                        ViewXml = viewXml,
                        RenderOptions = RenderListDataOptionsFlags.ListData,
                        Paging = nextPage ?? null,
                        DatesInUtc = true,
                        FolderServerRelativeUrl = folderRelativeUrl
                    };
                    var output = parentList.LoadListDataAsStreamAsync(loadOption).Result;
                    if (output.ContainsKey("NextHref")) {
                        nextPage = output["NextHref"].ToString().Substring(1);
                    }
                    else {
                        nextPage = null;
                    }
                    #endregion

                }
                while (!string.IsNullOrEmpty(nextPage));
                var result = parentList.Items.AsRequested();
                return result;
            }
            catch (Exception ex) {
                throw;
            }
         #}
```

## Expected behavior

Though there are items inside the older. It gives the empty result.
It is tried with encoded "folderRelativeUrl". however with no luck

## Environment details (*development & target environment*)
- **SDK version**: [Latest ]
- **OS**: [e.g. Windows 10]
- **SDK used in**: [Console App ]
- **Framework**: [.NET Framework v4.7.2]
- **Tooling**: [Visual Studio 2019]

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Hi @gopaldahal , 

Can you try the workaround mentioned in here: https://github.com/pnp/pnpcore/issues/839. Seems like using `FolderServerRelativeUrl` is not working when using special chars in a folder and that's a bug in SharePoint.

**Comment by gopaldahal** [comment]
Hi @jansenbe,
Mentioned workaround work fine if there is only one view field.  If we add extra field on view field it throws exception as below. 

My view
`<View Scope='DefaultValue'><RowLimit Paged='TRUE'>1000</RowLimit><Query><Where><And><Eq><FieldRef Name='FSObjType'/><Value Type='int'>0</Value></Eq></And><And><Eq><FieldRef Name='FileDirRef'/><Value Type='Text'>Heyram%abcdaha#abcl</Value></Eq></And></Where></Query></View>`

![image](https://user-images.githubusercontent.com/27617624/187855101-9d2fd910-dcc8-4ca3-b202-edb3fa0c1b1c.png)

If we keep same field independently (single), it works.

**Comment by gopaldahal** [comment]
@jansenbe , Mentioned workaround work like a charm.
Thank you

**Comment by jansenbe** [comment]
@gopaldahal : thanks for the feedback. I'll update the docs to clarify this so that future users will not stumble upon this issue.

**Comment by jansenbe** [comment]
Docs are updated, closing this issue now
