### ISSUE TITLE
VerifyProperties fails to detect getPagesLibraryExpression as dirty, leading to potential errors further down the road

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/pnpcore#961]
## Category

- [x] Bug

## Describe the bug

I described the bug over here because I initially thought this is an error in the provisioning engine -> https://github.com/pnp/pnpframework/issues/716

## Steps to reproduce

Not sure ^^. But see https://github.com/pnp/pnpframework/issues/716 for more text.

## Expected behavior

I expect `VerifyProperties` to detect when `RootFolder.ServerRelativeUrl` is not loaded yet.

## Environment details (*development & target environment*)

See https://github.com/pnp/pnpframework/issues/716

### Additional context

I put lots of `Console.WriteLine`s in the code and this is what I found:

This method: https://github.com/pnp/pnpcore/blob/cc8858fcc3d8721ddb47691ee7fae96c8d3f4fa7/src/sdk/PnP.Core/Model/Base/BaseDataModel.cs#L1275

...fails to handle this expression properly:

https://github.com/pnp/pnpcore/blob/cc8858fcc3d8721ddb47691ee7fae96c8d3f4fa7/src/sdk/PnP.Core/Model/SharePoint/Pages/Internal/Page.cs#L27-L28

Specifically it fails to dive into the properties defined in `p.RootFolder.QueryProperties` here:

https://github.com/pnp/pnpcore/blob/119c3eeb427fb1993c06cc0112d691ea057306a8/src/sdk/PnP.Core/Model/Base/BaseDataModel.cs#L1299-L1300

`collection` here is of type `PnP.Core.Model.SharePoint.Folder` (`fieldToLoad` == "RootFolder"), not `IRequestableCollection`. This immediately leaves the function leaving the `dirty` flag unchecked. This leads to errors in other code that now assumes that e.g. the `RootFolder.ServerRelativeUrl` property is loaded. Because it might not be. And in my case sometimes wasn't.

I have no clue how to fix this ^^

**Comment by jansenbe** [comment]
@heinrich-ulbricht : this indeed is a bug. When QueryProperties is used to load other collections things work fine, but when another model (e.g. IFolder) is loaded this didn't work. Fix is coming soon.

**Comment by jansenbe** [comment]
@heinrich-ulbricht : fix has been pushed and will appear in the next nightly release. Closing this issue now, thanks for using PnP Core SDK and reporting the issue.
