### ISSUE TITLE
Add support for permanently deleting a recycled site collection

### ISSUE THREAD

**Issue by devtuc** [pnp/pnpcore#963]
## Category

- [x] Feature request

## Describe the feature

Allow the DeleteSiteCollection(Async) methods to delete an already recycled site. 

## Describe the solution you'd like

Currently (as far as I understand) PnP Core does not support deleting a site collection which has already been recycled. It would be great if support could be added for permanently deleting an already recycled site. 

Something similar to what Clear-PnPTenantRecycleBinItem does in PnP Powershell.

## Additional context

We are trying to automate SharePoint Site management, and trying to allow end users to permanently delete a SharePoint site which was already recycled.

**Comment by jansenbe** [comment]
@devtuc : we support permanently deleting a site collection (so also drop it from the site collection recycle bin) as part of the PnP.Core.Admin library. See https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#deleting-site-collections for more details.

**Comment by jansenbe** [comment]
@devtuc : did you manage to get things working using the admin module?

**Comment by devtuc** [comment]
@jansenbe thanks a lot for your prompt answer, I apologize for the delay in getting back to you.

I have tried the DeleteSiteCollectionAsync method on a recycled site and it did not work (I can provide the exact error a bit later, sorry not at work at the moment), it did work fine on a non recycled site though.

I am sorry, I cannot find the option to delete a recycled site.

As far as I can tell from the implementation (I confess that I am not at all familiar with SharePoint development), the method mentioned above is trying to first recycle the site, and this does not work for an already recycled site.

I would be happy to contribute a PR, if this functionality could be of interest and is indeed missing.

**Comment by jansenbe** [comment]
@devtuc : I can confirm this scenario was not supported, currently working on adding support. Thanks for reporting the issue and using PnP Core SDK.

**Comment by jansenbe** [comment]
@devtuc : support has been added to delete a site collection from the recycle bin. See https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#deleting-a-recycled-site-collection for the docs. 

Note: this functionality will appear in the next nightly build (version 1.7.83 or higher).
