### ISSUE TITLE
Problem with instancing FieldUserValue

### ISSUE THREAD

**Issue by master455** [pnp/pnpcore#969]
## Category

- [x] Bug

## Describe the bug

> I have a Azure Function project with PnP Core v1.7 (I updated recently), I am following documentation [here](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields) to **create a SharePoint list Item with an User Field**, but when I try instance FieldUserValue, **I receive an error: CS0122: 'FieldUserValue' is inaccessible due to its protection level** 

// Option A: instantiate a FieldUserValue instance
`values.Add("MyField", new FieldUserValue(myUser));`

## Steps to reproduce

> **DELETE THIS LINE BEFORE SUBMITTING** - Provide steps to reproduce the behavior:

1. Create an Azure Function Project
2. Install PnP Core v1.7
3. Try instance FieldUserValue

## Environment details (*development & target environment*)

- **SDK version**: 1.7
- **OS**: Windows 10
- **SDK used in**: Azure Function
- **Framework**:  .Net Core 3.1
- **Browser(s)**: Edge 105.013 64 bits
- **Tooling**: Visual Studio 2019

*Thanks for help!*

**Comment by jansenbe** [comment]
@master455 : the improved approach did not yet make it to a major version (1.7), it's however available in our nightly builds.

**Comment by master455** [comment]
Thanks for reply, I understand. Exists any other example or method about how to create an item with User Field? (**when sharepoint column already exists**)

**Comment by jansenbe** [comment]
@master455 : option B in the [documentation sample code](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#user-fields) is the "older" approach which works on 1.7:

```csharp
// Option B: Add a url field: using NewFieldUserValue
values.Add("MyField", myField.NewFieldUserValue(myUser));
```

**Comment by jansenbe** [comment]
@master455 : closing this issue, the new approach will be in 1.8, in the meantime you can either use a nightly build or use the "old" approach as documented.
