### ISSUE TITLE
Support to use Azure Active Directory registered application using a locally available certificate 

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#970]
Support to connects using an Azure Active Directory registered application using a locally available certificate containing a private key like PnP PowerShell, see below.

$password = (ConvertTo-SecureString -AsPlainText 'myprivatekeypassword' -Force)
Connect-PnPOnline -Url "contoso.sharepoint.com" -ClientId 6c5c98c7-e05a-4a0f-bcfa-0cfc65aa1f28 -CertificatePath 'c:\mycertificate.pfx' -CertificatePassword $password  -Tenant 'contoso.onmicrosoft.com'

**Comment by jansenbe** [comment]
@matsla : this is already possible today, your code can load the certificate (from a PFX file + password or from a cert store) and use the loaded cert to authenticate. See https://github.com/pnp/pnpcore/blob/dev/samples/Demo.AzureFunction.OutOfProcess.AppOnly/Program.cs for a sample. To get a `X509Certificate2` instance from your PFX file use this:

```csharp
var certificate = new X509Certificate2("mypfx.pfx", "myprivatekeypassword");
```

Generally speaking, storing the cert in a cert store is more secure as you can then let the OS handle the certificate access control.

**Comment by matsla** [comment]
@jansenbe thanks! yes I know the cert store is more secure but in current development env. we have no permissions to use the local cert store.
