### ISSUE TITLE
Broken link in documentation [writing tests.md]

### ISSUE THREAD

**Issue by LeHailender** [pnp/pnpcore#980]
In the documentation file https://github.com/pnp/pnpcore/blob/dev/docs/contributing/writing%20tests.md is a broken link in the section [Setting up your environment to run the tests cases](https://pnp.github.io/pnpcore/contributing/writing%20tests.html#setting-up-your-environment-to-run-the-tests-cases) at Point 5.

This link is broken https://learn.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps

<img width="690" alt="image" src="https://user-images.githubusercontent.com/85994794/193049813-dd9a5fe2-ab0f-4ac1-ad45-6ff8a559ae7a.png">

**Comment by jansenbe** [comment]
@LeHailender : updated.
