### ISSUE TITLE
Language not working with TeamSiteOptions

### ISSUE THREAD

**Issue by frodale** [pnp/pnpcore#984]
Hello, it seems that when specifying the Language within TeamSiteOptions (using App Only permissions), it does not change the site collection language on creation, have tested with 1033, and 1044 (Norwegian), but i always get a site collection with 1033 language

```
//This doesn't work when selecting a specific language

                        var teamSiteToCreate = new TeamSiteOptions(siteAlias, siteTitle)
                        {
                            Description = siteDescription,
                            Language = (PnP.Core.Admin.Model.SharePoint.Language)lcid,
                            Owners = new string[] { owner }
                        };

                        PnP.Core.Admin.Model.SharePoint.SiteCreationOptions siteCreationOptions = new PnP.Core.Admin.Model.SharePoint.SiteCreationOptions()
                        {
                            UsingApplicationPermissions = true
                        };

                        using (var newSiteContext = await pnpContext.GetSiteCollectionManager().CreateSiteCollectionAsync(teamSiteToCreate, siteCreationOptions))
                        {
                            // Do work on the created site collection via the newSiteContext
                        };
```

**Comment by jansenbe** [comment]
@frodale : thanks for using PnP Core SDK and reporting this. A quick check of the code showed that we're indeed not passing along the language when we create the underlying Microsoft 365 Group (as that's the flow we use when using application permissions). Did try to pass along the `preferredLanguage` property when creating the group but that's not allowed:

```json
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Property preferredLanguage should not be set.",
        "details": [
            {
                "code": "PropertyShouldNotBeSet",
                "message": "Property preferredLanguage should not be set.",
                "target": "preferredLanguage"
            }
        ],
        "innerError": {
            "date": "2022-10-04T14:36:49",
            "request-id": "793d438c-2b2a-47b3-8152-458072e91f49",
            "client-request-id": "793d438c-2b2a-47b3-8152-458072e91f49"
        }
    }
}
```

Looking for alternatives now. When using delegated permissions this will not be an issue as we then use a SharePoint REST API that will create the site and group in one go.

**Comment by frodale** [comment]
Thanks!, i'll be following this :)

**Comment by jansenbe** [comment]
@frodale : I've been investigating this with the internal feature teams owning this and the conclusion is that today there's no option to control the language of the created site. The taken language will be the default tenant language. Using delegated permissions is an easy workaround here.

I'll update the docs to clarify language cannot be set when using application permissions.

Given this is not something to be fixed by PnP Core SDK I'm closing this issue.

**Comment by danielpastoor** [comment]
#1220 I have created a pull request where language is supported for App only permissions
