### ISSUE TITLE
Way to Disable Telemetry when using PnPCoreSdk.Instance.GetPnPContext

### ISSUE THREAD

**Issue by bk-td** [pnp/pnpcore#987]
Would love to see the possibility to set DisableTelemetry to true when creating a PnPContext via:

var pnpContext = PnPCoreSdk.Instance.GetPnPContext(csomContext);

**Comment by jansenbe** [comment]
Also related to #968

**Comment by jansenbe** [comment]
@bk-td : in PnP Framework https://github.com/pnp/pnpframework/pull/762 was merged. This allows you to, in your app using PnP Framework configure an `IPnPContextFactory` with the settings you need and use that same `IPnPContextFactory` for both PnP Core SDK context creation as for getting a `PnPContext` from a CSOM `ClientContext` using below approach. 

**Note**: this will appear via the next nightly build of PnP Framework.

```csharp
var pnpContext = PnPCoreSdk.Instance.GetPnPContext(csomContext, myPnPContextFactory);
```

Closing this issue, thanks for using PnP Core SDK and providing feedback.

**Comment by bk-td** [comment]
Awesome, thanks, much appreciated.
