### ISSUE TITLE
Download large onenote file

### ISSUE THREAD

**Issue by cl-datatrust** [pnp/pnpcore#993]
## Category

- [x] Bug

## Describe the bug

I am using this code to download a large onenote file (14 GB)

```
var relativePath = "https://tenant-my.sharepoint.com/personal/some_user/Documents/folder/some_onenote_file.one";
var file = await ctx.Web.GetFileByServerRelativeUrlAsync(relativePath);
using var stream = await file.GetContentAsync(true);
```
but it getting stuck forever in the GetContentAsync function with 

`options.HttpRequests.Timeout = -1;`

and with

 `options.HttpRequests.Timeout = 10;`  

or more i will get 

![image](https://user-images.githubusercontent.com/115566651/195122380-929bee59-499a-4313-a0e4-c7b16b9ff64c.png)

If I am trying to download the file manually with this code

```
 using (var client = new HttpClient())
{
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        var requestUrl = String.Format("{0}/_api/web/getfilebyid('{1}')/$value", _siteUri.ToString(), id);
        
        try
         {
        var response = await client.GetAsync(requestUrl, HttpCompletionOption.ResponseHeadersRead);
        if (!response.IsSuccessStatusCode)
        {
          var content = await response.Content.ReadAsStringAsync();
        }
          response.EnsureSuccessStatusCode();
          return await response.Content.ReadAsStreamAsync();
         }
        catch (HttpRequestException ex)
        {
        }
}
```

I will get this response

![image](https://user-images.githubusercontent.com/115566651/195124526-3441e77a-4469-4a7f-b680-c19abf0a839a.png)

Is there some other ways to download this file?

**Comment by jansenbe** [comment]
@cl-datatrust : not sure why the download never finishes...maybe give the Graph API a try? See https://learn.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http for details

**Comment by jansenbe** [comment]
@cl-datatrust : this is indeed feels as a service issue when 3 different API approaches all fail. Does this also happen for smaller OneNote files? Would recommend opening a support case if this is a pressing issue.
