### ISSUE TITLE
Add support for "ConvertTo" previous file versions

### ISSUE THREAD

**Issue by simo-26** [pnp/pnpcore#998]
Enable ConvertTo/ConvertToAsync on versions (IFileVersion) of a file
(already available for IFile)

Thank you

**Comment by jansenbe** [comment]
@simo-26 : did you verify this is possible using Microsoft Graph today? If possible, then you can easily call the needed Graph API from PnP Core SDK as documented here https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-microsoft-graph-request.

**Comment by simo-26** [comment]
> @simo-26 : did you verify this is possible using Microsoft Graph today? If possible, then you can easily call the needed Graph API from PnP Core SDK as documented here https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-microsoft-graph-request.

Hi Jansen!
I tried to call this API, but unfortunately there is no "convert" parameter:
https://learn.microsoft.com/en-us/graph/api/driveitemversion-get-contents?view=graph-rest-1.0&tabs=http
Therefore I think it is necessary to change the approach.
In your opinion, is it necessary to use third-party APIs? Is it not possible to use an "in house" function?
Thank you very much

**Comment by jansenbe** [comment]
@simo-26 , well I think we should consider the Graph API an "in house" function here. The only option I see is that you download the specific version, upload it to a temporary location and use the existing convert functionality on that temporary file. Would that work for you?

**Comment by simo-26** [comment]
@jansenbe  , it is a possible solution but more 'onerous' than expected.
I have to repeat this operation for different files based on the user's selection in a form, it would have been much more convenient to have the "convert" available in the "versions" call :)

**Comment by jansenbe** [comment]
@simo-26 : Given there's no native support in the provided API calls you'll have to code this in your application. The SDK cannot simply create a new library under the covers. Will close this issue, please start a discussion if you're stuck implementing it.
