### ISSUE TITLE
Add support to update field properties ShowInEditForm, ShowInNewForm and ShowInViewForms

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#999]
Add support to update properties ShowInEditForm, ShowInNewForm and ShowInViewForms after a field has been created.

**Comment by jansenbe** [comment]
@matsla : this will require wrapping the `SetShowInDisplayForm` and related methods from `SP.Field`. See https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Field. 

This is a good feature to include, if you're under a time constraint you could implement this yourselves by calling the REST API from your code. See https://pnp.github.io/pnpcore/using-the-sdk/basics-customapirequests.html#making-a-custom-spo-rest-request to learn more

**Comment by jansenbe** [comment]
@matsla : just implemented this, see the linked commit for usage information (will also update docs).
